apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-prometheus-stack

resources:
- base/metrics-exporter-cm.yaml
- base/metrics-exporter-ds.yaml
- sealed-secrets/kube-prometheus-stack-alertmanager-oauth2-proxy.yaml
- sealed-secrets/kube-prometheus-stack-prometheus-oauth2-proxy.yaml

helmCharts:
- name: kube-prometheus-stack
  namespace: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  valuesFile: values.yaml
  version: 82.4.1
- name: oauth2-proxy
  namespace: kube-prometheus-stack
  releaseName: alertmanager-oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  valuesFile: alertmanager-oauth2-proxy-values.yaml
  version: 10.1.4
- name: oauth2-proxy
  namespace: kube-prometheus-stack
  releaseName: prometheus-oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  valuesFile: prometheus-oauth2-proxy-values.yaml
  version: 10.1.4
