apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-prometheus-stack

resources:
- base/metrics-exporter-cm.yaml
- base/metrics-exporter-ds.yaml
- sealed-secrets/kube-prometheus-stack-alertmanager-oauth2-proxy.yaml

helmCharts:
- name: kube-prometheus-stack
  namespace: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 80.13.3
  valuesFile: values.yaml
- name: alertmanager-oauth2-proxy
  namespace: kube-prometheus-stack
  releaseName: oauth2-proxy
  repo: https://prometheus-community.github.io/helm-charts
  version: 10.0.0
  valuesFile: alertmanager-oauth2-proxy-values.yaml
# - name: prometheus-oauth2-proxy
#   namespace: kube-prometheus-stack
#   releaseName: oauth2-proxy
#   repo: https://prometheus-community.github.io/helm-charts
#   version: 10.0.0
#   valuesFile: prometheus-oauth2-proxy-values.yaml
