apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- core-applicationset.yaml
- core-appproject.yaml
- core-apps/cdi.yaml

- cyclops-k8s-project.yaml
- cyclops-k8s-appproject.yaml
