apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mattermost-operator

helmCharts:
- name: mattermost-operator
  includeCRDs: true
  namespace: mattermost-operator
  releaseName: mattermost-operator
  repo: https://helm.mattermost.com
  valuesFile: values.yaml
  version: 1.0.4
