apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: home
spec:
  nodeSelector:
    matchExpressions:
    - key: node.kubernetes.io/exclude-from-external-load-balancers
      operator: DoesNotExist
  bgpInstances:
  - localASN: 65533
    name: instance-65533
    peers:
    - name: peer-65534
      peerASN: 65534
      peerAddress: 10.42.41.1
      peerConfigRef:
        name: peer-config-generic
