apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: peer-config-generic
spec:
  ebgpMultihop: 1
  families:
  - advertisements:
      matchLabels:
        advertise: generic
    afi: ipv4
    safi: unicast
