apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-keycloak-provider

resources:
- base/keycloak-provider.yaml
- base/keycloak-provider-config.yaml
- sealed-secrets/crossplane-keycloak-credentials.yaml
