apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: headlamp

resources:
- base/cluster-role-binding.yaml
- base/headlamp-client.yaml
- sealed-secrets/headlamp-oidc-client.yaml

helmCharts:
- name: headlamp
  namespace: headlamp
  releaseName: headlamp
  repo: https://kubernetes-sigs.github.io/headlamp
  valuesFile: values.yaml
  version: 0.40.0
