apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-arc

helmCharts:
- includeCRDs: true
  name: gha-runner-scale-set-controller
  namespace: github-arc
  releaseName: gha-runner-scale-set-controller
  repo: oci://ghcr.io/actions/actions-runner-controller-charts
  valuesFile: values.yaml
  version: 0.13.1
