apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki

resources:
- base/objectbucketclaim.yaml

# patches:
# - path: patches/distributor-deployment.yaml
# - path: patches/loki-cm.yaml

helmCharts:
- name: loki
  namespace: loki
  releaseName: loki
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  version: 6.49.0
