apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pyroscope

resources:
- base/objectbucketclaim.yaml
- base/pvc.yaml

helmCharts:
- name: pyroscope
  namespace: pyroscope
  releaseName: pyroscope
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  version: 1.18.0
