apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: prometheus
spec:
  deletionPolicy: Delete
  forProvider:
    accessType: confidential
    baseUrl: /
    clientId: prometheus
    clientSecretSecretRef:
      key: client-secret
      name: prometheus-oauth2-proxy
      namespace: kube-prometheus-stack
    directAccessGrantsEnabled: true
    name: Prometheus
    pkceCodeChallengeMethod: S256
    realmIdRef:
      name: iaas
    rootUrl: https://prometheus.apps.iaas.wcooke.me
    standardFlowEnabled: true
    validPostLogoutRedirectUris:
    - /oauth2/sign_out
    validRedirectUris:
    - /oauth2/callback
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: prometheus-admin
spec:
  deletionPolicy: Delete
  forProvider:
    clientIdRef:
      name: prometheus
    name: prometheus-admin
    realmIdRef:
      name: iaas
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: prometheus-admins
spec:
  deletionPolicy: Delete
  forProvider:
    name: prometheus-admins
    realmIdRef:
      name: iaas
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: prometheus-roles
spec:
  deletionPolicy: Delete
  forProvider:
    groupIdRef:
      name: prometheus-admins
    realmIdRef:
      name: iaas
    roleIdsRefs:
    - name: prometheus-admin
  providerConfigRef:
    name: keycloak-provider-config
