apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubevirt

resources:
- https://github.com/kubevirt/kubevirt/releases/download/v1.7.0/kubevirt-operator.yaml
- base/kubevirt.yaml

patches:
- path: patches/remove-namespace.yaml
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: virt-operator
#   patch: |-
#     - op: add
#       path: /spec/template/metadata/annotations/olm.targetNamespaces
#       value: hello
