apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mermaid
  annotations:
    cert-manager.io/cluster-issuer: iaas-wcooke-me
    forecastle.stakater.com/appName: Mermaid
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: Apps
    forecastle.stakater.com/icon: https://mermaid.apps.iaas.wcooke.me/favicon.svg
    forecastle.stakater.com/network-restricted: "true"
spec:
  ingressClassName: cilium
  rules:
  - host: mermaid.apps.iaas.wcooke.me
    http:
      paths:
      - backend:
          service:
            name: mermaid
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mermaid.apps.iaas.wcooke.me
    secretName: mermaid-server-tls
