# https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#example-file
apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-datasource
  labels:
    grafana_datasource: "1"
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: pyroscope
      editable: false
      type: grafana-pyroscope-datasource
      uid: pyroscope
      url: http://pyroscope-query-frontend.pyroscope.svc:4040
      version: 2
      jsonData:
        minStep: '15s'
