apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitlab-runners

resources:
- sealed-secrets/gitlab-runner-token.yaml

# https://gitlab.com/gitlab-org/charts/gitlab-runner/-/blob/main/Chart.yaml?ref_type=heads
helmCharts:
- includeCRDs: true
  name: gitlab-runner
  namespace: gitlab-runners
  releaseName: gitlab-runner
  repo: https://charts.gitlab.io
  version: 0.80.0
  valuesFile: values.yaml
