apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-keycloak-realms

resources:
- base/iaas-realm.yaml
- base/iaas-users.yaml
- base/kubernetes-client.yaml
- sealed-secrets/crossplane-keycloak-realms-edward-credentials.yaml
- sealed-secrets/crossplane-keycloak-realms-william-credentials.yaml
