apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
- name: sealed-secrets
  includeCRDs: true
  namespace: kube-system
  releaseName: sealed-secrets
  repo: https://bitnami-labs.github.io/sealed-secrets
  valuesFile: values.yaml
  version: 2.18.1
