apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-snapshotter

resources:
- https://github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=release-8.4
- https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/csi-snapshotter?ref=release-8.4
- https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller?ref=release-8.4
