apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph-cluster

# patches:

resources:
# - base/dashboards.yaml
- base/ingress.yaml
- base/objectstore-certificate.yaml

helmCharts:
- name: rook-ceph-cluster
  namespace: rook-ceph-cluster
  releaseName: rook-ceph-cluster
  repo: https://charts.rook.io/release
  valuesFile: values.yaml
  version: v1.19.1
