apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# patches:
# - path: patches/mounts.yaml
#   target:
#     kind: Deployment
#     name: rook-ceph-operator

helmCharts:
- name: rook-ceph
  includeCRDs: true
  namespace: rook-ceph
  releaseName: rook-ceph
  repo: https://charts.rook.io/release
  valuesFile: values.yaml
  version: v1.19.1
