apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trivy

helmCharts:
- name: trivy-operator
  includeCRDs: true
  namespace: trivy
  releaseName: trivy
  repo: https://aquasecurity.github.io/helm-charts/
  valuesFile: values.yaml
  version: 0.31.0
