apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: prometheus-operator-crds
  namespace: monitoring
  releaseName: prometheus-operator-crds
  repo: https://prometheus-community.github.io/helm-charts
  version: 26.0.1
  valuesFile: prometheus-operator-crds-values.yaml
