apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane

helmCharts:
- name: crossplane
  namespace: crossplane
  releaseName: crossplane
  repo: https://charts.crossplane.io/stable
  valuesFile: values.yaml
  version: 2.1.4
