# replicas: 1

revisionHistoryLimit: 1

# provider:
#   # -- A list of Provider packages to install.
#   packages: []
#   # -- Define entries for the default managed resource activation policy. If defined, a default MRAP will contain these activations.
#   defaultActivations: ["*"]

# configuration:
#   # -- A list of Configuration packages to install.
#   packages: []

# function:
#   # -- A list of Function packages to install
#   packages: []

rbacManager:
  # replicas: 1
  revisionHistoryLimit: 1

metrics:
  enabled: true

# readiness:
#   # -- The port the readyz server listens on.
#   port: ""
