apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-arc-runners

resources:
# - sealed-secrets/github-arc-cyberchef-container.yaml
- sealed-secrets/github-arc-cyclops-k8s-container.yaml

helmCharts:
- includeCRDs: true
  name: gha-runner-scale-set
  namespace: github-arc-runners
  releaseName: cyclops-k8s
  repo: oci://ghcr.io/actions/actions-runner-controller-charts
  valuesFile: cyclops-k8s-values.yaml
  version: 0.13.1
# - includeCRDs: true
#   name: gha-runner-scale-set
#   namespace: github-arc-runners
#   releaseName: cyberchef-container
#   repo: oci://ghcr.io/actions/actions-runner-controller-charts
#   valuesFile: cyberchef-container-values.yaml
#   version: 0.13.1
