---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-core-config
  namespace: harbor
spec:
  encryptedData:
    CONFIG_OVERWRITE_JSON: AgCWaVsrfGeKVqWZa5wEosAp61zHje+khJo8N1a1Zq+ufRdABqAxYCyOdflzAZANtCj+QbYm0Kxw/7MceBU58jK7IMYPCst6sTzMoWwIBAYY2JvDEwasNSrbo8hFnM0ePQ4eETLwuQneiNoYMrQvBhN7bnpN+dIh1h9I17FmuvMcQs2/hA43CWLbCqTP7D6NsBIyS7/uDlM3V3cOXswD4vwjBV8JfPQt9dsbZoL/F5RAs3QyZzCnr5a/mP/JqGRbihxIMYKUTSPXSOZkoKJ0RMfTdc/Am1o0Oa0YR2Bq48RLQAsvB1rI8m3MwxnJ64xpGvnpBrXO8D8q/I/AtlJn3ZWIl9JOK3IndjJH0lCxx1Ihvl9b7l5Wbm1m6kpzkVEJGCdBpP4sIzRK7KHLCoFqj0GNj09+od2qFQP8MyANH9LqZwVK+STpS4wTWjwqw7lR/GeN4T+sohq58FA0lXkrYCCfPv/Jg/6H+HQSQDZqXscPx9UlngQ5AM/LaEc3JvHecWEA1GJ2IY+6+hmAmc39kGJ97To6Z795gStbEbIM7CJfZCHPo30vzf/XX9hbWi9jOFB9STV52M6ltx2bMwGgUgZEGFKFVBWUm3k9CMNMxslLwnBqLdSMin/vkLMVETb3YKeiAOGmcpkKq/i4c9YqIfmnvJCk/umQeGWTfC2d13S0Fer1epAshNmx5VWCwhY0VemDeogDDkuoNwpa+MnQNoHovZxTiU0VybkgQVmsT+9MZkkngTU8rahi+7Y4v54kYc8xQ4B7RcYs0nQu6EvD89mENpCuFz5OOIqNl+2cfRIB/jo58e4izZ83tPwBNIy9eFfYA+gUqoSTTBClnPaho4xgkL9IFhnDDhbcJoHLQxEwV4kXw/xMDP/B9cWi3ogntjVZ8/6bwFtyKN6pJ3PO+7hOOJFhpl+jl1frbyfk5AT0X+TmJp0m+FlKDnpImxmij1XFZ0VAWwZtjIafENas4hK8Db7v2PP8g6drDHOLtWZ70NLsPodCFC70j5d+3EIKQicfmaZbHfhefaIWX/wDMBmDbH1QUQKtEyQEgUQPFN2sYZtoK4+ckhbG7KiDZuTt3mtrTUCnVJh93813PYhOIiH/SiEbph0GbIxRTkmTfYNKDHcgqSoSksP8aLkV7FLzgBLpoKoD7u+cEU90dTlOb+WAvv6ZfNin8CqyzqFNHxkK7sbPejxRNDq3ZQgmuvQFM5SQ2vf1ZldgRnQBTb/zwaXOMgohEd/X+1XXjDf6a7RJU0RN6boyd8/ZLc6OinZW04lo9PsnED7OXoj57KKkorI9hYkscXCA5JFpK7nUAZHegb3WQHaJNGnhRZAyE4HISU27AWJyqTZNG2YmH6HRuIc72vpk5czxJ20VT+1Y0dXzGKJ+PqMNHGvuLxnxPr+p5NaSZPsSYkb9D127xAcmNQV9FVfoZCSVqM4vMmaJ+sicIr4vEWLbpzL4mDJ7PKMZE1KdQldRMpJ+aaAvQRpgAJ/PTxR0OUMfRigjiOdbg/bt+2je6cVKK6MDcRJINzpbEEV+rNSxY3yMrrbZENsp2pIN1caFIuzvN6xIQXkYFb+u4PL0uQVBKDJq2k5oKT8kR42+MsdAJqpucS1Sew==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-core-config
      namespace: harbor
    type: stringData
