apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../apps/prometheus-operator-crds/

- ../apps/cert-manager/
- ../apps/sealed-secrets/

- ../apps/cert-manager-certs/
- ../apps/trust-manager/

- ../apps/argocd/
- ../projects/
# - ../apps/cilium/

- projects.yaml
# - projects/
