apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alloy

resources:
- base/alloy-client-ca.yaml
- base/alloy-client-ca-cert.yaml
- base/alloy-client-client-cert.yaml
- base/alloy-client-ingress.yaml
- base/alloy-ingress.yaml
- sealed-secrets/alloy-client-credentials.yaml

helmCharts:
- name: alloy
  namespace: alloy
  releaseName: alloy
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  version: 1.5.1
