---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-oauth2-proxy
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    client_id: AgAKbZ8PV9vJijScv0tbbGR0eMLOtAKOonzPqsoBQwvmVchzgrG+sxdyoO0q+9B2suQWeEg3sfM64tTfvr3R8VREpo500tiZj/akI4eBHZ0bLcJ0ylqxPThhElsgB9G2ST/gONR1XUBAA1cvstyin7JOuz4+ZqgrO0OdDS64THZQv1VQun1FbQRgCml/JBRfqeWbf+zd8JR398jay9kHENAzuSoXLnA1GI8qOrQAoRBQnE5VDpn6xNad4/kKIwZ3gOAnsHuLeKq6WQjgXt0Izke9KY1BVdy7pe884n2QcydSHbk8pWp3zpZ/0fPjQIbxfoDaq07mNwJzGT2lB2/RgPE3pS5PdS8Fh51VBXTuv+UUnIMXguvJEKVAFpqGB1l/YqmZ4VrWstuNCl6zCbnjmbHX0DXBBji/JFvefenwtlgQIKKwSrI/dVqrcN24lDOExRrSqHJo6kKXI7OBQWyW6SY9RLbqjKmrc0toz/F1QH7pDNW0t6Uq66C4GQWrOiS4QpIPsMsQyukfd7Jx06qcwGNJe+GHDftOMaXgMBJqmmYdMmZZ4b8zH7Xn18CqnPws/UljEuQeLveYEvq8icL28FpT97HH+oJeHTZ6PdAQEdyTvxoVsY2h6GClaQ5tYbAzEHNdP5yMFBbJsVxdOxMlF8f89vzDnE6vtDCGsCtfANw8IFm5m1tLxzIJktxANVUuS56kncFZF9aoXFrtXX8=
    client_secret: AgBl07LUHQ6ivE3iAS5JAS7QdONnG0A6GZttkZ8JpSMYO6HXaV3/mD6pvzbkp6XopZlG3SaKgu6aqvkKrZLToNb0ajgd+ZtpBZVBat0T13vxX3I4uqqFmHNxwMCmJtzlOkW97l6a2I4gFIzdXpQnq9ZOMmnixKCuPY1P86GTfkLcmRb4GENpMoXX/WhPD8klkuiQJ+NxiEZqUO1/X5EPCOmsIa8of3hnznzquZwMtqhc5JqRIWiYgGVVNJkgCRWi6YhqWtQiYqUBn54Uhm6muektoYcW6WVm6F8UmtWjfDwTujWBMA5IIpJ278rTCyp7Dor6xU5nqUj/C+PdJbKYt6JLMbgEafxhVvRAvXhfrasCNMd/a+YpP+Bn5n0i/GUL5QeOfseyHCIlywUj1jNzz/A3yQwpZ8fhd4S0UixiXpdOLYi/wPeRLHlfbpYELmpVZkWU4VRaypU2rN7XRRMj0t936sytSY0R+qURAz2OMzFGGES3CS9w8emb22iTyzpLhPIQ4A8AbKKF2oehTDwjadRdtYElPesOO7MdLXmGPhKSBFUgcdj0Qgp+LlpnDPdpM2LEDTwHh1eCiPU7Bk1rT1f0SzmsbCeEYos9NOVUuyZmqnhhDcl9IYIilEfa8vrBulagtbthZK7yqjEZIWvxIuTalip1Gxg751v1++gstI3AbJvIJeLuwxiGcwF9ydBHPt9lJj9HgahrIf5LyCweZ8naQDjoVCUD+8AOeJiI28Q63g==
  template:
    metadata:
      name: alertmanager-oauth2-proxy
      namespace: kube-prometheus-stack
    type: stringData
