---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-oauth2-proxy
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    client-id: AgCCDz5gXvARykpMZJ0poWCbUGVWKj73N6uSCrmBdhw+AHRt3CMeZ4a7BdCGix4pjuI9H1hDGASLO4qRwiFg98m2HpkE/cIhtV310sUzQqJqfgXufM4/5F4VSkh7Cc/3gi9oxwDLnHjvbDH8feMLy6nYjkstNEhZufV6t+RmCCCnn9ugWOcVMo4v6tY9MBLv4bz04iy28lr0dOgSvLXLFPsnTQXvlR5gwZJFz7w3OrrY98L2aU9WUWMD1NI+81FU286otCJKYQ9FR8JO5O1XhD0Cn8ZyNP9RMt9VIj6cwW4ae+UQMuNpxat3Aa+7P8e7RfxXRii6Yqx9stb0MFO6fUEIQxBy2W/kFO0pchpno7q/QTL3tuBYc7y587ONCklbPRw6Wbvd8VNhLpfgQbS5pJFZAqB18yDhj4OdpgUnqhJAIeA4m2rSYyp4ytB2Hh2s2Wb+NcdHJCV1h7R2S6p3TOwHZnkKkAezrjW8aGdDGABAGKQlPbcupVnssqpA+abuUx9sOzzBdBdW4vXUYtJL/KxrkU+Z0TxmERz5WRQND7yi5/RhNcEzlXE/UfVpSTPRmcH20GoTmjYrgPp71L8TY/20R0XD1V1roj7n8D/tUO3VMcFP4PGuKtcWfhqhTZrdSBj5/Wnn4nV6/pFopZ8mPjMC7Oc6/aMsT6Co4jxwomLEA6gH8X+XMNMKKgw0Ce38X8e+0s8bs/WCZp77WPM=
    client-secret: AgCFrQmMSHQvzfmmnoHq4mAH35/Nyn0msqx69zOeBrrtk0uILAwFWm0rBnv5c+nfu3nn6HSZDYUrbniYHYC+VAV9NOhY2o9K7D5gPI0W0NuQ6Kl2gNSJUh9mUNJk+ymSDTBftvZHkeKD1BaEmXidsdBA8lmLxjpRuji7F7qx3b7XCH6/QV4OJP4tUHx+7cdTYjPablFyM3BEiGdy8jSWZSh+QkiURGG1OR+OIu04UYAmtuFVSJr9CrS6fFAX7Yaoat949U5X1SuOup5etZed5nEoVgTJRiQ5RxKKPGbjTsaWqe9lK8rD/T/0YUgPIATs7BvifqSBkCEa6z5sYVkDObtULhytpMPdRA8mlZtdSySw7+vjV3ji1V+YSuY17Gwlu4qs/cVe/ejQxiUJDDisI8pzJPsoLbdW41SRvy16kHsbDF/sUFUSNmpq2GcNZBvIKcNsmL3V8Mgl7n/YzXsFUgWXOo0nAqaIduIlb1kS/CQ7lU028VgvXQog+AgsKO5c2hQA2UMV03E4XAh5He1yBxsBsuWQ4xqAuz5j46Sm4p2qISniyY1IUY2mdmewYhNajsbSankul5/DOMMJtS9aV6CML3fmU0YyWlUj5SM6g6f21WpRXNYE+06Oo8H+jnh3V/zkaMrwCU2B3buTE+iZPTHwRtPpo8VKehhMUtrD8HePbDP2sl2mUJZK7pGyVqEX8m5D7hPzVaNXyATXcpbsIStleJgZYtIH1zui1blJNM7CNw==
  template:
    metadata:
      name: alertmanager-oauth2-proxy
      namespace: kube-prometheus-stack
    type: stringData
