---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCgBV6nktd7X9klovkBbw9+E+jpkWTDbctoPonP48qUqtfVwX4OYJYGtgrO66yKVwD5/HJzY6J2XPiJ2gU8kVQLTEWX+nnFJsxc9mfszmulbels3azcwRerL3Gv+YBoeTAwApE5NNgya0mOcNjzAMk7vG+KZc72snJ4Rm/iAzboUjO9v+g9pweqQOi/zWWEKcD+qQuH3mhXryVT5pActoD1af3V65vZDNf1HoRqZEJw/Y8EKZ8NH9M3l/EalgCYrzubNev6v9W9fon7tZWm89VKNjmyPltuqCnVPLUqucEzOGK8W35Kk4EDp2dBwtcxz1OwK8m6ElGlkiFETnbm9qlMEIFzC+7fFiEl648BnSPb/OKktFxbMQaMw+VM4SSjdwlJdyBhz8BfcgBr9YOh/9eO/4e+lYIegepHdCzvSxwCwo9Ga23nQHQcs3X9DVFPPg0m+flkCCfcIv9cuZ36K/7q2vXd5CNZ8FSTuY5NM6eoPSffy1xrVynH+fliTwsjVXi8pShhKFVqYNEhk1zrvPe06ChoaWnWGzZdFHpiSfSOqpmf4ZjbYcdIas4EwX/lIYUFp0bqiyHkeAs0PYmvd4zjoA2a67uApCkBKVQ+s09C//PNu/1YUNTo0hr3VJgvQEoWs8+aDVyHitnFA+P5bL4bIn1zbQIdpwPf/7SxfvUsODAAg1amaKDIaUuO4fBffHP2jdWl0EhL
    admin-user: AgCNNEj41tkuC0+XxdgsGn54FE6Ghu7fghI0pO7uT0gbaU5+NCHaEDBJgoXHSlGY5EN0fo7+UQcdKt3Kgz+wRhXhhGjo/fIvIO7JcyY9PznYDOddJPXVq602r2LT1T1kpub5BAz85ds4CUiqAJkHfaANrLyX1d862QrUIRhQBaq+0lvslIQ4L5yqfpk64JhL5lABZpoEXdpkt45UmSnJtGb2NKFC6qIdC+FiLcXwYT23VXF04/6Yc6YXRCtBJGi9pxppoyajFQe4AnUVcLDMcMzLCZ8ryFJYjTFPi4mvN7S4v8ERKMrRrXm2oFREyFJfhZTV29MuAExBVKlBMt1GV4T1cpD1IidVxxr9ZXMd6jhnTx2clANh66bRdiCrU+KYtlXiRxYb99fq3V2srwTDZFPpPSXz19eiwJD7BQ5nUahgSSHa6RL8fYlbCuR0DV0w9yONF5FgRFxWcIFmLrzYrG07x4ETj2NeduON4QFkM+Mn/hnF+z6OQB3trjgZC/qkohw1nrEHEgZxSijCtj73OeRtQHS6wBc2GF/Pah/OScsEi1hcS8gpHjvdmuP/kn1ryTd0p/HKo2XAkU0R6alLRAZpHXA/SZyt7KaWpoZ8kLCYBrXBuVBeGEIsaAIAzDsxxkFUhwW90ADYhqLcGBzIhAwPnYYad23oDgusbwV/Pv4FAkT4Wslsfj7hxwvOqyprBRceildN1A==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
