---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBIpug29lupgC+ddOAg0y6NuJyCgNU8drigBooUtWMFToFMK2XD/dVnSetowN+10i0vkhKXS+j8JoiyLBZOozKfFmGONdIQ5z+xuSYRqNZLpTsmwE73hazwEK1ydUzfcO5gQcGS5DeL1npUMeU0CIysrIBGCcG3VG/zrPQxRjB41IavKWeVBAgV5+9I7JYgR9dtokHp/MnrExYsKWeGb83gsHZ5Q6J7X8WLvk/ORorcr9gr9UudPg3nDJmII3z4HzEe2CzZMU1xPKiXdNma9PxcbmAfqNBzVOaG3ATzJkaaNlyhiVGiDBrrqX5VHhYDTq3EkUO/eeV5krBOQyxNNC1d1XKExnTJ45/TxmnEdWbUUwCpaQ4CsxbIGP27oi/XOVa6UhrM4vzNRCXOI7xmcACItl0Wbp7YJeXiVzD27jW/nkNWPJqoiizenTNr2BzhREiQE4JYex5czYqBOEu+gTnRcngj/k9OaCtJTGQ5HtwEuxUhPftSfaO0MrknHPYRjoW0M/o5vk07b5Y/+eP8MovDy7ndoDrBYQA02d3/K4BqeG2pCvA3nhp4UF1Akc7EffEJb0wvfTfRY1XKfTldD2TsNpMtZ5fvRR/fbWVRzDtyRc7R0Dty+/EuZpzzHpZxqf8ufdvqdparX6xnp9jiGGkN+r9gZc4HD7bSnp3vrQRZzWrJJU6fzrUOLGbimvgu9vywTRIJIXIG
    client-secret: AgCDkr9uhC/z8U6p5JYlN2wRfRnQpDnWWdWt+HZGnB7uSWi3ouegm61U5ZzY8EQEhNKdcNYMkIcwWhjlIFo7Y1jmbsuUSn7k59vy7iKamvwBELaKYz1m+NFr26IWnEdJi4myOOQ24JtPgeE+4cghV6MzzvEEn8SbU2BAK7NszzPjuxMrbMoXUCSkanoSWNpSEDXIeAe9w+L/NBpDDj1+XuAM2YSYZU1RbZ8+hJvnTkLvMPvHKC7WB2xQ51cxfiDEoCnR8s70mC6e+rmm25OagT0rnb6efNosh2xuDxGgWqiUUpTuQMvxBw5q1hIbR20Qr7KWMdfVBPRIdDo/ezM1Y1Chm4bhVOCpZhi3xnJ+nuXRCSNTXsdUKFGfML8tc+JIFAXzNkV0ewU5Y7oqDhM2Bf7lDsof8xlyKUPMVUnEZiyVQNPKVxfzsR2FJC77h8nffJEjgXnsTw0oRutPs4E91GQQHORldC7pBoF3sSonNN3t/I+Sg9T2RJ8hwDosYfrwDABwA1tDuK0dhATeW6cuje4pDX9m8W5CYK2x/71NoAM1jWUezkkGEeepXpc372O8LpY+EZSuCP1+tVmwmmdxQbbaQnLpiQhHJwmDbyp86XYp8f2hIBGARH2lCRr0T+HB37WfKMlL9aTT/d7+dnFla22069PKX8faseqUqllb3CebVO8H66Do7iHlV1zgrcK0zXzs26nWEBRUEaIPg3bDHmwc7fdpjnlnbe8MOtSiGhrEJg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
