---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBHTPjEs2b5vKO3A8hbNYNaa1Uph13hU74rrdQ34JNEFUxBlhMKsJbUovA84/9SI7cxcQJvwZEXs5pSK5r/r7s1TMdmcWgASfytgKAomcjbeDXqzi5Go2A0roDgXmxO15KH8xLZW5IiWORvqpb0TVD1v2AQKYS9++UxjfqFPp7B+zAuzUiY14bdzYkkq3rdfuU/0eE473fTV+EHXWSaXEzx4XvvaxnwpVcS2vorcB8E77myojzZ8C04dzO6MStGPMMKkriooNTmzXqz5eNYXxeIHn9Qzz9XFqpas+gTLrEzPdaQZTn6RP/O3MMv/WqUmH2B9pRqHIZjZfye5veUnzxZvfh+6KQ6ut2r+IAV7NKg7VfKAvtwXq2aToyqzzgaHwHd2Sy8yZ6FhphjvNFrsEJ0UGiNjR6KHwuyYbj/cPn6kwpUscxSOfxTk8XhnldBBLjTh9inOVUGG8LGwzrY7ToWx8jxVZ1XFsmPnush6r4zFV3lY+MLGifJJJmQKyZ6iCKPddA+Z3NuJm8hGc5d1ogxjBtX3YYSWp+UIIy/NYcxJVE5uNcwpqnjmGMgj7jFvpsohgI2sBYaC+90WCOFXeSXbmSGLHglBFAou/rha6YDsj8DeRM/2Z22Bn+GpTnP2Q2mwipT+7R5Ex9lXvRLsy4vaSC1RhhhOC4fHXT/B5UiuPw592jvXqWcyrIHsZOyyZOb9r8wHZ9i
    client-secret: AgBSN5higyQxl7K//xYKrh13S9I0iRZ9LxyxsxO3HS56iklncMa0srFhqfa47qZCXVaOvMTfQICsDyi4+3AXnjmXr84KeNzjBckAY8jSvOloLjc2g9hX/or4UWB1XEkv/koAft9bn+Otm7hmal1rfl9XkUfFNzWD7ncbdI8mNga6d4yQfRyL0D8xcm3mLWmiWxtC4Nl+P0JQ7nkeVUzvPQOggfOintNMpdIjblOR1LOcqoZC5XVLXxlLhIYXJMpNxCNlBeV8RLoRB5EY0mvR/HyKfN+RsdS6FlGRTo6Wvpx8L14s242dc6ECt0VdnxkaaFxJt5XvUyGX8KIUD0aHSKUq/y/Yd0dcvcYZAxOe0kDQ7wwcCXsgeydg+03zpV/4xrRTBuAAlrsLj0WzE03ARSD4HqiJ6w/7Z7RFp67+z19vq3I6P3LP99UJpcBTOx5lqX6R95R0kPXKpkq/YCBj0etzN77VDAvSrCC85CAU88vtHw++GHPFi+jl2egD9nttaoxPhRpM9VMTYrRL3oRBsXhPVgn2qmjA4h79DHBvTWftdLBDGORvspIlnWNRQcxNJQ8R3OnqbfYlaH/1Um9MkNmu8Ow8hUwDaR+Ak5cvNxFtLt7wrFKP9f6D5E3l5pJUz0Oms6g6U7XO+RvLoHg8vmwh0torPVBIvqHpLih3Ivya5YUwsXgcm9K7xH13+WkZWDrz+zHDRE2jbxSQO9Elf+VE0fWhbuq9LJJP0Sk22OLUkg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
