---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAdExf4RemPeL/m9aY/Up1s5crtiv4LNujJtN48mtn8hz94g0w/r2QU6BMsMZpT2tHeJ7l+dVHQ7E5gfs7gRuVgjxLgef3UILWBNyQX9WXnshrnNFw2c2wB9I7caBFOpIETg48oe9K2hxQyV0QWFnkeq/+s9BWJtFraD/XNEDpd4yS3un8NaczjrX5pX5T7Wowo3cYFAePi475l1jgObt3BIDnz9pTNrbqqZ62txcMpf5tfI4yaeS97MfxujQFuMIwdHnGIzqvUAJ7lBFnuG2IwZFmdYPQAT4J37/Dctw/Eidv7UsMcii0Q86XVHE1Czgp3pJpkJjiZzcXTJW1nocpxI2brq5hryApa2lDFEo4RoklLGeboJvFBzjXPGS092gTy+raOwFlLOdwuJ++xwL5852ThOCtPpGZcAz2ka0cq0tdMdMYQG3zaKrycoxfoBOl07sj4YX24760MHQNRIkej9pUPSTlAA6z1zAJcQe1e5KF6V5PZhEMB1SreyO/kQtnM6Dhr0kU51gPlk7VHnihJT5eTBeFEZ/haULalsDQ/bpsKFJQy4cMImOPULcoY8fzos2lp/xITbFLuwyqz+cxSq9+Z2BscrQZkm4mukjKnAok+fdoPGUnTZJqEld1GyZEw/vhd+9DSo4r3SHpyg746hVwU28ukJ70XslYMemdfqm7pCZFYt9XjKvqwfxR2Bdog9f+9oEqr
    client-secret: AgAXeOhnwApM4FRTxuispXn1ntbQIfl44vrqoCs4t3n8zkql7C1LKmvXQletxqPgV1lPIScMfkkLg1t/F30WzEj1xrxkp2snoTJ8+CAazjjo88WtKNOYQ45U8z5Uvfnt3Er9qYyTG+sR6zQiHrw1tROzCyuQFSEGA0U+ZAZ9VFCJLgk5Axuy4KIEuTgohOih22/UK+JhHC8POQTMetUfUZ/1eWFiY/P3H2vw6A2PEZ+rieI54484Q8eHsxZ03MM/4mZZbt6PoTLKcVNNab//mT4nGwRCE2VXkc1mSv///7ulRvk/gBv65UlF7nQ8t5mRYObcQ9W5v+0SzPcaiqFZ0wxOFLNu7So4B1rvKERwgCxUvL1GQxheL3zIysDMFaJ1ysGef2HeWT7ZiZvmcvKMaIQjsVwBnbSUGDeolndjIH+k/cRN7nGuKMiENlA8ldd0a4XiZVZS0rxi918X7yeYbkpBnVth/su2cNjXN6AJMbMUgNrp4moBeOOwmP4W4C0KS5MSlOVp81ZAKjQOK/1S9tgK1TfnZCa+Xg1XR+L5M7c9TigM5IgzBdpqmAZB5Yg5RzbAMjH+r5XC6WR9FAaiWp8wSLhBRktXviUyMIRdNhqxMgQAtrNu1nbexs9XxCKk/urk+V1MqJmw/qYQo65JFE6wC0nCd+zuDCYijRoTlIVNayfMvXheWuW12IZ/GrhN+fNQVd4x37bYbgncMs7864tSET2Z5rmtLW8mC+ho2phpqQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
