---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBgaN378BQCdozoKVq9cSPvNtDIjd+x78HasR4q2mnRloDboOJd68vKNoarkq6kbm+6G4E3Mb1JwXVGtKBm54MXbuJAGwrcZM8DbGXM/L0q5x0twX5bZ726Pq1Gt4/IQ6qJRvuJuGivXN5hhu8IPjpK7XHgtwkm7IqftKq45Xnr86lfDdVv5ozlBuvTH7bYJFvSUIqZPCCVYsfYt8SRN9XcpE7+RrG5WZqBD1LNqvEZkCDWxnusRuGnnpGEZ/CG3RDjEu0bxKqCEg4vd56Km9TNJT6cAuoowOTBOIxxr8Yugz4+wuFUHXRwyut7RU+Zne+Gf5uz58nQYRuEBReV19kSNRyUVQY1JDTNbKGmDdP40HofpFUvQYpAOMBm4vct6SIhFwdpilc/uaTx37E1G9icWnpWnGmV4kViWat5C5uGGbYGLOoBoGDAVE+l7TdLQiCTsP72XPYorceg99aH6n/k3QLsw14DQyl7d4VadeAKqBU9QOsXk0BFZvhNzw1BrBJ/ZhrPSWBmGNpBaRJflPkA93MGcYOP4iY+V20MVs6Hcgo0Rd2U0JL9Z6guilzPK1TsIOXfMR33HUHO6z/1bleAVmEtowIU6/Xi901V5MukMEgzrrFmxb8jHw2OmrBNjDGAwBPMPigHGEybbyyu/pS/H5xx39x6RR+R7uArIRvx9YIuMerxAmfbtO18BNPE4+yD9Ig405yw
    client-secret: AgAV81RGGKG7+K2A/NS+oyX0aM0OyA7yZOwC0h6aJNmmhNgYivYR5wzysP5IVBLHhToCPaFI0dmbKmMIx0F6+DZ1UWiPww2ddqVk05ohDVrlRVf4MoeGGqvQkvqB88vTAtTxgEFS39xkUJXuXUw1s1bAWbm6mDOVxWPi5Ba1HXvkdj11epIYlDTWOdfjxvRE8XCYoN5TmeNiOXDwwdRvpwa6oS+OZY9t0YQ4suFnM1pSHW4+qzY+TqqmTw10XYh+Wo4VAurhoqeCRaakK9ZHNp8pjb+X8r/akdlifmAy5C3qSzEuhoQksDO4XpfCH5rxatCfG4tKqiz3Sho5dRArbT5MDSo0J+Nsh2XGYjjhPBsPEPknSAMJelPcPT3vUGwhMYLmnaOgyCvxi49i/yCCPqF2lk22MVw4HXvBj/llwDJ7xFKyR+AbVK9S7uunjAbZizaAG8aOh9thIOENWhd2Z1kBVBxtrGEc9AYmPRhRBjSbvF13Hw5wsja8bDCXJLylxDguDH829+NLJrUlJlSUd4apfdw/jjnXp2bJsf7+O8syl0q7GhzsbuNop+4/xlTxx4jk7LuiyuVzgPwBYoFLTEq3104PVJwfFlvQP6JTAHQj9UN5D+Ou90SwAFQPfXgGgwraowAPAJjN3TnUhlOD6/mKYLq7LvaiOx4+1oQT/tbzB/GkDzkLUjxBq65GY6oEpGeoh/alnE0n19cyhBC2VE++lvAb+iE9/vZVja6zuGfyRg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
