---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBy3fTf8X8Ue1iIJC2M3R3NvwdqUa+hVNMKd+STKR4pgQ+Yns6ytGjFas6tWAlkBXQzLmGx4XCvrsXR/IZqOQAY+rCiUPIaDqwuK+KZU7nSMfGTN7tu3nJZkAcnkZbJS1cOgord1eg73TdGQw5ExGA0lZ28OarVkfQ/vjpEUGITuC01QEctv/iCNc4ar3V8wuSvpyZrsGal30/fP1F56cKXra1J+SWY2l2Gwr5jT6X86Woat9ixCN5Bq/cI5GMA5E5KfdOXNDd9z6+2lIj3fbWg4+1tE8CT9iJn+kgpQacOkOH+7ZGFIf5AeXIyfqDI4c9NZIHf4X7tCkv2Gvn2rzBOWQdNvJMxh+bjuP4yxppWAZsCY058xMqD8s6Nbc5MTa9hdwHTeXupfxL4AaCFFSNtcWtIwmcFrF6Qdr/FlyOejM2XaqM3HYMDuwyfxRmMhaiqrC9NYhYO+59Hfsuq414iI1FcbsIFWw0EHk4emYutQ/+oMzRRspNdVbaLbPnodZKe8BG/vdmei4/hfUT8Kf9NbBd+qnP/7XRuRv0ZT2svHPzp3H1GX1p2yzI0Ylk0l6WL8bD1bIFk/QSwgMG+NfsyY/JwxuO0V5o7Rdkvbh2SPUoQmp5kFQkEwSXhWcKc2z6fAH6xj5foypm+mHzNmK/qOZXYwJv95JimMKX3j13xdgTFWIGRieQVBF3MJdtxVSQ/4Kjrkflb
    admin-user: AgB+f0c2u+eCXHroXa7LVuXKaPp8IKjnBakh9BJoQ4mxBzSVJWjdRlxj368mDzVQAF2hCdrX/Kh88TCdXEOpBSQ6CSezq8a8HmLDmzInVRFZEqTKTqZgNKP1IBX5VDi0nrIiqtbwXFHv4pZ9A54rHm0i8VNRtjShMFvevtggArRqKFMEfQAOa999WKnFEpj4z0vzKZKYA59AH51BEGD310xmtzZBfkSdh1tcGFIACx69ZPUYmv7aauiFsqT/AVoX9mRBXH3VDipi5lDC+Ln8PPNoVgcYITIDEl17ReQIs+H/R3EpsVi1+fnsy4aET0BYwWlTPw6wPdLGxsyO7tlkXSwf0Rp/QNMmtbLkjzlC+G8F6A9W4GxrkxsrMjJCxGSX+RAibKCAe9ewJ4K61fx8KCQqDkw35t1HfDpMj5LDwjhu6CjKaKapgGcmBVgj8HuF7C8Sje5JZwHkRQZTkXzCAEFMoeu/eqRfU8U0s81YcYCiQMJ96ih8uQ3bmPvyOoMJvFGxTGmX10Nh9mqjQxs95B1fgBZ5GFHVim2a69GvDJi+/ZYcoIs7W64r2Q6hEylNsd4GH6o1yQSOdfqB43ugEwCyUp6Hz6/LLFj1MLwRnviUbOVbvbPvHDA1J11V1B+iuB65QazNSu2uJR5bNWG2Z2rWqRlA90TZB9xYea6XBiyYzMcHj1xxk+kjewP9ZxtyewM7VeJi+A==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
