---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgC7aUPbbGToW4ToQVbuTzGBAMSa0ampo79EERlhnlz7hiTdUKTOSvEok+gAXInysvrAYV0xZGq5mIUxKEkaR5Wu2GXndyXVUKrfqBOJN5yzTJSuUzABkRvrVZvoIERbNyAbIXaMFWw3qHKsyCZv645KeB4Am00lr/SiUw13zYNz18bAapJa4Q+B13vbpJk4gt2OpVQRu2Vsz/an/T+r3oGthHvn/D2t5HnHjyLzch27N96/V1WluHcZtc2F0T3JeGjTcEUSC+Bve5ay+gjhJALTxiyYWB/kKMezthFLgxV298lryWm8CqY4un6i8q+96Lx29vOZoY2y0T3aJugMqKqAYoTlqPnuxVKUmbLlNGD/UVpaRQCX+WnRkvlnnAPiMAsdUaEejamIJZdmakJq1flyTtXsRZod7MjZ4PnmggSXp0CZkfhRbPHUwA7hWspRszuJoH7BC/UWyvh/VsWcmbydrYPRwxRFbAd4du5DJPZvJlUwVq5gWKmQBcZnuwKt6axwRJEqkxKLM8Jc8inEpDeJ0IXHhG9tPAKnQwdu2t5jtMMY/gj0okOYYEzMsbA5IWWh5hjc+nGELbWCcwVtbjlXcLxcDn9RtRB0Ct54OYdRIzjr5zOqj16Dlxi1NW8EyxsR4NkPh3hfJhqhHR4FYYv+rcBOkepLmrh9FT30kFTDUUq7Wdj8xL2jG3+o8VmwbK1bQWonoMwD
    client-secret: AgBS4fmEtbmNFhOcAc+4Uw65Yb+fJJJs0vxocAb1gasvX3/NUSBA+vP0YLvZSaZJAs07UTbg3jRM6BA9QQCz4yswWSF75YOHsCTOOCYvA6GUVQ9u22/KP+H9MItv57zRDqZs4/B1tO2NGaTzPtsrSnj5w9N3QXopWG4wza271pLnHQOHUVBGe7RvYu2bXrvXVpN8hoDFaXMmhA49qJbOEoQqt8T/WTQ3SeM65DW0kEgmK4NR2qU2MyE8PDPHqx2+Of85rOHKDLJPnPlieKsNwi9xEKyIADnvVoMMoL3U5tLlv7bbQ2DX5Pm44dicA8zyEsagH/vqB/ZI4JFlvORFugvrjyhHkCawj5CdBHgfwn+XVP2XZByi86AXJRi30/iTkDKG9V4smojydXEZYcqYON3X7uBkfS94gx76hShmWYAT+nmZvNJDFHbfubLayBk5mYOf24bzHuF39TgZ4BsaP6XmSrA6BPJUpbSIwhR6hF3+yEo0EQBTosUOwqp1oSAOoHLyirRacjaCpWPjnXoZY/itOduq8bAjYcWSU7/IMFAaHpjseArzu5DyxIyIxQACoVBRimvsu5lZ2ANXoA5xsi7XfEIU+GmoKjCLdNh8Z7jk8RgJ9SG7iod59KLsIZgFoc/Je+Vx+XUTGSwGBaPxzRzUH6R4u0Euj/q5QMmvW9wqqSmW0f8m+VJYf4R+OwBaYICLjgO4Nqdw2wyE3dnSjfWLLwqvdkNKfB5Cvi/r8wecHQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
