---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgA2ICNKpP1MPjvXmEb9FKJSnhbYcqXaYuWzrUDfgoUKl+yvl6nZkhla92UrAdbCXUvo/nSFXukZo2Fm9S1S66SOt2NV3l+xa/EDlrqqxsNq9DIr8Kis+tax2RZbA4++hzRyelWdVaL4ilg3DL5suL6RTjkNTy5Nm/n1vwLIUFOsJgr1YRqSy9T4pH4cnKsGCNopYgZkLGlk6n3CYvU9OAqBlfMIZNiFWxKc7p7BvLXrxbtxgfOwTEn55v8KBayg8nv2X1GGIDEvxT4QCVPwbLKgoKubKhC4nwQ/6yYxfjaSN09tcIV9PVtETCoxJxPZcAAtG+XwITnk1PDeqnl4ytZIr7Qmi8LsGLWdVXC6JfIqQSO0gbNZzkdTaszOOmoIm11kQvC02s818jltadNAeOubzH2FP1rT/8PRSHz1cehYZxrZL7o0sdLS7Y2uuHo0NfwDXEF6B7TqihtoMrqGhuxYNIs8xORMMnr8TVHdw4gWbINFslphp+ICP/TefjYojvXJvAkm5UyMkcVW0cMypPgbVc24QL+zRrbYZhgQ7LOXI72Y9rX0RmJ0NG9U0dHJat/zu+t1+MieDii9ZSRXjQhOQSoNaq13eql6ceCEZ5bOMxmUW5qen6OnRuxJi75HwkfcsL8TB2p9FjUAwSl/8PffV1a3f+LEQ8FTLKPbCaGRMv7n+K8RKJH0hNUpGNDFS16z4Nw7ko4H
    admin-user: AgB+NjPhuzjv4HyAzMNxdOenJ10Rzg2ic5QRGtXKTMyH9RrffQ/LtXlRXFtBEzWVXimVP3KGPvcuMun0cF2m9YZjUBZ8SqMuUopw8gIRohLHdKZe5fniT7hiYyUMq2aQKBHC1pgsPnx7Rgcktg3Ykx58ZdBjuBonDYTs6F2iHYxEDSGoDo1VqFmSpTMiB7vGp1iv+x5NgBjU11szw8stMP/GqWW2xJNDGEWf54gX9H8VBFyHg7CDetX3sw2PyNx3fMVG8JmqRUYMa4Id8WYu/YWAmk1uTgGO2t5y18YVNAfR0oAxvPMOPIPXgbY4lKLhxr9wk+FASjhnToL+aGy65acpfbOxlvAuma+UDmB5vcER8oQ4VdICx5qEbzF6y8BhKfxzSA0kCg3FmW7uwT2floMc9p7ffIArrhwYYpwUY571uKLUL6lXWBHM8Wq+r7c/CEy26SzdVisnBlSISgQuQcDms9CnHTIihmb2BI9y8pDzM/KNNFUvYLVbh5d30mJLcQpmAIykSCQ3/y1gg759Ge9WmOf6/Pkptqmecphsf0FVMlFh0BkOJCne2HnmItnnFzCfDlCic1rqgrjAkh+VjndQ0JUTiLX/slcn/jhr4/w5LJlikfyNW/xRq+SJ5sgLgMlmnNSJB9AgqmNogrq8W05/9FA69yoG4uRZ2LgTDdpo2+sHnwrf5VsRh3grJoxx0n3ADICVaw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
