---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCSA6BeqKWWI3E230aoyHL55UIbh7HLQq+DC98+HXp9BjKnnknxldL2b6U8NtDsAnoo4JJNhtMZcwRj190RMc4e6gJ/Es8/llLcehzMslgM9Zk9n8wZ/fJukbOxUoNt/1RUSwdoiPWz20uqGxjz1BWbq0UCzrSC4r78GaSGqriIoXMEhtv+bqumoGMO3MXHEDOsvQPGShkjZe2C9YhAsornB99zxlkGIJtAZ9VVeVsPQQKG9E4iT1+gHdf1q2SDO71vDdMEngK+gI7qRNfNPhXyKoJtQwbUu2ntDWFZ1SBSi5Kzn26X7wbBjFbQU/ue86UUh5MK1pOQ5WHL18kuCkZ8vKmgp9kEQFsuZTXvBcwBgFdegYpAP/bX6dFQw4dS8zBYigUqa65QjRbIu5qfXtIUpDRZeZGv+Bz/fvs3llXqbxhO+vqCMEmJsmxTp/8fMGGzd35JrH39ImR6qSi9Ylms7N7ORcPtC17ESFMwMpv+2iMIMy39PN49ctCfKb55dvExBOG531fRo0RR0Z4KYkJUvFghAwf7Wc74Un7M4zMYZ4RaCrRiGZlLZ5C8D/y5tDht3dJeTYRoxEla4p+Gkvrf3otvtMIA1HPxLDlH/rUt7Y8p6wiuQHjHGewIAX9Bs8VXjWk319rPaxvjl4lfA+9oWRIw9LJavIsa5Ll/goDVMQSbtORvVQekMi/5SjLLwB4oapVQvI/s
    admin-user: AgArDOUG4WlRSY4FIYkB31WW7mN5Sth3gFb0PIVrMp6IGVwwwxVgRyjxJSbItlodFGVycr2uAOh2RvTp3Ad+JBoeIDfqUQSOn+YLBHR2QccnsCJM3umADNtl1/dwsKI+vkvT3ymWO1GkgKNYyKghcwC1kzIcUBuIze35anBVmBlQKcYsY908y7D1wABy+HtjZTligm/yqw96Mi8JOlsFdW7PC9CkCja/PDVlkTMSAWxAaL86xxha+LDWgDxeSRiwpowyPdHpS5DRXmNtW4fPBLAoPIQduIstpQaEB844pX1LsO9596arGS4X3mR2MBPMy3yFeqkBFSBGE2RIA18xHBJkRLnh3esJDgI7hcbu54oIvep/g3+NILcC1OOl0YLxiOa0a5GNexPZ8CF2i7qgCUxyPn6YuVAt8TPL3CY+5FRgsMO1mZkPs9mGP/QaBlZjnycnpr/8wkqMWi3NRRnhjXcgoNxe3qREmwH/xGBQMpGkOzScxfBMYFsgKWykHXqVCMvLRbC/0zZ5UKjnXNQvkGz71VPRSa/tu3vvXIL4RWlJ1pRjN5k+h2W9ZXp+FPp6AB3T/PWz+EJuD3NWw02uMkOWcNi9JR281vEZtwdlaPvl9GMH3AKMkDcO4JS/R2NVghmLQmQgLSWKJKpSuQHGHQGacbLfmsnmHaLVsH3+Ru+u7zzrajBhlh5eepU5W0K/0HOKTLeiZw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
