---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCw9wRRggfhgfuUQfuuBDDAu/3RtOl/Ii1qPLXVYJA7hCgOJ2jWjuHGLd1JUXPV4+HLx+KoTJ8X9unwAIqYx7Yd5cB0wuqF/by5Uw7AWz0Ycfr50HAcRYAUHrB3JJZUuLp//nYdrO2C6eYZDqpaCkF10rUEU2DbRvrd1lfSYYUfXWeTLMo7c12uAbkR/Qq2nWtErUTBC/6k93W4dhOtYYUrL6MhR7wbhzn6WJByr/6n0IbMd5eckAX13tdUf7GwUiGNo//k30Z74NBovEIfYTmCbM0dDEVBRjBSq7C9dsAzZahcNiIBcUaxj1sHri8Mcfto9/EjqHCUt/kuq5wxUcadhtPD4qwyAMTSE8y8zJXRlUiK1YL0IkSGdH8LcbIO9S3/CJUIBF0Cgkvu3b4O0oMTpyh9+/7DKjXcgke4ONj52AnGEs5cWVUyv5fQ2jv3ZD2crHkCOz3WesfPfVs5jHKs5w83Nz2UAIJRDITTYu1xt0e3A0WTnpxub70609Ywyy3agtoBOb0jML9TkRmaidk4bGCh+5suVZnT23EHAVs2U5c/a259b2COf9X3+EoRkqEoTakfzPrXchhnhPiFX0Zx96caxOAH0vPmfOhuAv/tAyTHDtLvnjS+XceiJ3aEndwbaaHPIrdOhQ9crFQcyZYzyw7QvWzXVz2Os4vVz5pFu1xGKWRF8Nv91yr4THA1bruGfqkDL2nx
    admin-user: AgAD3mGzZJoUNKc1XtXbXDAINg4sybglh1i5pnlUFag/3MtkgnEPLvWItkxBP2RV8FVzun2GoGPeWewMKCOg3vaEoSNk2Oy2855rRzzC+cXa1jLrMwTBZYwurzr1FA7rYIJgF1ZoZwB+pxd713zhcedCsP6ix2PekjwPO8oOxyShjb6N6Qe6bUGu3WbQ4HfXxwMvCyd3lUp6VXwPUOSrIorplf/GKqqfghD/Gl1wjCjEoB4nrtj4RTqD8AavtVbr6ASFiUwdjwETIfpBmDQc/ZE+K/c3iEtNG8PO/a/A8hCxeFMGpoBw3DXtP5+61FMwjTk2FJEgLZKAVN7P+YJNKNhH8AsDm6rHqnjd33dwKWN1yLDMXLYoPfnFs4upzJe0SLjufQEFCZJac+Dws8e42Dv/uN3CwH3W5mU+ctk1PsBB4fit2JeXwM986jjibU9k+sydOuYcz7l9wDdVTUtAJKeA6thPTTV/jdHxB+QkD9fq8dDMQse8pyVUX2Gqwr7ALHKXTnwgghmGnQf4vIvYPj8j31CfKN1tX1pYZlZxo+xB41SCmBEo6X4P4PCr6z/0tdxqiNdibuXDUADv8vOjGafqtyXaIfOBb0DIGviyG8xJA7SPjIf5u2mhHP9gEBijBExbPLORmtNZIhXtO4hO1/vgphas+aQRbBlRc8HPcWXh2m4yqhN3hbK8dr1qfnIJfq+goyOE6Q==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
