---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCOal83sqSyN47MgO6YgUyYYNW/cTy6jaKv7n/bxS91OF1as+rgt6inOnEElPy/IxUidf0HIYyIvVonNRD/Kpn3dOMT85/jog7kNo6KlWL7bxvV0HikxZgVgeFxPEbqF6rGFv/oPWRnoFXXvr7+iW6R7vwV37Q/wWRUqzkiQfAMqtgNeConOhhub2W0MVVarT5CXZ+oMTrU3efTg8HDzvL272wj35dp17mnuzDz1QJ5Hxb1kiwUTCY20siO7lSYA5kilNPFS3PW4j6etXsioFnYnKHpi0/0j6lECN8v7KMycpUl5bukyomb47VJ/JVZXPFQYK2GiuNVMvxBMkpbetPkMC0kTb4D/Ohc3HI5A7j097gHZGrUpI82sdxU5n70QnUJZONG+a9CYPNZjmJ0ttvJPKCeDdwMW4WK2cMyHBRcV6MhU4B/0luBin4MwLwqhomRnz39d3QZhO19zzW0iY9Rs73e5NOA87RgxJr4kHRycv9RHNkPaZt7YSHCDfoBmzGShJAcdbP3OkQHrt/D1j9hLfrgkOW0Y1QUcdonkTm4vbA1Knqv2q8WlM/9U41mDpDzVDSXXQ/eyGrz3ZcuQIUWfWKiAdK6hk1DXbV/HYYWcZKOqYR/zmTi5iIlHz4WrZGZlUOmWiXFtJ/92J73g73zJQtOeYqf9RWrK4pIpefuqebdSddCm2nw6sX/pTO15bii8SnWA8jE
    admin-user: AgCKaKxroxd3TV2CD1ajgXGOjdYOxhj5ztnu4ypUkdz+6lOonNlKvcQZKwgO/LfYRGgM7HYVedTXecT/xLtTL1jtH352JiuLLwhsqaS8Q2Earm/8cHy5j4KuljWOTbFlgYdEDJ3pNLRYfwyXH4lkpCgGiZBJ+XrvCpsH9V346XEpf7fH64JkaqG6IYRaBmo8WU/5H8n6M0deiZrg/vNOZr/2ode22VrvqBnl9BjSF8rXZfYechqXNqi5T82jztvIEbXUf42DylRB6P/VE2aUuG9Swlsc/ZHncFhyc2NuJ/O++UTjlHnrOmKfrS1W5X2u/0wsHvD1iGIvgkjcd3b4aYV7LNvRjTZR37qRVhpltyjmBV8kkvFTD8zrQ/wmYEAEk1u1dXebKvpBiivyX2KlQVW0DtAneA2Po2e+NSVic99wa/awTr8KBJekujpV98e+KJjCAcwQ1X4PX4uwM2+szX76WOlVb3tHSflgKmeUBI0vRpEN7KAo2x2sjfLHgZ2OG0qygT/LIgmuZSGCV+tIqSVqZhjeJ0rYX8bHCh2ss2c+AQShj+XcGpHw6RdUd6rWPSg4s4DtlbJ1Yj12ZSBP5OHLMjoteTqiPExubkiROJflOKlZqrLmzlDodB/KjvMoj1QiClqg3wnKIohE0C1QFH3VVXw5O/j6uL+G3/CghVMzovcmV9CUcrAWKZWNLdA9E3iy0OpDmA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
