---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAmMJotwzqFhaRc/foDYbdc8l+X0jlq2sLGIqBFCDshJGiQVYGqoo79RS68C8MS110Th/pMIV3aNPH71rSEtyXxVOzHo4Zdb4tahBRpvHg8YLEFcqWe/lq7eHYBN6fkqsa5wymECuIXncTKlF3Q3FxrqO6cRn7eb6LhOc/iyU8qBY31j8OCO6TLeRFmIzyFOjrFzyzaWZHoZ6Hu57JvObeD4MeEz+VIyAbPAqoRezjgFh7jzHOWwIrupDfuJCPaSVv73ADJ5bPsm3lFF+TKlLClV8pfzi3UU6rgOEE4wOh4RgSrAsTfd5EDQvRpGyHE/Jc8ItfFGgic9bowlA+dzh+mnDbIHVe28Qzo/NCYYp8LXhulQL2jnfOKZXjmJGyUgbMw/n9i/onx7krF+oAhFy0zb1a4dsi1yectdpHcoqmX3QpVs1s1GjgwZAl+8LRhSLxhoeiqUU4JTVEwLrTX5UiY8Pr0ph4c3tCvrxU0/qob+CPOHi8xbAJFdfjtpLuSBANlv9r5RTHtt1UCfUYmBoCdMLdii1Ot8Z+899Eg10GeuENb2G2kBMvj3jitlsblDoGNebp9WYBxpsyzFKozYjJcIq0LsfjO8C2d3kmpCWia5KcKJr1Nd5M63REHapevf6UpWQLW0h23k+nZXDujRBxilMmfmJGKEGl3sl6A4yW0PHiul3c5UUzwX3T3/uD3McHPjuOcrMTt
    admin-user: AgCcXRC0w9H8zx/dMxaDmCIJszYoFE5vGiPb1k/VkSm6TyrJBVwRjNnkYf44HpyHAlcgxrB2R4PeuNHqsKtIRkzRWiCL2sBoYNpFtWjmAmxKtBXmVXplq7uszmkvgMkX0SJMlc8meD/fzlaYqzJuG4s/bf/yOP610u+6Vo7KFDqLEWnS1KV4mUyLjZz3NNGFq4D8AuLb8RcCPkt255ZytFdTUCjl9Osi8+7NqrWYeKVljEeqHCoF1VBXzq/qd2571NKf+eHjUl63bna6iFWvSBLOj4HQnaYmQCjcZNXyjZv5lkikWCNu1eKetx5ZgK6ARUZFsDng58LcpTRf3o9eu+ymr/FqopBjKRqTMg5le6K+6I3Ic0kkxnZCBSZum5DG5Mi2Lz/O8x9BW3pUeuDEJ13P65pUJtLYhXmew1h5vGoHEzYqw6zp+NkXRkczvGQsDHSulclLQdAWdAUJ9Fr8b++nuCNJWrOOkLVfK0x1LxqCoAK15LviKdqJ4QDBufPYzztdW5mLrWerpGwVrIUxOzs0M8HEUerktk4zRmVHOE9lRqN88mvzWHug7v8LhSR208FLmycNv1UhZOiTKGWkoDW88CzvMn1UtFoG1PQFpdocdlz8gwCtnTl7ptCmXYUi9krxSEKYKZtbfmYAg7hwrQbPckLnFKXNZbks3PlOgX/9xSPKKs1Hf5kYqzZuh7a77gpXLXTQSA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
