---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAQtiIdq6k+YdNEBk3xqcr2ah0x38nEn7ExLXhTpsL0sAEhvh+kA8rbyB/zjY9229kxIirsHf+mrSkNQmGVMhEdMTWOyQNB7nxDYSrAqqcnhimHFqSPbkMJue+X9URLEbjER33UxB3eqiA2VGNlyQdOtlvOjaPpBgqNQ5MgsHL6F/z4qfOW6BHwbABAPvpgXMnavHA50WzLJPGfex5eDJPXhorAaALDtLC+agSGfh3Ysvo6epXj/Zr9uvGrZ7yFLHq9iioFMpxCTaX+wF6weatXTfucfWTGYBo927ModBaHPlODn6yjZpziat9DSXVmSIClRM4vxJ6tlmMNpl/2Jk+l79V0Uv+8za6ZguXpuwz7sX5wLX+w97pAHN2ONSWW5S/4WxkDu9KGHNRR5oW2J+KNJqzTWtovq5XSLctarUNlsA+cHm+KnXNhzj5zHAZ07NmAWRWpUqz/hwGkFv1snH5qPZGJLlqo3G1yoULtD8hmJXMYD8CDsSJ3DmWHBWqIo/KZGhiW9QaRKR+ojUDLc0p/7SVgcdBU8H+dJkWpLxzdRVBbwL1gKDPyRgLs7XGvpQI/xcJwaoU9sDTr/apgdMXYPZJR+yqbLhE56Oddmg73WaGtuO4TOd1xw99CFDto+YB5spgmyGhlf8hODEv9lfI+FGMe3bnP2xur3ooO0/3Tf1lI2gFUA6gEDFfwb/653eDetwDLb44N
    client-secret: AgDCjkcRbccrxXyM5p2P6/ON4gvGSnXxwgLZuWkjkvs5FMyJeG5rAD9SY6aSSgLMfvTZ/KnkDYmN5PkYklX/Egqm3F8Aa8/Gj4vmVtk4eT4rwdhoQsKJDUJsw1WfQIgDzARzxYWMq/sw9308CObgX5QdJa2+8alDBNtgc9Ug533ehOrb4TXH3vl5x3t8C4txgSL6f/A1FbjMHfven+EaaomkM7CeEQEGEq/+UbyGYZQN7NmbEbMJQyVeXHa+0ZNwtV7o/KfpsUMJQ06G7eyIKqpNXUHqaBJNhJ6KpnVIdCDXhIxp1hPxNE8Ag7U5Um2/0jSxdnpyRvEs6z2+LeCVtmPvEYrTqFpnK+07DMkSzt7xe/bg2PqNLh/mGFWqKPZ9kVeb6Moz0Cxm+70CBW1U+crXjH0jXPq04cHgu0mIJ9zk3q5PopOcRJNNRNZW5zU6yCvqyAYfCb5yL+QTshBh52q6AFn7Wt6kRjUVxbHW5Yj/+6oqen/8kxQ98TJMAXDq2gnC6+hs7c10l9mBTVuq1o9YNZqsycxe2lJ1eslzFfCWZWKy27LNffqGvbh3EmgN02+aHhKsVvJqq/jPixJGiHHkiO2k3tEWfwqzjZfzRLkkmd+viZFUYS38QfHH0SxXPBgvK4o0aPA2TVdUWiuqVlrouXiVEPT/6NqLXTyk4cl2sWbDxXDAfvkmuoMDOTEhWkHFVvKZimeHfM9iQnvFkTc2lNBOVN4inNRLqbHG9tBm/Q==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
