---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgASq2HQPcV2u0TyTIEc5HnSxSxZvQtnNHdPemZqsGk+87W4xbLsnyFr5KcdOdb6bK7+aPk0A818qir39yMTH4z94kKU4RDAFQ3a1jL+kVC16e+ruZlMiFh1BCBRNtjbijus9w1BQK1Mg+nKeN7JrO+bVhJnlqNlbS1aqkwH46EMvYLWT8ofleNrtc7BO6uSGcnS/6Brk/lNLOzOwE0AQDTllayyC/SIoh5z1XzVB3rMyJ2EZjqnHt46zyOMP+J45R7FgvITRp3hOEvgd9HA7f54hF+qnLZauL1SiKEB7r7H2aWmwdQVollkY/rXiqkm5xNkrCYEm9a9436JsJRF6tl7JvSBiSBMX/C/v1lFvfIKac9gUq9sCGlZXndJjTDNtB2e6aQ5AG8c0RUMh2vJvI7MDZeBSUyDOO494inlkbRC7704oNH8gn6GZh5mDq8a9+s7KL3VR6pQZDphGWs98vcxDWaWyv/TdfN01qJIn7ndv1+OvhSMSXhHpA1Fwet5udyoUWEhZqz+HJLjHnuoKMrfjkqWqkChAjnVjbZKuBbT5Hj/t/lAFX9I5oBbhA5lusGepnvCsfCWx4HEGNrpW9v1aIXPYIGfRjUUcjTSQc3DOszpr3ZqQRpBU5KofR2xv7l4HTnKtukvZL7Nujj8zAK5zR3pn5W0U2w/6wF2plPhHiKk6jUxEx8p1Y2G+bYTd3FjU35LXM+0
    client-secret: AgCZ8aNC4rRRe1CwVb2a70qK5ImoRcWqYJDzDgQ6xJZQJW3ItTbs4n85nVWK6nt9mn2s+nTht1IxiuqmC2WZkw+dvoDKzPWZ/vYAjsV0wuTCDOJH1jMCOpYvEd6qeaByr1yFwFuKjztoy5qWb0L0LXlPax1FthGi/+AiVZZLpes1T+91OQt6OvZc7PVorugtOaGEb/ORt2FabXwlX2NnUFbE92Dzic2DdMZbycsv5m1+n6+zqmUbyHHKKVQuaCshuJYJqXvKbI/dJ2bRz80VQ+mi/avoeaThscADoN/Rf1Agd77bZ7puiKIomHakS4EWbKRXs5Ku2vymElHn8PtZ4HJbt4wkZvJV4guNogcYfvPN3A/wO16tkFIaVhuyXl9zpfFnFbfGyJkmBLWR6rmiNh94TeWP7FunFpGc6B9HVQwc7R0xgcfaigWZCNlfMw9IrryKhcSlhRHHeR3lPYLlMGS+SRfy7ydHFjZUofUyHfikJsJ06KUi/YVEKyIh0q/O70Fx4LWxkYNMfyqnVBnGjrSe1JGjAD0LvMPn4Ef2nWUrHCAfM0FAVtAyyTaz3GXLIYZON9kig5oG6AnaQbud+e3wzmAj0EpsgJdGWzzJQZpq2oVPyzrNqoloFYk5OvGqnDcDBqlIcyO49DLec4Owq27a3oWmGv/4KslY9SKFOK0gsyF86syaTQo74MKGknzdXSkKmBnH9JAQ7ZNVSyvh1Wj6+L2U43X+N+xiq+R4swn0ew==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
