---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCh1+a8Qul7GlodqAF7tMqt57wvgt7Y3kNueOE6z1HI5c2hDwdso2jegGc5EZeZj1OHFkWHQyvJhzXpH9qobhqtN6PKXLnhYeS2hXukVH8aneNdCXqd00RFknuxxqxaGCZqt2KzdvGitf97dpHHeE0FsvoR1kcpBodP2jLrzCrli3DpP3gpnnG5wQOJp7SaUx4W+EZDlmIQoyf4R6iXKQHhcY34DEOu0U7hXZLmnASlVjKIAPlGgW8Q7QPWSzUG45ewQfT+/QSON4YIN58BAqPHZVeYXF86AR/S6ON7n6lflVV9pg+X0KYPJ/kRKbrKIL+52nGXd+ERonQpVbh7zkzs/fhb3zCt7medDV8+BHZ1oTEX7iEw+UoCTU4O2zq/DsS/k2JENtRWXkCdt9O37be2QNxsyym7kL2sToRJJfWgsrgy+cupFQmbO0OH2Zi9HUpJ7i9cCMAKBKBKuunRLFHh77kOonuILwAK9b9N196vBJLEDSt1INiPv9expTSMBfYazgtoU5GP9sfRboMLu8jrzcYKIzrz1/mEvPXaynC9a0vncY3YIVtoa4Wnc7+YA+ya/2voBxtLKTqKRHKwsWCyLgC2ccFr4D+iUo4gpomT/pZwdeuOZKoS1gqq6tXh0a3V1WvGeUBPZi7jHH7bwQi/9UCURygRMIXd3p1nT+21BR8lYu4y3TONKNGNIz9ZRV8fdoMBWoVO
    client-secret: AgA98V0vvG68NtIdnCinBMXvEG4Ml6ZS7dlMaT8mSHBeHThRaShkG4NfzM6Awte2icLoChR7wHpSiLHEvJpUrTvUUuMeVy09vrEU3o1Xyt2E8BHRVlGrPRXErbdmPN7K2X3zGHvSnTFXeGyWBDbs2Yh+cPeoSo5n6UgsLMJGS8kpS2xkwvfHCe1vKS88K5UmejRyNpmTyyALjYU+axi8DiGNYq6QfIuHGSWk4k80kOrFrkrnVTNJAVLtbcyYtnAWViYSwqGki494F0yrDcRc/yPitWMaWraIE2pZPTauM1YfsTBSsGrT0buNbVqS9a2lvph4dxAOZMl0mdC1S+mXfa6+zOI902C9nwoDCkxCNlBlUfSvPQ0C2Rym/XGOYG3aXZueSJxyXMQ0LtxKDlc7HbasopUkBGyUQkAQlYYWYaAIO9oVG+9/4K3OJQh55qIEyvlxZ9PJukrDw/dbgUjJxp04H7NZeuNluDnz1tgQLZZkBJZVoJ+s/RIrklFE83Itcow2Uqx+stIcmaTfsc98aBIxbfbpOHAZFPR6mpLGaa3me7JG3cBLBMJanDvYwRDKAZWdV+SJ0YDCABNlZi/DTS8kS32wTZzVNqQNE3m211XKfLTc9TDTJAT+i6eac7S+1Hu3YohmXoKRLGHZybLua+Nc3wYS42fhAtfBc4ISPnuW83jVSfjfdZ82T8yE6zlCQdtzh068HKDBQFzRu0ix4mnG8hTFTQfao1aARcVTsftvpA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
