---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBiwNyxI3cg8WzE0DZaEJPNlbVSdTwIdD72XdcEWljUt40zQS2WGQ7qbL8S/sO2ZWdocubwT7MKGLZb+fEL13k51gu+kwchMJA+P7UXGy8YXBIGuuhMegyXhs/BzyKJc0B4hqQzAkcoP4vyJ+4icQHUQI2U7icwopEV0vh6wKTv3vKPpfk0C0uGRMycbg6UbBWG1djindJJHLqerTbOy550gDsuyb2alqNsMdx/NiThp0WQVIYcvrXARU4LRxjdkRwVIA41UC4EnWB6ng2/2WfaOx9EOgvkYYW6HpJhCYMQ4xeUmOzoDjglgyRxJZW5WqZM1OfRnVjytlgtlI6kgkrrRvi+96FokwV7/Xb4ccGJACTZGF2qFdiu8/dlCbJywTzu+wd/USNmbe/LxPrXLffbbmcMIOAwwuZ8ghn9vUX9d/KIu6gTODmij9M7x5nhigUzBJbmnvx5CCwgNUzX+RVTdM5NGPiXCRXtY+cjHA1SmKkjmfG0fVlE5TNKNDyLPUWrvnLFWW7Mo8LtvADynuelxVHyEYEtGJnltReaDZQ1oDdL4xXEJ5bauOFDn7Lhtivsff1maY0kTKRe9itZy1rtU2yOoEUWwqZvIX3DV8WXOEpSq5NI43qcNlJryv6WOfr5A0rT+39Wxy6ji/G/zzLzKEBjjY4wVY0nERcLn2c3J7Ygtar9K0sYXvnxxWdxdXtrtKNGQNEx
    client-secret: AgAR2pDuMJlOARIov13ZdAmF4A4AH1zQEIJfksmhvDSJHT4HVQ+WLzD2JWALcX9JlPD1RzWQf2lCcceJkvHvEcwKuNawcWtnw39PRYT7K0SyJ1dseI4ev8Q9E7nnujZBV+BiEGwgRMklRAK1IBHUwIONvSiJdH4rJ8S+FkRr3AqmhHtWHqEnYcJQkJjaH2bSfGgOYGLFPLWoeHb22rBT2blcmeW2Tfi7f011g4O6+XrTiffJok95vxqmhg2I7XFhBSEMXah5iHQvSzSDy64QHiLS9wzz43BCisYDo/7duXq0bYwduq24Crw0Vmf1YBV1sMEaa/ro8h5i6xbHz/mHv6Ife5MhB+R7y+9YuOh2fNYFGKiPxcd4dCdPxJlawNpCDoj9Fu6nORH4ZNeqZT4jHARk4cYpee5r98fKKBW6Sx6AkqkLtjdalHf/rIlPjuKr9NPLoRYdA2fZrdnUXuZpEo3KsbobmjpNZXYN4Zni80vy36fMvnlTaYYEm74zD71xtoG434gSU6JRBlunB1Zvm7gYQ0yVY3jlwH/PXJB/4pBBO7vqFs3m5opKdkyGPuW4mt70r7fExuWORPiD37T1pwXkz8MqMD4o8qsOyGqJdHfZHG0IcxQ7gb/s+qT0Io320wUNsnpxdUzHdUbS710hlMp/3Y6Z1H9SO11B+BBI0IufqhKftkbfAf1MqXPeVaG/Mom+XNFsjhb2677UUIQExe0N17gKT1q8V6QDfAomCzgGxA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
