---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCSEYb7yYKsQqTVgCKhZNYOKOzqWfI/pSLgUVVQKPZw1zDmLuc/57ebyN6/y2Kif6dBQde8I+LKx7t3hkEDCazhM7GLxUTWBI46Eg/ILbkXCajHW6SzvUmtheVjjFsJ9KSwn/SP0mGojH/CbzpxUQxIA3amZf0G1jolO3+SaseKKi5Tx/qJskf2P2joGGZrNYyZ+1+CtHsWcVJm/twP02szmsfTFOazguEV92D8uLHr1/8ksJmybEtXol9WpgcrhzWygl+bYZfxSYymFTL6x8YGknMrASOeUiKqNbP/geNYO4MbKNICUyHXn2cpjq+Wn1Z9rV0H9Gj978cZmM0wHCWVTuj8bkNlMVY6zm4iZ/scG8K3jCLqY7tX9EgkqfJXbjrNxbiIvRpo10+bALMqvML9JwnpoPk7EmHdUtXBNmC7mJoYCSIcDxcIIkp8tWoVz9wfkD9qFjewWraQxyXfh5XcekOwb5Oq0oIuxGWsLAnMBF8nmzM24AtwVROBUlYWwtHhylgyYhqYtrJ7eUPr01y2M7gSOWKJGHUqsNFKNGff7qt7sJKOHhiJpdYXmKK9+WRPaEwwetPGS7WdUpDR7RBUUpXzkX3e5j3oTFRGekeZpmXSqUo8/MJq+GPRl3XJ6gEMgHWNA8V7hM4y/hv2DsmVkuLqfuRQmV3Frl++itdrVz9F2IXPn+jXSHrNSBHIw6rIgowTJWFV
    admin-user: AgCPLv6uy8hbi9pyaQojcHSQnmTRoreRJi3R8cLnLH7ydEuGIiSlOcy5kq4NxazwWhsoNmOI87QvdSkoZE4N2Gzv0aWyS8FfvigukYtZR2pNTwFNuwvNXmX3uNpglgTKy2stQp74HJD1hXeGYRySZfpV4SIe/j1RqzfsUDfC7yd/hLdCaBUotm8Af8mRqC++757EDf43l4iTxVPDSEN59jsnmDdEY4ICB2WqhmdLqAp7sMpuHvpU5L7yFrPNU1q8FkDSEjrvhs1xjtqPmwBoRNVT3bMss3C84/dccIgZwW/c026qBvinBJtrO2iaJmvSfUanrKZar7ugbD51QCEMKJ+hpDbmsFBtLfSAtOlCtiyf4QDhvI6zfNn2jkN+oNm1e+wE4OSFxb4A39feic07z3+aSteH88WI/VYu69FbAVST60aK6mkxbf23CyzkdPj/X9tod4lKndREC0pKUfIRXviNq3CLNOrNOibmVBUMXJVvVSQpZuEUsaLWo1THrd/+LayB3SbFmUCUhLWXWhiWyr2ZNq3LkWpVLiANxGok9lQazEe1vEdylqC9DzkNqcPcIPe5B0ba2NzQem7iNwxhCGkJpRM1+jgLUt8A9oSbGqkYuqPVbcTx979oCwlRwghjQni+krQnh8WKoqmsMw8QQO+S1AqMm876MP4xeHvJ2MMLYCDdj1jkGJhVyfR/oCwmx8jvubSo8w==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
