---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAkbJZSBZlpjvm+DlOeKKPjPcbtoPVrR79XJ/NKeys3oDnYT03C6XwCOrSDZeaKy0ErNN5i7CRcO0eQDntm5igFToHWn0fXqrFlbOBOrOwJiUX3jav/qeGQl/+QIItSk4ug7/Va9T7+nS/6XOjWImqrkmcLwz4GSQHq4obqUlZNjE28nqs04dz6KejLPbGgY8zIi0vvNd6aLfwX13Xl3A6GXeQ18H6Vz1buXtUiiY1sthc7+7o1Fxb1gF58vET2Qg8WLjmEGmeyHVIqNp6DjPL7LhTp3N63dBqygqN6Dj7iAtfxb7sbm3nLtINiJLT1nP0vPQPl9wQJRjLQA6+uxR62vwH/yB9yWywER/yI+1kJLDAhD24s+Ia0uPOcKgYxA8u3ehti08PGKq3IXNkSKHl5S9AnJ+i3deUfXIdFNPRBy1ePu+gi6kpDghJRSgCTK/2+5y0bskXMXjBHhjeuSV5tUeEPKhl0GgiwHP21Ao/uuqDznAYOzEbnZjiej3yzmq52ACSdun2avA5o240K50SYh1khnyZ7OpMhhP3o8b1SwhhfSMVbT4OS6y/TJXp2h6qz8DROXs4w4qbo8aVN46NelCpjMsG730mn6hnZjn74iW3n3JM4maOvlsGh+WnjXabvh95aS0M1qe8QFF5nHXJvZm/b8omClRRUx0b428sH7bseDZNb4Cxq7QQ2hrxqorvCYKbXb3h2
    client-secret: AgB0t/p5SHCpPd2SFxGPseP3T88R/9xgPcvU4bF0wQololMWc+LSEJZmQl1MThN/nIkcfQn3I+It2SPMJzkunhZJol+tQqo90yD5bifflhR2pEgFhslvV7q+b7s/dCTmNdmYr1Em0U0tkqwi7JfOjcZu1Ha7RBuvRRrTU/Q+7whEodFTm54YQLWgulX/2vMe0OQ0GZrdTGkrpUlX1ScLNT1T27z5v7ZNvmtnwGCOleRSG0MJjve/R/jOUFKraVXsc0G7ByJCsY+qSfsiP10lPfJdEAXeREHMZIarZEj6PbEz9QPUFVQ6NNJ1QpElR4+vGHwOKTNwf10jMpDCcAS6IsSv9f95dDoVBrW3P5acYGTJHRiSUlm1zN9gU39LLuWVYh8wenG39o7hvuEWSJPl97LS3dBvenqhzfoZ7acnSPqoBxS25xBlw2WpyyvvHd83YTgrJ+uzs8OdmNUgDQZegHIQJY7f9OzqeBdJwbpPNXU26M52qhlfOyzt1JaSIOlQ0FvgYoOkf8D+tgT8Vcn5ny5M3GJtmxdh26BcDRz+OnT5rvjHKnvrgafd/wrMjFo7BsKqr323ZHoeAsgQ//nvNi59FfwFHz2KPJ9gEEnPYcAWbJXPYgAD9KHdzNfLcbLdU+onS9Pl5gH0ZrgKCCCy3lxX84pbc9f289IoSnaMrs9zN3/zfgbQVx3apVrP6G3VuDWTsSB/+fJ7fJkH2bQJR4WfYwruvOkWy1/2ciIm4YS7oA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
