---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBH7yM+T4jpsVK/gQKM0yMr3w/0u0fK8fIr58cMFm9GRpXY8cMsI12FHWUZF3ezf++ka9NbRLaQwoO1JGomnbznij1aDnpUUQy2gmK0KVOuVQltX6GkvYZ/jhjZwXG+1Zifn+y0qSyXCDZM/GisRR0y3UB1ghOIqOs2QWMd6X7Mf0RD6OeqLB5yMyp5ObIVneCTQD8bjgQEuY19NyaOQxgUi6HGSH3MwBlEBmO7N/3lvIWYRjH/UrI1obLqNw3+yNuPTzkaWMQoBjkre9jm7JVON6PZD6lPlcWln6FzxPp+q8kh3pt4KSlocxnor7ZNEJDjl0WvLOOH8ePq4vHgSpariBac1ZQWJ4eAFDq2cWNPfqeTz9+QGHxTrH+UWYaVA9TXOSAc553eBPeGam0WHgqQB9opW2X1XwopA3eLHE960nEuQ52oJziMdaWMZ1N+7StrkhTqcbdqeBFuy/JhwqiZYCXpN0Hzfmun/H5C0K/YcXwkXfaypY5DwmOqj6PNf/syUaM/wL7TPwYhNH5dRa6rfo1rbqueA2KikNbtXASZ4uqqD4ch6m+nSh4yZy0cNqoLmoWYf78P2FWCaPHgbk7G4jcqztW6BCAM6TBJyZtF6c0iqX0FFzckpT6dWx0Kv52vY+GRMkkWPamLVp8qF4w/VA3aROcAGh8Fc/Xxtv3oy/6ODRFA4eZt5T9H9oe0Beb95FWmbn+Z
    admin-user: AgBr+mIRfqphgdnJKCu7BdVCtQsPNY5Q7aZMyJvta5Uxcl1sEEfjmaK4jt3MghYk8Yox8VpUFSPEEg2Goz30uMuB6GcPA7N8IfGeEFYYA350ect+uESc4jsUvpdFeJG3chnWpz4uPT9qt4IzC85Ceiy7B0G3G5x26CIDcEwc2dRlnQuwHymF+tr+fXRZ/0UIAn8GBeXOQoqUMZVnwYipSGiKZP0dgkpdRkQNG4Q2zeeBF37FjqJ8Xcb3wZ5UxQKOB8OJv24Lnt54R6kzgJ9iUiH7pHeNvR5Vr5yLy2fKeeBUPx2rg1oS4vSGl+nCVbUUJGNIuOPDxnf71RWFAm7f+FrsSkaMJAmsdc5uLjzJpG+QBZT58GJroJ2D9jbOOvdR4IDMDiNBUwKcCXQXe+FEeovXCHQB5QYRFNs9Ug4fH6okw+8bso3yNh1/uBCvd8kQykNXHwmyRba/iB412WD97hE21PtcXP8LwsEyf4kZJPOK9KgMhUwyj7sHIJmvlhoXzuc1aHf015woAUthdrht4Cw2C37uUMiTFz6/GDto+vELf82f2dk8PdOJGQurZ7XvFW6P2MM5cke8GlBZF1WzFyGzUeBuNtL/YEjdykD+yZ8lKJQf011YWiOtou8Ea3L52BNlhmUbnMZdi7aAgYWaM5lVVYJTyt9d4ozC7fbdEUkG/OrcdpG4FQHvL2ibdiN/KJrebFLx1A==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
