---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgA4FgUKyVgAOUUe5bx6Jq0liIIJhwBd/ikthmtEvddksxcSldJChBPXitQlYTpoQgWwfgIBG4MYcFeeBZdDYcZJ1R22JJIlJUQJgjAPvEjmwkm/XEILiC2qze8cH57z0U8n2zBLDGSmOJW6pSxPaQ65ZY/RdSr6p2xUHYy48bAdjmtMSGRMpD8C3m5ElyPRCzuoiQOK74T1Y96a8pYJ0INtRAw+2deCjGBmV568ywWBerYC2JQud0UPQTReIBXERdQ3SX0YYVTLfA+Cg45PYnfMqnWLu73P8MLGx3/2Pnri7XFEYBdfAbujdRhFKze1rNM8npUYfVhzDigZ6K4P1w7kB3Pp6yc1Ov2Uy2ZtwB0g86J46mNAOcj80eaKrzPm2+qjF8PavwOlNhotYM3K0xqreT/NEl7JEIqxWjswWgc7foOCAhpOL4yp0/ndscCP7w/eOZma5Ud6WfpPUgKY3EO0KlYiL35iSeSDRrV5EG+mA7Lxc+4A35Z3uZMSAcLvVKFN3vYhCxMsfecsJOGzYntzukA5LGh6yJLReqEK1nyyNGfSRb/Ov/bueJNOAHXMZopirsSfMnU6CUcSIkeCY6tmQ2oGpqeqMN0fcC0YHHaLwB3gmwO20eizZiu6/IEgYRsc8X3vV6zBiUhEuJgFIYRz9hVPeUblujIfnImtZ5Fwd2hJyKtHGjYjzejQdfWzMQQkWxqX/a6R
    client-secret: AgAxtICussaNmRsdX7HqgsehlUITM6/Zb7QU/DKFCsR3GN2Gai2RSKsxpcBObhUMsFhyNHFSfTa9UdYt+V3LUdZa9eEpVFVNFSqpxqp7mMS/dvTvO/681f6L4T09Fq9M5PFRmwCp8/HzM1UpA/e+C6nszZpsC+9tN5iF3AEtESmXUw32/HgopGEgcNl4/DpT2f+V1fgZeOvN5jstFwAjI583IxhAPM5SNpfnhDBPnqSGZXsoKxPJBiUqe+BYc40MGMZOcgLKWagEVnGVGbe2+bFoAqH4rw+th0O4rENDcoQVJpUFzDCS7MGY1jH8mng7USLPjltpeC7QvroV6ZwwawRf86gMNDYHYIpZ18Lfzx1nqa6d6xPl5KfC48/xMsxFZ52n3WSvGlKCoKI7S4AU+hRKJbXQU0/MpiNojcJnts0mFajiQ7i6Gk7H8XTdx23MQ1lgsWtj8BXvVRPHNQtjx2mz7ycT5BC4LHCpQsSn4lSVK56WdAqpuXMbp2v8FWsD6F/o9IQAYm8L0s4jMiWogZavrHnpekZysQ5ETlY0cCbFAWd233kPILVdhsKWeJ5uVaZcjPXWahhdqwn2Pkv/GmM2s7xr1CW46XB0y70J5pNxuhMLchve/Htw2Edx6lswkwdZMGny7peMh6sEC/i4tIvBre60RS+whKoZ+geGSdThkzqJX04xNRHxG/pNGH63Fb0DBOjnTBj1GpcdgsEqiHxeJmo6rMe0u7YOm5+2LOQgfg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
