---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCTC9BwIJZiKHcR2lD6A4U6iHojSrtl6z10Hcv7TJuCfpcFqN7QXGSC2EUeQ3JPWaCPyuQGHKJqgxjfnpMVs9HK/+KSIGKRVsWyX0qXcYoc+r45LNf/k4Jm9NSwjxAp7Da5ixBkghe7V/W7ho5lcrYMvBux8vIX2HFtYlf4XmCcMzqzmPQSaAFf103DyW85M37ZauRdnN5wdYfb0eyb6ODVtk+2ZUna/Qm/xoD8gLA0GPfoy4cNpmlBbUAE7xr/tUO2La1nU808x1pUOfpdd4+FitrhpJAQzcaiXdZdOEOMAaUYXDFIVkESF9u3q1siXQK0TPDR29Ka2cjW1wJQRFoh33FQ7DtFwECgr1uQIxb/TwMvjcKomxeeJ72Skh9XZ07AvDaczo7SI18tNDBRf13XzwXJiRmEBmitfCR4lC5AiACxzkwj5A5XaThSCYx/yJN5xRzt3L59Fq4Wj1RCNKMrU0MSVrQuZC9iE9lPAPcIfYZvjpvdhoyioIm/xC5OgR5z+PWO1KPvox+B9vzwFoWf5cSU4Z8BiKSG+fU2iUFrLBlbX4yewLqECjGsY8sgH+x56N7sUKaLQZ3sxJ9cJgBWntOm/daECwFFQAIw7LIp8dafAtZaUbTEOS24JwjGV1hSy44e3RZ43AejKFBoGj97EVDS1IeG+pFlp9SK+xpHJVpBAsisn52mem5YTolKCOPawo74K7Q+
    admin-user: AgBA+uyklcHYh+twXCY/v51Nv4XGQOob4dRRq/bmbhiF4MTXSl9oGOgKeajgjPuysOpc2SyTsApwTsh/Ba5ZAmgvTlTsSwBAQ7G/VgsERWWvVp+YSY4mXN8W2EDF04ghZ5r3iuM/BSVfowdJYeMPkrD9/MiZzz9DUFpNL/+e4/3ghGHVJeweCVXwabWWkLtBvVAjEg/u+gNjfhI12RhYhDsDEaKN0R3OzGOdVikJWWrOdWYJ/yNGAkegcm5TjZ2TXAtoxGhmoBQUihmWjHgNoB2NckTs1oJVrtLOdccANNxKedZ0o7s+BeTvit1w2Wro/TSeVN9ln+VDpFECJ3CMDn/XnY2iklNXO+wP2wfWY3AtYZzPY9k4f5NrStqgk4h5OyizT5PRipF3FX+mEUeJgugAUz5+zFiRdOSiM/y+yUUeJwahU3bP4qAcRbe0YxOPxzkyWpzKIQhCGtZZX4j2NRixyQ2hGojfoBjYw4WM51NMuNEuEDrfXZ0aDjFvq5HDzAh3Hz3eNX1FKjL497pOVyQ9Mz3Ie5irwALlrmuCSiWWPRB5qCjaH8EScH/NolYjBBHjtrEblA1hPfbZ2aNyDHJ2AMtV6BYh46Q1mr1nM4tD6WJRJ/rU71lbNwhDHqQKTEODp6hvqm14cTghZFIxt6C5aaFTZdfS4L510vRtg7HkKyBEzPhV38s61BMKOKp4opRAS/WDbA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
