---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgA7jx5dykrOB+bLV4dWAxQibqVcYXYl2z/w+ey9TPN46uRECwdvTyI1zb2mYr8fTdMRbaqzvUiAKAgYZ0rL1PCcIcezV6G6ElwE1fIVXWnDlZ9GItSosHIIf94N6tKYv0M57wby0lJeUW7fP1lAAe+minMyzPW28aVu6odI0H4DSImQWyVacDEyIK1/SLxVU2nPaw/tNflXYXAiLG3cn5X397H/IdR9fWsT/0ZAWeyQV3UyQIzBYyzHN+FdCrX24JteEkhyOqOEaZvAe3uVEv82TJucvkBCvfVBg/v5A8xqqm6yJ2bYqZ3kaZY6onMBt2gL0oIvqwWZdqyMn6IMxs+pXkdPYuXZ5tVdC6zNJSpiblemKW4yM8X2FFyfxqqxthHxjSQZS7KlkV9dBz8AuHdAa8xot56D5qUh9EZPfxjEnq2rK/9NTab/ktvD8qHVkVWjzfaFWhFcea0T062RGuzfvlm3eGCEC3Qcy1Iix39qi2zv/2gwrOfV/0YXPpEL4LOgp2iGAiQMr3Am9DiCuISZhmb+mu5zSZGpmKNAItZB0+FkIIlyOo/p+EKPDgz8hhmbbiUCn9Ke8LH4W0TEZ/B2tjMg5HjJkkUWApPFVj2TIWLBEABhLNaKUj3Umlll9pV3ZlghRRlsSEOwKMqk6HCrm4A2GhlPxdFBAZTGCuQQd07lvc9waPYUL49eZr8eMIgibXrIvBUZ
    client-secret: AgAWuQO1Vpxn7mc1AAZWyX0VaXaXCjjetFcXAcquL9KE59CV0DP3QxifL6H6vkedIZ5IKXmFfvxLzsTQ0OkWaVHNndqUqKENyT84+dcV+udCXBVYWBqzjmGkiuND9p/JAti1k8hUTfM8ZMzoYmsqIY9ql6hPA/mqeCXBuK6J6BK6s0iElAyE2jzwyvFRKbtB+KReOMg2xJ6EU25AofksBgvttxjKVKBbde0nKPsivraNyvDgfL09f9lw5cwicSZvNR3Zmsz0NwZgDyL8txTnLnJTY26lKWi9KQqXDFPqIsLCnNv9jNADuY++o6SLrvK0IBmAjgJZl9YfNqmv6AFN8iJgbzXVf54WFzR0ClXCRLvFxiGYg5tt4nTfgo5T4yB0xNNQkrQ82yZg6EB8sfHL3V5KspYPI3Z8uC1u879cvkvyKH+1fD38mPLMOUykgi8mPRboqHNJ2YP8vu+YWYWBSXt7De6XxB7ewz3dfWK0ZQzapa7yUUM8D/QqPikz+v8Ob3Gf1nXhMPwl/JK6QuiS/wsulGhPQu2WA6+TFPDkjD5S13QATEky+9RDsU4ADRZ+5icd7W/l9UDY6O2yg4XkCtJfU2PTrYOCVVeaj5y43v1DkJqUI4/W7mxpDpKtnZRumD1Fai/wpSkaTKTS2qYlxRr76e5e5FtRnAmZ67ndm7knAuJEFAovJkdF0zOW5P/jnYAaQymqjXGvlWPY73TaMQ76Vckxk+LEK4Ipxsq/ZIwAbA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
