---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCyMp5M7vGl6mYNxqzjhGD32ZtEPG+qwkxSRmd+APR+xRp05p0ayE/F3+ZmhsXbmhREb13ueosTqnVc67vHyhjHWdOHjSJu5OvrsHz2wYmJCj+C5K9qWruGRrPGsgZvt+555/izazkDxgSHngOlI6WQQWv7zRg9Mj8qqcl0SKRWX4spo1x/YWC59jW9sT5yNQ6iyBLmtiWR87oJJrV0DcfqHOim8gldMSdNi0K3+KLipXk9LA3kjm202ZANNnuiZeIUBaKcs6E1eP4G7+CL5byfE/BhByIe5MNqES5aFWNYF1y01M7TWSQvnXYY5bUDwRJV0Qfdfgt/le6KxNk9XOZ3XxdWtyrXXn3+uOD5aZ202HmyRIdTIWM8pZ0knFz+oGWpl3ld7b/SZRoDluep1/JOxUeJnm+yerkRcWpq7TJLJ1USWRs1/yRfM+Sgmw4jloI5tm2OZdV+G02Qcgd+4Zo4u79SGXZmFYsjzeTyrY6lBSfBbz+nMl7WYvtZS1gvKiequz3xPTmtJtWQHOMgohOpy6a9rFQ9TsL/B6d95OY9xoUx4FFz57WN8qcFHjHFuNijuHLWcYigpcZ7tbB8rY4toYsaE9GElm9zuZ0p7C1AhWJsATfW3B+SQjIFDaiDUU3inicHlf9aM6VAfHiozx1lFwFKxDHqxD4mnd0lNqB00+/+w2WGTvqPX3GHBLWFBudmKkdb1jFB
    admin-user: AgAMDMHS/OZPrrsV4WEDf8KuoKvHFPLTtUIxKJV2eHOqlOQ6FNv6og/KSfPU/PAOd37k9g73Jcwof7YoLhsk2Yfv+8jNpgnoYqu52axEKJTfA6zm80G4KbxhzytB6ofeLLQV/73BOX1DmAAdZjUAeCzQsAdV/rwxgXNRB5VBiDBtKoKYppZNd1EUfMLDIM9lSgjcRytw2QGT4cIz8nHB+ZpzyJSQooLqKmQ+iH7Sv/+7pp9H86vWpzQ3rnWssTWpPnvypmT5RcBMM8hE51llXXp8O/f22i0Akx4DnaupZ5hXr4eXuv0F26H6fwbO1n/V25LiCKBqD45RPEoSV3fpe+GX7+RPYkzKWyaYObsVvLU3fx8C2gHafl/fsXv4rerjTSWcKZpjeLcOt3V+F/ffdAJwHEcYhWCYquDHggTzfuNRfgEbXovWJQF5hVz7V5zxqUz5o7Y/UBhWU7YzlORt5acLwuyN1wB0V3fIYo2ZjHVyebXLzuBauCNsut5U8jUQfSySqOIy/RU3fLiWWJ6pRpM2fW7gLZ7imfoB8DK2Wc6r+vvScKaZNHMonoD/32BnDq1Vk4An/PiR85s7iqAVNdObJyDiVGpPBZeZ1lh+QLFItLIE/TLTzvJ2a6n1vatTXrVBePHeSjkc0qyGqT426aP5w+QWCdYgvnjel+hXQxpDEts7c4Ta3+RhQJO2asaHow5clmbZyA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
