---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCdDuKfvF61HMDoFwrtFqpM9J1H01blbL5pj6bnY7HUHoBRYqx74Uc+n/tt9xs3k3F8/r0bzJ2eazh2Alu4orjj2N1bVXRfX8XUwQcL9bF81M189zZsF19HFnRPrdwh+JogekMDzlq9bQwEudlzlF1j8sOTxcOdnlHCn1JSG0sr8ozpTJ8RzW67EJaZtjXU59u2XR7zzX+F6OkGHn7nM2xfSEuTCM+/aqkEPblvDqddBGKIXucOIzhkjaUy3Wc7P6pJTYEdz+83CeZvq0S9TK5U2b76VLWx9LrOzSeU+vQCjQSaO8qKb3zV4WI2fSRYvk9/My2EpJVFrvKpcchrAl9rGp4bKgXzOH9f6mFctNjhuFX7O1VhdnX++p37QIdBKfEhQ75+GS568cqSqDlShqeXJFyYFxQUeE7XKrbhGlzzJF+VCadeTKElOA8R9U+7rjRzfdvdIvCYsU5k9GUB6sunCrYvuMAW/JV0yZaOfY1HyZtN4EPE8hjsoQ2fFuu1Jrs/AiZi5RZJ++SGTK0Nwvoa9G2xO2DzsXuBMaMYcAiXSb9KB4IOTaJQ2/VJ4SYxap3doPtCPCYsxjxkqU4lAxsHEWL4Q7TlQ09lktwkKKtflomoOzNNY2v6fouSTIC5B42zb2qUlD5di16okLC+mFHHjD/pZtbLcBRyTp4iLOHiCewsiHfUjKtdvZ4wIlHOYrqTlMip0fOx
    admin-user: AgCT7OpBCj5r3f0bP4RcoEJLxEFxPUuL4AZeOSELcBbarsMX5twizTSHFoRzIuV3Fk96BO8P6pVkpMEnWAhseoX3x5fHKs9mj9R+7V9Ft7RKRaf1RxCE5kKmb7hvxO9d9EenfsJL5J1NNInDC4UbCL+zi1XAxu9jaM1QWun4EQIiLlfBtxw8M3RBhtBfv4rFGicOcQ2Gu2NXLMT5ZoejGe2345Nn5IFnlywadvhfiABhnNUxGlMXNyAuQLo6iMrefFf/U9rTjheCy7/JBDa6W8Fvc9E6VxtckU1SKiQL5PeyVXVVvvzT0xhQmcgQCLdcY7G5ia31AFiEsnsF3HxhYEWPAYpI0SJ4cW/k8QACifLqvA8Xc+Dx9Y+PDj2k8INGd1igyyLuXhDSh112t2hgH7ZwbkahBVoYGXceR472IqBQ76hLdqckKh9WXYt40jIm1AFoY77ZTlsqr4mCw979s+pTKgunCLU/tKSkmpH3R9lux3qukQbfqZnkCFJ6NZOO7+wcXanW6NwC25T2C7rF+dEJDYc7I5A/vQzqV0y+vPG9XRqZx7T0/hnmJbl8pK7zYa67141i/aLNOHgYt+XEIUdXYFU9Le8EY2GgnldR8sBpVZTcscHl1Rc+jWOLrBknb3FAhcmULxYqRdc9X1uR13youaa+4fCIBrsEK/0zaRZmNGrB395FD4agsJGSbV8hfkID0oG80Q==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
