---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAm6tDFq9WZfKTNSZOuckN3LfWlnZhCJnVtca3ZOaEYOl78AnfNaHhPqCIMjQfi+znCoMMBYVLbBhhg3NgEEtgTnuFtqdril8yi6MkuzqSW8myFRgZDLf7otdFpIqIDscPdrAY1DDiEW9oJV2r5Tsf9NKe4qMylZqvEzW2SlTFOoOkfXM6l1Fo2sg8ZA3NSgvby9d0kQBhdTJHeB2PePlPFsmWYa/aJyjF0jp4LTArCJRP90RaDbhSfv+UxseVtp+0INizpAKYbOYTSxpnF5r2n4UFUopmgLb8+FUXJjTTCFAWP6Adds55C5Amgz+upnbIktuUCs3B3nmxDN/3tF5Er21oINyFxStZSty6BU/0CJUxGEjw+8nJhJ6f8Ym/hS4JuANaQL2Tpm82N08et2E8rpinsHpIKepIytLkn2vLcPs2Fn9BD/FPLHTKECn0iWFZvwzl+B2mFaxhj9N/PDXnpPRdPrMDpdTfgxvUpXhqx+s4XYB2gx6msuMaFFM0oAYmst3lqCgql++ns0x/m9+8riGvhXqDVDvVA9YEwDDMB6nEbDLEzW0kqfizStvbMKhYF+W6IU2iEOVQiz3W32X1DrM1NigbOHtYKBfqe9k8STrn3GyHZTcinifbtct1pVOao1uyIgkTzQATngxVNgQeKUhVVEAPg967l4WG3aC5Bc4i/RfxUertgkJi0FoIX7iNgkAQO/OLj
    admin-user: AgAvG6UqXdSS8sxyocI0QZxZnin913lRyLLJHvFp2DfkSmbHKQhSc53dobT2aIchDLBV49v3mAfxgXKh4D7OWdyHI2zdB7xFTlq1RWfd3EL9poqxbHV+gqgT3/6zfuoNmc1QxSbtpKPEFK7jPGHTm9zpqvbCu6qsaDPDLiFD68G5J1mCD95PRQSNcFKNmcrc0av1fWr+1iRBxCPgOwgIAJmbt6wc6LK8ERQat6iajaOn0pEBUnhqK/tAtTGM5yAV/mkSJzHyKnRZm5F/zh9bjzBGVqgtMIG7en9Tg3Yu74qCd1aXW9Kf/DG1+0Fo3H9R+idS2+JEdh8z5rZu/+I7TN+IxYuBPC85v+q+vvT6uqTA2m8jnw6lyH+7NtHH0VciSuFoj3Ia7nAY5OMqCtWFhv/7RrXmVWhzFsEmvj1upEH0vBk7+2OKZnbA2L9fefxc9sxGV0ehak3ym7i+EPO4N/BhKgJYfqrsSIsZ/PkP0uQk51V4BQkhcGCbNCDFc910xUzOktAg5j8wCvUywHoPj9tQ+EeZB2kiN/OQzDNhwhnnzKp14W/FWy7DokuWhIIbCPWAdX+3/nT5JkLCt1I2nMSCSwrCVT0Hid4OwjkPg3FdYzBut7WitClDgiyBBH8bQMCayevhoM1x4PmdBDQLEAGtnN3s9mmqoPlIL1p45S4tBYTlLj0XuFvBvPDh4GxYzUhtyoVqQw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
