---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBe6rXiLM4ICOTvFvbV96VqJvlPStPk79sCL5ywzo0BtfLFuDgxCbNgTtoWVRsbiSfwxZZvYQddF6qrC5ccItPcsErKj5O94ln3dB5kug+/fvlGkHdPR0zHVP6+fqLxwOyw47mRkXNOOlhKX2GIzy78OpNhK0ufTkS3SR27QMHsUkWzcpRNL0P49qYfhPaCJbdK9Upqc8ur0hY5qyPxnxlJkj3fMXRPwgnAsRnLkonOxblQv9/xjjMfbuSut5D/rtdzZjjMzlNp67FE8w4qi8867J8L21O6ns7mxh/zD8q+LSfPBuyPIo+jvG/1OgVfyWpdqunC+C0XjIeD1vYTzPTN3H0aKZFXbb4DNTw7Pt5KfkQmdY2+9LpomiT+nb4kZ8VPHjShY3OENwnDHISTO1Z/N1CmjxOVUcsukIQuqpgd9gVDJKRv9N2OkvN2L0tleR439Z4Ljr5vBKLNRqDKeUOghjH1BGc3dprC9gOcl1a7LBdKrQizj9ISKzy05Y1TEIcoGQPnhZlGWotteRMDqyYpKQE7OYC5CSB+2645CMCv/HBwPuS3/HdQttkVF6/7eXOL74pUDlaZI3tZsKnk/TLOZC4fHMwJywbGz9Z3xU8H3QSxeR1miRNk8FMrR8lkjNiIEpE6CQZ/peyzk7FtxWF43PhhLcXnz5TchOCtXNtjGB1gPVXLGwb8bs/O/Ol3RWoFcU5yz1/B
    admin-user: AgCEX9Ny7A8UqBN2xF5jpdPVpspIzX0RiBI56VNFDHY0gcTEOxSJ5j5hyIlyjAIJvfYbbgTDHqBS4gIBR41NACiIHSRIkUnuZgq1VQTj9F8TPEc4Ob0/ca1z8I1GoChh8MWB04XPhAFUeK8w5j0siTExXHD8ns91i2G64/jGHraeUTMimOvN8/vCanEL7jiCZ+QNZ6Jc2bcJRnk76cUvt/gMbip8yZWQ0NmGTqz8634affqznid25vibXZqb0wSLXbj3Iyjc/V3PF1fIYn2e2ZGV3cmCyjAQm2kQmqMBxxl9HEsapgpPiD4p5Jb2PFjTZcePG9gvRd/KamsrJOc9/lLJ6bRFjUb2XDofEENAmzZmnw6yQRfNje3Vjjs0oU4ijp9rn4S94Hwao8TL9FSpM7ZZK4IUWTFF2u0uKFrUblDQ4eaov/yS15eGZlNHqJuSof4INl6jo3+Kb+xnXO2x/kbAwq1atOKbUdR5pFuvDW5V+nDuC0vnOIQSGTDxuCz1ssF7RlJ49v7e9hWkn61V1x/rTkAktWXDkOIYEc7z7pwGDcfyMEkHPuJWISCjTeynBdpBDAU2FnGz7GBXpdXeK9c47HlYwnMLQvREVf7uXuOcSoT+GpkNM60o0yqnylDoZcpDrxxRJa0W9mqE3JbxBeZMKrbewDpMRdEAgKsxU8VtKOYpw6OrMKWx+F0iKZjVoMJd1r3pKw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
