---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCZxLTMpVQhlQnIGrW+F5F0O+ZUOjcuyCoihICFHYxM4d5kJzRvlUccoxOzRcxBjPGgRucqXZJZBzUVyPgvJJ7xbU95iqME0u6Y+D0nb1Qi9L8FllmNREhqO5rrBbSh23zwnn1cvRGxpUbpcJ6Um1RoXi4QlnU409HfWeluxAAVbauaBOKnjCuGb7GBw4+fbZOdr/6yG4J/SQhnpUsv3tWO+Owx3rk+812JKjnzfmgDKJsNnSCpTCmV9c2tvXYIuzfACspiTgCPhDEKh7/JRgBBrSUMSP58RbzX4t+jfPmBmmIbpEJ05KpUOHWsBeQivQIfUwl6Mvn+cj3VKPDdbnp2+mW59HMX6jlkPxd2ZVykG6FNDLrtesm1Vk0XZbhfAfCJvDItVWpNfKzGgU7L+v3dB0MSOiLQoF7Qr3a27czDf+UiswpOHC+2Q1B/Be673oeNQQym9DaMqHCvl4Pkg25J71alsHSGZYs4nU8Nuzs/HkIsUAm3kpT/Awxco2U2t2EKyAr8gKYO76J/8gmx+gzPUjgxoOnpWhOj2GgzCTSho0BvIbOt65QhXbD2adhrddukyUx0FqrgDKaKTwv0TYYf4NXfco5X0663uwAiqGrByyeHcvhQq/RC5iJNB+EJi91wdlztBvOj2Rz3jbXW0fXYDuVpFEKk2H2FGAYB5ewOHa1fPzGaokhv1gMtKLqTXp4FFe5y67k1
    admin-user: AgAllYUKiv1gSae/aSs/ANjRuQtp7+yb+WW2zMooefw8giiruU/U5qQq4PPHMzee4gvo0B7YXYxKcfGNq6aoBSuwjsxc7iQVPkZ67OV8ax+tJZwyxd7FBtsizkgcb7oEYqvCPRavjphk+Md7e+v3mBaguEqw/hACnM4x2TI/JIYdfaMAZ1lybW2PKvUAdHPP6OPszwy69wAswg/ZGLOIssxhUN499MDEUblX741sHusw2f0apLUdSPqTzLg/QoXgs5mghL8OIhWGIHv8Izh0XqXU6U9gRafD+fTupUPGYn1HBxdgWCaNpZfYX2tdLinqmTNO0FZ1MTa8gInmnmGdk8Km+ojVrHTqKn2HCNNCA1d94H1shfb/LABGd9IF0Nhej88Ca86AEPiVRpv4cWwubI55MaIWxqSb2mQeNDqclAsAvQ6lGFgZWPkkwQoNfjRGHxxwKk6/45QHHQq+aTsY/0VMY+at3r6ATUzpb7YBiRRl2cV89a9EtTuyJ++WV7FhuiAiuZIdOejsEki65wn/tngDdMFL+euoCZwEVOFRj58cSfY4U43THzZu6YogPvSHLW0obSiZeVwJEed1vmhK7KGhVF2U9quZN5f8twYArtpWX1+Q/KDTYlxKHetHfGqYuvm9+w+zqDop47tJbFG90b+LdDuiozuvqzTDXkRiZLm0O2jTqeAjqFla8caWInx5Cv54xuJojw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
