---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCmBObbAV3y5VgFhaI1eroXW/5Yp8NzoPdXzY7ainDOzgCh15yd7+noonhMhatTcu7X13GxGGc5BKqWMtWAcYsruLfd15neHK6FCz2bwgJhkpJ40WXPdBWqgmMdkL3rjbZIHMDvWVFBC6ZeVy8A98Bu883BoZW0ScJKkgpOBNsBn+ylvDggTafhoEP0wlPT/+2DR0NA/FlqPbLkOGabht1K25mm3MZas8CPLeZObdN+YJuGNjMVnTE3FDVwz5Rl9nvnCDA+eMRuqVinGG/9F7euZY8eErjRRu3sd/hyD3RylDhx9n19FzGdcHhBir3WR99mpWvbHM+Js5od4YmkcF03hWL57C6J6n6WhzA/+07rvb+vMcBh0FNkbikEN3wag2H+SIrr0DUkl+M+TvpZvbW1Vgb/XThAhNEFlylMNxjM+xP89EbwfWwzAIdyecChSsf+dzk9dvNc4zAKFP2qsX7b7xwDeeVMOmU+5m5Brv6xhNhrxfUki19KpuLBi4hrXOn1joZoVyf+vPg2n7PheyfV7R2i3ybcIiLoXK1+WRkjsWl3wlzM4KOSABG6z3VGvrj9Q6JJDJ+DSHuGX2Bpdn3r5WE607Q3i4S0YAVXjpUu8luKaAiqvMNtspkm14VrmFmO/IrJHDS7oFJ/1nESxsvF6FGYCsYAgfZRqm6dUojjNEICzS+5XhNT62hroZ4IyGR2XoTETful
    client-secret: AgCkH5uURv/9JN1kiNzc4+biBHAo4+K2zSfrNFvShRAQA2XNAVnWtnRIJVeq2WpeOvHK/vR4z6g/u8J+g3zkP/jAlaTXqVXMNu/DSlA5gROZffTxxwVyUB+D+28qOoPTVtSTybnf2GGUW6O4//gsg3PvDu0KKNT7FkaAjdCHchdxhLUE6+o2tSF8ogcvBMl2v//rpD0LICxJToS6enXygW6JHzW0Ri2els2NFAJarS4X/oqIoDKkhmX5/r4qTghEfFyalI1qmkWF0MDLyJ1UVQXMJYVFq6eZi27iVuWq7fHEHmdg4OenLlRCSt/jI3tfoNBr3Q8NnbULVUqHUZf3EbWyE5/hRzM7YFSlGVHvr0C7nyIHFNe/GFtknn1iQoIqviQkRSWvbiXw6zrjbDjAi7orLGbZzvLgYmjym0YD6U0ZPESQMqmR+1XvVkuT1PAPXFYLBiY+Fd/YqJ05lk5tsE83I/zH9XlQwPPRGTzU7EZ5zERgilbOj09SzhoxV5BnczK/kzcjHOUc6mSioHpHWVNNHvsRNByTJ0bUZsCwEZvmKBUMTZj3dOD1KS0zLdQDkYrgnhu6UY4SacUp4zKFVCCpQJ4qSLULpHSoG6c0Vrs4iXSxRpadCVPaib0eGNE3WUu1pTWXY2w/9ssuFrp2rjDBRCFiDn0LNV0kDFMc5zZHCDeaZup9JW7eir6JVmHe/9yfLOaCYSy3jrAx7jb87TrOTuT68aHZH4ROSalD1aBUwA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
