---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBku8uqfJFy4At21V1JKJSgOZY/dlXzl/CYEGV2eZNRLIIRV5zll/CsrB3UWB9M2J/M7syXk1XqdOhQsorQjOkipQCWvNre2cSJ4OV6s3YJqOR09wgS21p7Ro5r3ovBN0Ouql7iJCYpQ/g1ex6cI44d15Z4FPNKuC89HsU5q2nopaWou9nrLoXhCWqhitoTWmpml+royavYtgGic0GpwL6rYVAx2coqQomx3e7gkXJxBBs5PTsnoiM6Qox5/Mahv5QCqK89m0KNEIeKtyxeeOgMLh4N9lUdFFNOj+KZeOq2MwMrYfJUy8mHghnPrCNa2fDIHEEH1NviU7idPc091/g7XVbMerUux6hdf7IoykGKA6KAzx2us+TnGbUuGB16UwP444C54iUE8MAsNhLEH0WejaakdLRO+nv+ciRirGIPieOwPoodnW1upBQGCJzCXWqvzzfeOrauF/ggeDQJgv0mlSRBRI2yrPRInjdHyckJ4qfCfKxDR4R/Xc93Aa3yDUuJTI8FC00CQQsWzaROfryajiXPG4l23pH2E1yFBk7NIaV7+fI5jkSoRIB6E8XXziUZAaI7kWHOv+kK2bdwu5Brg2+2H/ji+g1saHzVlGIG8Ffi1ZZjMDMDkKd87f+vFOrGb6IpxKymvrgi5UzUY7HGrWtuB8A1DpU6X+P4+fXB0Ryk+0leQW+2FdqQ6mAj8nTgUTTJJGxN
    client-secret: AgAGGztEcsI1Bojyn1UnqB1ZeUC/RBmfs4oP5IsY7VNn9wNst4FAOdnOnvtSkbTK4EsJhxZ/EUgxs0d82F7EP7PVf3fnTWgV4N+VPtmDb82+JBEgLrh8AJz4o9l45dRmDG1ZHvxhlFPGTb2PHDYdOglda7ilFhn2ZZdaj94G+mxMYrig0o8DhgVWyv+D8l8rEPB169p6hxcU9CIhdBZXVAUv7JYXvWNtkPPbhjWQhK0l9xyKui/mxXdRxXQTmyWq5jMsij68z4VTFLafobUDKHyo8jqVIDX6tskyo2wnoVqSRa1UR5BFCxvdfsMlV1VMxzJUWIWaMN3T1iCHL4lTgmJaQsxutdP7zuM0KqINgcYmjfzirqOkZ2Z97uLDD5YveGi9XbvUZ+EXxECemiAa0sA6AY4XRVkQwUb1RnJyubJLYBFAN3cSCRs0YV2prsTcnYUQjjxA/Ry575ZRfOMa7dSk8tcQ1ZUSh/IS6+ueF9sPSfHUNLp1tOp0CGB9HOa/U1jMqKl1Tfp5vRDsgEzmb61CRpv9IL+nRN5t6dJgYgLAGSO7Qf6Oi2nWu/sUD39+bD472P/qo+fleVWgdW0f7IcmpwheuqBEoPWX23MP3WrfuHNe2W/eTfhHIC3BbFs5RawBJR1tMe4MKO7cuD3IztjjeS9wl3oKbXYQZgzXlWviSuVa8dv4z8wV2LZARwES0KEhrP6ZUNGckBRf2KijP0w9IOJY4ulKbA7NQTecYPRg4w==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
