---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCq4Wm4UgB33y6Uk2MygBJBEhrXotYmTfe5qwSrOFgcWz9SG8U7lJBylvvMzQs+8ONCIxD+1mVXzMZWAz4P4DnphpJE4sWbXb95+h6sCtCewj31331MSBbVr6CYFBNViMtU+a1SqBi+nv/4eikRSViKbZaGQFHbhUjpZhs16a5aC9okCe19W1htWKJpj3hCau1urURqHTMoWg0qw2/8OgSAVMLEBOOUT2SHkWGrjh5rm++6Rx6M6G5H7Rva3iq7S7zMsd4bFl1QggjBQklV+XOvFVK+QDGOyUF443g4woM5e7cX+d/c0Ss6Ec/IjzpEkaZbG4dnonHLzGjQRRHCi3skUW0u17lpj7D8/GbSHWmSZmcx8ZSVR4MH21R76dnhZ528xbDA7v8bJRGPliGq8ZP/xvqAAMnsmUg+NHMLPRgbTjjaGItuB+eLyvc3tYWM7FeY8+ROuUIaXtCEPuE1CM1zsGwTF1bX4C1sgF+XMU/bpS2+hoQZYxX3PALyfOQyL5opcMb5K6bfJyovMgqghKDmqcabsix+uFrFRG6yl3AZUpr6jeyeCNKdu7qlf2mKHlELU5708HQH0fmPCat9x856iGVQaXCID2oi2SYSJB5GbP5A/SRrE7E729lUKmcVJ2OZgg4ko0U48IeJy/iNYm/qrnGue57B9W0RRRXQaE+P8tUH3q+Dl7T2qrnFz5X23vNlPBZCha67
    admin-user: AgB0qaBljFX2ByaplfMq4k95YGdAbaZKrnOKdhoeV0lC2XDP6SH5Q/XGGNnU3dXbjFQawCzESAtN3Zj8fN037+yICWcyfuYbm5v5heGPSc0gXPkKp/pngrU4kJUUbajRuwNVxFS719dHD1l1nwgkmyMdSazKtVS5BQuieNj7BJfBhn2i5JgJJBY/nlKleJUDjoyyAfurpEaTjJnUcdBEhTJoE2G+ql0GrzrP8HRloXzvS71P9JkaxNYDGjxSOtIu0Tc+DAHCBJmRYBdr5GuxV4zeYcC3uuGjdtndKstE5plREdgnjMA5CCOHGjJVRyzDHJaHiiwwkHzFDhEsgst8a1j4BPccYh4GrMRI2DhjybYFuevxNnZdZNB9BxHut40MqEGySNaSLIao3GbZdf0De6PXRDVRNEqK6BpU84oqf6P3Jy96eEwZ5VhmQMTx1x5PiHeVBhF1+Lrzsr+l0NxyO7lvC84LR7keNPFOTBrCDBihrtDmEnzAhA6z47mTm1KJ6gjSzsIJg7dqX8sU00sIrbHHgDC3bXfAnngzbW+W0b4T/Rmlj93ydnbUVJgd8+vbKE2EHJAL62zBJblagNj6bTVqpi348ik8pEjcDDvHFYfouDkqGTaHS/zIXLlK8V8gw02zc9CD5TEp835qAg9ZFEY08sC5dl17xmMz7K7RD92ZSz39qsAVi6U0wtMEKsXEuC+CLOnIgQ==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
