---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgA9lxNtEdy5/J/vSylW4BpJRoTR3CcEptnVEDL09NULUL9Gq3xTKNrowUE6V1hxl3cdDZJJzDb0/PaH230YtEPeONFu8ncUZ8uCsFDU4WtJHpIWXitYWYbgkc4/Ldv+w/g1yjajDpv3W07xzGgTgtUhCTM0i0DR+52JiKc7cbfL0e3w8NwUB4P9tC09dQNkM50xqMukarkTRNKMDBbwLOfj4u9pvOWf4jHUMWvHx+zcJmTVuvqLch9Ojkyao8vyljI4AlIUMOvuHWh6jYxPdCg05Ej5vmelz2fBGdw9ohP5o+tm3QMyzJAvFRbdDoIMMvkwpc+wBSYLpLRFwur0fEONJ1PcUQXTRNpJbQI2X6bLeE8gGI8cVKBcu0W7kDvc1uhVaYuDWezZ2ZS1Ar2WJQJmA0lUp4IN6f33XR0Uwt/Nb4PX4GrQKEiDUVpY4PNxlGpHLiK+wdgAfNu4rmEtCSowG9wXTZAjj8xnTTaKuR3vjcTqLty3P4wuEilyI7XlALnErHa8JRLoKjG0KI70hchRkeCjbtQQeRKgHF/jCymvX+zHKlYA4RY2jO+1ggHhyfibzC62RbfZt7OJ/LV7Vz8VAOWVNS2bIc9OyfVNX9qQFPFAGOmGr3FKaJcIWG+6oMXqY9d9bO4w4VLaPQA8U/pyCZsA85UXJe0CL0MXnmUDUO2XMZ6tE/XRwdZoV1+1aCh6Crkrytuk
    admin-user: AgC1+fecVjqg4WUNHUsqK5BLraTvm+O2boAWCaycHrvaGelWkIn9Jxu+ObEM/BevrGY7lFNunIOvDl5bBsTddsPnOHi+L3pFNLu+ahWSp6iqy4kcJ+BdyTdSqfqmYYxUU8Ieg4NMyBIh4ZYqt6FDu1aicfTLDoBgjtyb9rKxTFsJH3GmhFVd1fRFpjsrQV7prDpk6iE9XI+oJz2ihEukSrVVLm5eo7Lw85j8o6pgQNQwOo+oYTePCc/LYsHJgZ7ppxcuoIj4Ws792l1PW5C1tyFIgueT/lmiz2rk1rh5IU9aXLbEnIIi4+amKj42Elq9jhYq84bneyOWRmdPvcuQ0o53l5ccOTLZLUHUvPg/Loqw986tGfkebapmrb3QCnY2U2OGO7p+oalqOoavBmjQao6twi+jEElEjSb691TAeiFgfdURfg1Yy4KHvU7su+1AC43B0YHICMiP7PgEzpEiz09rJN2V+wpH4I+0wcOqBX7DhyPkOC6ctNmQcMVlcRxHKaQtClFHfNxCu/dD+/OAnLCk7fKpZLhc3cU2SRFqEBIOZsqVaq6LqWMUSNd/luSGrvRltkZxdsvXFr95S6Bv7FGTTuzsCQxWGaHsmvyESQvuOD3YfQE9+vKaeyajAh8DcW4dAwqeTETDBMMIgWklSkpFCtN3AEaYBCnRZz1DoDVEmcqCeng6y/xuaax3ytby+ZsaMzlIHw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
