---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCtsqx1D1Sz1FwIPf6KcWk7swxYAhUCRQ9Qttf5KOUgni4YNMdj6w4n0DUF5G0QHglxpcyoWnoaNID8rGeTnh1BFhU1s4oGqkuSK0BLjkRCfFg5cfHuPYVxtVsI4pqTb/ob0vprhvlgFgmaZcIG9F4CWfzPL3S4zd5QQUYWBvwsJhhsOP35RC74EpiCe/sjgzfvYv9RlH8cekIDZJb7y7b9JXPNlQLcZjS97UEacdIgkKmn5tmze3Ouq9mZSA5KNt2dCt/rGQiWWEYpt9ck7LXTQ6gUfDwYNq49/Bh39RUcdFRPUTCYPmjnID7I02QxdlZL9CTbnAwDwbT0PE7qqKJpwFtXE9NyC/N0ao4l73F0OcpgKfpJmccUEEzi9QaaTF8b1aNpPGyDhaia+ZqqwoX0OFXJ9O6YtUUNC7/Z3mvzVuyW6GWi4M1DVqLRSxetSCcxaDBhPJqZfKd4hs8var6OsQsHdStkUPRu9PTxV24tY7VXiGpeRPWPkt6AVgRUH4fZQ8HfFam00ciI4Bxwe9NAIh5ookqhRhq2Lqns3IcuqtgQ0JNHkQKEKXhkfZ5jq79t23WNeGcZJ5Q74bqmR8vZ5DWOTnKo1Exak84e0Ndz9eQ5LANoy7/xvcS/jIf33TLkcmFps/5AeAGSQ8bhs2M98qrkIcSVYV/Y7M5Rs6hpntLQuPBywx6wwAwl5CMcbXU3MUxQV3eI
    admin-user: AgCdwZjowHUVhgp3+rL2b3cD1esqQK5oxIsl0EMscovckoskNMWVHS4WF1HZFB2RNo3irRKIxSqtDEP4JuUhlw2itvpbxv//g05861v7k38a5vPyHzpu0wkUX/iIVbFFB4AhHtOvpn6bf2w4gYnwiXbS2v5W9Zy4zEghf9JrmLmr/hKAhqp/2dSru6EcUuN7fKTKQ4oApKksR7sZDtoQ9pwr6p/QJqKwUsvcLH+9s8bdy5V8OjKVzbl2+SS1TUSehax3Z1xKZ9NKbmbFF5IjGg6YrJiYtqcXceP68/m5LJ2qUjLASvSsDtvyff5cwoYNRfP6bIRIHUYUuWDPO99WqLAi7Dfp0KVv66kRywD5SUyINXOl0g721GCmwLfGOLc57aE+wq4l4mXuk0UM7xbOQlJ/7LzOtLSAxQmPQfDdFXKY+lMgDwgbfOMs6LI/cBI3fHhaEaOpswPPB+AWIFpN4M3GWXnj00xIjrGIlLqpGjCPbq5eSp83Z1P3M5/pnr5SSfdTLf76tQXgsQEmc9U4rhfWCmHm+3aonEFUp8Se4obdoGLNe1B5LlpZEk9OqINrDTOkNQAmmMKA66S+OXpIHASvk8OQUzx8FLOme+UWVWGbqj+s8XSaf0Cu3ZuVW6epzdsj7n/RNKjbSiFZXu6sRp7B30XmX0U8wuv58CPAK8fI3Z21jAh2vNkq/QMgw+/RUPcVE6CLFg==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
