---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCDnnydw662IF9+PweEmKmIfDmSlF2hmDqn/+PCjouv0PdrHQGshAjL1VO/FMwWC+4s+vLkc+ssJvEfez1WScwV0U19AjO6acF3U1Kck1xIoctYWympmBzzARrG4beuuPXa8xDbhJsGVzjny7qsto1DL8wPcgt6d07/s1fo4k0gQfkr+7DBd6xhww+p/RY3L+m0UR2yvlApKYltaUa7M7he2DNjap7cm7wNJbxDHogtoDHo0HoJkTKcjhbe+9q3LpIfaf2GExrk58uFMMIEBsvT1pA5ccdbzPh/Yj3wl9eyLxtlD8n8QUhHnYYLVnwM60u20qo/uvtmkKcYvIlS/uQwj+h73HkDnBT0dM5BE00ABZo60tfQKwF4a9Cpk4VxuFLB4ehQHGK7IL+xF0s1OljczZVRNvmC29hzbUL9PUx5e2B72Xn6qg3d7k3+bizFFOZIjP1mC1guxhaxVL/AK04ZBas1V8zkbORbiEvJove/6dXVdYsNpFfObUPQpeV1iUwMNmlz/+G6XD0bDYeVqSk7jHBUFLJqPzQ1g+0gBRbwvJicOpqbnDA3q6RcGwaSGRixpYf4VJF6Q4Tdly5YYNKVIF1wbQFlkz/w1YWVjryDp1+WfW8kaF2Sol7PPSjSRNTyXzorRAd/M01f3UnZ2cau2f23o4rO0t4DvznGfdqvhnroCYNLsLsCOO2J19S7OVLpCaHdpyeq
    client-secret: AgC2RWEOd7C2v5HKDeesni493e2eGw4gOSBq1OU7CCRf4/rb8xAIkKUFMxvgClQp9xjkGxmf180nG9FjFQklbBEb1ME0/D2vE9Myhp9n9xrhqsCvcAMAaYjlUCW+JmfgSIdSwu/GgAJBHE6feFR7dDmhjlDS7fPxr4+X1dsMRqCFTdixCtPhlBEPcWn9aoB91vAhLdHYnVx0G64lQxyDZlKmNYdnoposDgcOntwRYHugh8V8cpxUATpksCdb2UkqJtxrivdHpIbbxUP6O3zmNVikt+ItEkUas9Bs/pXniv31BchL4gR1cAWLo8wwuJGQdQlW71zCiV6BlaNOpKD+Um6+36clbsaNFJSIHRae4bB8XzPzJ35yErnSU9mY4cAaWWt91cWPY/wSQvbRj//Ti3Vnf52p5WTpnz3ZE93jPIstCN7EahVCooS4dWc0sGJIFFmNXc87AivhuEEea4n6pwTgfl141XS1W+d7GJBuKojnYEdo+C/DXZmlZ8orul0QsXd3crmsLWeser78M1c6K9bn07dkjuV40YZ/BISNdXEbb2ilBQLMohrQgl+C/96M8pV73A8I/ZJ8atoVj+FC3BKMaRxXUsn0J5YY8OwYX6xAmTR5lv4mX20H7k1j3utaT2GzwjNjre1grqr07pVOdICnC0z5I2OU9kyQadZNIRk6FrlKRDPl6uj+cucSj9br1yKFTHs84h7ONIhAKCoclgrkLWbnB0Z4qvgafk43iazPYw==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
