---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCEd9IKwGMJO2tZADBDUPzuJV9eTyPZo5R1CfeWAni+9D5dSF0/qx6ayMti9h4o8trgTqY0RHDCeoIM+/VuqARomPv+A+sW3Ag6+PG3sqYbTBw1glRHWwLIl0gXqM8QLSvY7qQq2ScXTfMWXL9Q4MJU/QlranOXkeK5qVSRmOTXywUQUakLz/2xGSL5qmpIkB6gfZ9WQSGg30DV34wxliUvapkZHKXOvzdXfMr+4VBxPeAdUIKNCslDIFi1U49gTRHfyN2wiNV5+qq5iTpLG/hWFTcKQPY7tJTvc7MZNCN3hdfVTCx6bmjwPZIHDjf0L55lNV+h4wUJgHxk/obXwLihG4OgZw2QNELoY0MTrel8IjDA3PWjk/p/NEZDl5/vdndDVKO+epvje9mEpvZCVPzBz+Ah2/TRLj6aghxOLulZ1LcX3EIj48lKdJ41D+CF4GpOmsSk3vIv1pgaG5HzZ4igF9yBETBwqdz1NOk3C8X5kp0AbkjWjLGaIX741wMb+9qOE1fM2ce4vSkubQKZ7DK1nL31TriSNmOGaEphJdbdW1+yBvvAy/oJ5VDhwmgpgFvoyTkix/xeaLCwGbLLgbVhaVMmRpILtqY8hfGe4ZMs/dAKsy2F0k8P6/NvEBKfrQE/ijR6v39vlTm8X74TFCdrsNu44P3JfBQzucg0W8LsuhgHXsnDVUUAx7QVxrt167chzARqzL00
    client-secret: AgCaAMhaZI5cVTJvtpt5cw+HeZSdEgLSDJzXaBTftLPFDedUNlSAc1AH8rFGZaVPXWKADxCQ2yXio/rFaqHZQoQoeNS6XwFPaIYIZkHwslwnn6XcAbAHZk5k76fOC/gVw9KjONiIbKduVJWBuYWHDs9/G+CHM+vgPxPWfXi4HgT7bkAUBMiIxN229wh3A4PcNSLzj1JWRWGFNVGPxEJVyUONGSe0pUOq6hsHV845vX9N6o2vMZDP7jgpAdw/DB1UvCZ7rIscOf5LViQB2n60fZCrosc3VFrE779ZvkgLQdBS2f7daiR1tZYD/75Cu1w/AW8WtqBT9/WuV3ujy6DRXH701n2AbzpnFvpQXe84czTI6JIQJdYeI+3lul9JjYUZLA/IWLy22yzcK+MU0lTdLocqTFmFyh/irSmoLDTNsZJmo5iJObXAmRIu7lYd4XjQB51CxsDMob6wP/nQuY3fNE6z/1W5YyA6T1UAewgPKR+HnhZXCDg0xytbUdQ/PJmTvxLssDDvHvwYr8IZS8Axo6RHF7WYRPd8aaUzRC4qJCRecqQIiMAWW02HS3fSkpCQU6wFSebX1rhwjCl8en49wfHGxDBHSZbc2Zv/Cs2D1OxDwPaiWoxPBHtktJpB9yXoBvl9v68Eyws6j5onnKU4SZdNdPCla4JgG1l4dWslIMttsk2uOB3cVHHmAdX2G88S9hO45HJuH/MeXcHh9afAS4BcpMt3Ue2DQuSa/6DzaAq5Ow==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
