---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBS+/Vvm01J/P1poSVhgcVGbPFv7DtzLnj5l6onIIgznW1ji9uUznr7N+MUofPcYsMIX+L6PbSQt1iWbNOErnvu1wu+0TVPM14WPVq9YLZGAlbW3A9hoVvq6C9RHd05PjTIP9ExKWdcEd5e/Hb2Z8m/8DQ/ADV6X4okAQE8eokXxpTN7b4AydyeA/N7o2GmOIAsaaUX74BVx+o0Kh37BwcJpHiuApL3mUHf/hxp5S+xXX7OP46ib3q8fSanEvGvUU8xxAfFNtb2Vkh8T4etF0VYQ7379eKk0MOGT/OxMMcxd+rNp6VyzxliV7+d5tGVlTUs3oQKBSRIrAHH312IgP5wVHKgiqgBd2sljIcK8rHzh3osPjROOfvs+eFajQunQbfGXdXC3z0A6mOBysBVQI2SALbayVAXJ3EN9JbOpR2TosrFm7E8KfJJdMLwLnkJGeDDk+8cmjmuaYXWMHDuV6oggbdalz3a0MSnPKdV4oQJ6ufupsw1t10LlM/wLll/5k2cXhDoxfoeH78temi9VZKna1tJVeWKuf5lFnGy1o+6wGyMpD9T6q0XN2vuJZO/lqa4ROc64rQ27s5iDFbCzN9BQBf+CD+j8Ksw12pN4wNqfmnQaR2wrO17yRyhwHmqqBDRxVtcj6bd5J8VyTzTvz+NMl+jSjEOLeBYz7qaNbn4xz7oNBauQP27E1i3SHmczUBm0RyHkclZ
    admin-user: AgBLJbCGNRqNy1i0Z++qiSnmRp3QB2HUBdJL26fUSeeK1qeWWPKc/NhRWKA6VM9apLLguAmm3ba0GGQaokXUX6u80T1yRnq8UT4FWbj0A+Hzvy9TG/0C1KAzXR7NF/Mg53N8fqQOxqjTaWUwDg/FFUIg87ulCG4wThroWyExE0YNaWeTtC4VQqQ/bZnSfBw/YshrE3LgUklqp9+8a2TYrjKgceCMDxmYqyhkM3ubzwZOTe+RiP2c5hGGgu3eyCT4jSbbnBu5PLralkOFRBKXqBS9kIgLCuUxKNPNaeljK0BQ0KYhePTjmCqo1XN0Felg7jD4z/CPY8itRRL2zOnYDIZKkFUP9sK3rQd2qUDKmk9OuMg2M9s2lRE9DEMplWeIuJKl06XxehCbmJ24DbXfoZA3glGoLm0HJ0GlDQqCEgpu59AsiAsnCB3X4Vf9S0WUAgl9LN8iMKGBLcLkf9DVlCrKHKwIDm4Pcyvivt37HSiIResLnRKY9nk4gNrnmkoNECynwUr6PNsOmg21UH7vBivjONGLh9/OL0RdjVA3SHJeDw/Roh2IqaTReU5jmubSYPsXD7TjGQpsoy2ef/+XjdayUViu8LcfXqezKHVm0GO8P1pUHdmjSjc2H5cmAQJulhlr2C23B9b0KzsYDAXmH3jkoq6K/jTnnta453RRCpfRAOdIMpQi5z4Ri9YUyAIuvbcaYaFbGg==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
