---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCUkezhq6L365dPfIscr9LDd2qfE9JL6hkC1biZrLO31WMTwzJ5CEdKAh5ZumH7iR7m2KMIFAZHwL63gdnZxkfReCUxNCG6jo8JL8OqRFOQoAYQF2lFbc9DR0ERWtCC7B42mgtpm+mbhy2XwYKNbJMYbCPHRfwyOfGww4JDodINxaOncGYGPEbBhPIU2baZTOk7MFrxwlTczqb30Q9Kw7RP+ZWU2fIh4IBqsniWfreXsgS0+lhCL5zZaauYwcjNfOwIaavbcU5w1L6F44MJpg7/qHdrmTo/ItDd0geJniKplYri65UGxLJaVrTdkAvkwHJsE23gi+hPPsCt51a/e0Y1VYjmC/oVQ0IyWB4Q992bQK2B7vEmsKaj7LrC3foslKrAmqn+1AJL2nGr4IP3QRN1omFtfDk83Q0xI7Vkg46g5mFOVpsFGZYudXAZULmJRiMhVL26w+f6Uk/PamPUfFJlMVyUxPqGc3z8iTWtDCIHsYVZOUKosbR2ZTiQXxLjp1XSsI58lSblqRDQJ9U96KRPRd3bY0veKyzC/hvej3LG382+QMxMNv+OFLBjLMwLO2vvTI4QWDObKi2u3pQzabCX24A3ED7EJ6TsMT7Wz0HOLl66DTUPiNKDgKLj81nFdhX435/kbAsOX7KYFze3QcJTdtmMOQPO4RaexNhRdJm96OTC1jBHM/Yq4Okj2UsYvA+FdgGhn/dv
    admin-user: AgBEerDENLtYUPGiRQDYRtdTk/JSm9ORFSYAUys5U/xTKCD2aal0Rx1g5mPBjAX33MDZw7PUNQtSsyACPPsNdDmUzSCkEsYZGXOnlfXrpNmrGofBJZDU0tCuWyD1MsiRbeIcDp8b7URXLJMpBW7m40eg05XPlAPHmCOOHQDHqKdcmM/rK3qVkft2kkHx54BwNoZPA3PGw7O5CSH5bQluCT9forTO3Y6d/yommgNZJqHsyrIFoRPUlSx1ySmaGa6bvGLr8V4uk+gGA2+dMkSJEmR5hoham3Pu+pF/W8Yg4sFmg+7FxbuA3BLYGtoI34vCw67uimZV/VeVOyQED/u6NXPjszNwJzuGRCwqm4RzxsvneoaL/wQDsaKtvXBOJXjTY35V+2ICBmSpDfeeoeQM95QaOAhkP9PHvmYfrJeqbGhnOcCYTbdv9VkMsqS+kz5C1JnW3q3PmTRBIIkLpLIg2vWX4yQiVFJj5cJWX3mOpQnLI4GL/surMf7dyCQiDnf7+U01GeaauuNul8hGNGA6rszx7mQj1MgyeFqg1qLq9x7271ASzgWH9K+Afv+bJlOn6PKNkIoHohHWb8wWhrtuGZHK765PMLdGIuJyDC6MRL0ZqQS9rCUWh9WyCkS3Xms7MG8S9gOW397lzHbnFn+E55/0NrLnblRTbHYR+s7f4KaXOynCAl0ZIA1c9HvfzSl4+ReodMjv4Q==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
