---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBlGi5qUBS8JNrRuX59WsfeBiGZyo/PbOq8OQfy1MjUbK6/zsYVt9dZk8Nky7qrecsygPD6eVlCkrp+sYvobiGNnwFrd4zZZw2QNc5UZeFZNozJQgJbNDYkHNRvw1j6f/IgxJKw4Q0y+SAvQPoiHE5Ndn6hGVPkkoijqMkixfK5Fu3+pxeRzpHYx/ArHQGVlBGnHale6cxB5hSZQMSf3CeKjXgeOU/pGxLiAihzs/51IIAm7OynGo7dHS/e+t0jHLrbm7IXM7AZ3JjpP7fWip3Gz6leC+YXyw2tgKDrhcrJIZ3CZWEwvsu70PAS0mEgBBqj/jG5X122mmK9sLNflwoy33hbZ83R2ZVnujsDn2Du9JlzLQm67tTKibCt8flb4+d9Tu3V97vZ8eYnHMTuQv5BYtkF/vLgnwA+YP9FDisBtQTLbqZI1Rtnfp3lVC2i7K+WV0s9SvStd1wXVliRB0jOhvcNISs6up0+7770ZLI1X8PQhmTSfRJTyg0Ml6CQp5e/XED4yD6uJ+Zk8XYfLUfjLOs2AW2OSLuXM35dBmAuUg5ND58FBuf7sqwLSYJ+sjiTWuga/WgE4vKZbcOei2GBYNQIqxIOk39hFDyd/YPJ4KohOGvbxAfugRVjC0WVAS/beptcB4qATBEC0tSuC43cI9FnIZkmFrG9xFFvwIQWlFfWmM+TwG6Oll2KD8KIE1c88ijR1dwb
    client-secret: AgB9HjAT8T4o8vHN24RLwf1uG6yuJenTlQbMShND1IeEYZFoW01GZGXfZ3Ct0ksqTesogtstOrxuQG+KDuSORtmsYlr6cxfiRr8hU3fA+znassPa8yWbpuoVgFvCzqB0TLiGzBl46aFQJ/HL3il4PWPfNKnD1LpQuv5rOILhVCMfsss15MDgqSZzJ6xv3gYuvfSMRzCcPbWWrF4ND4w5KlieXx9Ztwl5wv3c6nOrVRBbBOwDFjHgccf7Mlz7nK9+ZmMz3hu1v7vXqam2ezdIWzu7CR1YJCyHIu25QjSJSyWBzfHje9vkQLWTmkCBPaxtwwd7EXLDHVYyp0QiVbp6GeH1UeeeEIx/bZYSlz9PTSMdhEmfpWOc5l0YpjsboYwoyEza5e9iLBA/RDz023dFdTCO+QTvwC7LZg4W2ZCUish7DLbWkOKHhQoJE8F61o4Bz6pnj5nDO9rGLOZQBzekHgfzJZ0E5pd1pgulgDBTs3uQp6m8yLg+SMHL7tucqBKBu2fr8Gx73VlSCMyPwRlJHqD7NJvDALrNN2MuRkjSCMsSjvgQMBLnXq55HyglKW9eSpPMUFPvG0c2vlahSiC+Vzc73m79/SkOaZWb558ssNzZSPRrpol0li9GzLylyh4GDoV6v3+56ebLxP06H+BOa1K3uJboqjvTnnTWWckfwYmeyBi5OFyRqgqrYcF4/XBaspcMQYnxM3N6cOBHe7OjKJsVMbaeJvXXSnZumI5mVZESNw==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
