---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgA43MFDg/1xyU08grFx/OIQA9NJscOPprSGJkpa3wrFDaZ7mqLmA0T2QQkYM8Sn2YDmQ0SA/vt9YdfpenWhgxrBK7AGqmLFqG5bkdiPwSri1ZzqlC+6pGWwk+iAAXNyULGw5c+osiXS118TwvWT583LzP+SpTrYvjFcEWb93eOyeQcUces7bRHeY+qPp/VhDZ1xMyWM7HnOK3ezKZZpNkQkNjnRoi//GTng1liHAhLV2sObJ3L7oS4aUdIcdMKEEv4zKQp/sZCxCTw4jImsUiOn89I6p4U+uxsABB/GBP1PmJsRSnMt8icHEfqzMyMG/CuyWXvFdonfJa9h/V2sBL1CneCvcSdgOhLCcLPTurn/z+3IXm94IQtMZxYLIgylHZZCkk0lK7auJ81Y0lS6/4WSxFzaTizJSJjarT3Mhdm/3djIOI1Sj3aO4KE8ASFKSmcKt1Jjaj+/r6YmKJaA89USj/grD22kfVPOw2G2Og9F7AXWrQU3yrfqqVLqRkqWnHc9muJhDcIkAMSOMWUNj00U0mgeM4R7lSU+2RInSzcNsEsezyJ7CHs6QxHsE7WjPIouStZWtnnU9ZVyRsc/77xdqGB3SKv+CUHr7nWkT3pGrog0b9C5YUIEmZLA5MhUcLXy3MKpQDL/aROP/ar7dOiIb0xxNeqPfy4m5q/thw4DEoGozWgPvVWgLfO9R45R3GGV1xQhqEmR
    client-secret: AgAvKYKexjfzRV+Yc6I15To/ng/PrNe3CRo3VV4gIdIURKXOXUtyLOiYGSanqy+cKBvsEz7/Xe1tLPMhgbDNfcHDbbEy8iAHBLJkARf7jWdJt7K8zul+gQ9AAUyiVNz0XynZedjWxyZRk5MOxnS1DLKLMfeJ6d1+PAjvPKG0amHULazamWRMUc6d2Vq/2Mhds3E4kY9+urNoA1sO/9g8M4WfEQOx4pKN7vWIEXd0h/YUkL5/pcjmww6O9LGi/+Q4cRwi+tXICsCsFyUQ0JmEcrWiF2+TewDycMea2dyzbi83ca/JZG7EDq/7tlE7UCYl6+fBNdSMgis7eEq4wyMhYXfd+3bdqIIdBUiDIdBt3Z3bUdml/Z0cU3Vcw2UeReI5+rGuIvyvRPajqpg4fZrsbBHtrCnZipCDdRgWEmgAF7IuEGq095YHAYU18b1gZC1vGNd8p1LBDVLWbuQmEsny4M9acm58XKVMWUNxpcwtYwwHCF24hktyjgsa2a7qXGr3hFzMQp0xK2QXd54DRjvL1+/PTl+5d/GUOPy25O2VzkKaQob/5xGQpFwZ4rRMkXsGjni+VEALOP1ryKRJ0xMf5/ysRcKGcNweXw746dySwcQnW3U6l0E/pjtdcTnUPVVe2AD9IRi4QwSX5lCcWFGihQdX63u36mk6LZG2jNvS3hb+QLUGMmcfQLFxQXBz6SWB8axmQ+Kk4aPQKc4/YzuHkiEbzTHfq1cuF3LwHtxYFW9fnw==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
