---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgC4XduzS0AUGbtCQO50TOUi5C1wUPCgdzB6jj24LZfBHVFw5KGomsaZ31tubY3it7mcPaklW0Jg14xWP599Sm4maeLJvPLNFmNNYLKM7PI7MNhee5gI1x0BvUml60OCQsGPLE119wutoeIsiRDuZq0rhHwyKVVNH4SJJQA1Ai9uNKE72ZOPm6YLJs0fYM9X2MEr7TJBij4vVpptN+qm8Rqoic2B+6UfbgFX47iAn12ctvKB09aIXK9HqRfEgTmF9xjR9RokWar9UZx2VN30rfyEMmyKArfel717zShatx0opXfSdd3ZSEKiX/8QvN+a9IKw//uQanKeAgLjyZ4UuEtraR/VEzmmsxjBpWiRFkI6fFPvktH37rAw9shvm0NvovslaZEHKNEXTOhJ0MveZx0UmX6oEUQymLU78ywgr1RLeOoCXkysMpw/3cigpIlN1UgoaKW0wLnEgavG4mK1ijO75qn6ts8v2sc5UPP6+0vTBedTgMMVL//+JouxWBTr9hezq2zlcl67Izm+i058mAWdLWNkavRjm83XN64Vi+bx20xde9o+waI95n4+/4Y32yf1Uw1ayEKVrd3GaAT8xDIMuAD+0l2i/tf1Qf3clguKDyyZRCb41NLZU8Pu1QRIZYIOy6bQLvEDXEwmgxsZ72bgqQMJqPrtEq7s4xBhdL/CfLc6lr+oq7U2z2CGuwRxJzrr/qIS9n/F
    client-secret: AgB7saHO64Vek8JpMMuLZ/pFwX7gOOFobJiPayGqj9Srizy0sXnVkuGEQ+VBMJbG8jsL5V1GQHdrXm6Vm2z0Aj08U2efA4JnAzOyE7oxrTSaaZl+2S65rLViwDIajCHdWzTL5mgK2myMM1Ge3olB/GkyYfRvqI+y5MGGR5rFhFbFP7GFfVOUWlQ/du3iCi9OQtbX2xwn7op2JMhTWXYQ/C3RxES74CCwRDUVigKgLOPj7xFDyQbJi6Hx5UAImk1DY1aFXNLNWCKNMBYWDJCko7RuR3S3qqHV8XmlouGx51QLR4EXkM8uhZDWDbAGMgoOip4Uitka6vuoPHA6jV6Wp0dZq7GXT78z4M/YZtM4MeIAgXCJJg0SJ8MkQwH1rv1vYLBziq8v1+UlMBRjhax+uOgrdWAn3naay4IBv+YJVHlC0mFSaOsqEHwVG/ljegqQiZqB0hcuzAMv8jtMKeEX0xeYNnDx1f/YExy21LjDmb0NE8p7BSjnnCiHza0yGhGJF8FpjJSIL5Cx/JyC59bqtGsEIvbXcCsrsxAyjXMdJrk7onqYV5kcnhpBp1Na0+notOSmO5rjKwmtH7LwgfIjmiJxEeKTJOpAWTzPemm8ZY9XbJWB9UaIOPvgwmv6L3CWz5+aul6s5o6XkQzK6zM8IDdjlHgFWZv0axA1GrG2PO6PIEyfgbImLqbPLBOUut+VX8mKX53rT74OlpAgCgLU/K0GdI5Lnl+A2kRXatnHFZCOfg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
