---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBnfvTvV6l7hBzAQ25T9J5VxKmfN4FmA6/ff3epFumlIy3vY/cgo/O6FduxGNGGJqTyrxleDEbTerApfdqj4lhhX+6GuvloLTF4AJnF/UwB6M33JpkvKrR/fahUsk9M/jxhqTL6MSqqM06iY8Hi6Pyfxv27Jhoh8jB+rfmgyYWYEA8SO0c97Saf7DAdyM6kidxtHFAsLgNC/3Wf0VSdZeaB+kppYkUGprf2BmhM918tZbPLKaS25a3AwlOCFMQh0NkWGJLhDZjC1JlrpmGprcIecq5P83rfw7iHG+T4K7FFQFqQ8WA3ewBTxQhPX8Ahopnb2VyaUkDshtejSca/pv4Dzzq2S4ge90Hi9jAvZ+HSwDnj085LvXDg9n70w4ZTitWrWKWgBgpWj/xAaotCkFoELbTOE0Age4HPJg7A5V0m7Q3dZ1wJFMF7TD2QWz2SKvudmZd3+xMJ6vpDfRvFD8e3CH01NKcAV+8h4H3KBCYVCb9WYX15bbNx9PYcJK0yPHxFoRS0cq1oxMLD4dUuwsIxzuloKkVpF47Gk05msxgAViCwacAaWuq+U3JHWHHthXrc0DD7DRNcQVtticuNoCoxNA+0wdsvHBEty5/vXYl0qAos3g6yoIQfj52sTS2uqZ78dpJrpKfE95Nj8BUEIM7Nvdq+N7eVNINwMivV8/SOEPfZ0nyOgBVR+tCimRsm4abJeEyd1DSS
    admin-user: AgCfFbjG+injg8TKKONDbZcSy5jxelMHyqxQwuL3cwcmaZl0ntA/sCoMcaYUc3TV3x+xt9RO/LzAig6ZdnIt/hn4RILpaLdML5TQuWRu1v8EUT+8ZH1cahqxY4yXh0EzixR8kTtPCMiyONT1imTcG3OWXi3nkxtTtAsImEcvLdGhILcW4ve6+wmJ1NMFWq7mAHkBP2XuE2WgkEZpD+pW+VTGgccwH5aLQb+xWuqvTI5WoNasyoClVneS4dGx6fBCekgglTo5uzMN+MheuaUQ1LZVtD7EoOj5x25XW5Qz65TXcT/Wvnuk2OzbQuDhEeiKk65D/8CKNpPXfSADWzj/+GbdvyCwXZSCngJp4TydRszuG7FEImAZRM7T4xXng/1HsYaguMsN9/yDjySO4W4WwS2/5ybKM0uoCQeC+vW8vgQLMDWDLAbXE9mc+ErwqjpAzvuljWkRCZUkRsSsjeC1B60wBfFs9qvPFXmEhYTIH0jzwEeU/MX6FVYfIIerF0sFuQA/tYx7uKwNxEciOJCQ6Bf7lKdZCG0Lnr/PWzEVNHRqHC4/5FVCxkoCoI93bT9lNyCX5Iz8s7YSGLYgxHa4sX21iMtMPW13UA7goFDYbP+CTvc4y/HrNcSbIFgvSPqwoFWbzh3tBJWVklPc4gvRlpgQWA2iMWr3QtXN/t+Vm5/YFhV2SsZG6F0B183ago37MTXiOQ41gw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
