---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgB8A0g9gj0SIIxlSvqzeMV0HOUZWVfAuI3LOqLDPLy++yy6jg5pL2CZZYCq1TEDbPuTTbVjvk8LK0qgWYi2p1YKNBoWhtPD4lCPVcK9phasiGWNf2B7Gicqnrl6lFyEe+LTNH//6aeANh+Q5kaSJBRbf7XN5r2m5UjU8gAIAO2DvZnf3nHcCDssajFn0Vg6wJzoUgsGI9zIdlEe8nPGeZzcK2CgphJFptsMFutDkkhmMNkWT4oaa0nWGdY/zMhPCGb8nxX5vbqCr9Wt7NJRdGCfbXobkDWZEvgOyNQuBhrup3/iL+0OUUwctGcReHzNYNL2b7X6sjbWo580Fc2xy2AJnl4ioRvP+pfxRDnWk4A4Te6v863L4UqC1yG/b1SSLWQ51zo1jrE1ujInwM4ee1czewQU5PDT1RGN6nw301Zk7S0siRyHcMcrf4fJs8JzPZdLVwZKtTvyJnGaYl4jNQ+sdTYxdavAZPfNLEGqN2F4ekcpvvBLJA1iS/zBHt95FQqY/Usd3xgWjGO4hgOmuttuHrXBVvm6znSRw143Aq8ChNdLhmWZaHczfy26BGaNjMxNeBgOdpOrK9eP10VhebjJFJJOyptRt+wEJ6Pmka9HCwM2+nO4Pr9wJDNNG8oS8SRirRfG1J2rgntcJLo8DYxls0dZybrHIPMT/A3QHKnh9w3nGIVcpl6Sz9weJa3FXBfrJ6J02soi
    admin-user: AgCixeGh9EieX92BP2GjtjBk+GzPmvVBiktPCYIC0/jTpKMgWoHURoOexXqVHOQsXFvH2bqRajnGlvkGsSPLHkuBtBwdF5L9TCXCFFfAVaRE6evR5Jcw0sIFMZlZV03u6rmvgnvIQPQ9mR9mrt+9O/EJXFzRtor1j7ZV+WxFRUqkepzO4uld0eIA0S9TWcZBxD3gwvZIBYFggqYCtJGd8Gz77WuaGMrJgZzO7YnLrlh8iyZjCIYN2yraLibnsYSjyCwgaxiTym/VBoc7sUg0GbOQbtAbYX49AyYNquJJrEPO3PxVWGvFqCk5M/DC5lwJnchgk4d2eOPfkTVZ7Xso52kt8nv2zTOvkIh3bfumKh8/W7tgYRqaX+1wkVK/PSNjynlYz6wvCjLmPPwFI5g4PoE9/vht1va2k06vtdf/aM94gJc6QUYURGgpxzcnRTzJK5H8TqbmrL3PlzNk8kex7zxnWQExmRdY6pFMfHSkMH5zBjteCv3y7GyS8RxQWhp+x5QLdvwa3Pb9UCGu4VnoOYDc0gZ3feyfUnFlh7ILqNMnkEBFLPhlyGPqJg4cFpn3TNtxgi4xUbl7Tsh6E+KLKGi/7ZNms0DyV9l1Zy8d8h2u99m4OcRV1vnZ03FGOja1erJnSOACbzyaCGFCq1apL+X57jb+5cmpEQlqqp4y+V26TJYpS/qpNu24JzrTOPjAbkJoNwq8rQ==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
