---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCLGXSKxFIZ/pq30XLNgJ+3KXoPhqxTu+Y+7UhMiY11k7NKy2IR1lD98psLREtagBt8O3zEsPpIGqJgj6guvMjxgTIPEsAbG9gEkodf401VLYUgehSdHJm3gisERFsndPOFqzKymSRWlKzD1q66DumHgFnQLot/SEw59mY/ZSpuyEWY6Jr6LfnQ/ueumQCLCv2gCrc91rfBAlf9FgKgeu1k78j3/CJ0DGrqrsysFGYOQCAE5VmkJeL3irfFGNNtO44Jj+vGF3jPTNltoTAYJG4u0Q6LC++w4l4Wd2YgL88XaRbDZQlnajw1hzLf5GSxPcl1wW9LcQcVHODSMruMoXtgugIvvWzRf/0XVYee/0QbmIQVCWxerzLC/36JE5vytsuMxn7zZqAWvQg2O37dur0UTjPCzXlt8RohrCo2vOLegMNRoBQKcQg1krAWpfPf4vUBo8lyEWI/Cg49bzEhIp8OCrusOn74BT4In65TxnjoglNi6t/j0GNWFreUulwmeonM9OvijZl14t0FOdHUPXJ0PBUmCny1xmoh8NTrtP8yne+SOh0wZbhK3WjS2VRAQPSsmgTqGQyLgi9ZKjdD3IAtHOabTYhHncKiMQHcQPVgHs8Tsl4gZbHJXMlBVmhwFF2GWAMqcmZHIgVrqFa6X46LKtk3ll3w9IOAhNeXVHD7b5gmm7wmNvQ4g5aHqTztvIiu4MZoyn/g
    client-secret: AgDBDNXyQ1qKa6V0BYCN7KF0JpYSWLS3Tqes4O+WK4EL6rHGGzwmJhK0DEyufJT3M9ZpxBEu3cfmiHnUDXBnNcskjsUmsvN2CaOBjfGdVFHNynr+EV4rha3Dm7+YnQwcZsnin4EPeJNMXRm0lo6AlmVCiXdvCzLzRtVYMEDFqhTBxk7xdHgg7et7ssEtIcOGFEFQ3wKFXEmaca7AbzUPxXV8exzxFWkP7cRX/biIgdX6aB9MeUPKjybusWAmyfkO7YbMTBPW+n/sK/7MkkRbjxDOBrqdLEUwE2qoAl3L7B8Z/HujSwKcYm/u9/JaesWBArTCqbhVEqJwrUKfT6WxVbKgY/YqYLA05D+Oqpa3AYlqXa8yAykwe3HDbUKJD7z2kWZs2KUt24Xs9jjAtG1ypIYqKQ/ObQcQuxpjKOm2x+ttrD9S//fhRir0WCYj2cWCtN5oQ0n4XcTDKN50nNc1GT+nVQASqYSTG1s8Jzo/RQwM1cJEWyzoU80CqGjoEFWBdO/dMmCkt8WAl1xztkqz6Borr2viSbJHHcvLR7u8N0DEP8Szrf1esq1gKinXCzMq2X0zHZbcl0qe1aNV3IIsPCzpXXHCV+TuOJ3+AvZD1NHz9Diji462ITqcTYTLpB0c5dz4D7uRiN1B4Yk325xxQMI/LTcFybGoMt+HV+i6TV3YBn47dHH2F8Ze2gbrNtVCz9RDG9dn55ny4w8CMjTJ5UygpcsSuv4KaXHB8L8ljSQYEg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
