---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCfnba+X44UHUdSQgCVrLKwsYqvY6uVpX1KvitOEu/LjvP9GeNksB7JuVAMa1pmeip5Ri8F2yBToVisSqE9bf2VV834mD1R/Fpr7f4wGxhE0KJGcHL1zgY4VsT1AxYVuq4jH7G/HKKYE/TKLp9INGfAOKY5aOvU9aGPC5s7fh0wJdVrinZZuABMu8bFj+Y9nx9i4mX+MdDINLZ2spCYB9/mE5lphJzGshlk5TLTvamCxM/yN8aC5Rivy/PO8mlWVl9kaIKffZR/ZMatxNMZO694dWuchkdKwIhFc7RMLnxm9T1O/7iLZv2SeP6SKffmp3Y+Ba+bXEiQ9AldDPC1TeSUsGB22J+87GQlKqPnNra+/ZOLTKZ1RQFHUCAAYOc80tftM7GBlG6LBTbA6zU/+hCvqasEQ/8jR13vsEiTXgjTiPpwYw4pGaTnaTkZRjvCyeXufwOo50VV4xJm2l1Ur4kPfgWbg1RJTfujCEJ01ttM8V8qj40m66GJ5uj9R1PZEUqBATOsknbA6HaB0uGfsOFRhs37iWom2Ya7+dBb9vjXyYJePgNU1B7Zo6TRuPSsYcevPVVSX6INf6+so7XZ+yG675YevVgOROBfcBKt5cqZ9euUQ2X1bTp2Qxh6peZZJxf3ZnwX56Pfy81F+Ue2E5TzuzRDLnhINOitRdFpnY5gKakixTg6WXdnr/ziZJ6QIXwyMfrZN8bN
    admin-user: AgDBvPNoNGSnrBSavai1mC0YU0oD1RPCEI3sdJVEaAkMkOLlAL5Tu6eWmp4QFpOYX+xeZXnB1zxWd1VVFMAhWDlUJqv283IbVZdePIlqKEDI/EeOGqxWpEJn9mhTVLXvdI9Cj10GshqolHezffzST9aPS2F2oHiV2m4sO57IA3zI7MAf8P7HHapi1io6n5zTnefZLqZiqgWWmGnVasWaxyPw4/cYdYN3ocZgzUruYOAA6EDv/9CLZY9s46EPU6ilU1u8Fd2vUnqQ1CC/UnCLeAaDehPijXOz2r0nYmSSylL2mjWl8w3kQ/A2iatHskvvjuMlv8DD1d/TQiOMfjPLJ/hiq0m854czKqZkc3VBlLVgC4Vuowm0d9ihX/oib5f8kCMxCoCh2z+q4QMObYL/NNZHplztY390dmhzO6qb6ivf7LMM4Qo7p2qDLNCbN7KP+gxlOsc59cCpjMvDgIgddJJK/fEIX4U1L64ZHh9YEb9qFyT0GOJt+3ASWJ6nqOMVP0OPSraBd9hVMEt69BzhiMEm4KG58x+tx3vgd10sb+O19gNwv6vYBZSSsVaEQR3c9NpRqe9takODGOBNEG1mlV62wrkvlVXkKTmj+Ik4yVyv5gn0pHUmEqdH2SeljF4d6ZMLjOxMZ7BDTo09+vxK8SvPwJkIaGe5dZDbpWvAWC9i6vkjI+5V9a+Oob2EWqZS4KHYLM1JQg==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
