---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCepGU6H0dwKwd2UxTb7CIeEybSs52Q/LJCUd9ifghoZ4+pPTCMaWyz0aN4R1cdSj8/dGSjiamjavUuDpIXch05nAGPx2WDEfV2zfrXX1q7AwFn/79DUT4xhXxySefdugQUmx4eGah1cXE/EYo48b1gT1B99KZK5dvJZwFadziY9y7TZyIM621hAoz86EzpEjaM5iVTLx12cgyTrNsleXzJEsDnbXtliH8G+d29wddFCZLsH2K4vH4Qck8N2J173L3IaftAwTEBUo65z9awu624S+OUcRd6yNuoFQkIqoV3H+H7RlJMzm6B8E/6X00ObcZXCwIlZRs1IUmaC1RNGhtzKxJiEJXK2FIxAntO+hFPsnihsCdTtjMWFj3SEs+DUk8OLUtCX0CByFp64O5R42g3Di49KwptMAzWNYwqUo/5Usc3SIqOwVuRw2kSafr8smrPodr/7agA4mlrHUiJU/jSc3J/akAMhZWJhu5Z83CqM35JORegiSDHVrrtLWying8lfTRdF3aDBd0gpViViMoZc0iKpaqktdJd56fBcUhW02EhpTvydJZV7SxbdjnXXtDP4NlLZiWkFp4KaC9Gu1S6SJK3/s6uLZUWRQN3qlXZSZ3hFvtjYRhsUV9fBq9CcKRBWF5GR9mslgQKkDdObiUqgsJ4F52D6zW2lJPrsO4+YpC2+lUECwyoejHQPqLQzCl8NlYZio9Z
    client-secret: AgBHQp414xKxs27hluf6RJJaglRdbuEFFXV12lOEtmQTnU6x495cstFCJSA3c6VI44DbooB5MZVmgAwhd3MWqz6xirPdRwj5+L98HtTvRL1HBhJzcSu13K3CBZ+hnkVdNlj3kyQaUO9VX7NdTPBc9lKm0z0ibyA/wid7K16QBYq77clCAzUMG5sa6cnKyefttN63DdGsdboFBvFYI2xSVmh31rEGmY0FZXDUCzSAVlIRNRD29JU3aQB22LLUpYb2hXetmTtunKm+FvCZMnG7HEgw62o1VyQY8cZy0pSauTJnLQ+3RLP/BNJzVFIcDAv7SpBY9N1PL3q6twM+7pHh2YgNa8nh9gknmPVw30zQC47jxglTK7IJkotor4fPJBB0YdH3X4CLMXrPusmkMpJsyfF2U8G2A0r70ChRB+yDrjdtFVPi7c1TQXmmUFp1hfN+HRvX+ZzL/yrB47cT0WxcKK/Z3XawwVCii7jNcIeS1IYBKds0KhxILkPe9jk6f0Ejz0I/CdGEB4W8zugEpD7CWv7AsUr7mBzIiNYL7/1eE2Cv7n15N40Af2sB29z879ZB+RGC1ZN4d6uc06bH3LwhbDD1JRlxwvRc2dD4woJkIVaaTH3+fzsykkM6DVxC9UAvQLGmWgWbvB6yjfIr+xECvnDKZWdrmYgLhI+8JDBtqe7GlQgCfVNCIFrAMz1/eDEjpw/L+mdiK7KSUwGSz36o656LZpKoiFdSZcQkLyej3htz6A==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
