---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCdBBTKkZSZ638qWSeXKGeszqaKrNMLVRYiCMGnYGM51hnVMlbNZQcUqibMSrTa0dknEqVXCM1sO7fubnxMCfwCDCewd2Csd8kmEe1D6PgPcY6ZvySMrrIhhmHjfUk+YYbbW1bEBE4JvrAJS/bfjKBj1sC4bstRXfh+Ga3a7zHF9quKJqAWXira+acqqIvwGAE0CzOgemOrEyFZz7SuM3F44GHnp0X7eh5M07F/auXGcok+br+Y9vf3+yqYb3LkbHF5P4LQbcIa3xlq9C5xmL5+9FvnWcauO4Xa1ppX2KOfLTfrhazaGuW4Xzg2/ZSscABrGozEKVmEf+z01L5UZGUT1T8wN0UxUEv7cWEJGsPvVD9JzpaNYdWRxAACHyeTNNZy9SWjV+QOSC07tjlq5fL1Sv0MQFScalmKvUoXP6En76Cm1FYCo7FvLTq4cTNxkmVhVrqECoG3/9Bo03gaEKE6tCRvShG/heYidHCyi5pl8q+Qat+QV5IT1IHnswJHy3oGUKWnj0lOY2pn8uCUYBPFpqll83IU/dN0jGqm7/8PpXoBtpeDIyypuyU7hsHYAjuWpbOv6gk5fZ/l53HQ+fJKDILoFDE08joZ6ufdbCydBJSpCt5+nv4xLI7qsvhU5lUhUMTzukne0zIVx6Jjo4QduGcZz4tJHsK2ZizilykmGP9XYBPtXib/1n9WqgOmDkWh2g15HiYh
    admin-user: AgAlKiGCXMBut+b3WaIjJnurvZruK3f6ASGfFZZu6pd608XUhBY1N4Aa5ekG88Kug1cp72zsjBcY6xE6a+rPmQFQ9hQ22kEC9FsT6EksvVuMdRTTrDr9LP2mZQHPN9FBDjcuj9miScMH8HbGEcbsEKAreu/s/BGEKVS+fhAkGLsUIwhhS5avfR7U+jBe3PQli0KGpkN+Ss2SqnNP5dI2Om/kKSBOZvJnzHfRca/3Pj8INbvdm+Gcp8D+LWgIb5XK2ld4GtHhOJd89Mdba8iT130s+SeerpOColvlKVwtjpoND9pS7ytMO0lpAi0wVZNovG4C/iK9QvkkPGsNJDjCudpLfT6LBWegR81g1bZOwwGhuVoLEkePYkMMcx8/NY6KS1u1zNFJ4PGDAcO1S4VCI/vi5cGu1Qn3ySW4fqVq+wofBYqDz6R9RaDZvT+Lr/CKzcLxxsFbpBW/AoTEpYWTaFums53aDbwDtrBSVIBIneQQUw5z/d/QACk3M3gTHPQEa1z727mClMnhYct+iXWbzEwJ+KZGUlmr3pxhVFzmlmBE/oRBkU4m4ZDY3kSGjLOkhCgfCiNz9W/ZLIb5v4xiCGBRx5HxLNKAQL+NjDBoMcjW5fbzOaj3dcrfECVtFba2OCdVds3IQvPJ1BCP2cgiQ7ZnHAvZk5CExfTtAuI3bV6psMdTDxEbv7zFzDYbu6mI3DmUQp0mvw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
