---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCC7pjVvm43FP9W+CEGefTa5BJ3bCXFcUl3XtaAgpSOd8SWkthPfRZB+cHjZNZcbkwaF+0rHAvebc2yIyrjHV5xhwyFUa6Jpeqi7Gag58dqHOxNfYjCkFhuiNUoBafL2/l5IGRvtbpU/BCsZV3790b4gWBb7titfhxKlGyprs5E7ZxqXRJsmH0lB1FlWiASBBv2dUp9lYaYq01ysHEe4XV/Zr0CHvo7e7upoW80botFVh531v32v3O67Iglxlcj75hPel6YUjwgGH0ndWTeChaI82vCcEP29S8fs97aiYnb0WQ1AasG4uc/wE7rbthie5wg8HisIOff70xrGeCpLC+utF+o21XF13N9ZCkVBT4rdNWqB9yxWPGfq6POihoQdmecf4aYniM4HDA3hQg5PFq7Sv5131Io7thOKl37TacylPl69j8V5JICi/uICS2/vMM+7hMLYc1RVDiaTMtklD5GdRvsTncWZwMpM7yxtQww8gN/n+VaZ8m8bcQQ/vU0d7N1HrSzXPDs6YObs0jAxQKHcMBIBPaiNd/B9HyQZGPvrFNjRWYnd6lTcdhas067/GLgSW74/sBXIx9jexQs+nkufJdun7hWnvv9ijkitPoGZj5aLrEro55NJob32MuoDb3IUmsbwk7KPPXle9uMwZOigphLoueYZVYKxi/JbIzT6J6n+Id6OEl+3ZaIhq7H5takkbw0ix4m
    admin-user: AgAEMZXgb3Tv58+dVgBqIpldEIQxwa1RPLIuTpnLE24c7IwggRtHJ38gsaPNHjYSqfRnCpSpaXDWuFnpPIB/fSq2EDuLkdXPhFXztesMs8LDwno495tQTrCBJpUtlQ2jnSDa9Kp+DTi87xFwNOuuP/eYfBwN5x8NLOP9rDOuQKew2h6FoAXkMdg0uh57YpNziHKFBAL708HeskreBuTqO2+4jgPb4BIDUbx+tU77MOT8V0TeFbjEIEYGR5AI2rQzwiUFsn7RtFNpaEogxm3IJefa6FwYet7RyxTytJnwvob/xIub5yC/Y/x2RxA6mr3NrHwY6bZHIaoeKFZgtsDYzrpB9LytjVy9Sb+/7eFWSucrgCYERKnfdd7hbUmO4w7KTWgchpkxzPHMEWSUpXC4fFOXI3AyasQrpPXuSjrRZDZB8Fd2H2lS1+TPSjwBLMnqJqDfX152pw2kZVQ/r/8mPFdeBa25DodX0yYGPG8dT2xMBi5QIntiKc92VrfUaO4qt8WmL+KyJFusz2WM0AdUk4LvpPoTN3t7ZE7r190GWlM0M50mreLX6/hmjE3qUm1iXcYcPYSi6n317u2Jej15XQo4uT7UJNAWG6s3omH47rNOdgLtATRS31vFYT5lP1k8StALmmUHsZYQxS+KYRBQh36DW6FxEoiDMNwau7OpQnO21C2cTclDeV8jHVic04hgqWKW/HV6ow==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
