---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAucfRvA05EXs5JETUq2Qjs7MvvGEgBbFcpKn4/jLRRsP3APbQBY9JyvAuQ+fTUszZSBMAD5anNiJK8ww2ljNHHioueYK8zx62w3VL4H+4ZZ4R3Yugswmm93EJ88GYYatPUOBL5He27/iISKVxA8+H1Ea4GJHOoSeH919H1IbeEQanUICD76ufyrScZiRfml9L+YxzwpC3bSMI6zJ5R5dwjqtk4nO7X2/DOVNmX7GIAyLDK5bZriC/4Rt2qMYKkNzpYKdx/PO4p+BbEUjrmahHcMgAb2Khd3WiVOG3xQiAMuw8XD+SXDM1c2TKt1UbdlA6owqxA0hBreZb7go3EsRhJM1AJNoNzOHL6CaVh0owk9d/rfXgTIpRbctO1VTfajCAiiNr9TWVKfeitTPCzzSkF5XNmjm/k/fCcRZt1BkcpGmSMwbgnfvut9hNpNwLQ8MP/MtCnqhwvEMC0CItyU/9EpZnfgcumLjTpMiWdext/3JZsJOPFyhDHi/4jYtQPzs8W24chtTJ18qjHnhuJKrsxJHn82UuNfJf0uzl30SAhRku0RFCR92S8l4i5DCbpAs40E+dncSzsjq60yspPGjtsciDjeDR1IhPkfLXJN9b0lCn4OBV8IZz0qZARIiDAKqVyWUd53Hpcc0zp4f/tSG6keLDOfLUjKKKRuB7UB+ApatG2RF3xDyjYQIT8AD1CZH558bJFtQVV
    client-secret: AgBR9K8askk/Ms9O860/NVj5ySb5XDRSWqtcoViS1/aLdyev5YycrIx4qzRRpFVNLhS+TIAmCZMAY+nepk30KZ3HzQXrEA5I4wViGtYCePOQDLo1TYTB0Go74kYGNeWugzAjzniASVuLEcxDUR+wkuNppLXcLdVSfqKFvmD0vZFeQ2JO4cxaTlAQYm5YZ0tVEjTlK5Vpwi5PejZbDk10+LfTa02KUrjcFT4c6wB71OJmg7NvTi0F4m7nQOTpTs7wTtb4joLsJxkyp7/l/NOSIBVovyTSYJFsgwf/1B7MxWKAA9tjmpV2LmjAXk3xgHdlKH6Sn0QKAOLQ0MyeSqtt7+kKtE9RZCPCTYlqrhoJf6jmYAQ+B/P85xnadrGuin1l2KzHNbwFiP8XjPD3EbZgqk8btWFtw07xV+AGofO7dI0c+xjOEhkVc1uzjUnQLhn11T3nApEOK3whkaX20P1oMF5kAUvxrcwm0l4VweVB77nWV6saMKTIFak5URyT5++7/JnpI8QmOsoxDZkhtICsoZyHWN2y0OCd8Tsn1cO18OdRZ79DfovyloLQmnKfxLu3UaGXKBPgYAioGyN7e0ZxYiBKNdeu9tpSO5JRCRghlDLbqYmRczxQmvCgDh8oSEJUCLE1DzhZsHXzSSPaPnyarlDuQUStxDWPUp2GER9KM1uP2IRrlr5cP8XqQ73WelJonX+i7w0ASw3Tkq4VesJQaMTjZTDuFwWSdauZ52BxfSrr/A==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
