---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBNpcy17f+j4/3AClWippKc3z0r0UfgYDKvmJfyQXWjeeX+ea9z0cYIeQaI+yu0N7ql9r4VFB/doEn9LmYj+DA637jQwvPlFJlYap8nFTImlUfe9VTWnPWC8vSecbS1SKROf3R11Iwhqd3m8U6Pds2znRv+2GJjl1SfDw43whoPNfgmsqAGBE20ZUbfMHUhztqSOihqjerAMZ2Rd4isgNDE+Ji94VQxVmJEy0A0Z6uA0Uq9UxPx5gi8rGAXOyu2ejP2bzdv2GfheVqFJ1U2qwfosWh3NclKEICQvjdotXL9CtC/U5FaQ7RhkofCL8ny3NE+9mHpDtRfCRjzYCArUVogvC/0NJMlZEtYyEZoPxpkh5u5fhJiCk1GqT/Tfb/HiKnUneW/xYdFFHScOw/nWRkX37vytjcZqmUuA+LaldYTgX4POUjhG3kXbNyZx0WwQ1GS9D/Y4a1YZDl34Hrzjs2IIR2JLD5cVhGWU/lLXX2nltgHCglqaDvATwmfxSZ4QdhHsDk6JfbveAsKfsknpngkHQ7O7b5vSu2h0nlG1sFpHFvObtNqMlASwTdnDcdw6UsUq/SOLWJNdi+uRe0txrSCCA8nWIsDK55Xer3mXQOKPMa5LCclkSidrvswknLoFZ6QhPOl9O/F6U4Rwh5aABwo+A4REof5o3EqcWbITVsbpYEHz/iez4nkbfPrftoSWSZeMOzzW/qx
    client-secret: AgAlUE+gwWQuGagalEALtKA6PQrVLRuPmdct5HXDEqH8ReEpVt1rE5Lr3EM3nxKalDmdwedOQgpG5tSKZUKiqItYhV77PZBIFRAVGLXXbO50tvjtu4c+Z44Icj+gQg/75Ayx6sRyxqMTQ/GpmuME/bVv1xp7wxDKCWCLf6ePhIQQOPCSJpLI7Db37ceOTgGrO9VDJsz9DIfiq2njJMZ23fBE/nvyaFnaVV6mFuIQjaTd6WzscNv6n3xsxeVqnzg7QxQ0KRPf1gk8Er1+LyKbaP7ksRSV7TQFBIYiO9wRNgGdhHidGV9d0mIJyfE8qM6ofHmF0iNUDQ8poJYXwQeXadArhH1LKjD0CZU/BMAMgw2inCvYliogiLBhrYbwso6DPVAUYVfW4zk+8Pt1NDapSGrtOIzygbgxoXLUtYHGvh9UX591aWGF9d5CEASFXIxEeT/eR+OFtDSOJBTdmpGNDk0lInNdc/dlFMv6afq7HRhYY6Pxe3NEATrm24o5W37d4u8WoWgei6gvYfrq8s5DkffZzRpuCU6lSwrd9aVm9AoPWWPKdLjJpAit6KEC3sbDYuxVLH/p77KzamMU96LMkoWzRukqz1eeu0B8bzjMfIeg1m5zutOX6gsZhLjz/wycfCNrb6zTd78ak8nJ42yTa46Vn+27javLZHWBtKFtZtr1bRuCCmBYYA48v1Ex4rZfE2irNQrUaiy7rDp8ashBPXtCjy1llUOsCCN3PhJNhPTZDg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
