---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgB/Pm58nWRNlnE9X0c5U2wZ7JIL2JWlBu/28lk5i2dBZCNJgLpdr/nsgElMFZb16HILpZSZ6Uo0IUbeuQCJOl4sJB96jkcdx88ms2Q5kxZO1VNv6cCz/7lSCeZsURWqy4JXx1JwU0XQS7l1mktztgVGEo1OK1J7tzB1w0SAv7hl8NgO35vajtuJYIUFvDJLjlKyG5LBJuecR9EsrlhZrPu4PHo8tRPs5wseV1x5P3fnmkfkKkzlkGGAW283kpjUBxTHzYe5owA73rFVMkxMfX3c2O1Kbhy2dJMidJyrG95jfauJIcUdSd1l/gSbegskq5EYJaxUJjMNQl3YIX+67MRKW2kqj28QhGWwhssVR4snLXgxHyxoAXo+oG448araWJwRCrqjng2sTxOia0ntlru9sYbkjfxkZctYtPDiJvU2sz23AqeaQD46q1nVVplv1uPrDSaMlyZiYJo7yGnRoIwzrXQqZ10d/hct+k2sE0+WNIGMgjKPkayGjL6/dtDGa1On8MxicQ0UpHjcroHr/HB6HehANyFzl50UKAEfZmnhwH8QBfCK4Vf1UYkUrvoCqErekm/cpZGLtAH6onQRgpTg/RCqWf9u/stqmSS5Id8rkZIIpfSzp9SmfH0U4sOzCiFQ8ZYiT77kW2zZZOv1Zmya10fIyl1vtHyz9Efcbfrg27cfWcxMMZVgM4LkExShjU6StQERdB6r
    admin-user: AgCvUepkk3Arx7/FugKH543wNU0QM42c52sjYFfykfILZ1dVzsUhMegLvpyOpkvrsM4LH/QqXg1eCWCdE0OXy2Y0W9GiX+mtXoj6OA2BYnYQT0dVPgx18pIOtBGllCJhqHdvzyMKBbeKpeBfLTGXrXLIuWdd5Sqk5/kl0q7aj9+QUX+Si81l1EM4OVVoyyRwfLC6C1zShU5RqfR8jYw1r89ANYXfhlykaGKG0VnboKjzrdMX/g+rUHEWQmAmLTrB4mQBgCTLr95lKfgZipSz1qteEhTQF4mnuBaA+AqSYg4BlTXBMMnRihPcfRKU2Cb+DJ5LSAYlItdD65+LnsEX1d0HIUVh1OJV8WVzga60epIdHo1RZ2BJku0u4t31ypWKhv4nsmImAXqZj0mwLNlqjRHW6WO5lvCoxCJKzalxkii+GScWjFAh9lXX+7jEGkueN24HXi7CFDiAI9UJ00xvdg6iFmo79wSbL/SWlAYJ0hcHfsZjmWLXhEGrbtOE8Tc8Wk2FGQXaClljwPbezwPB+cKj4FlMCuUriBr14SiQMx/T7XYnwlGHmywyocCsHuWFmDYQMqbdbF6NcqmbgfbvzlrQKMyiCgnWxTFMuIvzg0S9EH0GDrV+6rvberx+5sYrVC1bo8wD1p46s87adzocaD66aC2iTgX210rYh1eSjdDBEnd0yqFudNYo9loZIcb9d/h+djsZkw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
