---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAarZISRKa8RH0zujZC0D1E7T+mufgfdVDlf8U3KqzwPvBRCG0wKO82yRIINSEhkdtqLhCogwuEseVNLoaIunT9BjS7Lgck3lWbZTaUmJ8awgw60NhoRgTlPL9qzsHabWsPYDeSGTp1mf7yKpJtQiC+8JiwAhw8mNPFqrDJmctyXxE6xT9Y+KMVQoFtefztThuyxZbjl+DNFyFgtGf7D9a4H4W4UpKuSuqER6cAaLNJ+O3W0/aeCmL5LatrIjWtNNYe7Xlf1+ucsUfnU8KlQ9mOS78D38G1q0vPEO6WaBlUFmYRpWrN9vSLO+v5ziZ+4q4d2d0tAhSgmtLCiwPrn2CCY57TL10u5is55WZUV0v2qn8sEvacUXkGrEjvZj7BdrSqIimOomFtUiKLhlzQz97ClA7FNoBEJ44r8ILmXYrLan9cITKWfwYYfvRsUIyOC9NhSASqweVws5KLbmK9BabSKUBnIruGPGQcI4VYwo5aw7/4bjVXzUPxmm8+B5NeO8zBezokYxGC3LTi3MBFgXswpdhmUIFGG7YPuMLP7P0DiZt0Zbt10Ctsm4/LheuQmDEmh3Bi8wIoFHumn+xT4M/ArwkElfa0KXpxDqKXrylI9ozR2qYp+fJ64JIR5MZfT3CkImxv7xpg+d1176D/0dFFSZh/HXWtNlfdrAXAqbCWkx9bjhEaAjHOu3VCnahUYgR/02/JBe4n
    client-secret: AgByF6BXwJBzIT3qvCUM43Uelj2nips2CASTL2BYov05vnCgIhnDTZ20EHFvVLBcaLLpEnX2NSIHXiibTDgGK54tgCy0YLxB9378A1plhaeGTcIytL1WZnKpKqNT0sV2b5XCld7Vg0iKcl7ea7V45/WwH1YF1V865wkyTy1fz/HZHxKaGymGRqg+yaxSRrt2kYFJqemrwK72LNvZHnQ/boW64FsX1JFGXfIg7h2cPCZt+mJmOzN0Bn6gh6Y2JwNSPJ1rk3Tu2W68ywf5dXbjSPhQ1quidJsVoTyLmhQrV15unamKl2qeSWZp4iCroBJ84tIQ+6ye72ldPzzQMIhB2z6kHX7IK/Wsz8H5cJSsZESxhS9kylBhmAu1SYrZumelVS2CaN/rRaFfxqLRT/+tm/ipak5WH85k5z/9Mx06jAji7wsMoaHCoQh5Qkjur/9H0gLSF5FLjy96jK1Pu/T6yi8ahxO0YciORIeYWuz/M78nzUYwK0G28g/LBQPEco3nbQLSTWaxcnd4ZjE/y4GG5YqbtqlyHf2DLDZw0QRTGyQSmuSOn62cXPpFDkVRbTSPr/dEMFSEmxcpsUvnGINrS14vuWZOsRk+lYxBhVZyhNZTAgnaEjoXblLqutKGuMjMc5oQjxd9L9QA7/pkPID56RqspqYoT1TGtRTKGG0x7KmkLm9mZwgDYZ73IL1xKR3damLUz2/cNoBRLnJHRXhdo9X/Hi2b7X6FMh9b51i9Ba2mNA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
