---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBjdWa7KoFe8xkvu0cfntd4BxLMcVluUYC0/j++nqWjlTRYydfwGtR6ZWJ0BYLgLi4tIRRO6dpuIOIgooyGwHktFNboZCyPkoxdjvpe621Gsb+YO2JSm+HGupon8OGEtsRT2rLj8NUtkHiDxl/IPcwtrpSc3dSKoPzxjUZNV0iLRxa2oj9Scw8ijXam5QLA93q1tAeDdKh6voVimeZntuiNsWMf4va6HLoo7XSz957PdSY7HbAi6S4YxtIYlf8E3quCBm5Ju0XsJop92IFl71wX4/zXpZJE6cQaaXaf6raGNc8R37XXfhbRcFrNWfgTruzPbDjUgg0MwqaO4e/+gMBFeeNqiTN5HyCJtNyarvfkPlRV5KnJbC3kWhe69RCxAoy6DYAzK+/PsssMmrz1R6QuPd+anY/dtzQQ4lU8usNgQI4s5CpQPwzXbpY3emdSurSYsMNg8XhoUl2Oje7LGs/rXm+UKKrVljtqeR6zQxcVQf5h1i7KuLKt0CMu1RSVniEk4/Bs63jCcAzpwxbdPzxSnE0P7cIwxN3DpxnT3L/6LYzeAApMaU0GauvZByrsvsa4tCGZ5tRz9p86RRDlb7gPPaw6N1tgeBuH3pSjEojcCnPAVRyi3SqRPTyfmVJHU3CndvUwV2pKR4XKt5r0LcN9JxjUjGa91NC7EmnF4G5NrXhiHDLIwUe+pYSA99reO0X1dZozun9S
    client-secret: AgCKkbJ61/dymNHdX1eNbWcXVq0OPTvj3czN5RcrEo345Jwb/qkVjpOa1z9dB0xFfwWz5SHUOhkpQg9TjXILzvP+ROfNdINLVzJ6yAOzZUmhK5dDnaCn50+lQCaWFH87hiVyxHjxl+l6E0HHULJ5O5rLAlIzC9StJqgonqOPF21IIUQPi3mjFEJdY5zGVpIgCQqDL3tk7l9FKY5L1RZdk6XNuanCaR5T+GTbLKtjJFF1KrnvqLmWyNqUTVT8lWWSzbt8JSiUcIZ2GzhZ2QLczWogwsdxT3pT28MleGTItas+wNxXtnQbElcWErWkqY41+v+qHq4Geicq9nDRJNZmtmrem5kvX1yBOiJqyNr6KLl2Fl9OAlaqiGeUoiwhj2Nk70biwBzI3z21WAqv+2FkB2KBoXWzNfBRC7WAR3xl96HgovBhV/qjFIAehYggD7IV14lCt+zC2GosWZcECrcdOWxGih4OhWQUk15j4jTCqebKKJGAjJplL77g+VvxbQOYamfYc3KArNjN7srbdHhRbqWicsffgowmZDzT5lBWScJa1vZgQEjBvaSEr1CCfzDGDOArBYCX/nUTK/6IQB+z1HbPUOjwpU/8h5GtFzwSilNo42Wp3bKwZAP3QG89Pn+DDOpcinp26jTmbZXR+uRjO4fdkylt/21oWWjO4FEoFCIsFtrsgmy+3Tpyrd5sVoM2zpsCRNWna4pmccVgdwL4ZgfcZdTxXysFkjO4WMnPfLurUw==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
