---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgC/oe8IQqnDwpb1P7qCKycPOsd15qtG79SxQB9R/gBIROYRgUrVuuDqg/KVPUNLW81N/c8y9g7kbt+5RnoftSCv+pqmRcDkFi30h6/Uyzr/TjbpGVXYqZ/iqEIzqBRiIetYzt8q/2q1G92VIxFAjTuJ10O21a5nR0voX07q4FicpURHm33GnmVnuigvlSL3XmIqX+4rBoqNaDhUCJGDFxSVQxoEm5UnRRGX0FzPz0vwsJl09tPzGyq3djG7DyBDLYr+JthUxbdHo2FjvPQqAhfcbChAlNureVevLrorlnOLCfdqMmii/rESwzCz3WY3jDsI2q/M7hH3W3FePZdeI8SICxBA7Xd/bhosksvlIROLf0Y9ZBwMpRTZkR6DbF5j/iInsp7dZc6nHoAfMZUdONnBLP37YyL+C3nbn5kN/CZp+5f4FufTFLyGiGOpqaYQIzUIk7e0dmjshFfo02ULTGni3WYUTlzc08WN8dkxuiYIggVlcfcFIvqDjdXKGd5PXmqOT/thtkrnyeEZUtF/ZFWdSHYKxoiahiM3FPStm3xvDSBOXBKWmoBu+4/YVz8fDf9J+9ieEC38lf6i7P0j+zVTcEAjSFKRkCAdKSTORcnnJST1+6d9UyXXzDdBsW80cGZ8Oz9I02ozc9n7EQPQwWqIezcD8dHo4HreUW0DZp/R9tRI3t9jEbEZMziOla53PrJP1b/KQCsm
    admin-user: AgC3ritgyf9hMeE6gTZxGgdYy9n7EL92WxsHosVYgP44Emb38oQEYX9K3FmFntwsK59Ayw7QFTMzFiozLfH4L1hsT/Qi42HEuYPMnaQ+zT7yptsGJh2b/EkioHUALnAUdsJf6NCGN0uLhvP02vzvG8eCzpOBk+ko/RbTehTY0yZRok4DycOo3Iec0DcOL5WIy4eg+y7GRVpiM2nmsPdXgHLq3szILjSa+ESYXsqJSgblW4/0muVdXgQzUYmWxtLH45ug6JosBKDVPRtZd4yRV8BV8iR7Hn7t5UyYiMEV72/HGBwIela8qrlOE2buIDAN3wQnnVLpFgGkZa1IKt5Emzi0qQ6ie9mkTijWo6hH5fKHDthEMnPmYmAVr9eBP38VB5vUCcCf2mgOQMOhJq8+aDpXVj4PoJ6G4+djW++qDc9D0BWgVox4vTmh7mw+QG0npT2DZ8NIoLruHZGomnIjdrzCgUNdGyK1vtIN3orKaUVCpp8oIvwnCeE4d8PH9ACjzkm3IcM0xwYIj4waUbgXKVcz2Zye+myBuRFf73KTBOFa4pB+CPaWhGmz7MRP6GKXkuN/jyMKEhA9PF/+b0e50QXOFzQUtu3QsfHIwjtj688idihbVrL2SHLZEmrDvPbG0Evdd292LRT0DPF16SdOdp4z/SXSa1HtWk+fEZQFZMeLz+afy5naLL5E+sol+bKrlWldq1f1bA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
