---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBA61h2DAFAmcveGEkEaqRo1pDiq8vtBOkT0MAEsWcNW8pM/99VJMS+FKgHCHGjN4DfTgsvD50sj3xATqeX/CLb/zRTIOJ9HiyWvdNqZGCqGhqNsUs4bH0N5K5ATKf5zJYzf29KoENPINV3WwxTDBwIbFbDXB5hXkCrJVBJJ5EUTwLuSLw/opEoMlilEZLMvq8Pk/831Nw5JXTzxq9NZabbXDZYFoPlnUwDfp59CLKQj0n27agbzts+oF23kLdtEwJ5ITKSXNlQ7uzUvBr/xXiANCNDsJP5DGh6Lw1INrlnhGehVa7LRUBQYlBvQN+bDV5FmsSZbSYrf66b5VdIZT5zW5gPproXALra49wB+oipiwYhGJwPR9TTlJ18wfCFoJ6CqbNVjGO9RP7GGc+Phctq/rKHKk5HvkhcOWL0AInPQYsW1Wh3yYlFyZesJ3SmH1t2GgeBYksOPFtOqHiSza9+iWu9iuyKRjAO7616ITr5prCEtJX/TxxhqE1ScQ6ZqyCTPf1ypIs/yfbJ20PpjrvMMgy8Yt1fbUla2RSKvbDeY3iIs3rVdbveJd23VzvmJVIGWgLRduPrSY4iK1ojPtOH9QCloyJQHC0Ei4PjveJA/HeITmCJgrETTg+icfIgtmmr5elf/ftoahbPL9KGSFMHT6dG3lqqSQ49B+G2U6eYGGMNEKgypUHUKzs2YyltJ3I5n+OALinB
    admin-user: AgBdFOiYm+6FcBYcm+1DqWhVW6s1UuTlTdSRsih0n5XJ88faKtrFNOmbyaOO2rbhsfAupJ92Hyb43VdAmVzWtsQvKDazkFzl4Z5+Q+6V9G1h9CUjS4owzRDmwe/gUBHnASkTdmM+g/J4QA7i/FPDsIzyorZVaUBh9/qVPUmwyvHFHoOA4RznH7Dt2n4BBYFIJaVLusfqEasqjmu6obKFsXAiJoE9tBOU/GxaBqM2nC9POLUFLnSes5gLa42LS5CKqnus/tIHcm3r2IO/YbB9QrFO55/a9Mw7xavPOmV7n/L3+cwcIdNV75c5RHSwsh8B57B133BYgALLA0vPANxlBw1PVDddFhUDZfLVMVWQVhwj/1x9M1aaPbYdO4hsoF/t9Y03XXOxFjvGsDUzRrBPqwUCSoF8XExHkuJsoA+Iz+kRFcGEKOt87Fa/hiTxlMYoro2CfCEM07uIO8X39uoRi57r0RVCbqoIUdlp4HS0A1Sn1804AoIxulqBDS58Z48GBR4C6Il4LaEfkXW1gxn1AsuItYO9uTXIWzJDVLC3rgjw066QhNNRs090c+lVOmD8lGOenPiV4rnQiQqeQJzMWv6UHRlu5EOEg1AfnEzH4h6zsCUixE0GGb2qlSuaSDx6U+QfyySJCiVSpb2oNygN0WgQwDYcVXjSUJR90fsxEEd2j8ad/DB6ZFayw0iASlj+ghqHtd+QYg==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
