---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAk3tZaWa2zQnswlNfzcRrsLzYEsd+5RSr0QbDLeJY2TtiJMiWS5Q79hGGXMKsY3JkrUcEfBnju9YYXzb3McyXA39/FNnYxFAftXrD/HTxAefG3ZH1jcs/qFItqdublHlgJ5G5WriCfIAN00Aj6Y4aT8ffiD+SwfMkAeP/YY6OY/PTvVAvcqPHnu0uNIqIkaSbovuuLeN/nTSCJI3UvqYrctGWLLUIscw5P//urxJ3cVuq3C6/zez6LyUky3tCWu5tyLI2Je8TZaj7K/NcItMW1c5cTCB36R38mG4HrcgHywfuOid8mvdlFq+5GgctKvc3DF65pehrePMxwwjahLHmqt9psz3iiL9hiSKMQvEx0ebl34bUEGDDMQ+gqmdPvie0+LPPD/SkJ/XDbwBS1QQtbgUrh8GRtKCoJztY/mlIeIljRVgf0yhcNiZtCoF+1WZcCzdy0hMbtBvjRgK+77muOZAQQeTImfJXwuAJ+WZDEczr3c4US8TZ5QnCr0bCLlf2+VrKIc4YmcKLIBntLzHmkaBCRG8TlqzCHxyBREOexfSkZfeSLgg1i1mgxgdxKBvPYHYEHKcGLd8OQFDsC+FPXVGsv0gofjKhIKZyBQ4dGFRIQCXcByoMI661qfMumDrk11zBrnaQnojmz16lqVT3cIEqi2PYkrv1zLKyjf5B26KmLYvZlwpa95k4oxWybA0l8ARtF8Nq2
    client-secret: AgAocDSUQIgX/t8SLh+hZfLC0YSRcFVZfzwxDAb4m6teCiHwW+ee76FAOWP/m+Y1GHbMl/wq67f7Aw2YAgn7lxWHF2/lCMWYG9yupmz04uIpYdgZCuE5+rIjAVY1TuicRg6vBX5tZfh8g7ojdbM6ZaD7UBcHZKdae+qKR5Mp0j/WqLFpdhbVJoHAJ130Hcf6ZGYlC/q7zRqCYo4HuL+7wx3dRU/YAiA6TuYrsFZ7r9OiBifOOGKefjndr8sZuKJ2WhnfMrE1B5mUqPNcWPysfltT5mPIwzZB1/e8U5i+MxEbttz3RWcrtdAzT08oboFbafY9drwZbFslHg/sSrYL6R4Kn4CBRnHobAdA2kqFnA+ty9BN5/yLOj04dBF5jHb2F3QE8ZTu+CbWg3TaEkffQ+uRfOTHmWLXqq7DL3iUeYemkM8xwhb65oWVhRuEO0TforC8YA90ipP7nEfYmFbaSfBKeO5gZPFQaRrBiaSIZJQEP6BN6ruO0pg0Fq5/etkghBpjMwEN1TDbiwp2th8t+kpWXhKlWJkEkLKmm43P8rTQtOrouZoM/fk6osh2J/ixnNeVht2+hmnOeAvbGHK4PPI855IINeu/cfYO963kG8CMOiE3yRNCwS+ufdHxoSGfBJlitmYNsYGcDaPeOm/g20HhIZ+v9rsTt7SYL6SE2DHNYsxxrLVXIEwL8ZrcTu2MoqhmCJwPxIU6u1wdPBlGD7Spaken8R732y8MPrHzmnSCfQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
