---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBF3YsoJEgThCkGkK5BqyZiNuZs7+OBCPl43onJ5igNaLZ5J4jccqvgSDlJVzUKEBH+LFSPx30W/hB0JOeBlEJz5QFX9pJA966Nq73HvzcxBCrKRr+f1v4CYMnS05grFrY+SjLzDWRjFdlsgNJ7RfAZ7AR948Rfw53wBLFa2EszuFiZj3QmcNaPcS4Ixl5q6m1y0hkVkKoYXV41LOcOyvjaksmfzHat8tvwQieDKnhFwyOFWJCM1D9zD+8/4susorzejewrF6pAK0A1s2pz8mIVyLNs54jOQhjN9qPA3+qSHU592cEABdHUyVrlzcunxcZmhtgRJtwuJRWrF+PT5MDxCrIpQvU5nKr7dLSg0i5AZVT5dAlppGAD2isjeYVL5Atp09H2bY81L+6uUHLwvSnal7N+hZi1OrBjAETG9NndPKtlsWtNoz0/QhoYdBCBZTrJXUQj4Cbmx0sCnMdkmE+Miuxm8xkvdsg9DK5RVS3CtiF2/HZuUOU85ovfAlB3YzNk6V8QZZVj116c7BP0alOgQ7d+BfJZK3Z+VbrMPHyjKb2xb3RZSuOCAT9zfxV9e0rspi5pRFGw5gRtsSuv/SO75/erEmSZeuHz6+ap/uGCDXZvI29JNhci+ZhW2c09zUbyTUWHlf/KNCmB39KXUqkpPnc1IEXSyC1/JFLwsgbNp2krTjdHY7fddLfp4gG+Ep2VF5lfNdpm
    admin-user: AgADYwuQgEfFqvw5AafKz+TrwD0O5m8MmHWipMr/ncYsiWA/xFLrYCj/p/c4OYxvEQVBDb+SboRLv7nLP2vlX65td4zv1hK4w3pifM4W4YS0PS4bVFq10hFPgKXAdIWeqzjFCI+xifjY51gwxM6I/M38hIO2aDDL9slZJN/aTeBY8b8vKb2wzLdxmIlCSvTzjPhkk5Xbu2Sd26+vrZF2CaXvQrNARSZgrlLV3TUKgwzyWf39EY6mojowWdMjpZm9zHlgXxolM81wOVPknCJ7pbk98xV55TxFNUcUVnPWhKKpS5tjeU9NvM+pL4oithccbAINk5qk1VdpnDXtA8eVgwBEug8cftrHhCxeCXd82RYzJbSuyek+T2WtXiP2cnn1oH79rCG2mfy8lScgpEpQ3zBC2HzowAS0P7ERo6XCcE7GmnTOPsx+0P7D+BjrU+3XghmWSJ107S/1gXSIP7QCircTWBfzb3P5+04abL/JB5tvJ5wK0Wo3g8L4Z/2EQv5kDumxD7YGp8FyAbtPf6AtP3+c4zRqCItXJ6dG20U+HHGy8QxIWagkKzAgkbGKYO8j9mtz4tNIs0aJTpAnTCbSNeq0erZE8pnYapKwlnzymy4euBR6d7gvhcaNc2bYlssXFs+25uZbA7NKvEa4VMed8KV4PgtvMQ7Gu28AQFROu1q6zRK55rMNQ1/wQz2D3vi9el1F2rFwAA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
