---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCGNPkKJTLx7cx8IptJc5zSdGaJ9lXBdMkTyPcgP1rT66mcu2V3J5GT9iwqeigCU9J+LWDrFqVkSSI4gJ1MjaV8uDdLZtuIuM1/lijus3GMenrjIupKAZj2F0bOan6jzyhMynCGarMO1HURR+XMQEZfP6OQedUAIfvmRG2rLE08Vzz0eXRa4EDXTN7bBPgvF6l2WLyPfrKXtNJCUwgo8xHhYCUo4c03BAR2y8SFUeI96xg0HKvu2v75ON2MIXBL5aoWDcBNSiWJuLGJA46iGzyOHLqqzQAnu3VRWUDYNjYHhS6Ndx1h1LaDhe8Ky2tAhNDuOfbcXCtoEHKUbDRB+dfgvan0oe3WyGm8Y2y3TuqZX55jV5F5dX3O0ZYP+ibjI9FXBQCXRVd6OsaC5jdaUA2sv4RN9INW6sjUTydlNemYS0aTyboHLw3BYqfHukFAzmjkIsDB3Fffsro/bbmhUNtkWdSmy1fIoMr//1K65HUZlC/GfVlDPunD6BiqCnUaSBuRnJZj1hFXruTeqFDSt1sS4orWk+1T9Yy/WVgwkes+LorWG4J8LZRLzUdrMa3E+xbXAJ7qPoe3r8e0rZ2pR3KDiJ6+iDNj184z8irq0K9jBiwfPS8Yrzj4hkFdt4FjI/BVclH56m+OaVnT+9p4JPAMq9lvg/sGfwbPtaqrNzr1Hg3Ls6RPCxDt51ZODAOc+WJ7d7ooifGO
    admin-user: AgArtatHxyfi+ra/L/LQOkP3bN9J1u/Q6fP2/7UJUu+3/UM+WvBk/qYUKlU0kv0HWPPohLFDvFdQwzq2kNDsGYdYB0N2GM+TAlXdU4+9ZKN3fX0+tVIkTQafTOVyDkJFL5Az+TMf41MbFfUPb3s9HC/sCpmprhNvpNaaW7GkO3PXGFsycU9azIWVJt4HByBSWfgRjxOX0N7BtVLJogUfM91tWDq5adjJeW2t9LauF+YOmxmtJyoE7GiieMh7Gu53ck296ZeGJ7rKxBntvC+sENtqSGq5dJMqLdDxN2SEAMz0QrHmssTtmaYkmu/G8QNpIELqfvPi04nnuVc944J+04gTkHTlxnqvERpxu5wmVRKe/xh4R3ZljYO+cSHr0rE+NhsTJWGmOCx28oNnbYC6R15AvB47ePZD4d7o0/GPSSFjrTbgksGhy6j5t14NX8DY+dns5WS0iOp4x6HZJcaWeJI2ADyuP4WkBuJPp/2U9bBuTsC/x9OwFrW/GTHXuCGoani20EdA0TFn9yznUma4KXAEEQYyG1zMcVNBimiKgjPox+vOhsYpVx/9x8PfY6OzDGYinOMQXTmbR+e0p9lGcLnsUbIJ//3nYAY6uK38O/0sU0dRsIZK52mkAvhEZLZSJlhqr1weHcblwh1tf2zP2+PTjJy+fjgo5olZjXcAM9RuFzq5+pkaa3NrT8j1ydrbFEwXjMGWbQ==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
