---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgARrxnpy8/hujLT6JTJ49cEm4xm416X2agW9ti6OBYiOVzw2bAROsmuak/p0b6euaCedSpCSGHRtWbOmcT+71KbdDiuDRpJqI3nIecq9ZMl1UgwZOG6DWP7d6MYqNd4bRL0Yyde1PAaZtcq+D67Ln9HsnASJEQFvbKD2ogVjctHqnv/9s9V/G3Dz0U4XJ6/aN70MbIo3t5WOBh5gXmO6kCF/UQke0Z6ZJCv1d6RPL2isE5sFscOWJY2Ie8NWpqtYN8cZyG16WvPkEMc2C/1dqi45StebV5ztzYRLCy0dGIXX0CLm5UqWnKI81y2Zp149KgKOxDNETO0G4RX3v4rqUIDPIs3ZK8ZQT3IU3UdeunlYU0n8EcOC0lGS1PTwmDa485YkeVgiYfdQNadEtdAUXDgbCDU0MFO0OOMdWXPcfYh6PNACEkDE7T4AytZZ7G1/g3S8RkOtnGUqyOPYPkq0eu0eCzoaPfvQNWGeX3i8APpkFAPaGK761/mimJc4UC0Il16z1elptA80AwyQLMdPN12MABj0frS4CJ8NRAtd/OSwIndWw/cheS2eNrNsZcQAksXflp8oHbhfCzcg57KmJlBzUqXJAMMlVwttcNYj7mzlJ15gpHr2JrYGvY+1Pk13KTofMVLXW6eVqYdKw3r6MxepbUh+7SFTeSDg6628wGiHfpf6rbjmborVLkK+3f7c6tu6ev5QgJj
    admin-user: AgBkZSxWC1NgWTWxzw+cD/rLQ4xgU/rEwKwDCU4NiRzA0NcyVZp2dLWboKQlQGuc4/Y/BYsgSRNZ9dDkcDtRYVpKcaXlWqlUH4GBPtZcfGemrSdO9/xM1QwX59n/Vmtpp1COos83xnGa56pa7zYtk8v/fBDWhHeEKavJTBaxghnCFYN/fovuDxfB8GG9wKi/Hk74oHR8f4kemuQHz0WjIjAKfR7A9nVOAxndHYyM1b5zKoYyGlscc1HGdVq6HhAlmqmC6c82qRR1m9XzK/9+TukgxWHOYcxTp0yM77ITP2s3PMlVH529M0PTiF7KmsAtYKDYkKr5pVvppa1H+NQL7DXB1TViSLZiXNwXiMyMJG7/N5MNvaVZ2XJZeGhA2pNz3uMByYiI8jHY8NIY5PGQ1C5+ORaLVLlLo1lAxzt/cYKDu6lwiKDgzQSt8qeVhFhGzBNWPz91tl1/rOjgyrSNQfHctzie28JLyKe954eBnwUPwcqMKLo6XFd2YAvFRoaK/hsODESMKX9BbLRollE/V/SiYglWWRrKG679HhOQmvhhCZebuFK6CJctlwGYi2P+vRiUI07PalDMsNqeM4Mf779JFr593sUS0auBdPMhumVuIYVe9EZj1P7dev0ku9MwYMVyTcogr+gpu7vJ37EIH1PYPbzzGqTM4Oi4ovVbFFXf0PfQGDLDC+3n9M/YXd+m2m/zJrE0MA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
