---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCR8ld7OPU0bflxYzeYH+U94RlEZ37Xmy23BfniiqU742NdwnWvJ08pbQ3ceWh00kryHndNR9kr6gb23FW4v6BYIsxR54npEeH42iYeOIxTUOWzHYO6NMJP1IoNY25+X7SLeVLbwEZaf4Vsy7diYr4Pb6Ky5ePXCictIanUVNvNKjHMyMpZyaZZMk8eSJ9+AdxOp5XBhyY46L79fnAB9ZzHmPmxTsifDNc7j6izxZoODEML5dDYw8jKM+0TNQxr7ApthNkFfgkhwyK3dDQIuWDht5vVVWn+zmqdFbPqyPuVEgrx7bq8Dzy32B6atiJat+55lXgAwh0mBIf1NMSdm6qw5im7naDi8fsvlkfAiBTcorhzHnubVMb+t8be3cfBXn1VejmSUv0oQkaGeqHJLTQwZF8OZKLy6nIWl7Vl0btH+ejwGz3BC1J/3MOUcZ4DF9rrw3JF/UgbNBn9qnsdGFFxZ4xG6Lp7XJ3rBZlmsABfZ0hb3D5Bba9HBgr6Yl8ZwlXgQXo7EysdzBninn3sKjvEE8bsaJn6/AXVzI+CY5EW7fFgVJ1k0Wtmjw9krAWMPjDiuPjvLmmqz+H3Q8oWKaQiR9BgLIWojChVXtsZ+Aq3FcXq0husZMG91rxLlt0Oe4YO9EZx8AO+f4CFD3xYrx0BAA5kJf59mbR+PLDBIDnrOo2BQFWpDNy1KyMzWuScXUEGpFW4GxFU
    client-secret: AgAiasc7rkirIboQefz7bpaXjQJdeY6xrMF0VlGgeQGJcb1kl/ECC7HOA5pyewMZ8Kae8eMY+sozHs9S5ZAW3NJ1ivjN+2X9WIHLBdmp2gFlAqiKq3716Z7AkSoY7Pc9IyJ2/gB9H072LBm0CewHHrVrQSlj1mk4LpbGv7U/IFK9eV/E3NmxoHgiCNRd5Bi2fTVbfvRslRcKxuBDrq7gHUA2+O7KpqnKfgbGDfUFm5JHS+k6jgSb745RVMffn84UR/89ZAzm5SWW0ugoDIQrbuejPh6cbKzH9Ems2SNNzcUIAfihTuVAThRMW5HMzInOzMsKJMYUfdjZD+TiGaLEvT7m9lQ/WxMRNsMSHAXGuuJOYCGGET4rYTYiWwuDv7Jq2mJB6ml+eBrMIZ+LNgZvF7C/R7aiaosVcp1B3ijbDe2IrfwpQGswo2GgMjtfmVFBhZh49bYtLki8TBBYhpxPBfKup1lIfhoRU6VqUB3I7fhKUgNiWtsyON7RUeSA6CeI0kNSGBl7/4v7MlFMJc7VCA6bXZlRMcY28bZf6lM2H48+rjFaxaTx7cXCsZdVeE/b3KpPeanNRqxIu3nexbhNt+5a7dirf596JQSiEN77M0b7I35ZHc8zZZTjYXGaEL5ipfalsvtL2GDP5nAIY4lm7o9U4d+jtyCSClAb0OAMh5kPCkha+G39kf6ecpGZnhK7YP6SStB8YNa3+qSHIy2TZNwdMrL47VmVpRpo5J4Nrlf+yg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
