---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCo3UugPzifku8F8U5M5Lf+f8ulpsEiQt0/kRnXMdPtIA4+BsvGJf5wfDaHDvNcWiLLK7KJyYO+TYu6rPzYfd+RNIvmU5YxJ/bw6mo0yQWpPp//U4cXWfqEJmXe4P1k/awEqQSKFdl4wKy0wHf0lD/88LYP/ks6/nC9jAUJyvTnyI71EjEerFXIp3TjnXY1PFSpKW13f9naShLaHppkgjXrrwG7PzxRxMqaF6WkmGg2ulEBI02lZMCYH5DAz5t6HX8ok0cFb+PrNChbNbHdVSdGknllj/NSpcmF67erQU4qLEQwS2/46PG4YbPWpyyeQlssVBegSiQUeKDfD3WImLB2CGpN8iXUq1sEmEfqifZDXLQE3HnvdOdIXC/FVTt7Ofh7XBKZsiJ6zKzdCo6xnWUz+/cM3JSK5vsP/ig6PiaBfQzh6dAoqb/w8ZpsuBrUT5Ms49fOFhVTMc4wWZo/mGWTwHvg+UpJWdrS4EJUILEE85dh80XDERqrkmZHIKVbFdfWRkSbVK03YYfCesxCfrlx34Wgdck4CnkE8eHRCeUo2IxyoR1BaOy4Z+vz6ZpSrtbc9xSMInMibWc2XgE0AgVUSMBR6Fsda1fh2fmgSlwkPlV/yEu6hWvSpixl2aE1YI7kotxHpXdt0yl3j1f2vnbxpa57pJmlzIgSv72YHq2BvFolZGOVRS+izWVfzrtBhHwQZ7TxCwkw
    client-secret: AgCcyPIjcNwYgIr9aTb9EcJK8vso/DOPp4oGF2yXyP9gzLSram3l44r/jhm+AeU7TJjnVWLu0h8raBwpC52ar026Ylu3BGcGMzI25+HxKP4w5cuTqYX6baeyzIf73PrLDJpgzA+PaVbnuXyqn1rNzENFNXY5XDLsGKGB+koioJJ5mmGvhETZyFVyPp6kiNNknIqtPew3oKXaWMkoEAUV0sIoPM6t1MEJVa6itgGs9Lv9lV1UA1eDKc5Yc4zCAKyE5sd15SMqiI6Af9qoLqSAJT8SSf12ZJrJuZ0ge/4DlWgYXeZ0I8BzOvTWg+O+URdR1MfP1xgFKN7gsjX7zLYW13O+12To7UofKgXRbc8b0qljZeRE9Fg9u40CdcDh+RuIx99W5aXoDrW+nyPJfraQKJ63UPDhXie+wBYtXTuCzh0oWt+eZ0YJPCZ7Qp537JWGqB7DYbHOABVR/kNux9WzZitHfh+NTtAHUsJFOjt3dWcs6yhleMxZisAx2F0qZWLy+MYj0BTxiOWpijdzhtzEdPi53UcFgsvSWjLlvsiLvDOXjPZO28kuwmhEF6nW9Iqw4JChA9HPmOoc2yj84l+1N4Fgz/zKG3SNnzyNFBlHayN1vu8vQQ3CzLZ/DyqU9MYaHl8+L+3XNWaDNGgvLrFS2CDb8UUvflmolwqP1ZfCbYG8UaemNoIoOzCvSoxs5rc5NnQtjph62iWHbr9sbxPdkvHFP5Vt5nWADONwu3EXQ/AhDA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
