---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAh8OlB85+OIEoyfdcTHnAv873i2F6AQp2DBqWtclOjF9ULsuqSuk0endj3/0tNZqSfQfAb1swqEdoNKOApo2TgRoPMvStH+kQQ4nl9bJO4bwX//ulPLJoGUUHgMcPF9Ah/4yps34yptdJ8/ycW/vk8cvIN5BZMBjFaZRYQy7TNsBDE6YiEGAFGIb8Ro0JtrDt4c9+GSF+u/RLM6Y/cQzhyRIlT2k9oFif6jgjSRcyFhgb0jCPC9ex6p8/5bNJNvT7XYz3aYO1prPxHdZlR3jszD04sR7J1CFy8xrjySl5DmzqviJEbhluAXVeapyfsL9qd4uU7ss+HNsm5bk6zyBsXTCyubx6y1A6hYw83Bo9ED/twjhfWSlpSAgFgrGyqbaupIGbs9YD9tqO2WAMq7pVIzBcxCG5buSfEr4uDrUPNAY5hR4AmeTU4w6g0mTEDsLeV3hIxev4kCmeGPqJQylGya2zj4N/u7AQ/5Uylv4w/qpmqHCYSwS0cIRyPyyMWgLdGeO7ZvZfSgCdMo0U5k7400jvpYGr4n1MUSumKYEIA+gKfBd94bpcfwTl1C5Z+xE4AMX4ndMdRfZSEnO1KQP1sfdTC+xtjDM5IkoAeSRoji6ckW7EGim6jBbouiSaUiagroGvxPdjmFb6zVCk9uVHT2RxkCtp6qPM+0a2L5kBehcDma01mIUbbev2E6zXwk6gju0s58ggq
    admin-user: AgAOrdWtVbEHZSYiLSsmp7GevlABA4tYS8JwQOxPY5ZuwdhyidOcrGRhFW2+D3eNd1ywXYU4TX86E79XEebycnQVbZ1DQ/iBgxohT65AzV/bdDhfDy2jTRHYknTypPi2TyaPnrAzy4PyCTrFf35LvVG30jHX8T8/+bQ4wG1KK7ZGAfxJ9caEZ3mQHNYTskOHSQgyh20ruky47mC3AIuMSguEF/s5jc0DtGMUypJgKZv/1aTM+9T5o9F2hKsCp47HTF+Q6Sc8PFrgHSgDn9Aczed/4mCkxTO+QfNrrvdTtqh/vxtlljgRfSK4MLwiosUizz5tRmp0izJxnyDbUHlFeGcRhPjzRqQawB77xrfLpHB7IpKYqy3UbVjlJ06XjSDMSYgEZOAvfO67EfNsMjICZ8mVpbHCcOxDuPNMJiTD73CIPze5PIw43oZGz/M/5yvTs7TbV7kYsDVTUEkR6u8VyhfJD9xFAh8F6fT0b0X+rSUmooSUBiJ7pYI/T9pB6gRMRtKIq3WmJqfm25FVsPYMl1cdvBGuPJZCYz67kU4/uPXVWV+pNwCTIvhlRax7dXU5e4n05QPT7MDcP4igYVTF9IQNBChHv+V8vzpFWt4mtq7aM0zYUdC3jXX8ca4wCQ+ftjLZCtGyZ14KfDe+Z+OWCunTJBUIj7jGJsCTd2JdOIrkXixt1Q5TMgdkVjxtnTLYtOjVtSuiRg==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
