---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAWqStVwSpFvNbVC6gixzKMEm50/AWAVCoiNnGV0HWh8fgK8lNJpYi+zhizSho82rLumvLWqHMPvxVmpSrLaPFEAqmvbhzEtqprZVCED6CAL67MsMXieNe/EDItTrsYgPTPyWra4koJQyKpksctqW8qfWZrOouuGFqGn4DWorPSDtx+jJ21GzxBWvbzW9pXDNHbWup6yvvWBhTbxFzAW+ioE84HM+2Lz07pHPUrQO89VmvCi+pc7ZcinfOHokXwLNUaPeFJh/EMEqy+fYJRSi7xq2n8moc2tfwF7GpvWuCdOW+m9VtH6U8bxH9pS7XXays+uf/qv5ly5HC3lXRMz1lRon/7ORP9pNl7WL/tE+RTBjSO6i3cp0yjWgQvq3VAd0vw20OVe5vpx1FVQW+Icad9zUnhMe8uytNQ2X6Hsf+qbD46Fh79oJJvN8AgnXxkgASqsJsSehYmcBUEnLJFCbDjImGcpIoD38ciaEAZR/FsoP/2l912C7fX/DZKc6swVDuQVdKGELJMjku85kwgq5aLwmtRbj4a+txAKTbiDHrOW/Q6PBITPrY3q8QDn4Bv694xSKeX+heGbImzbUGz5GK/Gw7Z/UF6LRhg/e8vwVYdUkqHS+T/s0LYY9HT6O4r/U8TS5TVIqboUzurQWXkbMZdHH0id4hLeO7ZjhCS97U/WPL31384uUXMlV//fqnedDP+iOVtnu0D
    client-secret: AgDCNEAp6EebxsM67gmkva8ohz3WE/faUXERB+KbhJ9lg2S4JdCXc8GBMyfRne1Ue7Z3xI6mmEoCZOKHSpiFz3uBAr3iLmCItjiBEqSQcgKvGGfdwsibBx6opcv4a1o92wKJQJQxPJKjbbKMoiBfZQSOsyFIUPr5kE1gyTU0/q6cj+txGJnBYYJzx5E1A39TAP9tENMZH0uXjoky/OJejpz8sp15Ac3KGhtr2YQmVhUF3NONgzh1CuHw7h212vpnDsBL6rw4n8olWe0FQQ/+HbVfYmgY7cdlJUxoNSTD6ePXOCLcm80o2nZtkU+QaQu+O1JVKWzEWCHelO9Uqv1ebPQZ/XLgea0ttp2FDnAaonaWe3qEX5az0EtdIvpq9Z0t1gWRQFaQjKwz+X6k8IAh988P+c69to6Z14SauZB2oQDkM6Vi9WntOYbT5/mgoO3C2sMxnZnU6TrW3yZtwGwblc2h7APHAe6L00ynM+2ak7v5C9eW5d18GYQWCQpU4W/6Zp/zuRc7fImVFnz69iDtzQgJ7Ba1gA7HKbhFL5BpReAMWm3YqNMC8g5mKVCi+CRI7gBiEnKUgQajAceelx5t+LApYEgY1aMOV5o++PBrs2/6TekQF4bYGrM2rx1wMVlDONkU/mUofc8JequmC1FHjlm2xAZS3fZ8KlaDH4GW57xLRpx+ORuaKl046VAWBfLgfEnw8mdRiVd51T7QzscPu9Gd6cRb0tes0LujWcptmWZWUQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
