---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBnjvwpAXZwNDlUQwfNGuWw3AvT2vQIrLaKFP/X/PYTF8dW8KS8YnGh44gUB9HzffqNlAf2DdLuNlB1u0exQqX3ZvO/aFJ11BjHSfrLk++0dar3pXX3QgAtxPLF2OsvouVQ8V8uh8Q0fJZzkQX637JmdxqplC6TeK0nq0rGg931sw2YFcUrJ8wpzNRMbw0Fy4ELlyhkewoeuh6MT8CAXVGv6M9DV/qxsaEWsGUrWnOEsOO8CzSX8bhyKZAk3ZUR5Q67RcDA85QRiRVaeV+U+C92KXFEKNvd0/nsq23BbRlvpogRuXpnnEwxHnWTnRMJe96xpTQvalzSfoGMp5J12syv06J4D3K0jCjtJGF7O45phh8hdfsNjygE9AOkuah49Z+rG8jjoeVUPsIzy65V66jZzTDUtJknzXHXEdcqYFY6AOtV0HqbS7tj4jhFF/Zf6vePb+gcVMoDrmYmR17QWfIuuEBCMIteaYB1TB2voMhD+z+CBwp+g9OGHncVybD8eORMdP10AZaVxYZyE+ZiheV5m8Qz7FT0sJi0OKsXSI+ZyM3It4WN1yyqIeYgaK92vDMCVgL46ZVkbwWpEkyDTiXLgLgGMx6UtC+jwSjtXTMpS8Oqguw54C1WceiX1fdw9D6CsNVs1xRxrfNowpPPDcqwG5bZOovNJwpBCp229w9tbigX61K0MbPpep7Evp99V3xHZ28pDrBa
    client-secret: AgBTwE4vOtrQD/jmtaPbRkZO3OTJrn9qTPHmdJOpL7JxMXu3enR8h1V92pB1mtL6TKxQ7Tvhiws5+wI8h3KtfVPttitHms/9L1leo7cMW9yFmFY5E4f0cHgzvbZ8AvvZIQG5l5ZBAvsewdyezY3zkUE9yOKeO0Hou18MCNknx3GCO4+RY8v0aIGQlUzw1OkFi2+7qxyBEZINUai6gpg7kG9gOHkJxd1yHbIizz1HivX+NqYz0Ku3+2cOXgrow8i/+korSnL1TqthaBAxM7JhPtNZ8oXhbwv6oUxlcSEMICrJEkQZXNDcEMAiaS6NlC4JT4g8YJ4xJLp+tQbbjB2rqena+BYIJv7MJSbDrdw1fAW7dzq/y3vYqnmScaQbyHuaistx6SYnpdP9RKKOR6uMa9cV9HVr5afITiVG2wYaYQxU0/suv/OisID0gLjRs6JzFAUiOUIQgS7DXVREO1jdSbbojiHVsBvHjI5NTFjlZBDbW6C6XC7Nq/X45T2uWhLeDtfFvYiSLHJoakx2aChSGl3GUs9lRUxfOxwdSHVTXFh0aSYrT512URtzW0pM2BmEWhxNefQBSpzYpDz5UlNe/2t8uKsjeN0qc2ErGv0ezlsYVO2Edb3Ms74iPiyYuQKJm+dhTXVaKwcijiK0eF0kfcdUR/9yikymGnoefvAqajGKml159PD9JjfDCFUz1BMsZXsmakEy0uyydkOv8l2XfM0jWNKHs2FcBjTmdwUeuHOcTA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
