---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBnxnUoPt4S85H6tJ4eVVs2fl3PiwRxYVr4Vz2XTrNai7uNK7dvOZT/VeaJReuNFEl45+kjCp6ah84kWuFbPXC36c0OzwNZP0X3PAqc8syQZiKW7tJGFhBJc5+SbsdoRSa9YdeqsmBbqwzs1S2Gpqs1BvfRJUobuzB1JwvEVzEOyWAaSKSpBUh1NvHnmwpCzUIg1SDNOJM6+Gt7VPblAVd++C/M3aIscPcH+71z00nRTs4I2yWuFwYnMyzRYdNWE4ZNCxcnGiiFjalSYrkGm2SaPTfsq1uXinuXS75ZGzUlqdKe73qNu5TaZmCnW7If7ZbG7mK/KQ4fyJJ77NqtMsbK99XtxLYU8U+7kWJP8vVWKEq8emHxgO9rOcaXtClfNcMQHXOPiDbhro9/Mor37ofNeZ2PyjsliY3BsRwr0BX2pMOsZ4j04NSl9Dh3VtfWNBGsdIhI7vJncwMr3hDQFtLTAPY9Gj29gQ9pGNEL+7gkdq3p2REPMYA0TrQvy9FFq8QRU0KDMe4deAH3mX4AnFOKaN7zVSDkwvHoVG+AYwqRUR/u9BpBc2YMEitlcK/iI9bHIM+w1KZjlKtzpmI0Is//juXEoe4K4wdGOVufDmajHcygLbam+W9jRwhQSZM+wz5cOI2w2vd19j1Pv4zUpw1yOzialOQui7cu58nc1z9y8HzahzzDptoJCUiwrz3kHMlgFsZLlb5T
    client-secret: AgALH8hrvR64HvH7o4uuILO9gCMiwS0crc+xc1ahbDh1DCUoN7VsHjhurpAtBzy3x5KZC0zvYOpM5SZ8KvZ6shAbaeBQRbgJ122HSeK7al3oHkDF5Qnf8sBvRZ5nfNJ/FObfY1RdQytfHNIRlogvTFNMnDn0+qseknCScHUfq0vdvUK74EGHNGKjMer9K8nMtgIl3fJGdMn+34V0pkYpf7j7H7yIrBX13uqqhMTsIBnT57tW7p/IkmAJBdkGffLyte0mMr85WuPPw4lPDX0dtDzecTUK4uuur4G/AWuD6cmScOcOLaAP5Rpu4jk4KfaA//z7nSpAOEPLY78QtCQIRSJ0GBW9u6vAeFELtmL2lEnPUXQtaB+Ogjq0jS8HP9JWca774FZWILOtUwIc7TmbTzNIuInMGItpFVu3IvFlt+B8sLFkCU6cKsjiaumweujs43AmmaSerLJ+v22Dxcxm1KMahWXCaAPVp+g1Puix68Yjj0swSHuFYH99CJFtEYXt+rXtxNRoKcMhOfSy7mcSyj52x1PQwTVzxm6pdDcPUjIT8lAHZ+Xq1Q/gl7PWNNqNFZf1rblSckxMZwzKKQsQUySgbzB4TusgXx/RAyYgVSEa7IoyhpDGqWx8O1FvV9pI8UpjIOUarJxmxT34s4lQf7Q0iCsOmu6NrBi4XJ6Cqz2a1a/dmTH1nd0nlfCwu0J7NE+o0iJibBHTb+NZlUM24R9E7rw0+3ukwSsHpS+9k3DI/w==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
