---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAr8OVztlI2HabgM63wENvA2KYolGFC/PtQINgMSbFC3XCoQWCEFkJ7YChOaFII6tTUIdj5FGM7xbjgzyQPLpyEXTt3wz0CKyxD9S9OGhm/01VYVxVmPIIZSLZytcxf5XKfOPTdbrj6RWscl4XplfT35q1gOIqV2nlfyJVWLjtmy8bJtJG+7L8wJAu4k2uYKmtvbvGIULkIoFki8gBql32W2eUW1KY1W1QMOjuV7SoLe2++DyiQtWqnVf6sjUxfDzAJhfujbt+xYGtyzM/mjjf5AaezgKw9jEOF7bg0kEz6iJzMImwAVmYPoPwQ3zgZkJwdAWyRC38+c5oxZf4wrmdezBwGE5Ut+uRkguMlLywPek0y2N7tQdCZT661NhoivW93J4QS9YcUZ+mUDvq765c+D/tz30ToQ7IJl9VfdA+wmkgEMfEzq+rMyhFqeaZXQ3kep4f+55IqakA2AcAK4Jtufms5HyVwi7u8mHQJCOUWPUhj14EXREhrgp5wQIkWl1lTKHYjjOSB2iUeNhDCz0nTLjE+6YMzA+bDkxViJBE6DXjJncDp8jqAM5fEbhQxQ/xun+aQkLEw2IS+VWMYAFnz+PkjxSDI4avILcSok48YdFyURQMxt+044mliVC0IIWFqZTt20dVaH/fyuG9rHG9KSxlcG8PfEDfiS/Wj+KgrK/NBvmHxSy8KBYLCWzsA0ZQILTdXH9MG
    admin-user: AgAHrzXtzhiqjvLm1il8nDSmIQ9bCya6WERsBYT+P5MHcU0GIhNHMFvS5eAK7sE3rN2uTb/r+tZaEMduUxZ5bWCfEHD2ueBltG2aUsDHBjh+ObClTsPtyVdIs1Tqgb6Eg0scidzbZVhID1NdXE1h3627TmvtPyILquhT31qMqWtYz6nPsHtzMWjpKCK8sBuMFpGVoBxpZ1dVCf/7WSfAsYiZG4uVmDVsIVBZyNQAu2Mu0VyUu8ECQdm3sFsiLZBVXzs+v7bw91H+fWXcrSQO6C1JU0cpP9PvWJvoVmdeeUOD+epNNw3TJAz2CnWM9Ml2YgLRZvQsM2VaTeFIkgifhcPUdojyeHT+lxePTO+wmlRzWb4uJxxzzm+DomnYc45jqtTTYd9a1tH6gzokJ4pkhBu+FT8+bSAmBshDC8OkUtn73JlDoUF6bnvXfIYKKE7sAoz1K5fFqPn4257NbndkFC0Hwa3qihE1UwFRlDZv8ssD+ES3FlcVa0qmgZN6q9PhgNG/0Qg0TMOmJASm8fXZN7aI3+lLfW/KrTyCelRArOBLhQCnuKtUgvRPpAa9+nV3kM3FB9huOINljMv7SecFqS5sOlXDrjGSpFLHyZekRnesqadItgYtHVQ9bMC/YH+ymcAS5/LujIRChGAUVfvqLSNJKoojgAkNBPn6YTE0Y0u0/eN61b/T6LVuMlCHzqYtviin9CGIyA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
