---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgA2VLN+OwuH4i9BWEKfT0ZpNxUIh2tzC37mvXkPPFCzP3ByPI69u59cxJfDmjpK+W43eoAQM/mwIM+gCll8DTI7QnB/dXh83IHDH+XEvCU01ty0n8lbK2ucjTDXJSRmf51UWwaInfJbjksiBKYe7IVrOPFTk32thQ2Thy+KLfAsk0jvxQBXYJHvwzLRdillDY0E5jmCBjyEUh2QOsWadoy1lo2C40VEH3HCUmZVRhvsssTOxn2mvLkKkAxidhGADnpd0JhsHrEwasogdo8XbeuQD0jaDQ3skI3LsGDo4h68JI1YgEfLJ7v29uHvJztu8tgjkqJGLR5hMLAk1klKPzUGQqz/yuHGKH3GCfxmAvPP+9dWV0qIgytcudPOZMMQdLLvrCeUkfjMfj0c0ILecL0CBxyJP96utucHsQZMewEvhjxxcnAsnQ4vckVtjNXUn1QtiBPjPrnPsYiYufTm4PLhKKpyLU/32O/PpauWOc41Q+bDKf9VOlTNmS33g4HQAbfQRBj4Ra/CKTKFev6fzsDEG8THgCfWxsHOXMg+s0oz2811aiPQtOmBv2v6F3hAg6/Ktu21lC+qEpVbHSYMEdvCaHNXLIyVtv8W3tN6vCOEZrcPNifHE+U9pCkQpRuCl3l7itJVE6ZAIlUP90doz1DZMAmN924g5VK72GaTpkoMd0jA5Raqmv5LH/8KVZDunadKT/b24FCu
    client-secret: AgAHcLujor6YJDmgcnYaVKyW8hW01BsAasLou9ZFg2L4xJa6Xpr4LvFgRqz3dopLLsgTmcRNraCHzCBtFBioK+rRUxVjlhxcZObh8JIzKsrmg0o+yVbRTGvXko8nN/l7r5QJ4VJJ6ik7l/eOxyC51TNZTl4qM0bkgqHNFwsXKuKi9SU7ddy04k23yIKAm6JPt2zHRRKamSIZ61fFLxH1jjPxnfY771ItKqowFCNoZ3YsT//NWosjTSulfrvwQiJtA/MKit6cJ1ceCmzmrO+y8C9wK2vk+67iI7ltL3oKMBdrrFo1l3KChZgO7xpO9Tj2ev3ayPrmQapZIUKjX3z59foF5sqmvHn+ch8n46HNwTlHTDNmxfUxJgfuR5kJJ8NC0LdTq6skURXf1oMiaayypP4edEigOHqWmE+X4CxBhwdONKebmyFQaYEqYNsYreuuMqi3DjY5fgTpB90yOcJ0sa2bFO02xnKWEmiE/m9S1IQhmihV99OFCuYDzcDpiPyS8oo6fOqHeSDCX2byh4eFnExsMfvf9pWfqPLhTnq7R0DY7hNR5O7ijL9q+82IRlrBNlo16MKdQhfR9MP3h6piNW0j5Wc+/+HthsDv7XAyKBeN8qHX1l3vAAPPGKzgpwq2+SJQcpeZrAyxu5pzrPF4XdoX1dRx7kfwQWqlViatdQrRPR20k+YEQvO8rm77P2PEVtvUJQQz9TjBRoHd1pB3LoHsb+/+SGLKMNMq9vzZVV9aPA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
