---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBsV6VhGu6jVygD3euZXqkx9Wpsz1mXycfvHVvbiEXEPYzXA6M7YSfmoUH5siawmQeMdOsXU50VOTcjql8udx3U0gkc5BlavcbEAfda5rEv6wAhy4Dus0gkpYDe4cWeP7BFlSqMdm1xrw0bNXjGbX7c09EmV5PVFxE1ugOI9s81j/RXF/5+GU+Bt3L1fKXTiXKI1ooyn2Fn3+20JW7p+vYGqcC+IkQ+GqZ3BfEu4bQ5yxu+unUs32o9cXHJfILvAht+p/Xdc1Qy+6uv7fR04BHxQGhfJBJHVTYXHVs7dInLudsAAIYnrP8S/2WgPHnbDhm2O3nz8A/xYVu0VWgQ6UpkqFFSWmGr3OhRrZOB5BIp4t/U++xKlsppHKFhjgbTZgrFI2jBh4cqtem68HvT3+i5gAushThKPlp7w7bMKOOYaQANJi0AQJmiBZg/xZowxjSQCDCGvQCRgbhX3Cj1J5wMpeAJwihoavCmKvChcs8dRNcocsasKXtt9xZr/H3kQDBKHAP6jY7K190Rb5odvmi4RFcuXANEUJiHOLSDxSx6JRk/s4IsmrlfeGEsqFbD+kbLNBJRhJai6tDb2f94QWS08bVEonDwii2OSqqinMb8/XDG714W4uCg6nsXR9qLM9jhJAZ+z97Yo5S9vULi2Ep2jNxA+1CRBok56aIVCVCbsQabtRK7vYkPTV6q+JiGzN3aPCTJtGBf
    admin-user: AgBj7aY6ajRKoFuJsnb3r24RA2GT+WyI34xpbdiNgvpPHU3mKOyzJcJomV49N/F/5GgxdJ75JoPVJRygZSoGZL1kMez/ayzO/fshxRH7V9xx1gabWXbUCbcmlNv0+qabLa5Dq3yuFHrO3i/NddjQsH5XHg5mzrCbJhYLc8Lzpb7HZX1YJf8eeEXnGqA5hoKgGjKCeZzRADB/WRj1Yj/iCgYSAHBU16SaSjUFN93OMsKLej0rJQ5ozP6SZ4Aivnepz8O+wprLzWAnovEtl9zpfXxtRw5tStqcXhJ1TP1HPYGW1FgAM8yPLbjt1d5a6JqLul+1K40z+4QVfLGkPzJvOyLwwNhNDjq3Q6a5H06yD6ukRRxnun0md8TJeeU7lFwQfjrKAXbd3P+peQJxRBTHb/d29pzrPIcx0uWczVqrEmOPwTBCE1+Ld9ubJYEQYl9HQmkFoA/QEgTRtFc6ynMaTGEjUKRRWS/gBfgrWRYYB3F+si+eyzj9H15lcbi2mwyXE05DE4HccyiQKsBtEVZiXNLKL8bARIaKSsGGBAi5BVrMnbDilkOpkSDfwpGi23yg7jXHrSCYZkoQbhZQB7EIHkW4kBeh2/eoShHA91TE7ws9P2SFBpr4GPqjKV6CJTtWhS3yPY3ml7h7BiofpIimzT5GRfiZmWgEWoHgJNNUAnK1dZUeWQWXy0YfIzKMpLK+CGi5Fmlc5A==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
