---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAOgnKqWVeplSs20tk9VMNxvE1maBXNSNh5ut1HERDwC8NaTQaRC3A+EPZ+IzFLYxoQDfZgigLTyHQKAepPmwYQD+wzenSSVNnGAmKzpW4XnMBYDP9KjzgISJPwsMZJDjuF2tjTokgGLYh3pwok8ZBj8mKzUx+vlO2Hwc1EM1Ej7hgU8H0sdHEGakQ9vV6rSyDQtcLfXghrpMWXWySnv4aUrjroDT13DkAp9hL7TKEr7KuEjNYcfIADx7uH7jPkkUl6OUyOT5jEg/K5prvEs2S9yWVAZnuma0uHU+X+tAu/3QQBXHADEgy53HJTAs9gRLi+6s4I3I4OejFB+W30aPP70jBqW92M+WlRSG78y0Hkx5fUfT9lKvCw0md7LeyFcg2K8TqDHbDpIIKxKTgujVpEO6S3Zr9p7ssQNbntMVTemnZoE6nWpBch32rx15o/h/+NXbOkgZKY2Ria3w+kQfCqeRveFp8/8ZV7GHzwvgRj5rWloU0oLUBK+TzWZhIofR6EBhtdsMRy6to2PvJJR7QShCvdC5aWF1zUGnspZ+Y2NtYoR9/hXSGWjCCsHSCT3dSnsCeD7hiDW2biZo4f1i1LJZCE9oEP5eHiwUzteTvb1xE0UepfFeTvOF0lm66Zrx+83EH1+D1iJPYzTA7bg7GOWpU1Y8xOOl+IFPXddlmePuuYzy7EhVzVOPX+/1DUk3MURKNYvxK4
    admin-user: AgCmYg3Qgpgny7X4O3BQEMyhJ4A6dZAxIaXpFdiQWpHXp9/7OvCoaugqdAoGCnHxAZ6fGRrPw4rO4K2CG5RqySd+WOaGpMnAcnIQQtZyHFRICrznw7CF6i9PQrThWtNlhqWbNshF2+xYDoR0O2szOi6joKEgM3CZWBLhC6TpP4mzaT1u+tyWVIgHmWyZ8QJ2OQnhYDahiUUSaz4dqf9HwgO2jNhYU3QBEqEyaYrKgKYwj51zJ30g7hm/5QImJhBAqsmSn+nAOpaz9JY3z06MuWX3TTXmKCFbAA3pcFJ5eUJxjqy+rkBP3TJra42dIJ+hMs14TwlJV9YjJ0g/OK+8Kprw0PXIGfskeXensRcypXH90jNMEMaQzk9T/GDoHf7s0KMP9v2uy2ddl++w/6zfce1pjj9HeT145D405w8981DQLngImtz0xpeVKgrBytcnPqGnuzWXauFfBwUp8ejA3j36OKVV59Opmyz3wd0vHTxffPd9td1AxMIGIqveOUnVUi/V2AdmI9ijkvginuP2z6XK/FjQb3PK97Q5MBF+6Vzn0ZOAcTc8JOhM/cTCMcsUuE11t4v7yGpHIkxQhCqUa3Is1I3WffDWFxTkRL2age1ms9dMguivDmwfa+5WcE/KxumQcUtottRbDQ/IPKnJLIqU2XkPRl8S7omp+fakE0GH88r+Gmr55V1EMOXHM7Iriw+BgIuOyw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
