---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAPG2I8gb/6evdapn3sngUdqSuL7wuoY/Rf2vBk2L1JtiV27KqCv4tMWlJpom4KgZmYHXYoVp+9agH5ZACTYVQmOfbCkTcN9kjsq2GTVMtZsceSEnw1RwCz7pQkldm5J2r/4XQlJc39Sm86ZA6DyGwqLcZxFHIYJRYF4MWgmT+bhNzVJMP4y1ElgDPYsEM4lSC24PieBuWj8NiXj+fNFGOZKRgESOSArzduwgmrYgRxuZ1HGVOTC7GE1UuJrjLGOq5Y5Y1OOARq5ePGvKfyGXSzmitTtQW8IhRvrPY0NGgSMLCf8RjJ2yZpz0eySEffOIPCyGjnrF36v6tkm547kBMoPkmMNeP2gs5YZ/mcF5Ckz9w0Mb4cx7ichjoX+CvUn3zjdFJSta7zjahAcN6yEy41aHEa1S19oSU3X2GYMQU0/9YYHkLR80VhSBpOIEl+S6WRBzDIqHyBogyFQC0yYFYOaAVYGOShS6To7oZCqcSdPobHs1Hxt+1bN36RMn5w4OZWqGXFBGDz/B+Ngc2hidJU+gMJTOYUIIRrw92OiJ3p0FA2XUR3uevHSg8DEDe4sB4Cuyt5+Luaj27/HKEWjFo6GCNy/wv1/ad6dsM+mYEETfFpJfqiM4fI7A74h4TM+RqyvqMpGuYoqpPrpSdBx66hk3uyKkKl4BUe+HgE0LUseozA0wGfVS7itLynNUmkollUhwusJEjp
    client-secret: AgCEnI+94XGcs9tS9bGoPsgYtkY4hFGSzaAtKimSv2DI2bxR3zV2WAt6AWPy+H81Zok3FpeE3H63jf3ehcs+tyi3U6LRHYKXaID7hucd7C023yE6BEY0HoWMz+gmvnETrEWRwJaowJyuFOnGDLqp2PpTprHc9/i/xcZmCUuOU1dhf1T+lA5s7RDFqt/LlvnyZ+nufj1zz7WsVHGdo79VCa7GKecXw8nMiSw4PDSnVHxdWl7JPFtABjl+LaxpoSrh2ppIJoY/x2z3teEF8j0wTNoigKX0HOu+Uyy3jGlb6nrmB3kM7HfVikTBazdScBhdgQQYmqMpQu/1rwiKJpI7bM4JCWCsjdTFa0JHRLsrh3ANi3dHfBemi2D/tvp+mQDax93R/VWupeMpnVXX86Hgi3pu1I/uR8RlCdsKsvb1YlJP9c5gojyvoGwGoGMfbb1G+YyQc2lQ8i19xO+7XgEqXOGTBwa0xbJ/vwtmGYd6hCRUZqTWU5Tmf+RLgIt8sbXOB47guZhPgqIiM9UHT1R929XXBh+1F03zr2Cg9vYN68ZeuOeCtujM5MaiYHATjyW8rFk9Ur1Da3caka7tuTWoxIXgwcqYt+bzT0UvaObuzRoQukEBXbzvkorRLLAhBurblIS3y5ANu6M2TzqrOJNoddevMBoA3BIE5Hvtey8N/QhxVB5ePZRTJA+ClRM9KuBGRQ7O7K+mNBJozt89WjGg3Xv/4x2xadkg5cb5IQNafxb/0A==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
