---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBCmwSTxREYjDH4WHBLPIqLwf29ayXF6Rdxu7h6cqMc6vm00HGROAmL30TkIp2zRqESEZIHokLJKljIG3bHlQUgJCnnt7JaA1VIGdAWB58Y9uiSyOt6VUrXMctp7BWTWzwxALS0iLL33lQKQKcX8FEjmXGPi+4djnlLylloOsgDnNrYIhJlXIlZNrVOltESFsMSG+rs9qh24Rj8O8bk4u4CIuokaVRzYBAiUZhkH2WKbhdQEFvIfgTYZOWWiQMyXnZLPdd727wINxm+GU3XuVyL/lFEDOIngJ5GR88nSJEgEtBs5C7XjKlGt70A2o4Ysi/UrGGxevG2hr5BrhiCd+x512YPKhXmtZLrHUvmNHTN0Eb6buE6PPYiove28wUtnWfjQn1oVqpS2GTBjLQ6ZWywWUz/genHZEVBPfg77yMIKxOp7KCmq7HvBTQki37lBoigKmHEyQ3iNfFKP5DjF3VHP9Uq6OF5a0lwXwmA8LFOC9cSwYUV1LDWIFsYZDOYHg6cXJYnvyIKSIdknISAccMaz/a9PXMDz9AzFUOSXfd2FTP4wOH69Pxv8XmimDXPKqUGfVrsPpwQniOdUUhRjzFlcm6rq5AOFAZ2aV7p2YCdRzu7N4HiyxQ0fF0R45mOQjbVOMnpmkxRD4XeCKUp5amFGAmqomaA6WenhfG4OM5gKEDVCCXLIzCUtL1jCiYA3cXhbXqpdG3O
    admin-user: AgCmwpDprp4Z7NK3ZJPtFL/YYs6QF/VZGt/kpCzKb2BByblww6nih63kLvmHSL8KzGX5rBoz8MVZmkhsvNp/X0l3rqh+8sU+8USqd0jxJOeaEhTH+1ntO+20SFAHl2ZwxJr0hE8yYGBqsLSH5ACMFUy5CsnZqCY0f2g9hqiLL1DbATmG7m0LUDl6jpB6bGQjjrqc1EQ7e/8ZFyBYVK6pXcDWWNjA5I6E4wf4bx0y0evVVLtLusTjOLfHiRZaDuB1Ks2clQ9Dz8ShorJY+1BiejX6T1telekVKqoeqSSra5naiHzlSKtzFebRQtuxzhfvEo4moo428aNdP3LXp2q7LSQXQFKpr02+e6MNK+H3Kro+DdBIrA/++t+ZsbRpn9Hn9G6B5X77YbTqM7WGJ7mc2C/XFVf1R51DCAEI/5uxLr6vYjkkoZi3ZJKJo1eTBXcoBqDtn5nvHjfWXxbbkImO+yTE8PcQft5fa0gRjTL/gp/0EYMT1asqRW3iFdh7E1Yv7ucQds69mUZoLbvFjtoTTJFor+/ufCICX7DJsol5Ec/SkOsVHXfeBQf3xzArsFuB3a+KXC92A4IGjgSPVdCPd9RHnjhHAizkjABgI+lV3kCq9/WokqOlTGnFNsqREna1LMbxyTnuvI+QwSaTDDW+5ZmqYoN5WkyCkoMn6KKLaofIAdks/fcpaoqM4/6PozeWBtGbIor1jA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
