---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAb9mac2oHe3kRWL11uM9fKEkd2maHkpc2hPVkY9qzO8jxEUcYeFzq/T/g0tqVKIRxwUgog69xHUq/+0jRdK3E7x66sK2J6Rdsiiu/7zCgKle/clFCj2W++Snx4mVALySouATTANXqix6e0Vqcns9Yo3prowdHwwpETmvlfOhtsJ2cpDyAmDvpA/YU+mj7wMwB3DJl6aLpbyo5rdp3ptQhPJV787zx0dnXAxTp5HyzpgeALRqu3CzUYMs5RaMLt/ehGJELwEt4MtepT17X90hudToMDXCSuVHh2U0oXOmtjlEWTZoJz/TbTZeZBv+p8zIkIgWUUacButV/N4lBG8dYPxF1ZSdJlxvD6K8qld+wv/LCPiZdGTe8HliJOHPvYE0s3GA4A4Z8ED5YCFErcHOznXjIAca1uz/Gnr9ojvoE8LOn1OQpoy/lm3cti/0REy5vtC+/XD+Hpnk90xf1gYvTF44SMZs6PEk2yhdWOeOtmaM1/5lrdqdpnbWt28sdcFOeYsgGiU7EtXvyFkPtupvocnBQ7ltb8ZAFBfXv7A0o65gjvcy9UW0s9urcZFgU2F4F0HQNyz837Mb62NK35YajNAvjbHBzoyU9CRk4pdhneGuXV/071qR2u0W9DUJvTqHTTXesEpfxcM6JROSB9XVWzB4eA1hgnZPlp/E2VvcGpbqYegw1Dfpx6nETrwLqahjuLKwcMgLCX
    client-secret: AgBpYlchYT3iBx8noXJnLWAMLyhnSgWRdHwVGe/YEAlGABMCvH0JifV20ATVQVIlyFil0xbpYUqRz5AQ1MIptYpz340Fj9A7AAFjtYGTevexMF07d1Ot1t0wteaLZdsZtMiXi2NT7lDDPX6XNFWvMP5cvn6F/jnMSSd0F9hrkvUykPBeu1G3s5rayQb7/a/3JJ6j8WGqBAL7jKgGXm6VABp1JtAeEiQK1cGvLz3gfMJB/5VE2ZMWSThtGAcZ2AqVKfaz8LP4jfmj3lhKza38jLO0AUrYDIpfS/41uOMaLjSQJ5mIL1DEFUZm09zqu/3yk0Gvl+64Ke2LrHdNVGHLpTqEJKS0TBSTxe2Tq90cRr6DnRRwmt8sqc0VvsVHy7ACemQx83gNF6UnOZNCp2wJ2wuUSWh1UrTvKoQJZdXjw4iPx03RD5fsEJWBnpip2u5vxZoW57Bb8W9vWvNk3csj/13X3nwjpoyDZoAEhOuAvYqz3tOqW8BHzAU5T8FZfki4G550F3LAZ19XUG3YI3lOAZ6dJWcTz+RRR0csTbfbqkJL0bVgj8tXOJJ48tYEpzs8+KNaTFjgBucZLee5wt2Zxl0Z5JbVgQPD366Yxww2KP2R6jJ91EdrWx0bU3/PBkJP9qSuPoJPhX9dWg9c2ZUHwHLqAnS/3zOCYhs7saJWRrpYe1+ux5Q8jOA6crODdQIS4F4teo8xcujePBWNYkUr6YjeB5GkLEt49kQQEEb/e4wZ2A==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
