---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCK89oXLQW+fM2bMMxG+w7gvzGAtLugg9cJ34osga+/qcpyjVPcKFvInd4ItQj/AU6Bz39rWr2EBZdAYAQ+8uAWZ4g8EZ2H7f0njrufwPLPNx+JYxbgX2wNwijSpCZd9qJgCbCLuOPS1twbE3QAydz0BxUyRxR/1W7qrf+llYiOKjFiJb6AnBprQcymwN51bL+GtkXejde+TpenG+cYe3rkQAP+tW7tVlszmDvpB6sWIWL/wSWYEHM1/KnF/zQnvTnhuLR7yJkhbMXjcaO5p2uhDBe/pvxhIBZqSvjokb8hZHOMY+5pBj8SogBn570NIxBhiTqZUD8lWiPGkurFsGn9yz+QUYaIBRG0nYXKw/F1lMOoV68ir4XSSeNFgIfsIDUwuiNNCQteFEQ6q3dIRgV0AaDKYCRdjNdB4fHMhGmhB7Cq+Ulgy8YnPaxnm/QEcQp7HHwDv4DIL5V1KZ+JkUvbVN5tvaQebb9rUM0vvNyXCEPtVTHrOdkGYeBVe3NYTYsw1MLsc0RoFkwmmEj+FvmiMj72T4L+nqfr70ZH470kD1dbpFMuV6XXan1x5E36orkXiwNdE4iSb5go9dqnCQ8X87yeJ9U0DjVCLrCj1oitQw3v21GAHF8ygwP2PotUB5h+15+ITT440iPFJEPjC7Ss9A4AoJzL8EmVVXughsK2lIeNfaTxf/FrxTwangyYV+P5Zlzn7VHy
    admin-user: AgCdGWcXExkY0FdjxQk9FWiz9rJfHpzlcAkpl0wPOhe7LfFCx0NyPVHlZli2hhavthN8YOgvqumEghAvI1trb7WxvH9k7cUyviyxAYXaiWQj25ibQIKlzpNtLWjWEBPYW+MJoR+WHPJj1Jrma+Qk2TqhLdUCopiNYzbg2NLnLhVzbzTiXuHDRIpfsb/H9GRH33IAiVEE+a67Ko+rOufi7iUTYu0p7TUUq6Q94BpJZh9iwNXRpCbLGEKOOZTeiV5OdVqlBMk0wV6W1ZsREM8jMhhFn26hu0cULkGhZhx5iKtEWxKU2/j2oPou2VkZdFKce2wEVgfJ5+R5lIZSDXLEtPwLOmTxXhdN2tcwhRzHeIScPzyEu9zD0lSRdT7a71029020oNXAadxoEHDoihST3ThPdBmTuQu19lnWDqUDpx0OrZ2Iz3rNsw+G77LLkmhwqZ5FDsB0egjkEE1ErdHr2sP/P6j/R4g3GtCKNg12/WIYLKAHrj1E9GFfYjVxAyVTSdj8MRixWxiZSld1KOlokw/Zf1S/duuudt3t5aRq7066ViMCi5U7cs7t0LoaBE1haZnG2S1Z1Y8XB8EampJNDyZ1UA1HNyUsrRa6qilzkY8+g/usquVj8cvnGavj3yjdd/dQD/wdL1SNLY3OmGH1mjyihEcvbiu1G937/44H0IiTT+6emYDlJFaKRSdH5E/v99qPVUtAEA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
