---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCeNYT6+Sr5behKIEyoBlAQJID0qKVep3Xfp5pL4IA2Ks6nRN6GEQpZ9iCilAed6T9dzvGNunWlLy9hlsX8lJ+/yoT8MHaBiRjwoPwgDDJ7O0Q2YhNY81NrtUeaxWvsEG5yjFb+oxL8PNgdcO3MZmYmg0Tt8D+gnjQzHzqCMWuLMZkciaFNCpF//QtXR5acr7/TzcZ9xYUPlmoUC1faCLKmh4Z0Lj4VTss86VMjN6QekkWjn8WAnY/b2PNfkkOS0VkLE6K6yOO2E0XHxhGE5gjdFLKSxaYCMmk8k2TZ6CgVmrOm0X5egvuzVIdwofbQjIHqIwGauGqGO486X/RkVy93gXzYWt/ZitsJ1xbCoVA75X+SHF64RJ8X+jCUUviqP+SJR04KUkm7zYv8FO3jFoLRjdnrJBz16jFckgP2WprS8hdlzLR+F4P0jMxhOYpIcWsyf9p4UzdARiBBHIEjWCq1PFQflSSe7MAWixZ+w1BBaGNifxORcnFK5fgouRHz6W2+v/KmAPGPcBk3wLbbxVytYbpyfIzfzJjEPhG+vPCyAkW7tHpWwa76jv36jRPKvnG/Vs8OGHd3QkFXN5hOm+OBOi/htmEH++66YMp7Dh8MpaXfeQtvXI+zZR301IndzlTHk09/uI115jZRToiQOZrb4VFAfVvtDE16ZoQJLoRFRC+oz5cl5Y1Dxo5ONiTIt9DB0nas6l0A
    client-secret: AgChJYSOPYJIMk7G0wle67WkyjRhHODszuObiIA7ZFKFZwskpbMxVkA/3yUbvkalWoNqfoChG5cbBSYhCXt84EP8QBPtot7JhASUPFHAio/LN9VhHM9B955uY8nfCkxwJCx+MNFo4jWvsMScy3hG4sSlvbpMNJzW+Wajl+o5gej0IyuliHgptYgyyglN6cT2TieKEE9fV69nAXGDKylCGO+xStcbPW5mmhYjWRU/WpmzX5uF+y3OjSo8Hka8q9mga50eFHAPp4YWrjTP7t5awCq4JWVin6CQ9b+TC1hJU4ob9ubaAU4EYl2jxD/JUYEySyiMx4W70ziUygmnFUIEmimHgl6r3pGnhLrUlcZESg58YhLfuEb1a6wIckaF1QyvWflFf/qUX/Z8I2DXNtQZJi/s3mtq+bEHWjwB3h5pYOmEhMLJ7KQCKcOIfibaFW9K3cK+xAFoJI++cvmB9vGwmynmy1KtCF/SJYRHrPdDUbAkb52uROkSHkLGY9JH0dgJu1zCy3Zgk11vVfS3Q1+zhmHyKilzM1nhTL6gH63XIE1ICoh6o7QsUWnINFQXNoqj5wTGiEK54xxNzGFDwnJCXFRvNuLKkDupX9wwgq2TmvNqBesa3w4ULnL3Tkfj8MtY0nXy1nB/c7QWxQJw6yISe0YdJzCKgoo74k64sm4gdc/5XSRrphZJgVzVA877+gdukeiethkCao6/Jy1482WcxJ6zk9vRl5+OBIPKDZcsdNfVhw==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
