---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgApDToFVbcQzEWtIwVQGVTfPA51H3yBddZzDEb4Lb0IgiH/c8I2kLLtB5Krv4sZ3gdPgaKye/ROhMdoNhyT6BJSkxfuRIrSdQZU8YiX1nGH6UDKlXrlU0FR34Rc+t8b0qODRkVjJaSiN80rZBepg5uSnS9O7xWLmDeNxVXQ8Mu3+ru0vnt/0+oBVNtCiA2tpTAQy3f845RFdKvea+woFzRgA4+sQorxoTqwZ60wR8E+mOADP0X0hPYRtSe69T0kpH+ys4ZU84Ow0gBxxyxhjaw0HNBGJzEKiS4Y6/6l6IfFlrUoyzS16WUy68UcNX0UyBMzlFAc1AmDFh0ysVdz2FKpi6kLWr3Smhgc6fSi8svm0bp7kOk0VJbU4uEnNLSus5zUhbsY5jxYkiQQaUUBNOmvvzzF7IHLE/U7/YWEGhQrcDFG8RJbSDlcmHB6TrUyGm4+6odC5jf4CH3Bh7AFhD0I9t2MF3NZUTqCigUZIGYq/FHw5btc5PSGrx07dN4LSXIsgjuJUr0LDRbXSy7hgbumOjlKP62mpZpH92w1NZC0SnJULo+5qsm5jVAU1tAqKcky1cHupQPN7IpI+9PaEtaB3EEwHgY80Vf2bvOCL9OoctHLlc3cXbEpcH9GWxTS27mxo4VQ/OKFUl7mfz5a5QZqxWGH0akvuQy3TXFjQuOyCEVZ1K1oji3Q9j76OWi+8dNOniWm1fpU
    client-secret: AgB2Lj0l5CuuA2es71n5m5cp8OG3gRF16bPjA5SeMJemTqLz0hCXozlo8+7pFMMsoNcWruobhnlcCNTK+7lFJXc1jyc7dIK5CJ8uCdeMj4LB1CfKYGXYbykguVX6CIEFGsVdUg3KeTrQH4VH4gZwnl9MCA+Bi/nVAzgEd07kF1dxpAq4LB3hMrL86nw9tLm/0Opwj5g0I5ZZt87tEZMPsJ9ueFVw1no8UajZaLzc6GOeUbbNlUDND1vUR9iXAd8xMqvwMV9Bb3M33mm5f64h3LU/jX1VlwM7lD3dlnLJnxQeSkQ+kDpwfHCuLH0BSiKS4nMG52QIOFzno0CAzQQBAGbQeNG5GXHwZCZIeG3tIaLjcDV+ktPkO7rMyOgoVeMWBlwj0LrMw24zVrSi2upyTuk2crL5PQJp9j+u3grTP4YQXuHFYNcD3tG+r6RE0Bp6vo0xu6dmS8mArAnPGz5wKTHBiRNvu0ltmxycxm0zr/Vy6pxfOuObAkmd3VARJYqSyrWQgla2kQ1g2BZslB5+KuTTgIZkSCbV0x0HToVpHA9ukEzPQMR1fetmBV9tZ6/rctsnnN/kbpjqG7uEBwVke9K+uizVuaTG8xArBGDuAHWov9K1pystN0wNxnqm4tUOyZjV5zRdU5t9igXxnqIDt6gU5c/9aAxgVCD3YC+FOLq+914lzjXoUeSLZ30ptdM6LfA72oSwCTMgGlRSXvzJ1D6HFKIsTyQiUPi6weFq5HyO5Q==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
