---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCgWDYVkBQ7CKCU969rS0A0Ack0cVn6o5jppNJittD3cu9tJySZ+84YPwRBp5Ib5Bwbub5wx2LiiuF1NnWkMNh2Gw/aRyJCcR2AH+hhXukKGUZhu3Xlqr7BbKiwsbBYG8NveImIZLD0ajsmkKgv5tzU7/Z/cyhGNlb7qmT/vOfH65Krr3NHBhUzAZS1LiVr/XzIk5wueXmQ78wez6vyBhIJLe3TMhiBLPUx8LLxl/Lhy1P9RQpkSxZomRKljd6vfV8OuwEAX/Vcpc1/DMT5ulYCMvMuUsdlj1gY9bdQatRo7ivFJTEHZoqb+lc9YNCzFDTUEMnZapX3jhnjIo8Ak4MYAlsN2sbxbH/lRMXRUo4csRWCgt9gBNoiyJkZI6AMAhP1LoccVG4sZ5ojZ2YKsmpShHTYDIUyINVMyEm6jbNSQh/ZQCyk7oh8WnqPJccrgiqg8x4mp7BlOE+hr7uPS0/2LB/LJEkiRraP79vtHEWVuYmRrCeA1A+ukAcHD+L4sh4OC62Khi75NFFqsk/I8XL9DsXz6iBNebSkb01g4+ubCpPwnbOedrTrGfUHzzjf1g+PawTiTQJ2X8IXjZTr8n2YgudNAcGe7yd5XgpyWLv+PX4p4r6492CkxDb1ZuasoEAOWIwrJgMTzuxtX1Jiaeia3A36KHQ8IZLTH669xCsYh7GY2Dm9Tn43USxbHQ/nQmSyrDA27jdz
    admin-user: AgB9bK15jPElLXHTqHmDuUevhymJ6UGo+YLYippAzrZVNu++d1tonkNYMiyIJ3zmJAdSD19fqypZE0EhAT0JndRvuUlYBV8vMc/VmIqNe1/tuPuTefFmb3fOUClhLM+hmqWa+qMe42V4QkoFy6xNxPMtiCS5cciB7iyahp922xgypRzfMbstqITTu26mNeqrXbmMHcUJFs/a00uD4OEfN1SrbdO9ZAZQxRTGrC2tOQQ9NHyEVKRQ1v2cU8VTEqeFYmu9cHW+H4rLyrqpR/jP/7C4eqzSxaG2VYsyXcBeqNXEBf2JDIHPMcrk3GLsUkb9o4zQSKtxyAxA56KCnHHCp9CZdbU9ZyewYxF/nESJBsucoupi02KSqvNoQCRkh1P4vz2Id1thXW6DRKAl05fAeYLHGFvVRhkBcjVhb3MLuGsojjCC6vcv3fdX9oRi+l/V94KOs4kRWff4rdES9vPIAEXA1ElgCFt7SUhNOeuUqrXQVfVljKtYejZRPibSqT0Ecq7qXnu6Q/7lbVgzhmI28wo35yD9JquRWKzK4W5OiCrNiC3KtqPwoXdDpQNdsYznLGP3/Ip0gZZHxY6nV7d8fhy4cafPn3qqTgTbXn6ZAaw/6z2J2dKhZHLTOYzpYHZ+X4mZo/KYaclE9D2CTZgCFzobs9LDA0EIdT/ckao/wBdgPDKR440gW5r7cMuKjBXDUw4GM8p3Wg==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
