---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAMPafO3i/nSs8GV4rxwz8PvY38QmARgUlDFgRyBWD/KWsPy+dP1Z4PDeT5qxELHmxXL/HnR/eVGWdyBOF8DZE7iGAI7oriMyjtEMfl+Mb1yhssylUOZHAOhzORPWEoaRJf6I/bae3l565Of9D7YR1dl3BQOVCUVPEBKk1NfW2E/34v2ujZK0ht3m8vR7UMNHasqQDXi6Iml8T6mTJ/Nm9sFWVIsavrm1iZv+3s45HvJM4MwRLylHmy1YGjwGkNTKBO3cHy8HpFFqEe9UheKunjBotmztJVJ4WVKgLInbfcQHJo3YQOOgPJz+r8p3FciKcR01ETTHxxnvCRaPsez5b1NGeRNp+SGhfEBifZPm12X84JrMqMDEq3TMcrD2zDtXDc7MS7JIzhx2ZuRUowJl7SHzqK6GDGlLMyZF6WGFSYLVeO6LTtez0QklSr50GhCnD3JEdHL3FtSwLOz0BMy8uTDPyHLdQ2Ir2UpiOrSuwg6aM3WnEdyhYLMRf1dCX6Q2QVUJkxjRjWib5onZkddC+N/h7bB2aS59JsvJUvqT0Gx1MjiE+vrZGLqDYcokfoaKuLNozEp2U8xXKhbV1KEKWus/gPO7mmxWqyw0FZhNINjJBJUfCfFwLBahKsXAl8h/Aejrikb/hx5BKu8s3olQK/BEXLddllYcvdMTy2HTZG1Gm1lGJEq8ubzJ7CExaFX7NYnuId794W
    client-secret: AgCUZQpKtlfCOmRpVSAaxdqpTy8RaMo7NrvyZV5wFweBEJlA/WuYnB4jbFjVWASBeTbU64bEWCfH8OQEYKoeoioH84UkA0V2SkvDfKacKZ7pJRCxeK6tKKpaC5qBLB/ioj6xtAcLZWcIfP6Wrxk4XDTC01zcdiYHhrYfxVr3KwYEcTDSdJXGeWhW4LdSkkrAT4XJHQbbM5ING8UnqqvNjcMF+uCgknTCKveelY2b/kwroA7HQ8rEG7EoKOA+K2LvSqMkjbD/c3ZA4E2bHxm5q1+3dPK05YCuggFWSYqao5hpfmuVAWRtsT/hRi0PWcd4ZEmBI6bJ2DwdotOjEiQwy1ktO/w3+cGfJRvhhL6r8NupcMGMmLLPK7SVsOhtvURZMcDAAz2APRBpjBmUPfCBJHJOwCq5f1XL48u8MYxzRdprPGikOdCjQyG1n2CVrnUhrMGyJ/DVkNrPKqaW/5AFrDNxeLq1bRvDwmja66bM75lKkorA29GuelPPmAevnw9vxfCQMtHwHnLHK6Oqc9v0d8wdPnBaIUca090ByaNcdeQ+WzfikZg5QqU8rWnaQnGTWJp834CqOzMIx7GdKY3na7rKkhklgn/E6gZA6ETr/u2IzYS+XvKKBy50Viql0RfCti5NIoPxChDA0c6XkSjYU+cPvaMGzcWHicsQG7GhO1FcvRLsq25HrEMzj3rJq3KGOAQNtUEJOzcgyL7FPVqpBtpm4u6WtcvfcdUUE6A5MTN5bQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
