---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCJLxvXEecp/bI+wM/Mm8yekje/27aPd9OdAwIwW+YhkCKgrvkYi+BA2DdGxkqUqz+AKgfxyoclaKi/jY/gJAg/LdtvFER2vtWZhXqdskt4GdhA3bvgoH2m4qPVLNO1lUzrs0tx8aD5304aoR6/uuBBge7GcZgceIIn0ILPntUUxRizh2cFJCnlOl2kPNEJ9ToXFXC2DGwEpYuu4dlEzPXgMp8iNGlprUI3dMEWmosOidtBhReCEsf/q3uNjx0laf/02IKyJr29nlHcn2ORl3xfkYe9x8bj3uVFRWvAYh5Ck57RfaEO4YSIgIEFUxYJLi3SymjTncItboR2VgU2Qjbn/T5Uvp/BzqRCQqpJf/shFb66/P69w4jCws8yjLA5yNJxCEgw0cW3TCC1Mq0RiHBZGsaBo64JeQrC/OGxfWjFIC9nV4vHFnAPdvKBnBtLpZrBQsTYkwXJaSu0gMCC2MRNFbp2YTMB08Ks+tb9TkmHMr0qp+LDeZJhDC6qEMiNr4QJMEz31GEssl7M1nZRM4S/gElZn+aE2I3jbjftZI2CdqYFWYo+quxHbbcu+okJK8ErDhuO0B9zHtvN6wevRp3TSiwej5/el/sUJgt4hywWTW3TTjpu40DBT/gsrhBYst3tWzJVFJYPs8EmI1+qIIxUFS3TJLrjc7CLYsapNijRZwRZ6bp75TOyQRIVa53mwBg1bWyL30IY
    admin-user: AgAWudX7Dmkvskckmw0djgIUIn62HjCRBiohwCAhcmqimxa2kjrwJDmClZANBEoDqhWOTzZVIzdFHptGoXPS53wO5T2j2XUfSSFdwHcbvqJzSxlrIbJa/ETu3e1bIBIP352aBt7w1jV1t4drUHyKzSGqNnsLntjOXA+tHAIzqog9q1kunui0npn9qyySGTjhGvjpmHpncbTAeZoIMOmXcNgUCSkhtTISN6bAlDTdXGSBPYKqcGU6Q/ESOkS70az/IaEYx65vdfDjTnxcPHPxioS85RDvPajJykufJ8W/UfMaSaOfUF481RoKqGO3nhNtgYF5Bc7XIKXEuhD275uIiCdVTq37SlCHUc5L9uJdDv2bRcgClSL5l5FFZxhxRV/+JebK781ouePlLAUENPv+PBRhDFpzlDVU18riUwyovXcrv2CKi8toHps4TGJlepry8IazjrSxU+Gd3jUIaFKRAeNNx9Z+wpti6aCtFo0rF2nJrTgec+5YWmyn2ut5mwVBC00yORAklDn2l+ciFeiLpc2wZ44F9Lfnu4HdGu8gHSeShzaYnJo6I54v44b4Tc4uAjnWa3xLNyeQ4F7G8jSus0xMDv3g+o33yjFLZCo4XfgGaPCjaKoS3FqvP9lwZP4qt0/eXD54eo5r5eoqmS4gedvpEoRe7p3J/SD4/mZ+Ts+OirlRUud3tOVar6O6GnKBQkzh0wxiuw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
