---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAmZjdphmmXtqpUn34kQlUZT9ZHys4QnyAWzOYZn0PQ5XAeJXq/SEu+HK70Qte+fCFVbG96eanvYpOjJJdgNen4O2u8WLbkgMMMNm6jWazozMgGOIUwWY7MW8Qvelg6UxYViYhhHpfsorW+5JNLDDa5Hp553QfN6JHaxkFM652/HjAaynomuD+91IbO/IJuwHtYJ7BkocJj5QkS2kgjEaek/J6mNcLYOaMkOnpF9qO6xwJ35VpnVC5MSlvIbsGeRhboVww+O1usgXHtF1qgxxoYeNMdQoGtUvROfDc2cNzEvb3D7YanifFHdnUhv00k2hRDdEmj5SH7G9NrgnF+fk9MCqrGlQZeJuF5U4ZmyJRMuiIQeu0RJOO+l7fCFr1XdGG82k7HfykqZtICzIlCUkbsNW+8xUmDMlNFBoZPDEuCzGUlny4+hZoXi5ozpSR/Az758SziIY58BxhTY/Wur/H6r+B9bygKAA6bqVpRZ1jcQ3L8z13qCfq0qaXCx/EuZbzpNCV+6O4nAW+Pg/ZqUa2/Z/ahxf6DkLRsiWROtYA0prKPEVO0r2drdo1ECNO+s/AUvR9wfScC4RkKb6D4BvfGwd4naFHG5ApoU6IQ4RsyD1CJ+KULjK8kxDUH0gtXrOPzpy1aefD33n5TAeREhpZ8+hH40BseDJh/la3R0hOaFgtaKBjF20122ayrz20hKZGGnnFTK1KB
    admin-user: AgCSxElzaNLevPmQtZmLv9Gzq+SY3vTq9IgLowfXdcmset9ljzAwTifxgGEGVlSuA0gBVJG5YGuWmr/M6pfOxkjx055mdKLG/y/ShIqWGZkYxKjGGx4rnW7ndJ8yCcw95mnYy5OjHHax5WJ7BJUOvzDoUB5vyXtUliCrlcdI9/XvF9//d6tvpxs+1f64qdvgRT6mNNuEfAfljaKXvUnXWFZo2d4/aUqAwJeTbw16mwvrSFMHxZ5WHR3kl7UjdDWS2v4mQeMLht3K8JYvwLc6nXgk9bhODhyfzm1sA3PqYG21rwothAkhEQCwwIQfr9pCY4QE4kQFPzbIdmZ0FoFUHWQE/qTVQMnsIvN/F/OOPVE6lOG1AUWj1UkQ5sX0+jQL2EaFt4PO3++nKhSyKaqhFZSEhkLjIWvJGzWOk27Cv+z+4HxvcMQlsk0Swu2UwhUnAdnB3fB4Kmka+AWBMQkve1xTNqVTq/K+dlqPHjtnrdbhgS1KP9XafpAqy3pbz90Z57Agta7dYTB6F/8c/ODYqrRPwYSqofE2HTplkQHz31ERFGQgc18BFUeRbq7vNrCkZIEZL7lAkmc3WlVnNevZenvE/8mFcpzm/v0lreRn7GRnvxAiH132kDUUK2bRgm/p453fUbne9aCEIlE3wF9WcLljSHLtDRPMFQUASh9znPVd7VJZh7FdGVnmpIvtcfI97F3kFMkyEw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
