---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgDEWbmPNrY0yMG9TfAeXY13WMv2BvNAqMgDu85EfH1SZuy43z3Q3OdCaXzFv+tCPtYP10TlrwqgQeWSoXeHy/CCoetpV3eD2suy3bN2QANC94WL46dHP7NDrfYhc6YF7ENDaw6Q0GdidA/sd0lTC6lYNQ3t0aQkp/SZ+3+KLoJO04VGTEaPtb7HI9AabtRv6s2vzryfX0jRn1p5BEEEefzzEI4/TR8h2Uk7z7qlQGWVw4+5ISsT7B7hIaqPhw4i+pioecXZYhdu8YE7HS9qYM3DDPQpnEl0Z5Bz/U5/GZGAVg04W4JFk1pphlrUHFpqdRgc/Y1cH+T/DwOth94KhcBVOAV2HEnYB1mR7NzLGkdYSGboWN0+Y7Whez0mDGySyOhOR9BLOqrPOSmyxEV9egonc6nHFLK1mWWDtgaadv//uPf+K7b+8QAISCLBBGNhpNmhDmHsb5LS2OhS6sbg3MRRVB494ZhH8zM5nsCBqtSZOigfB+K43/0okhvx+waNkiYhDrNdp70mU1iElmHOlS/xQ5MjQKXVxR6LFfYr2p/3mCqwhFa2clkIjgpCaKzZTis9Xf8Wj9rjBY/QMCqzZyhea+qDgG8jHSDF7MD3r+Yg5dFJj5Q2LLU4ARo8IYiMakjmG15H7wrRuc01blaWXFfhyWyAEwIr4yeEwOeraHSvjDgkbDD2IBy9nIDIkLJIuXotYZB8AsOG
    client-secret: AgBP+e1GR8LAfIHLIr7SUErwfUP3vbGNkyKxv7qeW2OPWDT/K+CiCY+4eTDAkq+I9ozyTnRYgbcHO/SiBJl7d6XMHSgbVyXTw/ZsYejxOqomeOEuqaZgensz79vQ42BWxBgnL34TJ7/x/OyvjBi9GaPehrNZajtWnoVj9QPg8GCmtxS1X+vmUW0pn+nxoAAmWMTbzAtNJa3YRWe3MEV7pRdUX6gcvMdyGwaFF6ZZzPabkxncO3SncZi1zM34/AqftKivs2tVjcXwt9ekP67puPWPavRxWPWh18/VZBMnDeWgP1WcDRsGNHFPSTQPbyUTAi1Im4ki0E8WMFFygHFB2Xs4KqoG1cesLWQSd4XLrx0XR9Z2NMXn6QzF7Dmu4KVbphpAH/+L3f4DldCvdVnp2+eyUHNjlrroGfOAvceoBiZ8zt8eGkB0tN1WLCoIOvvtCcEZEU8XYmXHZe/BPE1/BRKx8bDliqfN08LdWFqFEN3mYp8PGBF6UWNdzN7mKr5wV0ReEgMFGko98QMFJGGqzsbBfuPAuNnB3Ao17PhmKSugNKeyeZrGPKiGxRtsRCzXcn0YFfFNLXNmD/CVhLHw31nO0lfDdw78223icYySgB3AwzCdhhjwHvoKU4MdwupW1AWIViL+1VD4WvY7BFvXS8sTQHD4ke/Yp/hkZVkCibY7FcZkZ23UpFLCRmcRRxww/NH6YeIspTAIn0ErEb4COz7jqvrRhAl23Ew8QtOpEzlphQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
