---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBjcQeAq+k4WHOd7/cXp5/+hKhWTqbCEJ8fZ1I4hLdkt9kUIn/eH6AJR4cliKB7GJ3WAiKSXWcL1nn7zCzrF8LK9TL2xxG0rxM0olwMD888PStYcbts5KQS1sDtNh/lPxoZRoiGnKNvROBV9y707oFkOlcniRnzr0qvbiHQM1bpwdMA/b47CvjNxh3VrPBxswvekcM3LPoWzRQnSDCCxJC+Eh5wyXJqCrD3o0+GD3ciJgJiJLCNSZE/X+RvrKSZWXgZ3WYrAt/LgwraRKE6rYxRGuT+MnY5i9uaAGcj+A8OJ+lvqpBuI7hiak0BpqTHM+QsAAAnoYo+O8taM1nzxSQbvpM4Qy7BKazu1M6zPx42q0Ru82y7q3Kqc0KWYSAhMErZ/2RCoHGL6I1O5JcJz5WuftmXSYk4gg5puJq53+esEOpZ9pDzsm2Ufje9gXqo+m3Fv+hvDhTJNHQ8nZCvlODdmKOSYcYbJSRLK9ONDkI4dc3/XjI3hhzfPANrtTwxDe4HkY1zv65VwF2PhZh+6T1+03TnagmsSZm+Q8DMh3gplfKBckXfdiNyt7ygJnktuhwt4KfpbfSDwf/PyKUNo+s3lG9CPzPGWAA2LYVhvHAMoqc+Cm3EqKPY3VTkSS7rSkdSdfvBlabuQem6C9VQ3EKugSRlhxVnAGiJbWaZejBFB13M3E3NvpCKQPGtjTC8RppvZwWHc0Xs
    client-secret: AgBsYk+GBztRtoG2bxRmxs0hSIqCU5TQtoyVDVrg4tTy4LOcv+/AEo2qfmxEFOH0xIOsY4Hv0FM0F423sUoQqPLrYf5eAIaErnmnXRUK6uf10v249110oDuOYqPolBAeBrAdXRh9t3X0m6j+Uw6IHPxE/5p9m318/VsW2A7tBhjsGSZqdyJMWTTcfjZ8OfRfYVLmtBTmPgXeIkmK0O8NuCKl1xyvaQt5H7rpy8Ej76Nfzb8L1N/XsaPdLpYBai0n1q4pkUxTfTgSTt/W63Mh2ngT9kYKBzW50QJRWZJfz5olWAYRCdq+smc/GkGhy6/po5/GB4RXeckwGo6pFokJr5t9NyEkkZG6OtwOKoqhU4+878LyhcZnuU/fnnjpM15Mg65PARM3sTACnRXad3TYK2kwitKdW1Bh7qG1JxKOjQ4NUrcwMm7PtfpzNcImf+5JLzx+MXD5BrmqwxO0Z/PqnMQ9SH6WK3CXLWtiXuON/KpTNEAnkUPlvLdf4cqBqBN0drEsc81u0zQ0XV7SToiLEdcq9q1Yi6rcjtMM/iPg+a69mRuVNwxbduAp96Qak+oJFr4QJ+M7lIfRCxM05xQziw3df9E4OnKhLUa4MsuL3MBGRJEsUVnojywu3Ik+cbhsmM8+gz0+vtM2JBE8ll9Zeg6IUjv9nCvQc3POmoP2KCfK3USH+/xuf2pFO+nve9u5IP3xdl7RgjIxjh1fPiMcwunTu4UamxVajXtpV6REpB/Umg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
