---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCBpEakzkGYzseucZ8DrkYDKNYHCauLG2rCe6FvaboPqLgnWq8tBNDp2UeoIoI+cTOwRPLVqQBiQdfTHi6VFjlE97hui7IX1dhGab9oDb5qXllvbtVacXDWzw/j9PZEuJOvFg3M5Hjr92KVC26J2QrU1wVxykcgToSoSwbtpz5hwB0GnQhu1T4sEbUoHGAy0N5t41Dr/XiwcvWC1teUxf5frL90HYKTT/MIXDs3tLoEWeqqkwFc4pLTREE8kU2TCWebCQ0ztWK+XXJhWVvI6wFrVZcl6uTFJYmp6VsRoJByfyiHWczoL48hC1WGU1G5LhpvV2k82BUK9nh+EG3M5jTUTDsgvCzZM02w7oUvSII/Akb0AR9rzLK+GpCyaJQoDIcRITZZAc5xI98yyU1ai2AygH5zeLuG0u2mx0dd2F51xVPWJLHMjglYaays+FiUj/8C3KNcFigs0YKscwR7AZ95/rgcxAODvoRlUB6UQmTtaQvitsg5Pm4ihUbxJfXVwUc9M9Ve2mZwc4j+Tj6bPavx4q16tM/9bD7Uk/4DiTy7O7fGCYXwJ6UXFjZDTf8puS3UOIG7cXQhx9XGIR8D6BbovFggxxzw1nIowji1244Z7dPSmYw3LvVnd0s6waN3bvbPpxHCMGTY9u2F4jom+J01Qtxxpk3ul9oJRuZ/XlI5XnzmhAmQSyc1iJ56tEzGjk6CB82HrtE6
    admin-user: AgAeH+KxbtcGqyiFoLRIUvEKNHgyBmY0oc5GzhSlZsmh6TpSoP0XSPAEp3Bi3PZcMyTKLtN9oBKSSVQy/nXqB2KH/tes7VopV6TnJmBwml0jyorQxSiGNVdJpuXo9rMZCf/DJPHlY9o/1OX9Pn4bovI3Alh5L4NU7t6o05Wmsc8RMcGZTQLfKgPhJL2NymLC/2QRu71iouCinQ6bbir619dTlh2qC4c3h2rn0+yXdzCBVjmtNQjDv/f+08UO7nQnxa3tTYOIs6lhlYqaLW+OejU1E8pxAZFSlON9TTlHUEuJUTLnLqwNjq5Akq3HIUud691zDsHGtAG/JFFtddPRSeRYhg/jVXy5hH+kqZ3tSGjS/OlhHvJzgaDNmhTLzgQ8hKw6aLdtrmuzlSvfBX5eW7FoTbWXlqMHMMpXZ0CKc1h1sJ3Ioq9rQ1TOsGvI3ksVYsfp8H0P29uCXgr1XuT6TAaCEIAYJEfVAyyDqDXW6xfmRl7RJgdyDLXMjyq2QEEUuCubZGxy1sXE0hiWPAtrdZmTTr32B7/BOyJGXyCQMa0oRdOC6N9ckqFK/ESYwLkX2h4D01VLV7aJr8ppxJNtpjk3iOlI+T3wJgr+gI5xLuxF4L9FwJfCLpxip65QO/LT+GRMQK2VMAR17F19oJEAMknhVa+9ngKep+Fvos7rLeWpuJN+ajQMJi+nuqF8wfQ3nJ2Ide5U0A==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
