---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBmOvFm8izzFIZwO/gOaBqh4OjsF5gTbZhERVcEkljqamXmjaO2DiRIPIkOGdStcdxWYOwzvJz0g6vdBUQz461oXl3TXMnuPmyO/uOYTwdx7KfQaSxcN+wRSOlnMrcpT4695DcDV/p85XQQYelHIdfkXEJStNR9+Ywe1ywKWAZ8uAN2wNcU4WUZANesmvesVguFmP6oaJCKvGWpRCPPkjjCmhI0Fj5cx3obwBoLGNsDxZw6K3lZy4/v6qRE9sdHQvoJLiTPu5i/U5dHwF3h+srDO1gax7ayCwCJiaxumbcAUCG+XJzJX2YdMDk4kobtIJYTgFuhYPgqcQ7ffekkVWkoLKpH64f0Su4NobIenjFn24++hcS1MOARI7zEnRccz0e6QbJ+VKvIQFdavHBIs00TjmjAnv1mGWuCB9RQBTAOpXooucU3zEXOk3xaCl1ndN1fJwau95iHKOSJ7vdZG0Y0sczlDelx/U0KJ0vzL3nGkglsnr63SsX2Hy1gZtuTYasJHJtRKJBx08D1hjNKHuLTSm0z3r8P0fyJOE+mDhOzqeDwutzs3rWMR4lIG5EcPVHOZQSHjiVSFg1IcUMEy4kb9vZ2I9JFFwpMRkawp+bEp2IpyB2h8yuY8AdhndKv6jKyfbpZsl1Dg0JEJfRaRISLaS94eFJsuGJC/wdWo6uQ99SZHPMDcWx8bR/diqR1pUce+LPViimU
    admin-user: AgAGmqJ50G4OPH4KKfzx+rRWq7F+D8leRKbToX3ik9epcdf5bdOmjW9Z89aCd63LYHiIQxbyAI8XNtwtfWxwjkXnoG+oMyGdHFPHHAvlrT7cblp0XEJJnUyDxW9LK7+EWy99AitepFVNTSQwaTqyk3KtOz8tpmt/os2GNqyv11IqPF4mfbdwWFOwBE+ozgHBBjx+DrzB3oj+CKauCIkCmKtHUtgtlAvZfq+W0JgRAHZ/MfCRemmzA6HwEZoI+7V5qz8cJbHF1Y0xecirRtzHWCEPtsQGbUe4fT/37YjUZkcGRkj6YlVE637dqOX/AuuUEQvqLwTZI/+0IaXP96OucbVy5DHRj69oeQHHi0/grCPw3IAd2pQpdFa2/YWNdqwdHhfGB60QJLa2rXWKdH7JywVOUBTRO9Xrb4mWj7fYl6hk2lT7jwpwd8ziImlS9pJwpZfVQvn7Ge8ndACj6ZrU2zI67XGPFcZh7+FQGdZWvaoj8Deecrvi8q1H7H+A/oH1aO4sPm54wJjbrLS+bNzy8BwYevu8U0LtkmeOIIK1jgPEUfqUuDbl0RP6i2nzh1JBhWDd1VnReGkm5BTnnfH6RLOI7GQ8UZqSMPnOMRCihj/8s3slqT4lABjgsm2PCCJk/C76PsKQsP7w1Wsy1UZANLYVjuE4FDjjiCB7Z1G5yZpRWFKgQZ7R/ZRBrCQ/ih0E+Fym1Q1w6g==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
