---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgDGchlYZxvl5eBXcTpfgDzOBeMZs/6B0/utmmfGksvGXEumvn7pam1YCkKj6WVTXAokhHguuU+xiNpRbD17Wys89vDtYQvwPaaO928lrZOao1/IUFJ11eIi0qGX8tFyMPJBID5W671h7vj9d3y2nbAhanGgISGmAutor5y68pRT8lQfUJt15Zng5+cjDWAIo3EsOXf6AHarZUYpI5EfzQ7JQFHDbHLOocBAp8V7FDc+U6ZImj7T71x3KWIzQp2OdeIXZp9XoJf7wExLpl3oYaF9Q+hLC4kXBkw6qtWkMS5jnDGf0ZYsb2gTBsCCxLHQTdZ7yfQ6EyVK6YlJzwh28I2hV+Dv6Kj4JnliJ9hLwZKNyq4CuIvWpgffQHFJaXq7miVOx+fQhL1IOvHDIm01JLJqVtxJuBS7DHemWR/GymKS904234L5n64ovw3JpTQ+M8HjEl5Vsa85Xz6t7l62w2ZwdNgOEAYlCjqiCTl08cXHKcxL+Vw4+kHAA95956+zE9qDC8pZCqjdL7Iyrpo77w1JzAFbXdw00tl+4LRfHvmpPb3JjLC64gWxTNGFrzFbzWl+cizQDAw225CHQmXoDoj0s/xlCmVblaYnRyTyfUmyj/y45E6brLHr2RjNJ8biMdKl7qMwJF3/dm1mmQ5LRVqOKzA1FtQ0zHe6V0G+3+G3Y+Jeakr+L/O5ouLxgoEfr3wEbrEHt3ea
    admin-user: AgAH8zxD1L3U4JlOQX7ePIQPBwBLgj4UsVWBAalowO8q2afQRFSLR8Lmsvj1fd75HZJSGtyNM+oECK1qYHRGUhIlhsEA7llkHuuWpWbq50q1tZYR3IOOtZHXCmr+GKMcpmkQ0j7TuwrZAmDt53iuUaUbxeCZ6yOlND+ki/YbGkKMdCenR/xZe0ojLoBS6kRxnBWv16FSxlYvhdK0s8n5UispcXv384IEP5V5PaUikHk9JpJG9PQuizYScCn4RGV2/o8Oq1DvYKv+JwHRtHCcp0m33efUb/tSmFhOwTI0rjXHWEmzWf9JCLx2ytf2pIIK/zXlOHKG/AGqKPsNiHYTqoZ3Xqw1tzyKOiTN+Z/g5V13KKFEGxzkpN87iTd8TPl4F3jJsufcIqDqN/uNH7GZZIuyXe2O+70jdZdXkhDNBxREHeRbVhw0h4raNQawhoxnBnWNETOePgEpwkWHTfv7jEGzJFLSQU0n85FeT/UUyPUIyBXfvdx1H8e1sNOdSc36cgESyHSKVnAJ9FqmM+l2Zsu4TBXObZxkA7RqUW+M7jdtvkJsUiUPrBTzOcn/Z3U3k71mQumUOlaO6G+kmbzi0n6/J9x7wDHWGU9Zb+YfIdSsrBpTSVxVN5exGDjHinIciQb6GtNRnvWAdID3NGyzc6Tt/3tfFCqgSqQ86fg11H/zcHoPkDFsEwdrhnqB+dV9JnpdquDaRQ==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
