---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgA6calIjKkxjBguYhNWeAhBgb6xATCkUvsGL5wBBpy0JlrkBvENBGyHi42uwPJVUBU+we8ztH+WqhFB0qE1lLpb9hDKVq4PgA5iQc4Fe07shg2xgYwFdLydpempdxIVVQAQi4Vl/7Fl5UB03e47QL2W06XNjsU1E8xCuL1jxn0dDNruZZXRUdl1VXAc7eRZf29s4Z5MTC4Q5IGMe3nlV7cuwHj65Tg8dznTK2JnAc5kX19OtWV4KXmQ4aS17bRrpyALenSnZPSj3WYaEm31Vm5vGIvDEKh26vPERu6RBfyF7lwvcW9z4XhTQaIMsnewJzAtrpiX0wI5ytYihn45Is2HifWUMNK/tnyVPzL1sfZb+ut0GagGguJgG8TpU4aWkopPV7WjgWDgpyKkEsfZAdPRbozlx1WEIZRq/RMZD21fCoIL9ITAfK453yaBojnxeRDv5/4smUNOCU+Nc4HW4we4pFfZOpQyaf+d0ixmnQZke0nU5Nk4Yz4RmpAfE/f3NziVMpfn3D/brfjp5R/SB6wI0O126BB/2fUHydDJdrSO8vbpNkRWfrOAeWxFRbzELgDHTvXJ/UDcEZQs0sJobtQF3eIZw+YSp98vrYeQs56LdARlSaNHHAtxDRMEYNnDi/ceuA4D0FU9PssRPkOfdYCuPB32BotgCCP1kT69rgnGKiTHM6ntnLftU6h3HlOxeK8mZKXJJi7e
    admin-user: AgAA0R3SLYcZR17JD7NSNlm6C3ABdy+FyBw9PxNyj5HlRAsUsWdfxWgjNsYAglfRn8Z5DApGeEvmINxTVmO+TypNxGh90UDNrqQCX6BYbpccRcOCR1Bx+Hl3XFoUrMnjVY0UYUW5U1bkMXDsojoQa575x9x+CZMR/m5FVraoSveO59Q7JzBtSy7WTXdGXC77baoscCgy7cfHQyE5VRz05jhYG32Sl0pYXb4H+bmveobIuMWiFqn4cGfPx3DZzB+reQAaXiFynjX99vFMz8NmsK/rlJ//4NU9GF1s025z5LuPhz1TN+ekgmZiLADizdmxsnCn+Mkv5nnuy3BhvprQJWqXdr51lvUn3sM1WD8kI7WOzHs+wJ7p18yfUa2ytMgkNnqyJxaayBi/tMrytpWnZN5jSa7y2/u21jYH64eg519zg3GII3vG8M6gk9bI+y/ujh4R948CscN3Q+YmYFAyExrbg1IjhIVZ68QRwAbL4RbFnLpPRyaP2vVFI2j2wqOz7Xx5Kv/BTTchosRMHYKqAATz9arIVdVqAKeGdaDWuzXj1FFeJrIPmj1ajX9DXv+ofD30iwpSpzFkBARxht9gLjQ3VQvDExH2cYJxzgPnKrzcS+IzRQCyVj6GRHlQqeTuQjLJ3O/o3AQcv+e8lHJcDWB0WlZJM6nKjJknhrcfMCQrEce2hbH7RD9QAbnE88S7u/HMthEluA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
