---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgB79Zku5Lsa7h1XYmIQPun4Vzhx9dux6NeLDznqTqS3Ly179CtkVXMUggAkicG3HeQYfQdp6wcR3IxDPOvehLuLhy2HfueNKf3IwBjlwpUjGkt79NbkTr04z5FqKLidZGvcRtr3DcJa3JX45VZRG7DDlvx6f0+NZntCwa1p/ZguYj5bIboID59plM8xL5hiNXJdOzxwCC2l+xj83IMPNgacp/T84XQtqf52BgBuAhYnAzPvEoiQLM6Uo1KXZavaTh4qtChQUTj8m/YoxthSjiw+pfvKiSEFppIPHFBrqKh3DEPjRwny+U2ZHIgX4rHZOmTZx7L5EZ7fooocTau35rvlNXGcjuEcylrc4pRrDKF9QYb+zeAUZ+dYQ9WH86UqIEhhr+o7vNmliy+o7wx68V2FFV2+GKJywX7PEUmZvLjewYyLWcE+tQMygbZJ/VN2C2mB2AaA9/lF542MFbDGaQSG0vmCG+mWzP2tEDsIOa7pjeFiRojqN2mGV51BY8wFjml1uEokbElPqbGYglJmcuEiXalNxhqHQNdQINwUZmHq/Ji1rjYq/wDfgNsx0jBYPpm33corijgylqmX5ysRYh0rTEUeK0LRi/GyJABqzReoNGzwt2LbXb4GcMEDSDe2B+mngE7mDCJy4hsIDHe0v5PDR668soeu+wt+pZQCdAH0nMO8pfL3Dg3V1VrnaltxFU8iN893Xva2
    client-secret: AgCar/niGXqNARBvMLapgzJFH8CQpKbICy0prhu7HeglXrHziy1GEuE66b8kSXXk8/K3KiQU/+JgVovB6+q936mcP9rHideQAui+NqsqCbkp2r3YWGxGrYZaMSKTrXqsx/0EYsKcXKLSBS/roaamXghfNrLj27yd6thfIRdt7CMISFnwYVfum7wAA7O5snOVKgFFnCi9Am0aJcFMGu0/wk5YfqPEPDCHgiwl0WS8kX1kn5mTogaDXPbl6EhQ/kkjYKTyYZI83XxWdjzPiBALF9d2hehwhZHXS3fwxWiN4f+8qyVkMlav228ses3Hp3tHC6fjlZeh5D2LeoviYDa08A+a/aldlJc7rw+zmXU1V0WB8gT+SgTfkj+xjfhPpRCg0aQcSVnCdTY1ZHlgE/p8nTqp3+nicrCApFBs1LdMKeHj4v5jwZdGgtz93X739kFP+FlSqoY4XvAzUX/toQ452QCepxW+YJcMlaZYErMInaGK7hfhAoWaS3KZD25VLie4AyKJulz/wW74hHQVu09mGkgCxb8dLWIjYq+kjXT8k1Xevs8yZL7eGYLl4PTAiSm8fN9eeRD3J0Xh4us0+8mFVDw78On7ZCXpOOuyNt+lViHs8pDPfUoKZXs3cN9LSXHDl1tdZhAarqFzeKE/gYUzuEAhYl14GDIY6xyN6I7DIOesIEsQjNs9JzvaP4VBiCI3Dlj+1nVgfDWJDqZLyXOUaUPYyEWt5JiiA7M3T/l66xUbog==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
