---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCiPoylkJMVzWunBLakYDN8jGogP3qWmtcJqHuwbMXaidVxkz4YON9Q1AugliiHhh3NA9zl3YbnOJn2KfaOhgQEq4DZ/2QpkI4XxtFJVpu0Kc4NRsi/RhH7Wj9QfyUz2xgMjyEYgIB6Y96yuiXo41WLx5pR+hpzPk5CijcbGP1UqbMi+sJ7t0YWcUgNc17tGh0ZQh4VOUexAwFewU5Qj3htAvqfcyQNIPoQdH2WWkU0h+S8fG6IVXVuvqYybU8F00wNX18SfEABUzLhw0aQGIvDpg2wUh/te18KGU+0N3iX6Db98j81DjSx2RSoKCTLwai0lYawlJWsOIEM9sxAO+oAaAA45ZN6TzmxeArbvlXzrLR3A9WD/l/8n8KFBJFml2e2O3RfY5ouHU50EVuQz8nOz5No+wEq3GF88mzPwjVWqCI3ml/bwv5blWSrWJ+Uli/1xhmYWOoZ8tRqvwMzNZgE57/yBBmJijlcrEdqrwVRN5srcgPA0FOc9jn/TjAvN3Z4aHANOS4VgB1LBqwKKkkfN1MbHeLAowtm1wPz7A61IOgbW46+EU1PjyIW0wy3uLw+zqJlpp/xTdeU8IT9se5Lt8LDUZ5VvvygE4ish0QGGNDN/7FUYSd9ce816vpJcF9zOBp7GKsr3360PmLr+iT62BS/6uiAwYxwBRXX/sFJGUe2WfkQDRfj+CJ95GFuLDmWXEUNBy0m
    admin-user: AgB4wx21hz9gnb4D3yA9jGaNK+oWXBcNXipXCoAV7/v37emYVZs8GUKlbQjSjwmV08Tbk1PBYhPa0kAiMltSsy2bDlPrK3qMDMJWdw2e3dtubfmPavYv2wafDX9SrLBlW6pB91i6Ex8+ObKpD+dbXvwUhtqrKnRzTlEFhh7+uXyEE3sC8ztRwXL5aB7IlWEV4xNmwjKW+hiYIUydSOeXRIUQYuqVc54K8n65CeQWftSF0fLKsIVLrujyXm1UT9ufuguIDnm1ShcGkaOvyGYAXJajzHD+AXYHH459Y4Nvv3FqxJwHR8l7Yg/nWc9tw45twybZBUsdbKVCnmOddAZD9MirRh/4aJttkUCzgnUQyUEG0kTozpteLpmDoo/u1SI6oKzXPobEIf9rVAKNvq4RXT2GGQSCYVeNIPQSWZ76wVWKeXvECm25fKs7/JyXGbdPOBLNIaZkwR2CTTOeFiN+yYZiNqXVZVVtOFpYKMpO5O1cR0biAgbV6ntbsLEWXu5l0wHQnu8Yk1IHUGAdd80/4xJWegLOIiY06Qoe4n9lresf610yTffVgcpr1/mQ5UJBRQPMH5jgkHmbbuiFKw0rJTRg0fXjWfWXUFh70gIua+VpmKT5nZGOkl3PiB/gQdb1hAuSRtoPTByQJoT8P0t1zlauEjRs3TmJ2hO26S2ds6k0ucTw4vxp0bEC9SMVtTAtfIgLEuy7SA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
