---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAV+iBaSXZRSkXiJbtIbj5OV2MGcBbgkb/UpsbdcqGY3d5lWxoTvaCoxWjtrt7LOxr932pWl58zGslsocSqxsUBIjFgYSyzINbvlj3TcqolIs7l3/ZJr59yZE1Zrof2Uz2Sb3Vkqt6MJvS42Efvv/AlFFT4WdlvCPwxEY8Bp2E29Hxj2Fgg+ZouK3w8GHiMQ6iaUlejWWjZ9eVPCZ8hh5YjaHb8lxO9roadEteNNisF+ayMi4mNMj4a061A7ksscBGkwQ/DazeXIOTSTaPYUKbmJuQWlAqr1pCjcC62r7rpMO5eZoyakaMDvMM+NE4HVsrzzE9fEWh4rg2lXxYGbBJYo4xQCt0Mebmk6klgYw7QnvhIG2OGlTTu1EJCKeI2Xq85rge8yv0K2cyJ65ThpFtvC7+GKNb/yoHX/aUfaAtN+acYnQEk6wBi0UIFE1+ePLQlAhg/jfEPxLA0gjBouxmZIJLa3ojOYyq9zJfuwFgDJ78z38C2gXfpjhid4z/7OeG9H3zA7d4T5K8LYYhze+ii4cU0N+lotrQc0BN5XKt8uCv7TG6PIDfWet3cZSTNFIqO41AQF2XhAmFLLxUqe9Ya+TCsHeK+bUCv7sdZF/5FTkD0MOgf0Pafej7IHant8LbGWJN+x1N7dBaWYFkNTsOXtA4q82LZMBUc/Nuh2bseU5Xmgx/mXzQfhzLoMkaLrWCoF+oU45Lw
    client-secret: AgAajVrVVFrq21HmPOsotX4IWCBprBzLGgYkGxQbIERros6Imq+qv7VCIHzmPPxpkQcW1HSux9fJvgGS22897EWSrWk054fbXaLfOirorGQcVgP42KqBGDUG6WwEwENFpwY4NBePATSFgOh2r35Kkd81oiByQMMnRgQGEJlS/VQXzEg9YRrP7uSBPDBMAxS4K/oqgfu9qTUrLERD4UXUZhoK0UYjusKnoO8gNFzQHtvXxHO5Z9itrcfDr5+A35kvovNG9S3ziQx9QUACvHNepgJMwXtw646eSakcl1S2MxhFzIFRhdM9Zu4hz2adRh9/DOegwSpQvc9eIhW/6Ew4CVcsvi0iSRggD+/HlvseGkOjdmN4qHUf/Gm2aYDs4yl06x7ZzHpCJMzDIHWc0Mqr5fQx3QzF939W619D4INw1RcT5SDxc7BqAG7QTUQuKXW7SkKywbdI6eo8wuDnkDZU2hjtHfbxaiV2KAMmiivuaZ3ONw9DEiEF+UnmAKqpYWPX90eLOGhvWv9W0CaNqf6hM/Iwh/bqWrFQvRH0fFzhSz8MuJfXnEAi6kdvLLx7xI/kvYsrkMBdf2X/yKtyKV53NG+GGQy8t8bcuWFX/HcPpQZflIPIPW81TeK0yA4Q+gBS358WlbefcqZTaNYCITLO5iiEevhcUGOkxuajqc7pVyIImcwMtV5dtVbnqQP22wNx7C7qiXXJfg+wZo6tSlRPLunaAhwy9MP4XT8EHk1XnINeUA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
