---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgB2oUXTf7key0w5l0zmCYAxKzdLLE9S1UedRieMPo8kD5vy0qIAXGJpa7u280e3wZJPUoR08lbTsj0I6kXowxiBIU/2P9XVFzhWF9zYcLzf3+RtO2sGMJh180C/NC/wWmjqPeM+4DWD3Ywh7lys90b8uAo1546fa2bmPz/L1hBfYvZ93gjoMCC+Tzio6IZgwkC6e/9VmISCIyfI/3pUK9ANTtFTkCFVQKj/tb1gCfJ+wp7kqkYQVg2EGKXtEG+kobKRRishBgTigpwjdi96HB7UnxwNYpPVbbNq0dZC2HZ/QxBbQtC2HxdeZccsAxj6OspIgmJ0if0Qrf4B7cRDWwRg4cojE7POYpFiX1U9FuYLYSTPEY/3Yj3woza84pvqluJnL2NfpAh2ZiLTHyqU/DrNi9av8DkxMynQXtKRhGye0sdO3EYS6fLg86tGf/94m7dppmrPVI+7dPyzgU4PJ8HOHgT4PwWyPkrXEK52Dzr3Puf1t8ZK95W99S1c+fXfCUjH7QJwJALblAQTRrCAE0ckW2YLbvXqJl8YzVcmYYEA2OXdWEAjdmBZYSNG8vlcqGedUqZGSa8up54h4TiAjLkY1G6qIGy10aQuo8nGNj54/f9ryfWKO5/fAbyycFQjpNMXAKHC5rY7Cn5sfr3LWzoBjdU2sbI7NiY4pEq1aG1skDpWOv2WUWjP2OfIcV3w4rB9X1p1meCS
    admin-user: AgCX7zzkeNeHlSsCwklQV73YOZLGcLUlA5QWMK/ocpXzSvtqzQpTVvg0JVNO00MJCbMPjs/F48k8fNqV9yzjYXt0H4cp5Z6HlaKXjrsy1xZRz5voqpXg1MRZ7g3Ao4Ad7GG5wa9IrHMNLRUm5myCxDp1tUHfLEZMpIN11Wagkxf8u4AguA2XjtsUYkX0cgZwr1i71bRrlAAIC3ww6ymFMaGyMLi7Qv7v916AwoPqhbA+WL0emA+vq+TEKvvOZ3IvvuATPGfe8y4zH/AF5bRpdF9hqjXb+8MrfL1kVOYqooV/dIu4dJohLK6v3zrRqupoQZ+zKoJNJXGFGRKVHjTn6js12IoHtZhZaB7f/TPs0cgQSZTO6H33OUYMMgX50vbjK9gIJLoFXB/296BHVujs6SqC0heP9D7j204RVTBZ6DEu7wTqHAvbJM1DeZ1ThwTT3TsfQAMV4N3MsyFxgYUsKO38Y5s4/xpIfKo8tSeXiyAfQR6MCRLxw+Pg720fobOYwoCB3F0vSy68tazsAN5dLZnmqmyffoT49OGtAROL/oB7s+htAQ/Fyu3hXFZ2rJYJxIOAKuhYhKPAUZ4uAdhMCoAR6QC9oxXsxZ2kgdH2vuFNzC90AfwLAzHCQtVcEXG7JgDbcvwCB43n/cdWDqrBpVP7kclt9nxWSo6h1II0zKTXzUq5nKBxfCdeST+S96nJwBZJVaIHNw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
