---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCWrV3Fb3uxxnccf0NizdR04A4RCMM7PyOxd5/IWFTTjPFYWkZgvMOsmL8JyewUBNmOeAVQrEXsEiA0muKgOYSv/YVUxsuVjtukiE+AexcImpM7WVG7fbiWMwpfIqhbQMER1Ez3MNvdDPpEk/kM88f+PcjgkQ21TULq9gvwd97qKB6P/QQVgUHBYIfJJ18RvxSKMaaGsGjdg/Xsqs1/2Ek4Z2JQpugRmQUAVvcThW8L6aafcnJfuQ3LgIIB7IPQNDYVrhKSYNeTrI5aO/5C2WAN7WlTGLZ0EfGeipNSCwEI+NKkXDTjQEaLR9Q+D/p1nQhWjgP6rsgcTyBFjNip93L4Xbv9tKvDzjb5ORxBKjQjGrARMcHbQP1bVMCW6EuLsHCUebks4+7uK7bILdAdfmesa32OT+PlGyWWIkaXUNWY2Zg1hgnU0RR9FwZUVWX+ZcZ7uOJfa1T/5Y/4JAxmb7SSyuXiqMAWn1F7Ti0gGcN2BuwCnzCfw6hejFvVA5knLbX8lE9l3H5Dzf4agVioQ5VXpr1YK2Hl4n9EytGcqMmoQpUWK/tkrGMTaOoZwdjPQEP5lIcPV+HjLcnx0rAeFBxnDeYsTd5O9fdVJE+73TTh2KIG7iIU/q9QVsSXYwI82OrJ114ejT7pWqV/mggE18kAaYIqptox0Fcg/mSGUEPgFc3EglHudfxHvqS1IVFE5klmM0lIjgHo
    admin-user: AgCbmYtLT8J3EhfYTmN3QeZXxsJJj8IH7GBuzn0WfnkgefD5sZrdvd4Iqfotg1ZvSNhVG7SG5aj+3QrvLcHNnIJ3BVpIw+IDN0747HGtjpk6vtSsNH1fUy/1T+qFOpv6+ymcFns9TScsCDnHcxaCDbvNlD61YD+gTXq2SlVjBvktrH7Fd2XGgRarPQH0vp8bNtpOjnFidX3WGGm8Brjr8+2Y4a/NgTxZOMUV2XUJQSxHZ0rSzv3YlXKaJfyweU27I2KE4cZZeyoXLIjjqOugaysss39luQ6EzFJ33zHaLpvqft+T2Nvzh+q+LcyUdYt79Zqsa1ZREoNvKTGl2Tin+ktHoTz3/PnW6Z7LI9wCCUbQAxnxTBW9Hdm2DTgBkF/txcvR+UoAbC2PHgMM1+tINXZNLGz9Ar2albryWzvo5rCnfl5nA/lZrRkVYILWTgaD4crKsgCj3K+Zk3eDjsd92ENAz4dQN/nW5zrRxPHoq27oukOTABqZLHxgMQuDUAReaeWX82pCCjxI31LYjlaMoKQtzhUHivUSOii13X4TcoNWF0dwaAfMlCjxuhP/9P6BEjBsdxCPCgRmjoV++wY35jYDnYhcVbY/3RH4B31BQtN8y/9jOKC7awESNQzncofCilVMLi74nsbp9O8amJcTz2t/2EmhuIJoxe/IcIkiLN+XSkhroYVowLyAJ456NDxx1E53mUtMCw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
