---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAJQFIUk5/xexYHUt6qXbnKsoYBSlYTWnoZXGwGOP0/MF5dqfrO0duY97FhbYQfF5Eq25/B7oIGtBdvlBpe7fdZndFxf836FtTAcZSWnSZ3R/TJyHZaVj6AdNiCKpa3FAfjGIRma1yWXPoMjFApRa2TtGMzcAxiCvC+IZDgdNPCq+uFImsRgLhnCzj7BVqAe+pj1W7ZrZV2Ptd5KEh8BQ3iLYff18L42Cx/asTQ+bEHqq4rzcwk2r0EpwYK36J7g9ISGDerJLJ1Q9eb8QCqUbG/0w/eJ13BzJlHjOzpUq1jqC97v7ixFvJdBJ8r7+OQg80mHNzw0xD4k4rky/ITKcKmRNsITdSMfe4RQduoq06E74uC8Dic3DxjWPJvHFhzZftlsL7szgN9cbRCLlAxa/pUkenAWLI42iO4WFkXVDveoFO0jfpa26L6+DsBGonUM+qhXgoknJmh5m4ume2BzHtU5u9gY/KR5RH2wBB5QCVbVDTcmmKrC3seYrp8UTCiRPHxZzYlrgl8G1SQDi6/VvgiZhyj8rPT+Ns5G9R+JJ2G39tFZ9Vqqbqkc1JyKhUyAQDBJ8UwKZgQXGa5YSLzuVH+wOvwrlSZpikMgqmcK72TxSZL2/VoX80weaN/5cmT8FscqXesoA3bsHOyzp7ATmUNwF14c1GDAhXpaeTQh1ntlNw1zRJSp1J5mSaPO2hDSjG0dUWYLP9a
    client-secret: AgDB2wISmXdnyMIoJxtlEHBiRLSc9q92QVe5ptZ8slX3saWFSKqpwcgnlQ7X6JCl4t6c/r5efqZNHIYm5SpGqjExz2LgqQ7LNsamQg+zOM28FAEj01g9wJiRGwEDeegDVTwYAMl/qKfF5QKydfJAaTs+tQa5eIpCTo1+f0HysKjI+2RSQD4+eT0ky+NDGsorX+ZG9yCVZtcUP0fhEZDwma1Vj22N/XlMQQqmdrHX2FiIAW30v0lncDX0wYRjolxz1lrxbTnE0Si/wdmfwQeF/ceFlekgqiSm9+30WMzAK2vuJqz3KylsJveapk5DXSkNpQmSareF0ETJ0p+G7LlIDu/kRZWgB7porwfKYD3hHM1Tk/qs3LWCzD4Vv8Dv0d3+JtuTDxwLtHa3fuDf65shwd1qYmlVFhJDzHvmGBu0KC9DoJv5bPwBoSnktmO0w2cvYQzqxdUaRU5P24JljH6dvebQhvFq/J6TPhlxTSS3irfxDywWIv3KsFwg5kX8sCqXUGKIO1p13pCgmzl46Vyrcz+MX84nU1fNniBvWEX2obuwOv1aOzgWOr81NsRHQiOclYMIYr2j+GSLYAFILLeJSfDaUzx4flqd+Tzsfk/2uiU/8xlNtXToM46NvuyaRkYg/bHm63O4+hPeHTatxi89kYTLEjjVKtDrBFKN0UFlEX9rDm4MsZj1eG2XWG7cZSzAIH6G2VT6VHm8L4xLabz1m2A9ND56K0Jh+jZipVNkQ30OQg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
