---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCInBJOaxL9fZUlptBXKWD/d7mvBxjb9lfAz97zRYR0m6w+gr2ZBYiYCJljvFlKMmk/NqerUiu9MqHZA7njt8a/IaPLyLvy1E50U6UWQXBoHj0fW7oRA3HestXeJnuvpmJR652a/hb/p0tt3q/7YZ8N6WNK3H1U7c1La2563yNm2w+e467mBnl0rRUyGDYL/L0rHxHIB8ZRCW8on+y+jQRWdymo5QBlyiitUk/QGLnZuAgfnBnOZzCdgpGHv2LuoGZKfwad+mbUnYyukkaAVtYN0DVA8c9cmaJwXYyx9su81c/Wx6P1fU2ufYbbJk0AR92BZnSHRTzGR9qMnTzCYRjLMoN3ZNIxYmQ5PNug6Zd8IcN3K+BY7Fy2jgClm/Mcgh2QS8HCr4pKyBBVgVaFdrRf9HoAeg3hVXfxsE/Eh+cMXpijb9oCbYqMTWAbpf8Klp9eazjjZGe34rXYr6o3kt0vzXqrADamdSt3jyz4dE2zQRmyUBuaij8k0og7L5VANK5qL2VNbTELYQr+rYfgbLpx6BpfSm4shMMZPjjWTr9VPI6VUApnCXZUWWfXT7jukgB8zZwmsrtQToL1YcPEzRAiMBcw3/+yNZPTEDtXdhWFVdQFijXYDF2ARxFe64eFjiTtMiFI0HteDKMRY7aqBThM1d+/aVOp64RJJlYbhLtQv+xEbkE563wk0r2r9v8aXqT3mv2mkFSI
    admin-user: AgA1eVBoOFeNS8Z+pccqq5Vs/5033QzKakQh2ahmNjM9xZWbCU4JoJ0jkCvOGtWdDT10gkON35sUk/qSi+cYMZSOXoz/Eyh8MbqRGS8IVxx3TYtfTz8Rp0bqXAV13NrWd0/1vBRu8LgAz4gce4A6Dqo7/znA4jeMLynXVxk82JwUkNfEvig967zQWVJ4OQtzntm4H4c1Lj8kS+7irSIPV/vmPbHmqD/ITN7W+XGjlS5qOtXAlArWdSIy2gBvOHIlB/hlQL/gzk72YocnOJ8SyQkgPJwr0N+SKQmv/iwdP1n2TTpCf3gYDe1Jz+0NKjNyebK2gk32ziWJUlJe7rGmYapEBq6xowKCA47OozaYKsYdvXz2Y3pGkxUlq5ndoQiwnIbG6uUTSCC3V8s1v9R4jZjkJE1tT6bzxA2Gt7WIDEg1MeRN4JJQm0av/jjkI07lTKwiJziGnX2yFYgkYRsDwnZvKgJcSYQ1IqlOQDQbUwGFI1SsW8vyhcWq9NkFegX7JCjJ3pYtjhrKte7vIGMavCjhBotNROSfpSYWwGCDW7uS4MdPOMn2VS+jmeTRq7x66NcoNt75m6DTYPGBOXT7ww6zNGSqHuDR90+MelPrMEIWoNUUVDAMh1fJC7i0Yw3wR/QZY2ymiaQEIEVjqYTQjHgrF1AZLSR++doNirfGKY58F8kSjrkd0tB9N0wQ1ExGZ/RB+12tAQ==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
