---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgByPAoaF9xdjTpCZgZ6VaHtHk3Xe09wNndfPKWyQnvLBazgmP1VS2lBQMg9Q3cN0cAPOEXcmvS+jbpDzkdmhrD5Pdh1ioEwtTQLmFPAS9RHRDeMJ38EqSMBFt3uLqhtP2TQNbye0iPYhyWYON9IS6rB+XJ/37vtHwEEPMFowlGvSAG7Ol0vq/z0Ak5ct7w6LOQo7wEINNuolBoJHMagY8UjA9ODnQTh6pdcLTsvajLlPQseNYULEPbRym3vZxx7HAcihdanIIWSYYtRRrcdT+pXJwr3YlhXVKdcpHuLxZGnTqdYZ9xBAN4t+YW1NSKvOFbDcXPaO1GwhOqEWV2Kez/O7oyBoidQHcBP56QIVS8NWNHKo/Uz4p5TmPaPXz7qMKIWn9jr53inQkxAedZR7RqVaVYWQxCfUHUHgBkGult7GUYh+ZZP+HImJYKAnv9ZiEKntb2TMB53YO/aGoYIYKtEAGEctIeD0/New4GlcQdb8yMzw9/67puZzuE21EcZHsjLQ3xeKCMYy7UO8h1evhvNxbPKixUBuN4x+KFD/EAsgiXPkDGL26eiwMDhwkwdHZxibk/a5mtp7X5uAFjugXkWfEXYWyd3THoPMu+2PDA9DjahQ7wX9ExoV66YHiUyUaII6Y3R+bQ0XB5E6Ew7Hn8YxQ2rs9znTlW4N+rMtemAvgzMq/mjmu7iGkevqdPfLyubu2F4ncsz
    admin-user: AgA/3qlREWjZSpxIyPD8FKPjsObYB6C8RghnyOkbnNriYikvofuj2NQb3TFyezR9S50xQLVK/Iih5Eu3T7jg+BGHl1Asd1iN9zBRJqIx541UYfeKJx2aFakkyfDauNPyEjxmdL5v/EEl/007Iyp9OKHEMtLrzz7RFXY5ob0h/WZI8+nHwBJITIFX1kC8EkWjln0XiYDipO97Rswn++E1FBmPmjeCFn+90+iWSDOtQgeoHiuAbYut9F888XBd06L1dGhy8Yk2aU5aOU+p6IGYi3oaezaVTO07u8E4fA1Jo1ZhOXNXzjRIbSMHcFnyQ3PhYRZPkIjwe5Ng6Hkng02GL00QZhfHao7JbUPW5bS5G66ihIz+ZD2AmU1843SgyXpTNPKDriX9ZE1GLtMIzhSmPBH1YkOwgj8P+Cxhp33gP2cTylA1FlPm6wt58c3ZU5MPYNJ2WiKQzVzREy6KRanMj4q7YKPL+JbeeGVLagXbnaKVHIp+ixrfCD8MyWHsXcbc27YnSiA0W5bxDksfyfkukzPrBjS7JP5V8Wy+3Fc+GvL/aNabpwFqs/SeN0M9oj4MbL/fsfIDCzE67NvUviT/c1WQ0gPnfIKpliBccDr5k4dpIZdkYbBRN4yFUJIcPV75Mjpp0OWrY3p+WeXGnX/3969Npzk/Ga+vfTr4MVqnN2XNs7TqB4hIYqjq20B/WqaUErDPb1v94Q==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
