---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgDBt+Houht2YS8iHCRhUAsiwUsR2fO2eAnbNc8XLnzNzykYC5qKby/GDzmj9QvPaODTxEb2S5eSfYJ68/pehE0J8hG+hP9jrKlELHk/RqBY9NSxP5N4HWCh7AWmy30zAM4pidSAkvMvPRErwz60XQaGfb8V1hDh6JvWk44EP6nhEAlQqTQU108hx73oMkcZ/a3BSYNjRiJqh8lilZ7js8uT2q09v+4b/Zw5EUQnnVQuT243zHCMN1TCI+FPUp4SkuiajWwZ/g2OaQNdxj91XPK4BIuR//JREqmMvoOJETfITRbZI5zdHsOMcyD9j9Hmnrhf4NqtTzO+nyBF20iaNYTfvqvqhprdHdbXBrgoSTouCScMcN2a5cTnDtoS61kRTqwNFZZW2sQ0QAqEWciOVJ6ufahk5IopYwxr57SsI/0V+432DRdhVz8t1+mnFISV5sBVfW7EoULLEJws37dp9yGxiT2Kz8450PJ4DpdBnOplWCYzj2yV/Bah3Azv6K1CmUHeIRwssATEu2Hl1gM/mtFvNxfmFu8m2ZM93+3ISOmeBJdEKdFWepVIkE9Mwa8pqENiImlPuoTElFUmFgMU11SwBRq+2emHZ/5QYvujrTuWJTwzBvuFbAbR+qjnXn8xATfp25cNRfRHeyjhzcTw9hJGVbALTzIgQEePw9D0vxDIjddIgcmdPTp98i03axyavmNLQ3Yj5jOu
    client-secret: AgCR/DpIvxVeCJ1ANDXvAOvhv/L0HXtgXvRNAB3drDXS1PwZ+X758pvRtuZb67i+vbNftBwWnoCUHTglLKdDEsM7+RtnZRJbkscRryY5ovuQErMcTb5Q85bsFvgb33dmQvqStEJyRage6cb1d1g+odHQglRYqZ1dnp5wfHxRReyB5GC4/PI9nlNNakirw+2BYY3Xmm1CLsR3Fr+Vn+uAEcrX+0kb3YgATOrcGj74DGmMsReEXZIjax3ZYox7YOSXB1ZFCnSgWOJX7K5VwQ0VxNCHPMWcThqunNH0H/AHzoQu0WmpIDyEdomFefXm7Pu9WF/Q0bnFfEWqrzlE6MYnRobSQUeZ448ULChJUhqE4vfTDl5lAgMilKP3qxNQHOU95LFMmduVJgz4ROO78N9YglQvKI1VPQok0tlb5pdZ3jjAPrHAXP7fsT1P+NaTD21jRlZ1fdJln8vGjXVGB1lpD9sbo0DtTw6aKZWcwJBHT8JfpSMSB02U/Kn/T1zSklvlTYz4ggJ03MqbqCForMtgYOBcq3Ajng03u6+aayYIS/at5aOoSnY1RpzH3ZFKpiT+gMUZegrwLGoFWrqWSJ+nru+UznAKwkC245+y9mWkVrzwwd9X/QayB0heXcFjMjP6Xb3Myda+F7SZ2EaTo1E5yml5XGtsb5SRx8uWzUruOobnhwNG1zFRH3/HOHeSV14lj6m2U0VLC+R3WcEQhAKjVRBYKSqlrbD8YCGmJWKXYt6GQQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
