---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgB/HzP3Thg5MWWHGd4p5v0c7TCUKkpLbiNvyiWrH4dwrRoZTlfUY3elBwRP6Y3NbvTw8W0Bwrr0fBecXBjD3mmpI/55+/YlKMnn5D6tG/LKQL3zNBRNE94ErAjT2SxXvyA25ibFjyXxFIiX4+x35xnQtCzRKS52f8YysrK6trs320jSZrHPj1EnEtBw6y0V0ygOPNWD0XyoUTJbBbNMqYXPrhbjtZnnTJ0UEmkMGeoibAtbUK7VCz9Jvasz4bg9UI6903PMICJI0X+suiBd1rcHtm1mCkSbIVGYKPGXYY15B7p6+IrE6w+thfwXjEW5QUuwsywiBm+KE48PG7xrPh9AE4LaqgEsCpMKpNTGmxs5n6YzPIvTGf3AOLaxdm7hjWteoj99P+WXztj+BFVvDIaOkkHmwhY0v7vVGBjUosJG4/qmQzoeiQuwlqJse5E+yWutsmWDRKBUPvoO6OfFxKhmjnhFVX0sC8ywgVwl7oCynEsAJhgsrq8e2IYR3IFaeA9yqlDdDebNr5e83UCSGu6D9rac6PvpsBLcb1dGvwWUH98TAcGA+Rkm69yREwRxSfRPtvsLhVNJ2CQwJB1ac0N5NEqpIMII4kINd3f7jmwX+RSfv8K2wcBx/wBUKWGAwTrBGcYOp9Dl+YHUl1do92g8J3f+n/vvEXT/XYWMDXSDHJ9LPllYLK1a8r53RnebBM8tjM3UO4Aw
    admin-user: AgAJxe64SuZwyuuahsVsNxZrJc0w3I6/KR1+QEBYFZOpWz9BXCtAx+YWbVY9v2xTu+Oqp7gQPcKrV66aq/2COKCFj4KUKMrjtJjO7qWT+j55ilYlZOQc3Ud1GuD/LUUyw7+iuGriQkGLmvASiCzZ8kZ0d4AGOD8FQyybbcDY3Hl+wldnY3VbPU4MiJbIzUV3N1IOEkOZyivNZRD9d+KvdLvW6MkmsZuMK6O7vaHS0GtyfgH68o1Qhy05sByiGSSZijkK1yZKD6u/1DecWaYovqS0EDGW+VUB26Y9ly6s6Gpc1XzWENLYd1r+RGMfVerQtZC2AgQtpcFz403EYmth1jJWHTmOOEd9ZOugOb/KSZu78AWJKlYYI/3D7FzELsdykMw41WaDEbBCibCZp4r7JhESmTp8GUI32bpHAs3qBeZMJEH3jkbNrqGRTucDvKx/KLiKMvAaGbiITfMF+78mC1yn66tEUpo1H7gZaIWfQXuvJd5PTnHxgxVfh4x6nnj8Y0pxHbAYrU0D9I4z+gJFXi1UVa8cwlmJ+xDzF9RxJasTRWDJd9N2420RxD378JH0UxU7vlcUExDKhjLPWxp8+t0AWeClzlBguqavWo7to4H0d9o57dRu1Jf1+DrQLYchDp2jV8UlLd/FY+YXlN3V6+eBi+pIg51K1nX6GHc5BZRiCVUtk9a/4YQHRxRwZu4WxkXTooYUnA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
