---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBlLxNxPydRIh/2Fx3Wg552H4JFYu2dv5y1hdaC7r5Prx9YLqUePpTUBdbkjzroiStUxOKlg0TJhI+vmq174dYaMbdAYupSpWuijjVzazcgfQJE50pj0Ic3DZWvtG2lR65w+udm31GGshywAcmLdKrqHQsN3O49S41kStznF3mSJ76Ga/cNIFPIF9nY+7YyAsnjmqwkxkmvj2S1igKZ+1olAxlFOBmXbDAgauqvNfyFBwR5AxUW2PvGd6Rqrq6mAQ/8UXktklzXoiVA/Y80FIeZB5ZGXjUlZuk+GR6GVJyT7vpaY68TB9Ay6FD6mOInOwUc0cLq5GbCzFLiv3dJYRksKs0zUrkOEq/NKOTPNi7zAynSNncRd/pIDK70K6iuYkdredra2DbADhX1LQRgFifeYWnJrJrnqwkd2PzmWXWT3rQWVD8d4UfNFsIjgAz85YquM8ZHvVj11xPGxbASkNTywnCq/3Q1GlZcD211XoND3Hy6zPZpzCF2IHqmeemQ6repOb22FeNbHvV4pgtjtFC/MqooKAA90XevZVCyIQ0KViTbBCG49pue5fi6IudNkl4ytyLnIu4cPshxRpB8NWQniSR4Ulp7nA39DbVvI/NhTqKxUFYBppfkunwVAAYdNGjmrMbyPIgTq7G2/ePTa27kCuIcqiOcdBmQbdYedZXLiqGjWPR/xBDGUTi8e25UmdsGjyPOmzql
    client-secret: AgC/j2yHfZ7WcemFTSMa+w4gBjEWtX/bqpFeS2EEaEMKSvY6tBMcAFVotnAs747rqZvdF3rJMPRgTRV6FDzvMr4QX8VTr+r+8OAeaZnMBz3Hlxb/CBnRYbkOfSk/DDIbjsb5GVP44dwoljdzQqHKKpGrFIi99LswyZzY2uWcCtaFZ0GLgCjT5ry6JjWxugtSGLCcUaIBQy1/nD7fqkuc303klmEybNsTaH8K47Um1tWV9UZvwRlG8/vlPVdfwXtCEIzPiQ8kB57VGIT2a5Q8rXxH1sTIRyq+9ggBKSPggd+qiQy1pDxTAxRBtl3mc2CnhI5Xzknqwsu59E8izEbO1FZz6uX3XjkVfXu3tmA4PVbS8P1iB5Cz31du9HjSHcycbyVHTX2wcTkaer9jFKQKX4wZhs7YwzQW5J8cLUUOuE1ExC45IcYugS9SGamXW0nBRWfHrNNBlfVJL9Vlc18SM+2SQOriU4JTqhy0oeXa4IukQ0Of+0aZyPjK1zIq8R5ntMuEyi4e4caHsCTWHJV6jtGcRrbaWycL8YPYSA1jFH2m8oqMee9HPDsKcsv5/ZVCnLBJKTItV6CJvpON/aZIA9eWdy3oGn5v3gMcsRyUXgcBImcw3UBSj+Irc2Zw7mqqN0puU7nH1EgGMY/KZZ6brkWZjgno+pIV0WZnEK2idPrNGLL2cyulKfc7Kii8rzFvy+ATxQ2AwjZyToGSU8IBwd+KdJ64jSfqBnj1hcldsRhL/Q==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
