---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAuMcwNZbS5MznjFWLUi83BjXbVj9EBIml1CtuFTOxgpRwPSimh1UdHVX1A/cBzzs8Xn0Jk7YSgy6v6b7msDMiPK36PU+29IuHYjRurlAPCE3P5QDFM05AFsZs6etrkNrztFnjohbibUq+ar4xARKgHOD9ovz2Vfs12MUXDD8zBmJ0uodv06nqXSCLnmLLJwH3266obUTnOb4l67ze9S08EyXvmzil77SeWDgJxvP+NH/EZxrHFEtF7/cOhxqqaFYvJH+SqjhemoVxUlABMsxorA9RHCJOZ2UWyd7o/o/3LS0wQjPKc9eBkDqOgfO5PnbrhzNa3MvrtpnGC8bMxpD5Wsd+WlXjJ0WB23aTOxIvMcbBcql/aiQBPUi0QZaL0GGIBKu1ppBdBiyLj6ntf87uQvTIJ+PWzOevuGv71NGi9+d3DNiOL9kAGefuBxi3SZ5SxgsKzuDB6a32rLW7uoGW0njLckJnmSGdG5yunIMYJqkHFcYd0UZmiKKdu3SIkqzyrbgJ2cNms1LYR6VZ83lpxvac83PzXy9hwNR9vmO4Z/XBTYOcrOf7keRc0u++zK5l9KGESMQOMmMcKSSMzdb1237FcoBV5MTasA6vY+ydP5ujPRqEH90Gq9xzG/u3QK+zr9MTFMr9hYq0tJ2wh7UwAgem6G1pTTKXLExCZf0uouzrAf5xMJ8WX3W+Pelsh2HmTk8EO3Pjv
    admin-user: AgAw0uIndHuo8MFx7qhxxwheYgJQqDbuZsfLOXoxahNM3ThDMHiAkiaDAX8s8ejosC4p4dN0aChlXSUp+NL+Ni19OTPy4G4Lwd4QOBkvcM9iXx4t/Xw6sqXZLjAwo3V8zgFtCpPzRQKOo6i4PZlIdKnxeUi5WxcjpnpyG3SPmrpN7DenfBZ8xbn8UhAYfZUyL1k7511Nd6lawMqNzqClC5KQ/loSUffSLyR/y/3VD7XRWqlmrwNBrqZ/McQSBpCm9o/MSt1Pwi43fqe9iWLaU8ZqhEsdGJP5DohWOBfdzaWq7AceBMGbzOsIgAHUnse8pT57Ih2d98aucS+MXACL9ppGsf46QgbspkI/f++rIfZOUTVJbEhJPNjs0tlypd9KTX10iBM0UNRZWEHvik+0ncDSW5uJeYKIMGImqjXyovmnl1PdOkmy8+tywqlnfGntoakBqpMcYaDdDo5jVbA3nhyBTM+R9JuCX64CWAOg8SzgyNKOhQWykJ/oKI/c3ozezyLodU0OliCcMlSTtmQXpfXTVzpm5z5jhcCACuaYPnHbCLG60OiJSAgXNOCkQuVAPYG/SyIdjwIFhe393CHK9NcqKwcStykl5am6qX4z16559JS6epYJY/yal1TCqTYbdXCHKyhI0JYZR58tQ0+JXWcWoPPqq4lY0IXBrnW/eWxDeLXe1acI0r6gXAFFQ24VzbQzV0MwSQ==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
