---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAfJgRaPcIl0qsuHwo9/HoFnKyvH+Xj1hsuKfJgKTFpxG9AV/ARvpwg4Ie2HauRb86BOB9AQTxWF+fFGhdQ8FQmYrzkSqkBEgBC/mlgBfC6A4nxXCmo4pcNOrqxQ/+jGxZxitI17ojsxCF9KXRSmJCOQxERAhjDmP2U//9xh3OfDGgT/KiYZY549Gr9dIbwcyhBHkPyN8MG3agqr9FoQKmszIyyO5bj+cRGxasbLltSZYJpye+8oAEt4cPOd2685QR/6Lu80g0vtrhnCimj3YYqj4IeDS2czrtvmD4PksAFFmJFLd6vnpZ5XlYW63pB3NQd5XmCKml+tzN53lWqWwWwZEigQzH3rJIsPMWHZ4q3fniap7LBBfZkXbDmFhKJ2HyAfw20fq6roW0eqOEAq4wtmkKLf2fn6UtmAQhqCZdmfyG1zJeYQquMa4/UsXQqyFhU/SWVhwmNFtSIVfX/YSe/pmE3/xcP4AxcJhfiNFfiO47lhO2OR6GGhZ0+KUyYRpObqRr8oYjgTHsJOurPSvC+Z58gGdgFwZ7HC35cg1JOl5YmOpuE9Q62bQFnO15pQUnVF8KYi1uHs/kfxRcUYMdqM0i+AjIRCMrouPOQ7BkooQmt7tEmIo9SYkMAmoMkhe39hM93HsLl9M1Vv1O1YgZUKepvHkCZBvRZe9412gQWkPwgedECh6AkNCvhYl88GKWtaqjHn6UZ
    client-secret: AgCZ9bdVAMebcUPPTjwj+eofZEFIugNxo+ftYwx7Ao60FgQPS2Z+ZJmcv/QWSMZUvLRVzz/dzztILPfE9nvPdQ9r3hH0dE68gD5xYJTlFS1/05H3wcCXzdRSw3vjhLhZwyej51rxw8cLjnsnRedSxIxT49W1Mz5X6BLc2XsaoGlY0ySMmpy7PrSKgwu752Mv7pfbSIJyPfY2non/hM+WU8ioMgSIm+Rk+GQmFuIsdsZ/+gKaLbuja+RtNxSZ+Jl+mVvduruNJFj1eJWS9d61nUOGfkxGScdxHaHAbcYHFQwHekr5JtbQ6leiEjmOOFPUm+Qgn1OvlH/FOU0/68Qkm61T37vOyMNrp9OOl2O5b+v6AU+BNryk2pkbABp/qdZskWf75eFLJ99Pv5l5zrCZGlLvbaleLYht2KFDMqRW7AifvC/Qpea9/Z+Y7SUz566Ud6C4fcmlJxSQsWA2ht1mlg/rdSqEBVD4vfQiJwyD3NVhzLg/H1yNc6+ecMQ2a0DNAvDYYDDMeHm7fONlOFfo3KBnEW1sfboCHaDQ9Pg4MvnsbuyRtTxdrXMK2BTsY7UI/hEvmbLe8EcGn8+zJrVqKWyxLsu6GSmYEeGcO3qUu8HjSIBW5OcHZfg83kEjWC7U8XuU56T1X2hb5Xg055xx2OiuE24/mnr1QB5Vr+V5ii5TRhbL8R2xxh6Qr8T4Du4RGkLTL85AQFJiy//ab1tlLttGtuhhYB6lkGK+Tajv4lvFgQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
