---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgB6fFl/U2N3uMrM+pb2IhVRILDU+J6f8XHx9a6FtluKgcraJevzHdYjom5auCmOII/T0ZVkdX6SpjEZDQSsXDYNo+fADiE3ydIEqafhHuyohsWLiFLYxlVXZJX5iYoi5TCI0kLh4q0UOmWVZL0jtloovNSH1U0gcNIOcdpiQvn6faQBkqlxz+HQt6BB5H9PWONPQ9BPBqs6b6gcbsGHR+v+51levmaQKfFphHJ9YMyWs0Z1JgPL8zfEIcV9nOLuEoacUiRs3iJdyCKG7PN9rGRNgbaS6fS/kiu2ybae3TvyfdidHLDYJwWn7+55Ip6X5PzzOOWSO/fflxTvhQoeDxnX0A5r1r8tq+E+IMoNkBSWgTlP0053ayR2uHYxkEsndhQRxqBDImUuv0wDDBUHfQ2grLtlhDzfm+rjaLQ/bFBS3bRhPwgIS887oxWwnCKgndWw9zAzR7r+AkzkA6crovDRj6qKMQYjCe1uuEO/Z4rgX8nKHmQI96lGPQVYFTV/kUgMjgHkXIY/w7mEFHnEu6h4hQfbKCuER9LypM/Q/w7CvPf6Q4mATwzO6Gy4DR7MriSxMPNhffFyFn9GtUt/1NeLpThM/D9xqsda9wQSW8AI7jps1HESMiy39rdvdYykWsiQZ7wcDYua/liy4rZ0/mE/J1Sm3Gduc2VqJG2T7IQgz1N2rk9Bko9YLInPAqgcsMIdxh/hKhlL
    client-secret: AgA3wP01p73oAc96yd9GwVzOzS4mO5YpnLOASfxiRDE0K78A/jb+a4PImdW1lnPlA36khR22NeyTtKLloHEqp2MHjEQRY86FssWqgV6l4XCqAb+43ymt68a/LZgMOAt41j+JO3SS5n4abaiMA0nAAW6XvOJwbK6thfoNBoU8fFh5c/ibjudTZIxk1nszrODD6WBHyqOhGSngkJZ+5KwlRdjjT+QRYsTKpqHQTJNz+hYt9WoASxBNKqk+n0//4QtcVFw7A35pDkm7+lPOq0oWY4ppyFTjufU0EES1auKDRm7mUp7rOixRlQV+9oE8W0fNeHWzJchO/2FGtzSf/jda/Rh0kabWTgZqmXQSBaDiYY0VgRa6GyMf/SRncnaNU81P7A1vP1pFRtWB4rXxTXnnUt/YgoaAlG+SJ4f7NSWmvZJrGmcAfeW69c485FOXg24AZDdQUQK1ksONML9i6dxRpuxVXorviUg0BqDqxxNTf94QbB/TmA+8Kjr04H4l06zy1cPozrHQ1IEIa468Th/W57+oLnDlJT/AR+c7QYV++ezUXlFsSdXnVyqYkHYX9ll030rkHMqgEYI/aqXyxgFXBg+WPsWRnE/fa9eOazAbql5amY6e1sqPfNJz2lJmcI8W0htizXP49GzGmC90pKsG1WEVRC2OkpAetGbhn3KYXXY55mtUVaUwzoTpJaw53YRn7yjDCSl/0gCgnuvKh6yWR70yeSPTwu+7/xDX2N5EfO+lZQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
