---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgC1Xtw2S0wPML45T0sq0RkEldDytLGEhUrJ+HM9E9oU1ibNo53UYFjfoSyfPGfgaLXTXgrNws1cnVetNsySP1UcW9A+P5aex/lYiP5EHz7rEv7zsK1mxR+VSOS5j+FT8I0adDccW0w8DqzfT84xlG+5P9yKplAQbyWPhV/vqJGI3yEA3N8+oedjN0bB2NfackUX8ma3+uzWsLqSB0Rcvo3XsS48mDjTCzhA0NG4uyFIrcVBsXpvryA1Qis2LC3Aj6kpZ6Q0YeiDfOBsedw8X7HQVEYgqnGPpg1C2xxQOwhDFfbP/aet1kP/9X2U9pfIWrgcsgX56DU5Y4vx4Ih3J3NRCPNabqwpZEodzV96WqCWCWJSCwmEIBReIfUgRqvyrbtE2jaZQUK3AtBT1rmI0bC9Wgnn2df3BhWZHSp60W0A8AknwP5QYQiDvrJby1Hgql12rZofVcJvP6egzz7DSJV7huvTeYG/pxPeZSOToAh4wNJ10ZVEstwne5hXIj1yVibol8ZVuvd45UhfgYaDYbqWzlIT5Rnp5aIPvj+FdkEY/a/Wf8Igy8nsO01Ea7mj9kwSvYbWTCfeB7CET4cAzsxExjuEy2LY0Ol49nuXWBiHG7tGOBV8Jgb49kCiQPTruqp86HWqonJygsPi4xU54IYkgoCV+uRDFIalynpkUTsadc8IUMWOpsChGosdjgkKfGvlYuuaH2Ih
    admin-user: AgCW7nkCt9FLbp5gOmjrl7TLLhNDyOuik5xwbpcVH4yI5M1NAFI+TSu7ka2Cf8P5IaZSr+dXAM9XZM8biPKjXZkf8M04m6A1y4v82uQubAm7hkewGzqCCaZAu/TowxHEHke/UqLQblNHCGdK4hCljTgux18Cdx4QtbOCSAUVZaKXN6aUCcaPO6z+0Ey5563mczakFJ20yZRvmqByg/PQwoRqntTqdyt7m/UG+9tlP/NZgvuoNsRLMYmE+VQy/pcAVEaom16/9uQBa99X5C9NlOOFpSWP5wCgISh8brmcUDObZH0VvQs5hOT/fuImPdGlhBWeZ5RvLnPoH2HqH7u203ESRrxczkDAXDnoIpIMb63rRR5AkGmxHrlvvV4O9sbSv56QG6EfWXaIfQPkKYqbHPuX4s21yHlAfBPsm+q/Ii/g3KPywSBVTy0thYVx+y4bsyQKolDhlttmL3e+1tgoFjzp5uBhTET3WFloaMh3tvHO4l+A8jznXmXr11SCwpgGanz1/5elInDvxjhWnOLsWY/92mwG/8mPECbOURbw+drRG3rueLvMjLLiMJ49wALaqu+HZVrtjlI5wgWdXuTS38B2ObeSOqgyD84LBvRp8TWBGHcwgVIueNzRVx6mfsBhGcyV5AETX3PNkJleyLo5h6xWb6p5njk8YIh+pvHYnbzq5HDj1IbuT77TKZawG9AKnuS2wX9M7g==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
