---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBdm2C25JhjAPITi5IOo/eAha8KAJGsNh7UfvRDzUw0g/JTcxgdW0HXfUIXTvoRUAVBocCebJ16yrdukA9A1l5OKAKH1Ycfyuham9xa77Y3BlLRBjXsRC6sSJ18uit2xrwYZoZBO7LZzARJZPgJSOTynqYGYRcCxQr5My0Aea6s9k0PZSmuanxWn8qMkIFPlqvk7KY4w/vOK/LsKiSOmeZUI299PtonJ7xyLizzwMyzGxFi3o1zJfWOeFs2ZfqsMyGEQiDk+qckgXJJXCWUc64hNfd2p2LUNMev/FkbT7sJ0yO+59LyDuDfHxsTkmFajFmyHUV63ctMEBsn94gD96iwG6oDrOYTlLX0IQy2PO2Tdrg+7rT3WbHbBCsmR0Z9QUmWdxFSZ19+JLIb2msJ2RprsZZHyX5e78Z3li/uj3EuGqbKWG8gWqZbNowxfwN7nojGeGnjG7t8lSx4BeJWh7ncLicwuvO2JTyoG39GRmTUV/Yh9HO6vkz2gOl2HO80L191Ap24HQkgEGs3lDWwCiWuLRoPKpAeL7mOg8uWY+gC5HLe2/oCnGIFuhdztFw3vYS3rzniBgrXL2+oIZZPAjISQQ0S1H9q0vaSseERSZN6Ty8/AW97bwpeUJJNInJ3MQk+EHqXqeDkg0VtS0VKWEjmTjfzn7gnoNuom1+gLd+lRCOuU0VjDaJvxsaxkIIXi8uKI3t/4X2f
    admin-user: AgCvJCz/bMkAqpbNyDfbH23l6A431t2XWDL0VQvJVZRdSOraOHemk4t9S3S+7j36HUQTKxeEKIdFOJ2wJSPSpnEry/RUEmTa4eURACslAeWZWM/LHlN6KsnHoxUD+zFeluKNHQmutaBnm0LDaNW2jfCip/XzcfsihKR+8Olajdq2uvHZICds17s6i6Lu8pCPnL+9VoTNCmvgr2Lb5fnVr9qcGHeDiV2fN4BrnTQs8ZcgDjP4MK2uDIvX4U9l3VutdZF9bPutcJDB1+U9b9tM6EBmtZdOGc+ZGokWwyGG5kSF2cnB1WI4SuqYp3024wnQqKNpHRURiyNcatXlEslHB+i79Cg0EgmVxJMRbWohkg0hPY8XOATamcE2xiJNENiix1Obo5HOe2f7+QKEZtb6mZEztkUTouJrkqYdqpa7+NeKjBZzid9CfWOn0gsDEAhE1rvvaNff2qW/zMkmXO3VCfuJM0efs/Kib0DXd9TVn8qggJ6iCRbK2bhmX8GeBE5/zn7EH18ipFSmPaNMNNPmKzoee4dZBta6P7G275/C5piqLaHDwcGQ4fdyjH3QU0uVReNPBXlrwMRbUhEzqVKP+5Xo60mAg++S5gdRQwAOGb1jramQk+KHwTxRCwNWuVWN3lKV8jBDDfWAjIn9y+fq/of4JAh5PJmTKyNR0+CBdKvgF31IbGkda9dpQr/3tJyGKYtjp2K0xQ==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
