---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgC7oZb0ihenu6oNuWZNJ9JOAvONvEgzReOcEkBJURdQURYNtY3BcOmkQ+9GD58tAbbQjQF0PAi29zZcbJpi3QJYOOvVitHyn2gHUNmlMHxaFOXB0pFulHHWDdfTDcM938rJJ0usv4847SHAPkOKeEghdiidz7WpiLELcn79o/GQES1+6lNtfV0Q+fWgWDLnZZylUABQzFQOcOjDzed0ewzsoBaNWHDDB0PtRH90tqLgx1NjOXtcHkqYor8wooMKTdAYkYVEx6Aysk9cGxT/THAQBi6tqXEz/4RgKtc3vh5Gm1UwQZdT4/uhGXa1DJFNCc269Ha0K8/DH1SVWYZ004jHU2tvkNYksNg8J7FFriGWgy/HCmjXidJdJcuYDEFJxB8Ff2G77dbX/+AvifVSuZYSSg7fRmv0xqwmZ6/wbXBBDdJ0HrKkPJnQQKNGLe2qe6C0BwWkNSz4aTM0QXvvnwEyz+6SJ+0/oeyMOEddDPJyqkFCZM2LtWf94IXevDjgARH/ATSHEO4c5HWMIf5t8A8c28pJocEiT2SwOtWoz2jIFPDUBLT7/KOXsKHO0MpjvMay5o9K/tAv7kqCnXD5hEWxBje8Rc8gC9Q554yCt6qG9Jsto1hB1wBpcOuYztaf+un6lEViGaYU2I0NijOqXWJvZ4rK0Mjb6SLCWPfV1gAnu2z5MhCDv8Wv4DUTN5mZ0DmViF+vueAx
    admin-user: AgBB8dIdqbAki5+N+oX1GyfSe5wVgmDszaMGgBM2ygw91p67S8bUwa+d5VUMvVejmZTrTs7LEuX+H/f+XpfqriNPSSYVDMPJBCPHZs6ARxVnSxzLtxQViI+kvAgz7cuZtiQ/Ox9LK7e2dJyedJLJdON+AmYHIqrVt8RfnUoLraptDAv87j82J0QrCI1JxP6vn1G0OsECKV3IxKSzqUICWtqs4MWqD5LDRKrPec794TM5Z0cd7txn00Ju+LexNoX8N1njmJcA/YxpCA1HeEOMcyzqimyeLnyn71cCTnv2n24ReKhCz01Df2MqTkSFz/qlyQS/HOQE8qlx+5//Wr4U1F7EBReF7eGjqTOia47CvF1CvKo0QE8M9CelAJZjpZ/Aal1sndQqrq2C0/cMXQY09Z5MzS1JiK1HpRjXJJROlGhCgpp/VJRo7OHivAw+1suu9BANj/C7gHTIWIMmjYe9r2EKCreLNkE21JiZBHrdcTuezOhHjVyRmm1dxkUNToY3jQ5uKR+Qbh7l8dCWJsNc9I1vUpmyYa86JQr5ucOzTthv5m0ayXviKT5v8AeXXv4ga4mHEXW8MlFM7G00KOmtQaZkHKwD/Cjxe8upJsxLqpJ/oAoi/B/31d2kt3HiV7vUUKpQcqXpUL3/kpuY5zYIQgOIK0ZcY9F47knWxeJm0rxHLt6GCoyNc/PdRGWlHiPdnvGWNmg9qg==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
