---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCmuPWJ+zZ+ZYfD02IIbRsgZYPFBLomb2wxfj6JClgE4JZl6Bes76x2+f7M5GjMiZEQOv+vUBnIpIvExcwHhfLiSAwQnFuvfSgilKiv33nqggWuTdEqbCsGyZhhbfjOGkXq25PKLjJtHu/M3NPyHwHj1ahbXzU+e9XeVvPFKJxcyyXVOzvHFsEc4MYDQ8zvlADuh05IEINu4E6FWwNuR5ENJ0c9APClB2N2Yr5zzRKkefKpVhIjR+jXS1Re9FFfewix0OTTAcSm0n14NoNsEjGA0vMRqYPWHt/kMIMcbRUaFRRzBeW9+xfvlt9ZAyOdifNY2fqZ+tFh3880grmOap9bTtI1GZBdkKTEwJltsLjfG2Gz+4KgSxio6R6s7DK3IExBT8lUnA40DUPhAIb8dVac6J9djdQV51VGRrpRFhIB97CPYk0v/DO+jKH/OK7jqyYRzuRejfuYufGB207Ve8H+CSczlMEQ5s9ioDPOpHM6Vi7+dOcC9dglcfUn1CV9H88lW9i8/jHzSnlV3F6rGlKokoidykgp4fJn4pk1nHCgHSR1dqRuzwFnwUySw40xfYgszKexyN13MzYROEKVaxOWYSzaBPEJfCKbk0E46RUQVL0fU8HVCABxEBYiILo11dF8v0F43SM1lzPjLOtj0jb/GyErRies3lT9wDm5Fi72iWeibo0xAkJKpfRCo3MIYB0tz5iqeeg4
    client-secret: AgBFok+n/Prpt3b96QOKljbhi6AuMbr2/iBWUCGVKjUCAr+hJErhE6+/INbEqzD4mEDnABoulJEOFnDeLzcfnVl4t2i8ObWPNKnkzwquP0Nzu3vxk+OKPqJw+qeJ/+CU8UakSZQM6CGtkcGmCJKd87gF/fXCHPEq/+CwsOiDf5yGcm48tlFCLVzoVTDBNc3VO5kahRVJlEKINr1VHxul98kSpyr0++v3Gnql+qh/9Ur0YafleDGvf9q+7x55qcspcAh5jyhcojGoVEYMDCppkrELO1XbG+dzaMAJXxTssICJGLQHpcTOnSmK+twm/V6GJe0LxVLdMJPFUc7Hc/1s8rpC1RSxoEQoq+RF1XTYfqBciMM264xTtfLfEOmtbH2fn2Chcx8O7zPAPZVSWxi0HE1Hb8xMCMEfG9/htUNHTueKY5zD9f+53WVrqz7odiQnFHO+h6+m+n/i9ryd0cFO5TNBOevyIVFWcsxED6FV/tDFiu0zI0bo6vPM0TSR1kHxJYBG9dGRui7kLwhop3Y0VRbuuKT0yJ1WQ7W4YififH3qImzAQsAFBRtILDqLasv1hYdJKQHpNJLKfTqA8TlK6vE3eR77djCourPKklqEGrwrxiD+LQj4XPO5lorOi2lrXWXpoK7nEbKn51V9xMO92UFlwr0xzk96KlxAJtG8icx5aKU2YSFCVX3TqSk7N4Tg0mxsoCtuI0KtdpOuGHDJDRG9mLtg2mCBH36ASy+EReiqrg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
