---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgACMcmraNkwwOWmvfddNmZhhemUYVHuioqBH6EXUONSPZRmc1CCxwpX2gMzOyNBiwczNYa7H5yphsfGIIAoBvRsQpgC2G6tbZeXANeoF4m031CI8218qz2IsI7JaGs8OOitfFUQhbaxGa2f4rJ7wuw9U5+e9UxfDSnqR/ykN8l5Kmokcn1j65Kqg1kbZ9S86MzD/HJTxkEc8Q07FY1xKPXDsp8rPpv1pQBPoThcdz7dZLIBGNCLapPB/6dFwlZ0zsrt40rFlj2r+J31ttu7zAnEvuxBCr7Z+M+eyc/IjtRin/XrGlozXt42qJ40pucxHHOOmemetmFGQMaJlRDngSyeBxfVCiH3oQpgYMj9sHUTw3SkfW5t6SgReke+zEC4Gx+dnET+kZQkB1o3niZW9UBahcO3wK5YvXWZfjuNfCfvedERGnDIy2uwFIP+hkC8ZDEsnxXmrDlTgTHIJQ0CZsPvUEYXgG5sw/ZYTEhAxnpripIFsFKtKfLm4JhJa5jPeFWd2KZCAzUQEqlJfE3K7PeTaGA78Zu6kei6p0+zeDzB6ztixa73oMII6CfZ8JayM/QeF/mB+svNDBHwibiY/U8nVPvemHcETIJt84cO4FngTUhlcDDJbWW5IbPYVc2C0+GcWz6pL8k0hTj4dtmRyR4S6nWP4KSfAhn5i6HqWWNxLbtYJZKx0ClVXpgwAqhchwMG1wTDaOsk
    admin-user: AgA/fiwixB5F+LUyVu/yjpsGeKn7udm8GDMildrPXreZrU+5EhfMtU53mGP5oonBnwFLe7R/+HCSA8FiiAM6v6dswuDKw2GAA7j3Jfm0LH3V7EAb7klwNcKcqaXFYe0ylsQ4Bx/0C5qoV/CnozS+W2F+Q5FnjETPf/ylxgWwnubfqE/3NEHKbug8p5VM01VihStFdqWe0LcYJUN2V33WgB1R9aVNhIdqD5JStpb1Vo9fgSNF4nYMcdAU2rWk7T/wlOxGMFV51kyqXcsxHHgFl8AcMPlIyqq7QqoEBcELyHb+iOcP3Ne7IzVQhUWDEePFgi330+i6LsQnhsAxIy9EcMkhmk2eJMFnaRwvS+4PKkGcat1b8TezHGchoHSdvTCPAPZY+JK362j1QVmQPcK0dovbIK8d/e4pOnn51HQRXCOx5NjX+tLJujBeqRpQ3ph3Mn33wfDGx42PDyORz7mqrHU+vE24HgPFTM3jNEf4BrMum2WQR3T6fAup35nZtLE9k3TxBfBvBq/JMlwOFm2/1NtndyLR/h+BmYsHOJgvX/br9KoTlb862xhn+yzWiX6AJHuXaWgz3C3ZQqNmMl4wann4JiikyexFbdVygiK8Nip8xyzYq8dGPcmooqoHuH/R8T8aUDyzrKD0UJnE5ZzgJU43oasCmpqH8bqotusQaC++DEj316ZCK4EpMIBC6Rw6jd94ydbakg==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
