---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgB3V+Ix+oKds02pIMl2hFKzTIgTIYUP3ZHa7Amy5fs9Swikl2zJPbMLT4QHGgdujiNcoR71zHRIzJezXKu9PfvTOb5Jbv4w9tro86o+2NFahiHpHD+jh84Z9ieBWmPozt7J6jvZGIQ53rOM3JUGOB0gIYCu+K7TdKBuFFPmD5IQ2swrDFMhnxnjJssxut4IqEeBV3LaFQVc0j+KGfqrD4nd0On4BIW7YXYxqkYnsGoeOx8MKAzX+k1jafZBFjUjSkf5ZH2p5n3BvN0mnxVwL1nUQG6SgrHsPB5jwcVLwlPsjwFsXFtoOb+NEYL28U0gPxFInAW5p4MHL5Cfods1CutYM3DQdGuKpb36Xb+2MJlxcrfBYI5UVDQDb+IiDKbjtFvcowyBCWfZ23ok96WOKJQ8TWHxbHsIV5URSg1bxJyqvquJHDyNPJrYmeELzvWzVaBrn81bv9eGs9AlXEbynw2ONf5OlN/pFdbvnE7EarojfFFFGu21OSskItc1Q7D3w6Q/IuuCXjZWnH20J1NUw+M2qFHt4wIMsqN4vDBZamUZm0ZgN8HwTPIP/6dpWHNebuIkTLknxgJLxExaFEQw+OjaMpUNUb0kcG6suItOxWiuNH95wtQke0Jtvvd9HfP5vzwVHTPG6rmAdLhdsRT+CYYxi+EMO2iZHkffvH3nA368360NF0MNnIeqbTRPTKx5XC8SZgq1gf8J
    client-secret: AgBGaiKI2X5FrgVgGaXfO7laTiAqvpxDgZaD2503NJ9ncnV71Bwn5fpQZK2F2HfJaUGOo6mamdPffLYCyyHkffNsIwcOb8nh8KXiXuA8We47ag9M3mHwzRWp/Gc1KI+PkRhAqkWO5F7SdwpedkuRBUhNyahR9WEJJue6BJBCcV1hhokL9BTMbV7wIkSdE5SaQ0IhCyCsfcFErICE8U4zXs153kWl+SIRCvvPsCC++KzzaJUkIY+Lf+RiEBH0wcaNIFnn4AB6jdaQs/c6roE0wL9MXm7j/8UmiwPHIR1BXOQyVm75OsUZ5X4x2EtbbnyDEqzEkR6JrkbeyBkNq5ZhIgJgfzTZ9+S95A6o0iWM9j3yN0mRK5dsQSmgDpIqUYDA8mZlEruT0t0S1iDQy2XylBKlM31ghwZJLoiLOgcUaDv+NKg8yl9ftceEKF9gxqaVtof97D5GI9MVCLwfxNvYs5BXe3YcR88Ev+Hu3/8Juazk9h+RwA0Ihlb8js5ocaaAHXCJn2hL7q7KSC/I3YJZ328i0i1tsElrkKhjQFlvn4G5Fd0pCPAXU2WYqSrJ4dg+cUc9MyTK1zMdTd1+k39Eg0nywnZQWPhtE6xYE+qyJVxqDc4iY2rwBwCGIa9m8zUM7Dzpz/T849M6MbLp1q48hm/tyN840pWeLdJVcdkX615VKONSYogHz3gJGTRX6HYSX+441OFI5S6aOBY+FD0DiA6QkUa7ZZkBYYDHobC9rBfSAA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
