---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAksgNrOBqZ6PgQFZxKdRU5fJdmAznxglMWqqpOlwiLjsFEoSDDHV8fDQYcaA4INI4T3RsKTkI/H7zF1GoenLWMt6uzQFEQ/HCNk/zw6aSjQmBxVXl6+NI3gM9wClnYR11BzjkzlkCry3mjx+qoB6W8ZsmlKAxqANq4DxqKhagMMi2EcbUlTOYcZGZyAlpbSk+xm8jkDkP+KIZtwEZPz0h0afC3NKySvhWgMZxekmQjb3Jr5qFN9u6O11N6OOuGME8b++6dPd/LjtBYIVQg5156P5AwCJqnz/KZED4xJRCVbNQ1g4gGhzYiU7wSkPM/436ScsaV3VGYfxhQRUckWsC+1YT9EVxy9am3eXeWeC389uomBzj3b0eFRTT7A7FpHYLLm2aLCome9IZZsRE4dWQ8Wd8N4z/rLgv9GqJ8W+0rUu9gIbgJk5awh4GAeH7DTIhKUvbgebc7PO5zBAFq0EFMz8fvI5dZaHYfxbh/hQoDeCQ8K1tHu4NJKeiXNEj2D9T9Gyn5aii3IUxgbfS+EScfTKAQrng0ecORrh/PBVpugwYG+DksP0q7FPJ/0gxLl0ZZM3jYZNMrEfr3L+JHXI9B3fv2h29+VuKUG9upGFCr8ln3NpUlAAQ5tRD2+PnzIogdcOWGP0mAsqxoHac+WI/T5aj8axcpSqUiveozQzua30/kPFZrvE7oldMTwZkbu0ClrNtNgMO/
    client-secret: AgBEiKMNB+ZKzlh0fivN1MxM08m0PwxDPINopGa/E7Qj7G0suXP2bLDiWAPjr5vBhQixQjmUjzQj12ZJDW9spB+TQo4+iScTbGsjDSGFQmLLP6XImwiyxkgZ2LHTTyZqdk29D6rWXuidR1vFLSkCOjH2wlTa7vuiOrtaDLPXqpD4pYf3uFq2ZozGI0rKbDkYwoa2O7nwI8NBrv96aiXxnCtnPP3vTlwdrvp4Tv9XSa5wqZB89zC/v/g+B6d36R0L5TexxMmsOjOPW6J0ziTJZXkoO/hFJOdcCnwofloWZRKX44HgVQflrkxPAEys4Ak3cx5VrCs3JC3IT6ZiAuluoUFrN9y37h9fNwS58+J5fmfDyEJoXCXFIzObc6aJMN+lm6bf0p6ppESZRZBA5S8CgnZGb8Zuq3QuiZbeWZDHlJv+tRFeKTvz+w8w4NnDTUGxfbSfAitQk5lWJU07RLCe6PPShpICvSLdeE52jByk1PHq4IhLApAvnLC45bcTFH/YwyaSScsk3gfuxIFHwUVrGCqfAXA4zTH+vxXNgVgy25BdY+68rJDEM/PCDYqhuUe72J5V0hDwjwI/pBk3GHWwSzzZT5G5niLx1Tv4YKbSWhQHG9RmGA1sVUJwmPZ/63q0PUQbcBM9okQxzPJ1s9LTHd3S/CMsgi0/xcYoiLdDxSNHD/6iZIKg1B1eLgSQbG0n0F1abszR5yVJNbKqnuxdxtitKB/TAm6rGQ4AGLtILwmUsQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
