---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBANw8Z1Iq04qLETc8qZqXGMaeY3nj1tuyk5WKcxv7GFEolIoSG4uYEdlieQXbTZrSkIt7bGrE8WXfRV86EsZ/iqk12eV0iSX/7Q+nOLFXE1T9jWVicqbMSmoTW/UYS/2E5A03htAbKzrGYoF4d8KnIZH+VBjDp4A2Lt8OnsEHPRttXK5WVgDwlKemDa8aJJNP+y3Bjx4DOk5Deo96YLF/YTsYlSK36ihYiwSIGVQYZvN399/6FmI+DkzPQeNVcVgagChUVZXv0ziEdPPhTNyrvpaAO/rwy8+QZZuEhRMjKbsBirDS3xcH5RO0Ot9Mg+++6+XJ2bEFZip6V+78nIK7d1eH/sD87jkbA6ouZb177UdFjLcnFRjgKfFtBQUqWsE9W2LYt8rhI3B/BlBz9r0pxdbGXfl+Jb2VrOZNz/SrrifEGbIM8hbhYDOWyw2jSzQkUejeXIAjD4GJOrEzDvPr+jrvuFSk3qLl8OA/LMdfLMjK4u4XrHuGneMZ9b4U39Z0lWTHH51mQ7WIo/ByyaWZiZ1TF08UZwpAVlMV6dQ6HWp6/zpkqetK+fmjDy7p1zjYlOtYHAqkbjPsMIWkqYZxrLAso2LBSgdrwApCa1oCPippeBozVTmSYTCfp7YfbgnCwjdejXtrkvpKkrr41Yr3unBoZXBk+ivTAhtSS9RENVNLLg4LjJld+LKuCkqpHA/XwidNQ6knD
    client-secret: AgBRbiTY0wEIZerY/A/CzNRRGCUzzYsPaG2YJQMCXJPMq5P0v9mlaoms2thD/ZSylaknutt1klgSJkFat5DOzTXStyf4vnlqZcuQGnlmeN0PX7AUEvwI2RaDVL8LqsDjdJup8J8TpRLLCUBf6t39RGCHW9IRmmwygKP1sDoSFJcJPX4EE5s1KAMTlFuDiRNZUG4dxDAao+lemfixtBS17pIrDiwZ0pWxwWcx+4uSB95PvQbkE3d8+xXf64ZWWKko6g1pa0hPoinJ8SM11/jhQz9nmWlKYVPz1oe8wwTc05AL3GWvVrhwrIKS2uMFvHpBYZrjdcmcw/8H5VUITTHqNsnViNV5Wl2IESQrFrT2Zxt3fGe9e7W6x4ENlohv0ZJwF0Lmlb3E7QZOpLxHE6BLC/7ccXaKQ3Um5+I0Z1icHrwzf6QKWXnCGT5eFsuWDsOK9hzoaU/2p8Fpd9FNdf2DhFqHvMW7xYsPaJfMnPypdlM0LHI+n8+FFeS2PkTC2tD6qhfxOGbHBwpG1bkJb+qekGO5pCGd+SF4pAIBiIlssu77L5DqD0TsixaLNoUuO9n1EEP+jr2NxRPkqvuHJweFwlQzZmjsVVd+OVZaUnLig5MWUcxmuJnNz8cX7+Wlu5PKO0nVEWI9jd7FiZF1Vcye+kut2Cp5DtW5tcz2CYJFrGXUystftLjxheavZR5eedMHmC7vBLOxDi26lxmdhWJX29GQrzaScZ4uCTJsURcM7D/skg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
