---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAiJtfGcQ9axXCom8Ucob4c+y+MFcNgWfxVJVkDv1OJUXx084DoEMoMlC+kJlXXTtkATSzlXAXLFzlmAR9wabVXJEkW3xjgG366fWWIf2q0Hxg26ikRiUStQbZhdiXclpzaPXPyLRO3/gHXXzxmlohg+o+L2D9ImSL69YIAQKXihXMIl1g8A+0mkzXyiEpkUNLk3C8aCK51ePKpehVv2l8GxqH8NxDrMGHCXdpFfHsIQPbxb362fSjkwh3nCoDjJkyeMu/BE+Jobf4otdcucYGHqV3ZwGJ7hQcZONMi4F+2MfAvOsQxv89s8ijarnXZ59qPi2sk0AH68d+vlg3tShHLQdsaLlxTqJLPa63tmYs2JsPf3cx/Yebk+ZTXDuS61znQ9YhcHo9+XTyNLer//CDp9aqvwughgw2haKiJPL5CnT2xRNTpVqVirC+XiOlSo9P9bg0esSQYr8D9tWW8mlENKdXe5c9WQfPUX8DJM4xUF6YZpedlonsgeQctdR4AuWL24cyacT/2dZoSBiX16OnNjO0rkfUVfLKFjPfhxzZzT25B8anFOskunSnjpkBO6XrK/ScFQlIjvOZgqEVyet5BDkrGh4RTHuAP2NFxM7YOGX6ek/M1JHP737HhsAlxobpM8DtR8qH6NH3kbt9ew4iHdEo7HOwPoZHni2B01Duuzkpg7LWETyVKcDDg122R8KjAYeVHfttp
    client-secret: AgAZsInMgRc2iioHUaZEJzDkwRfQmksy4uiUhD802qvlRjjXdszfPTpOPIWsWUgjmPBXHrFnkUdGiAoiFsloNVsqf/vxP1yN8TYHLoRDaCbcBRjyazIzGWU4aTwlC4omcLFn2VgHlZaqNpiGT2pWFmmwUtlfa/q4Go6XNo2ntGAnf923JjkaxltKTHhyjVOGu4nGzYfQ7jo9M1YoEHMJSmeYxS6euH6yNSYCiJjniL1tWDIOehY0JPcxb2rRGEketvyHyhq1l9d3KCz/M9sEpCJzvVLxQoxO74GdtA7I7zQ49oiEF3KlQzDE/3D37wc9/Hy/HU4Tixft+1UHTl2xCh3xD48qUUeAAfVeCdsPzySxzk+dDcd2OmM+GeM2nHhVPwJkbFKMQqPBNowZXoEGVvTCb+jZlMmAVgkLTd/y5UobyQNxUnL169/ZmQtXtR38VY0eiFe1oE7GMtDk/5KoyeGooo/QUvkOLfLpVkw212QrlCKs2gCGYbaAf7ffE2SGW1DY2V36L1LLpLtfR+PQnJTzS1nMTxjO4KJlMvdrS76fhOpJykfIeNsCWBVpcDtzBQb06vPMr0EkAX1UW0Y9+R+s3Mq6W6jHWP6DDqu4r9OzsbipXOYlXhQYp1Go5A/q2fhgDzl9CzewoyRpK0QKI9+YjhYsIMe80jPqaTT1bk6VlAa0YQuvqxZ1j1udQue52SvVMLD6kPzDvv1Ex5t2mqkluFmPr0kTgNmkEICEPaGYwA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
