---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgA5IAFiorkRftMk8cqgWqtZLa0ZZjJH4Xf/pXETKb/jfD+I7dk1nXLuU5MT0pQxn0NaaM/t9D+lX70Zw+dX6gpe0ui3TvNrk1A8A/7SskL73CGOCQrh70ds6XbZ3TA841YKoF5cJyxBLOeH12RgrCnVDKB2YefGk1LVN8lSCYTEr8gWZE1+ncH3zjHivN383ACUJG+eEJhYxHTm0zVnEkplyqThEg1yCTuJDHHDFlwJD/Do4JTYg6j+HczLrgF9KDlhP5j99rfS3ZHLzWrfmWowH0dmmcbKNiR1QPRh/cu5GwQJJpJVUc8A74+zGZFHMmYYso3/sTv5y6SdUKm+eGSuR4A2neT7ibZanBaTWVY+2M7wITGlKmbuP5Cqq4XBcYdenZRdYqPBhXDRqpyXcoGzVwGoz+8SK0fNxN6BVEw3beFnTiH3E9rH2+BiOlL3UBjZg0Y3bmJ+v5Xbgy67JwgWJGrY5f/vG7H4XsVfFvF1xk7SxDr0dUqY/ZrH+vnF6hRxxORR/q7YpVDQquNop0sZ97auabVYpvTbFVf+RhqhQ83vFZoK7dQVShJ+HaKFubR5mdya8dZXLl7zIO+BI34ronSfO0Vi5FigA+/tLQ+QuOHpyeAtCMtMIm6sHRJ8CTV4N69sqrAl/do4g3BURF7nqH/e3ZjgfBn/4sNdyBJ1wtDBHatBlBqczA4lqFGDIef0O7RjfOmN
    admin-user: AgCdED+5GV32JzWETb4lzPL/uoEQZhuxkHssGF1cUdombQHwupHBrx/jKGtLzzk4CZjcEakvVGrXZTBL+tKWTtvgML+ZT3sYLlPCTkV9N8yBMis/Yeg8lcTcFr8Kb429hAr51DDShHwQe9pYY1Ihz5qvNCxFTVt82huW5Q8k/zdDi+NsRwh+EnoImXT0rkKtjraR92a6UaXXrSsUF6A7UsxRQPDX4F4PxKbBgDC8NP3solPYSCAqR0MrCBg8mgj8FVHZJSUsuPRDQYjByl/H6p2IplXMb4D+ZdTX1hFZfdvxOmloZPdgAU0NTmUH+RztzWO/w6P55XwnbVeJD5UNsghk2sqt5c30XzZSJ52oQnWjR4J0PGA7T/ExrvTt3Y0xuyuA5tPtUY1OaVQWOLp/sZc+Jym2S+kwSBcDACjEKedhtifJlX4UWOuHEfwV9Z9gZFxBTEl1WBBJqQ8YUdtkA9wNffVyR9etS4qxU8a9XAhSmJjiyNr5890mHTr8Vdf8QUH1WCabMuAex87bTbPkKbPZY2hmzbrQzspuYFv/6Kdx+00n8QoTUr7MUqzwv2aXMhNcOBDTUn9fibbl3r2QR86UGYP+Pz+oxOznbOrXj6S7VhHaL9zyjnY9VPvi2nPmg3oQMrJakmYn+MXFdQKs5aJhZci0h2aecfKWMrWw9XsH8TH+VpxrvivC0VABYMWz9YV7oLuAvA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
