---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAINb1L6za4xrU27AV8CCzNQW/nq3xFNgy8nELzUQj22nVm3riPsicMRXAsgH9V+L62R17JuvIKTRv99VFTPX7HlzCPKS9bfVXb0evxKdHDQsrCG94GUqVisjkJlMPlUr89QNQCAUcc1j3ooozBbozKch5XbW1GJHkZxNovqLO/reSGSd8dryAyaQJ70YERJSrvxM0Lqp1RQGjrh9U8naW5kfTCacxO4AMdFNqp3f9iLNeQ/QwAD6TvpnbtnhMT7FVSaIUwQ+6mPn7Yb7zTLlUajvru+ZkUoZfCiMujPcGGc/D/dzbTM64DL9u3i7bylVgDpAPEGlt3HpcPA6jVoMJSrPjHh06Sle5FDICjiEyWT4v/Dc4kvYTrC8WDk5ADG3/fVGmE2ZnLkEYz8OYNL6ktSkIMzGxV2dTRnyhnLKO4r99/YE/41faXWPAGBq4XAnwp9dwpFAvk5cFPhoiW4hBM3A+YOZuKXYTjsvHvcnRM6t9DEkJgEDKtj2hRMkPOCp7mrUH89SjoIKwX3HwsUC7XNbvWWsU4uo6onhUM9NClVk7zshVIUgiyuIze/W1Nd1XIVGCe/Lt+hvH/gEgEJuZGuae+lHbhemC6oiqTL97DAS7C2viq3iUJ4QuMw/8uThzhxf9jv9eXbMNC3NgXfcvtXsCjY1tboYPy1vHfXu4VKOhnMSMSXl1x5SOIcLvnRzw6eX2AMnSz
    client-secret: AgAsvQ2O3cxRr0bTmUex58Sy0zMfe/5wmEHEElCtC9ytabd1P5AmU3fR2zBQVvk6SvIMHGsFGviK6N9Yk1pPx8l7f+nQ+aXKJgUqA4jLg8Mus76B7tC+bSnQxMha+BiQwVACwDg9DbIx/rcz6D2AY82T/WUZNcj5SI7+ozXsdbQRI5ejAzRDRSVPGxAIMBTRM1KUsO/LBrxAbWOZ0uYGKzqizTIeS+Sy+oi0ff8kO2P6Fko+nNJ2uuc9DILAjyL2GP0jJ2z0xt7UGWlW6t0PqhZspGVsM+UC589TIFYGkpVt9X2DkY88m17MBYYuoMvqHkjVSzN1TqCGG/xVB9Mco07i1eU3BZO6P2HLHiz/mOsuVjILcAQ25sVh95Xh8KxRSSzuqlR8o5DO8JWKmWxXoRfx3O/xv92FP0Eh83/WInerLgHBcDfjftG5u695QXn5SvpzzE+JRmkJLW86Et6XNAomE6kSLLDmT6SgXaFxzuGnY3CAWUNH29Vc1VYcXtEJOpH+IHFJDM1NxgslnF3sGcCyjm7f0vYVZAGMe9dSimwppFCIdGTtcFd6gadLVctihc2xmd/AQiaHKX2uH7bDbtPnvn9aOhMhWE8s+wjxaxV6oW9bozDQMmc4fFpwlpo+nSDcPIvw81WoEysJIqbE7BshMvoiRUmGoXMh7/jGPVcf8IP2CN9L3XS3AEd7PTha9pphPxL386uggPluMHhaezwqZamkkA2Ty6ZYUXQtMuOfLA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
