---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgDAtMuZcpfU2qoN3qEHvwdCPucgU/b4zQ4ShnZB/0hSBBt5w0DKlgU64OBKwbNifloOSu8m4vuGB8oAX65p5p2Vf2QSQjnjM3EDCvBOcPhxt3cdoX5EyfTRQPUwmNX93fpLrOZQl9B+Hw074Hfjd/scTeCKnR9ttfWD6CafLnXkYJ6KAPY7nKPWg3byPFyb9btIaAWTggkRuOPP3QS41zB9zioFr5b2KpXZEyZ3aMYUuh3joKlvC/Myt/WHUGzAlZRdaW+yRpRl6kX2GhRjxnPQqMLU4LmL/Pl61w4sGGvNRAuHQFtGvSbVj0P6pC9IHuf/ZCWxYMK7ws6hSB4glBOMAvorTdYowT/Cfj0XbJjuu/iPQle9WKPd607POMxI+9wbCNLxiO/blFmSNPXeFtUPByCg5K1ZF3fRqrQLyCQov1cInzVkPVf6lPPIb2i9GCIaByX3vdRuSvC5rPvuHgt1Fdx/pAuzxiHuB5Qi0+iCFBIRY9pKUu/QbHgXy3vhKlMQxsb/vyUBaLbvPLJikEwHkbx02Zmr012iN0BdXUqx9oIvSyJgOu33fIpr6duFWv6K5J+xQ733vsZ93rPxyRT9SfmsOZ2uXIS7lLW9kk75+ye3m5DNvxLE9HadDdD7IeLi2IcwwoB13ZL0efS0OkPa+EjuCN6ZKw/vA1UtKjKmSJzd3EIB+uV4aCmEzL1dTUVNzOUCtcFf
    client-secret: AgAkyBLFUtWfwAodvdNMY7cVfZqErvW1myGJjaeaufA4cN4pypzH89BZCBdueqfph7h0vxQsP1HviYefONPAuFgnqWhXg/2Y1e2ApISCPy5/duhxwG6so+AAps3C9wR0hV6VY6smz1izN6BQ0BF7JJ//Vpf435Zp1FE+7/TfqoAjnZKyK6IstlFwQYDK1VBJ2Ky9WcIYi0LI1hbJDy7nBCM2yj55uHcnM3jkhhrfRLAXMrpvmdyK+R5LTuRPQdGipfqpARpdP9eySSd8N+8DW7sLwj4JJIvr9H2oFCelOCie1cAhWzCwqDc0Bwbpbifk8qOn1rnw/GM+gp24UXC6DLWhJ9vrjCbZlGGse9LGNpJf9qLt4BGEBaV9DPmph2KVlqGbT6JqDYPlwHLWePal2j/OnDUPCxf4RWO+AnsH9dEBQEV/N6zUC7uowUDthTML6gbmX6L2Z1kfAA3AmCkjv/w1sHGOLiVapAOoWOqqnG6JQXz4BBC1wXlZ4TIfPgaIKb2rvr/IcIqpIFhsqOzPK1xlQQ9SDuQDHAO5IBRSGOBlDjq9/dTO9Q5kbxd38l4OUfnJqhee5P40/saYO2Do3TTRo6POKYQGf774CPPaCeUsVNpxssqvHoqce/k99M8u35eE5ewBycNHzfD4gXa7HsP5pROzQal8+G4PzullWJ1CE1IeEsvx1Yx6n6OgM68CiQIT8twCh50Tz43WGxO/mfMwf7spfLnrVTRnLp1k5x7QZg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
