---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAR/if1p2JiojOIXX4CM8WISzSd26VjATPTBP0LLnuhxoXCttTaw5ei8bIefrifodwajlqkMCk5iHbgrhWFk+Fn0vGJLIv/84UY7yalw5u06kLMkMpn2qd8xk4nzfb5RoS9PZBb+RKPut29to06a7hLO9dKwrCbTbDB6ms3+ozfDVLJu2xeiIq3O3vDeW1t23vUUkM6k9v24bdb/ofHQCEV6D5lB+IsL1P9ybjasNjhonOZZJ6DBJgVtomAWOKdKfI0biEYGqJkF/360kfqRieYnx0Ct/+hEoML6JrgMHW4Ewflr2liMyJ1NQCzj344LRU15u4v5ZzlKof98FzlmGcNur/IXnjCCInAMrkSPEDndlKWjGq5tezti2RANfve49rqKFeoRFLnBxHo43bJiwSJQMaNTsTjUaSWmc0RTAPYVC+2/Gify4OqiCBrR35lutC0iCFDNtZ9nheBwN0XlaxTTrTbEY3u9I9Nm+sKSNved3P74b7FdHvtRkFJFvVDF5JCsyq6zge0xNRsiBfDpqDov2gtTodaWdNa5TnOPNaxoFhCmKE+FcTLORDti4uYtGvjr1GLoSuj2w/s0wvXI3h6jHbpPHwS8JXjQ/ywdnBv540+9oTk4Yh3qGP6dly4zE14dima1Za7FFD0btqIkkEadJxMnW77WaiAqV5B7jFm4D1Ss139QztZQuWniQ61ZYAjyoPq6JYi
    client-secret: AgBDD8PEjPMoOT18ytGBbpbXl+7npQBws95aR4NSkmwPUTpC7gc5MqCTq/NvdqSHokWAzb/XFCg7e42kE/fC5qK5nzahK+nCHnhTjkY7tf3zZ+G6Z/WIs8ydjKwZzDWofX8Ly8tjwqdb371pYJpvEmUREHaCdX5pblvKBdwvMRqBJUIH2XMK4ZvlY4G8sqEntT90BfAifVhOaRCSVDtpzL9Cg01HBfZnrGfWYhJIBc7D2MJj0ngHCmZXJZE/95WFsn6gkBw2QOzKNikABopfY0KH/b7HhZa2CaBD19kaxqE1Qyy1/PiMuDM5a8emR0IzVV8jncqxo/kVhbuvls5VifFMhRiQq9RR8EimhxJmcEV/EpvjWnkCHVPk3ReWnEuLvpz+s3f9fBhJrQEfo5bkEVcUngOLgWCfkdKfT8+hGwQQh/jSPvo2KOZ9cgIFBwwMAq0AkxLKBQij4vx7yuv9P1e8pzqwQJikL/otWP8o7BJswdAogT6y+hO27th8PNrxbAQbRuuX5pEvi0LJL3vv+V2ePrXceUKhpfbUSmkbgLXbv4TQS7DqMJk6NTaATX6LuWXpC15d+UzsFPvHVXzEdRCpLgnowVzknDsVJizfnqEhTSZl8iTe2GKzAQADNDLH4VhX4/IfiOtQ3Myp69/TXg7Gj077e2CA2fj1ou6jKXdjEFgr9KJSIZ1i69rNvNuqPl728ZZGEF0fU/HtFoKlLPxNmXT1gR0o/6iKfxhzkJLAug==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
