---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCJaEB/TyxRoWP/V46eMpP+oFQ53iQfAGcHv2ed7AC5lTMiIq/fIs8QQkU+fuy8norsqZG/BLNhjo8tBf8XKvZOQBADAH/H3MofeYBwuSOsjtxFn3m4sc8tRX3CK8WwvuxNGhBN0Xm/Up37EV0OXcBSGop4wF3DckHPIX77N6xGtpjM406CPVHoI/NF0Hdj1R8TJdBygycXTkg/ro+NSIpauIcxcJwHziVY1a5ekKyfxja70KOjn1fajBvF2lq4PpH/U1mHarLM/eJNPtvXJ3pQQzG75QuByvlOS8G4ruvMr2ck7fISMj4LhDItgsMc/oCfSPXItCXLhE+sMmc9PEM2lbXNQj/vpVr4r07M2fMnzpWQlYm4NDQosEeWGKjixcT6N5wIjHrekRdSthMZ6S9x3MMWHlpkggOpENIce21wckdX5GKZSC6XGpgALfgy4p99Ajm2/DoaPvO5U6ZJJALo/RYsKZZRJ0cSBV4czUBDW++TbiyYijCUhvc/uJX5nQ9KvlzstNRmNzCtD/WXqajpQAl9DduNIZYTGklfFxDiJs6/Ky4UdoTSj3nFF1U3scR3+lGwCQ57lJ//nvcIUDkEgOKJU0dF7fKE6vItCP7Nij7jwPXVVmwgJ48hfbKnHg117c2okz52XHYk2o6bVFiZxt39IRbp6Yg9k8CYSgSF1gRTFaYwvl5LpUkHS27GCK5CY7EcIfeG
    admin-user: AgBUSRIzHLueUBNSxWnQSpVrNgSUayMBAIHtaNES59/e4mcKJFexHHJgVuON4D1bM/Mb/A1LSL5kqqs2K4Ia9gEdelhTsHCMpmAhEZUPi1XpWilDiZl1A7QCfDe1Wwl1/Z3p3fOTCRsFP/FgeH3kJkMcqKEYxZfJ2Ru7Jse6K8n7ouXZG6v0BeagoPKTgFTaaNNhmMs0bq9U4143d3qiKOfMFFna3lsTcL1oO/f5Sp3cMi04Oz9bNCJS3Xr7kIQm+SlU1Bmf0pdpl3Aq5R0c+uaeJTTUpBe/W5inDDLVe6tKDFxhu0ze9JPMSx81VOcD6whVwPSzUniXUk5+zFSNc7Iyqt1lg3tx2y3JYsuX1O4tpn9O2JxxxtnoK/JFyXW9yVYRSm4uTp37+GRZI0PSTWBS2SfIo44EwzNADDn+L+eKthcWie0RcsqWd5aR44DOpFVo8C7nvhKYQcbmUzszbyVcrbd1sY+uNO0CcqQBhfuammgfpAfWWCfScyv35RpC25EXouRbYhV+XTPgtSQhTkUz63zfLQHojhVpMaqmkxVGsEw4KGSQv8Tq1pafhwunBdW0Fm02fNl3xvd944Gn0QPjWp/zwc3ecvCdVFAdWmjORjqDtDL8TLTlqpK9h3KTFanYL2auF3v8ToycUZZnr3DQ2nDxE7jv1ZMVpEHwgtP0uJXDefZ4PvAPgLqKdlqxzZnwQNwrNg==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
