---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAXFypOH35+n7SIqlBbKTy7yT4HOwY4+lpslxYK0M+BXaR6zFvQVY91GwZ/sdCZdVbNeI1L4QBF9TQKDez8oMa5bytUNbqAuo5iATwgN69qZ7la/lFGPspJ577NyTnGDi5qriIIk+gUN6meScA5N2R81swCQHFkS89ohEJ/KmuKkBYZRmilBrVlVY9dv0mLjtIeLUxbJl1cJ+7gWZ4QsTDMBFXTMFY+NgBB6F4qYz97q5LvDYPJTjeR6k9OPQQLUAVFo/cZHWcprpltH7K1T7Bqtc4G1DToW+7HFq5PwaC9xPDSj20Q8sXIymqYBuMLba/rVm62/pSsbCi2tOk/vUgbm6wUBdAdN86Bjc28caHPxQUh/pO5hHDpiOcfjcJMnEKQFkx65fKQTd/RucccSEul1cK8X5eFc6FnAqYhUSuAYIkvJKA6nvjSCfiEtHsB0PwVc8QFAUwmSBDA1yM/xBWhXJfQ4iAsBjV8FKwImTETiLTe2u8Lp+wyNFW+EOGSTYz9PUILMFBHy6BXk4FrSTyQHhuE9gGS+9KYiWa9LESCguq4GbUvHMfBM1+wv2seEZCGm8QmikhyZq3vV6bc63P2s1DkYcbtmjVOYUqUTAcwtcE5Gw3xCASJDglUeEGOE83CBV3EyafbgCnEf3B2Qm7p9HsAE54RsVhw+UkVLGKDqJWMh2m6faVleFlr2HMFIMfoXl/w2TM4
    admin-user: AgBt0IzR6kb45T7o/pMhVDejNt6o9p9RTCNBI14+6h5reQ+5hLRTOgnKaUwBh8QPJ0J536NAHlpGuE7Ti8h6im48o2aPQkbv22UjKYkzQ72+AAzNvEol86eLKz/vhRCIAFA3y1K5IjerizDWjdZ8Xy4awtQ5OUEb62jtbRoQAKP6JSAU/5VgFTSJzazU2HqNVbA4AZB4Lo/XFtZQWc42QjAxP8Zs+lgoMLGiAKELRbQv1LHDgZApUTFCyPl2hE/rYp5SIgW0JeiStMqCV+X6mBX8CXZoGwwovkAEf/aviquE26CU1qI3s3H1uXglM1jLEB75g8rl3c3Fz+/HbvZsaG+y4BiPmYhVZUQPsXXktyt9Jv7sSGckijGF9iDGdOusKEwnM4DkZSj0tb1hP65fsmpgwtRsj3Sv/ljEepDcRjqT4P6AkiLklE1HjpTIrl6ySsU78OPSEGmjHPl4AI5SDf4IPX5ZVAKF7CYNvA4RhAF93/44zdPaP0CKsHkO+f6K8/OkcqLKHM8fzpVotTedp5+GMrnHPCvazZ9f9h4C7jK2QLwakXfrK08E62BPyimF1M53PTTmTFTi5EqkRumPNFXxUyP26i/CcuJHEIBa9LzJJ5HAN//NwvHugWl8SN+yk20VQl6cBX164zNlO6PDSSBQBU7vXL20jzIH1OD2nfT9Po/TyypeYpex2BaBNs6gnLfenBEwXg==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
