---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCuIyUGsPNN0GewysJPto4AGwnjy6FV08oqrSv1p7rnul83Y0Ya9D365AeinDXXXWGT1EHxp8VZ8fUXWN1qvLcsFdvHWRPtOrBUBYzsiK2PyL9L4IeB96kPAaOyFSKbrytpBnt5AUzT+74jVVyZnJRaWZS6zZ89VNtbACjVeSII8twww0tB5n+IipQ8PYvhzR8Z7RxDqpGw9EP7nHwliOjQEPoU9uaUpi0Z6LEMvstcTttNmMfZEKfcxZW1M2XEz5wOcY4XcKzIopsW8FRotoehRT/6XJsGrF4e4/kql1MmUzGyBXYjVZcT1HmbHFBV87U4QuphJxNSj6intgmn6tVLjWn+OE2iui74uH3FjvZRLCV2pvB4Z7UzecMaT7SpVwD8R+fmr7YniRRZtZ7XjzDVX2T5ifMjJrfcpIm/tfaXcgy6i4eQU/cqBnlXGl8OywzHSFB1zoxk/TDJs0p06EMwbJeEZy6W7gz3QSm9+O9gcle3jOGdoNZP8882bkqJVAbQUp8rJG9q2/TKlSexvPVPT0QkrCMWdzZHeuPpdaO2BiU1azToeD2jKNOYGhzez76U1AxbjxY2eEwWo3OA8lYJSaXlFhSoihxreDGh3WQhdIqM8nLYGWMKCNbkcZFk8jpgyO6ZIx1VxXCu1wXmo12HWBId0JH0UIDX//Fx1xZYY0/GBJXKoWQAek8m2Z/lMYGDjBKNgmc3
    client-secret: AgCkQXAncbeJNulXbmGBrNghXPcK428oJRICZ41ThkU3lbPVRUn0lh9njZL2Roc9kUN9GprOq6fVTzQIMmYgydJlWqOnDHLKhR7vhA5vQ82td5HN6gbptSP1JG2mI31EpcJ0otuq57z+9Fj+4PjfX/ebRtEDwrJKRdYV7pC9/u6rMZUil0fLdNrvRhpXl/IX+fB1XSBkJIBepeutz8z8JRyy3S2L5OXpNpKjye3L2h7j9ee/EJZNZepcFhEIF0ohjsRP/cuQfb2a9PlgtMBVShgodqPPZZKZ/8fGr57lSiVH5LvFNL45tDbRta1g15z+rca4EXCSlq90/QwJEjH+/nY9LzrI9XNC+XTo0gZqR04CZWIqoU8J7I6UueUlKzeMRqXfz1Pc96XMnTubvfQRZfkmHQnVH/nxot1LuFboS9CL7KI1BeFU1D8TP7QDrFCJbWqiPGz+esEpyRiLStXrjdIkVIBI3xMTo4H7lz64dVqllYyOGxj46oyQ4DGtlPg3lepgL7EbSvUQc6BxXDUDVg7t5sojCMcfTCs1qddmYtghAqN80xYBM/ZtTI96aDQt9F22Sugv5xZoPoELeViwwtyEWH0Zmb1jBBn1q3IGnNP7C/zXAM6hMN2qgnriBykTcl/f+bSegmPRd/m4nPp+DQTDj6zx3b7kodwITnnClCV5ncCPmW8+d4VSbkog6/MqHHmL1anndrM5VeeNQvgfbhgukW5Z6Onh0c75GEC8fbQ9Wg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
