---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAS7OMWHd5u7KDFj6pfXEw1i2vSf3zUJlnQ/qwbNjavKvQqDfNxjjvySAQBjyzjh8letTDICPYIedCNomQYD8+iI9g8Ft0665qIS9NGPA24pjlinCD/USMsHgmDGwlGR4gnoqspOc3oLHkyt3d19VzjGn7gZ/PBmbXpwIi5sKcCEmLxRNMKRPwokCqDj7G5YfDTWE1HVNikxpu+AgbFRKsykHK6OSHKfEruWW4UeUoz6oDVc//dFApx8ildU0Rri9KIXhiL7djujdTV8nBMc3PgSMWHcSXDqSE/iEvUrWxzzl8whPR7/PlB/FRcaESgnSgUDOKl9siGgvmJbPWnJTIaRZzYBDFs5mK3OZOSCPO06ZvsukCk9TJ6287Gutrb3IprQRTOQvAyjYFXslXmEbBNytMfeJ8xK5DnKVb0X+RKcLUG4mAjkHvaGVIAsH2xOXpnnd6BkorFfmfxQA9LqP3k6Kqes8n8acFDybYNz3S6Nh7gd9SbBfjlR7V5sclp6gtDijW1ddjstn21lVvZpNq1CsHC+SC9D2+PLK1799Uy7WyyGZ9Y8n08XKjnDNPlE5D06G7aqDVX8peV1oAzLaXGImuZlmLbAZ6kJOHLh/w7XDZ6IZZ3WK35q9xG/UPC4fhNcEjmGaA5OkRSh4prOHn4n3z36jwKJ3gTQijWTMaMde6NLFnGFF2DFduFMtQQ30mY9RVcWIs6
    client-secret: AgCbhehUb7e44kBfXPgmTDDABHXXdbsWBGSlC0TrX5bvIFPnU93WJwemiK5ROgns2tB7CAa2eqkJuRaoLVuww7cCXOrto2KBsksWSCLsQb+N7TzNa8uLSsnSUWzK0VmBSnILlRyRFRqUWIE/XqQrmJaOv6j7q0hafFgovA9e6Mobw4HoScorIrlKi8fDbNUvzCHHOpiZeKc+bHv7SNEj5ACQkHNjtifRIMeT1wFKcjoTrX0ixDnUvIeGySHGF+xQAvZ7SO+s5s0Mf554+me9N8fQQJzJ1a71Tx6OoVDUb3JVyCK3Cveii8yLtwkLMHpYHnM5oB9CWfsLgdtBjlGRykuz0ff33DgzNdtU/cx4omlWG1Mi7+R8CVIVcD1IoadvJPh6dETITmkbfOtOshUDfUFPEshwbxyv4GPcxkPxi5QRp1tdgbQNUFGkpxXkchvfu+gUTJPJtYXe3YTRC3kgKWkWBJlrO29IArRTIzdFi4QVL3ruKAySXDe6+THBcEqpp/MBpvxymr9tFnT8d4stcLHovb+abM/KUg/Ft3T/tK/XoY9XDKZZpaGtUBHOYFuB/izefBTCsseX6lCOAi8kdHG6+YG+x+hrwaQu8dhrblqa3DVzuFXS0vDpH5z4D2tlAyCrGGEvTu61wE5IEa93TsA5ufl32E20pOccijjb8dw6Z+5zcf/fRvD45aG636gpWz4XH6G4K5axBuO8ox4UjOa6a2DJWAui3cnVjxV2IwhfMA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
