---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAjpmj5bHz3x0K/V49pqvAA1KqUDeQuEzVgXo/ZIJXu/6LaSfe3rNtSuLVCTNK37cTFaYakMia+iU81YXy3rmZ/LDUEDnS5uY4c7olcaHK4P0XVMC21UINGyO67pDmMSSn0mp6XhlacvJ0BA7zyFyl7pLxQW94dgNVS1jKl1Ai52lCHVKFvSe5Up+oZ5hPgLY7aRtjc04qfH2QwW6QXMumkB9biPJEYYYDVc9pU1n7tweftvwX6zkc91djayGv4wEFDdmMOC68PBxPEmMRt6kGFaJuEws3iLlTxyAIqA9PyoufYkVyOUiAVmUyWDmNuG7SnlbFelwoSbBqNRwptKVpqtSyglqUCRKFs6USaCzt/3SsHHPYMPxs/l9/sR+CmBdR5AaRLdksMdHa7UvTNhMpnqoTSCWrfiEClv/VThBdn58tPluMjnGRm7dldlcIbC3cTeL6weQvNCFgryiiWLaOJ4l6/BvgmRV7nFMl4rFSbMl8eJkx39t3pCvRbv/V5lmfRfqbWV3/sDB+C71S3J85qJcsDv/qWsKrFk6fsFfoa9sLKKQ8RO6u8+depwOCs+f5D254H8Px+cBv8FjLk5k56sKccC77xgvtQt63jFN/HU/TBBSSnfUSKjQ9dagCu24vo9oXHOg3ZlF23JwgIdUTIPwC8yUqDXGBXVOnetZOx0pdJBmMjORI2UC2EvKhtNFuydpWjmr5m
    admin-user: AgB/z2bHE9H72+MleaXzpMAVaQpR6wcxhDS0AwH3t/T0Cc1NbnsN1rY/rx2Vs2xOrIOEFaG2qA1A/FUeFFI4tolVqZ/kdcJmOhELHjULOf2TMwRX8wlfPtO5I9gYhARso/jDi+qEmq/xXAuSXLyTyOKjwZZ2PN4Qe/4pctXWgY3oRUhOUgndJjSKLtC8a6p45Tf4db0QkfH1TkPabQxNrtfVgfTUKsTxCNF6vHauROtUcDYGRmFbxU3oJa7BbR9hvFQGllqOH5DJ2IayBHnreeh1iHftjsA2Kk1BgVpCPJVkVAPQMTiLSWfo27+DVxIZRoNSqe5ASgdYldbAGYPWxSfxJJoL/m7Bh+hKUx3qff62oTbyVW5XYO+NF2K4Z/LZ1Fu5qTGh7ih1hSPYHIikMT+pIVwPvkavs9FgSvnIhvXs6sJnVpdaPsbpvcNLokiobANnHZYSEt1ZZ6B0CCr+DpddUTX6hg9QejiugbAcv8neKWaXx9KsxYzkS1KeTTX73RZdsGW8fVxqU5b4Q7znhcAFWEDv+FmVOWiWsSwMkgOR9vLGYVhk+KCkWjZRggHDhe/sLt+flgrT1urjkUJumNk/XSXJGZoUURQfrWlm1efRMRQ/R3+sOX+qjwptyIotmYYgnpprmm/i+8/2/HP0IqKGTtOtUjpC7GZnKBoIed6Y9VXpOfL7+LAnI+f7IBb31Vs2UpQNyg==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
