---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAb2AhLfSav95zDgCCjNExdB7DlrzpoGcmtNadfdy3+vrB/q8Y3t1fvSJzLHy4ftfNjURsIb5B5Ml0K94B/qKiERdAOtkZmTKjN9X32bEyEDo4JaPj65zg31wzzxuSKsnBc3V3PcNvlTN1UZ9cfsBxxTD1lmvVNMDy/9nqsxa71xC82P6T7HKyLvVpNe00yImcZiYqJxk6ACAftLKfXXa+32QlJF4BOR+ZVx3X/sTPENOlREPKOnYEH/UgIu02dv9LGRxtsX2IvDiwTYUgXC253L1doPyAoi2fGHoyToQbIJ0ONXsdHTQDTRbsvmKGv6Rx/deDuh2rF/d1jlxTtsT2pOJWHf4Lo361RSQ2a/rmnp9dM7LWoYtNZvp07mW7qlJqJZBEDUO7Ns2f1iCUOPA02RTr/xLCHzuMp8nUex6E4saZIE3C5AnuwkfK1yhJpev2HnEUZLDRUMDmOZhu/c3A5em2j1cWhP1aTU7uZKCmFUoUpZyfkEBi1w/tj3N0gkvXFxLrrJxPqlKmupjckXQUXr7Jtr6pwUsemI12f9B44AVOO372EBlmBbrDdnJVd2dnYaT6iaIjlKVPcub5ywDTrtG7DSd6x8JTKZ7DkbmLTIPDI7UtIuenhgkvR0PtO5MunlgcaL1PIBdQ2/vQs6mRD0AbCh8w70BpvzBh8/FzRFzk9c7EH2r1teV41E9LFj5DbabEAg2PD
    client-secret: AgC1ZlWqPNklKYVcTK0jysECK5OwYOmBgNJDrra1XhA28LZZ7iCUpawos1guajIyRbdQJpkvbOzvdoqSh3u66FS8QGdLRNvazV204icVCC1Kt+jIqJ0W7fr1caN79U9BLTmVAspx6Oj3pCfwvhkjmDM4W7MqsnJdNljRw1z0W/7dN50n0pNr7wSHYN55NAsdF/jViFizIkUyi+/zgZICiTE0G9t85wZUy/U6kyT9mVSNE9+o6dac0BkVTQ79eAzhF5ptbIx/P5x+JNWyjBOF8JrkMw9nAygtWMlVyiuGCfNVUHVYRMzu/vrzqDkOkxTcuGqm3/5QjoqEJKnYQUeUy2LM2nALusyqPQ+FDS06Ld9OrUz84iR+XUSyLk4QPK4hCT6gplTEvma79iA3/7kYyTNncXLW5vXx2Mcq45BSJZJhequNUmTNJeqFtY/TptujXAM1hN44N1Kh5YCLfcbWGQguFeEhzZxm/L5iIB+la4DA1YMr8Y+PqE8wZUUofuuATWJ/29mxNuR1RtADaPX2kqtDmtoqEmCkpuMI1PQ+REaGVb0FG8q+bTGEdjWmLAkynHy9xPVmkiq8FPvlMednb/TXadqjWE+MzxREcg8NlcIz3wYe91jKECnby1R0qhoTPjHllGArd5mtQtvhjB90NJ8T3/PQZPmX7L5zpM3/v4rhiTzgxHovQQcxa4eJZRo6vh9hdldrQch5v64W/Apwzi6Iei2io5drkPU3NH7TG7S+5A==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
