---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCq96NulsAo/kN2JMa2kOdrNUNDk6T0bBsYdCLunE68oQOpK11LRu37/K7Xha2KA5vhNfu8++779bPQ3W9ExtnXn8ZR6PovHcxayFIl7hRC3ZgvNNCF5YnkAZw6cSACPcHjX+Usq9xOf2cMR5VuNHu6kyOJ9r0EKxG3OxD2UJ9MjjOQ8+bfmgO7ngFoH4HcIc/rhgtXzFw/d4fuisOp5AhmR2M7JHAcn6oJBszh15am96ivRu836KYZfZWYOpBIUbw5IZo5kHOnu30HzEBF+C0/I4P1tQM7H4JOE0PB/FJutZfwrJrg69wbx4M7NFj2SWloK483ro/rnA71NZXe3uG9lVzo3+B3w6ttUOa9Lq4wZo5Pj6w9celYdmXUeG6P1umv0gO6V6I46zSfXcYVy/Bz+0HYc06QJFUK10DSoTGkbyc4H7JkJuWHQm2kLWftuH5x4FgSzP13HJ5GiJLLYeD+vmgROuNYu/nAMBVkqYIg+uzjMvlGXhw7Cddg/KhYACeIPQirrbU0mgZz3Vcj9ql9qxdyH9KGmj5BgqCmHJDmBx/noWL49JrZve4FS7FYsHunQwn0B9VgPyQGi7v73WSYBg/OS0IsA6uhNBpbVax9ckyPfIO4SaHaWkrkjFeQ1hQ/S1YejJuhDMSK8DGjqx09/zH3yFv3658DHsB5XdPRPjTpsxL3q8Ii7oGKMb8WOYeQSAa5++sx
    admin-user: AgBOmLkiL+Gut685FtJLT+8Ck2GknKZ+ez+s1BI5dsyEKSuXV1dslk1BR96FwFYpDeW8OVdXa+COoTCKn5Hi+wfeNzEnC7lCE+iT3EHN+AMAkkkwIHH2vQVu5siuOxz0BHU/4qbgmO65AoHLJkk7U6qcfEoVtdTVqxbswaPji++XDCIKFEdqpdKbneAU4NxcAw+ybLVtxHvmq/03oHvUXRk+++7XPLxfGT8rIcH1W/0iLatOOpTAM6TEBxVP0j/bQ3XjiIAF1Wb1Bms6Q7NNuOMu74spdqMDbGgFiyjDMB2A+D9PQsaqLEMAweU7sLu7z2mSeRSijeOUGfH+JtQQgIl6xiYW3d30rnZUfoIprFgBfkMO71L4ZvcR5q8YJwD18zJItfk/mRndv/RfuTIewoyFbyQBzPie2WFee4htbiM9uMa25Ks4xNiP117CgHzm1FDxWLmDK7LiztgtIzyBT+J+DfZtkJe/424XnYP4wbvBPAEAAPpAaOu2fAbkGGP99WCASoUPAoD+CEzncjoCkncVxqpFAO2uZKzrQghrWrxlhrCkqNcYygigGiA/gKc0JspW5acxL+m6hoiT6E/OGVmUX61zPE/6vCCgb7HFo/QuyFzlxWIDjF+BCfyoIf/EchnYTZ9ze7n7BgC+DyZPTqvwILDgpuvTgPK6QsNpd/SzDPrwopQGLZDmSSdYxjrnJSLlrctgWA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
