---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBEvv49HJ8VrvD849C7VfDPzmE4RHkOEpBUpO62OVxtfxGmLVi5c2c8eF/fsD6B1a4ZU/YyVy4nDJ9kMmwBFyNo/RgfKuNjpKMyKwSBTe9yxRaTbruIO/y2+6wMokvh820Kidv0T4prjfHhscOOtByVWSqGsHKiMsh2xCMYe4Ex+/SdzqyH0D248XAaO3u5102Z6KDofDMi+v9GGWqamdVrZ/jtUxOsWCAxuFjwrPVo9m+VdOq4Wu8OjxJCO8cBk38xmrWgCEmux9OOebm9+C5y2kgp8xeTDGc7mWh+Ca1bxkpRFFQaojeomAvEq/xddXjefoVgW5LmI02Lf50ndvxISjtGzCxBqDo7vT0v3iHO5veIvLJo+pE+KeZ9bQgmbRCUilHhHhGLh6JJrc1Qb6XylSmTXmLmotvGr+25TxFDCa/MQSLR+RgcnLI8N4NFCuSPXljiaNdrEYfcUhEIknIHUHIVbe72+ULOBZ3OtHoJdUhUAP8zIkg/8RtZcCWDFpEhW9l8KjwcvjpJTW7ect1XYeyZY1qkHGFAi73DSlZEKfaIsdk09FHk95yuVzxxcm0sjqIzTVatk7gTHb4UloqGny51bBhEmy3sWSaxghXspi9nDaNfiS/QeK2OMrxcoZC9JGQtuD5ovr91QF1HQ3SAgFvjVBaRv10nDdL3VGZUbHSbEXjNpv4n0T6WTy1iYJx5YuOiknrr
    client-secret: AgCqKKa/Ua10VzlrmmZvkwgwp7LM4aOYvWEFi1rvpcWgAyF0KGSRk/d1yuSpcKR8A6XPH8gN890BJKHD328G951o7YrM3rEOXHh/JNLhUSCs4x8vbr6japABjGHAQD1HvgDtO+PgB3DCYiwA8j6FN5VF1mVtvVbUKV0xHEgIUtet1inmp9iQuG6RGxtkYahJZ4n8q1+37B1qp8+agLcB8VIvEz9xpVIWVIKbEE2qNXPkOP4k99Xj02u5+V1gsrbKVfi2e+F+Rjq83ZMLLywxbr8axffAl5kkKK/QGQPR3HydC2vlqtSalMCerr/ArETRvRh/0RTaNCRTB6W3W5T1i/eN2Nd2N549je1LsUyNokV0vOzLCLL9g/V8g2Pf/3fk3nmiHFvYC7bN9tFcD5SqwaKhe25Umkoyq3mqk3V1pJTSS/zQ+o4j6eoCyn61UnwDGb0kbMH+flp9IWuRdDOUq4nJOK51C3CFnBDuH8GI1IcJV0nD7lFO/5Ta6kNe5MmhhTV6fR+fij/wrxB7wx+4oAofF2qDrcUqdmjkgqJJDM0ckW4GC3QJtJqMTj+2W+DLm8wFzI6zLTORCaodmnw8asWLz+M86xNbs5oPuQfz2/b88dxh0mHFkIczeDu9OHyrKsstuOc1K1Thaa79h+ff730ERMA6VUH0Tu6HyUMjYsSxeLejy1uuyeFXoDSIZJifT4kRnkm5Ee6qieGrrfMX8SBFap4vaHvILuNsWvEclrnD4g==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
