---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCSPAxmL5FwbmdAgTgF5lUqeM0veTAi5IGP1he52A9LRE1yHRvm15nLy7ma9wuQ4GlYSR06rI6lNdl3HnhvevWU5QPLRTfBk/npzRuc8hhKlvNKMqeCTJHeWXimfuGBFaF3ZnzNxSgOBpMc0OS9ht7oipR6LoZlMXpDYzNKuxb2ppynH96A444RYX9Rj3CiqQ0d0KArkFPDerU3rH0K32zuM3X2x/9Kjr1h6lCxDz+Nw3NFQKrFJBmmq+tJBNK7njUWh8HpK9mhukZTeLO3UQkAoTtCCmAGajR7i6rB1OGQU9Z0z2WOk/RxEtiZwogaEFX/mOovhGht9Wlhw4viOdVryjhDBCPp0NcY3Xn/6xyRPdwnaAxSkEqeY495SzgUb/uL6dY36HDYOSI5PZ78D+x/sHDXLZBAw/sNKFsZIThXEWi11yie11yRyCwjE4Ta1rww3nSYCQrmy+U2ieoHW7i+3EIfZ20Mv76MmePDI8HZIrOXj9sU521crCkM4jUHp10h8MLTlubOThz3fU2QyLLAp7gOIU5QQCBtdMN7fQYNYUb4PRjng/66eDZhuP07TDE1uEdBbKZoQ7+/XRv0px/8NVoTCQloBX88atXRt52hvcEJN/WuoiU5H4Hs9tgxFPq+mHXQH6QAxkOfLBFOPq+WYV7m46xzc8HebYIDHk1QNt+R7YtocDAv2+PCnIMq6p+lA9gql6wT
    client-secret: AgA3TDrTXWfgS5N2qnXCWQ59HfMc9s4vLCe2SrobFQcKGBj6fPvYFcngeFJ57JiPT+bUXwfhqPEF8Cj3s/JI0L5Xkkt5QiBUm+YyAsSyfwzX7CunYJTlMVxDbBHrXQLTyoRE3pzffID7a0YarmvMelMOeXJ0MiTrRh7v0LI5LC1XMjil9f9RxNr71rLbF1C3xmJox5Ps1TU0C4R88EldNtbFzZdZdvtBFBFbn6LGoRbqBCCzMlNACqOaqCp6V2H78wyb6bEpPsgeF3zt1VNSl9idWXb2Vg7uqS/U9fD2pOc22VF2AXK3N4aHlzss9oGOc9O/XAaHK9Bovt/i1cHimKd2k4SdpW6fezKuQCw/nFZR9TheVthYasqnqrwNKU80j5vi5jTOZPz62WKoZ5n11BzOdfGej1lBo5xeqr5vgHUdMFsri86qxLa/RfA9qbdm4M8/qaHnFrcqkcF1HRFEISjic7Xe0keKtVrDqNxLBhCeKcvfb0PsoZW541sYJ6q1+rnW0zZg2EQEqsQy4iYgBqMVvH5O8v5KGfJsH9l2DAU+5Q8BkIey/uun182o9a7uFeWZzr9z6blrk8WqQDiFAK3/hHkhrVW/miYgiMr+qxNqXerQXwCAmiiFX7kIAfsUNCwRtjrMbtB65Gg9ND3JLBa1lKIHF+GbmXS5sD2AYuoqmLhKmuSpRW3jhhjj0+8VlIOA727ToLFjo8zPob0E/dTHl5CUq7AH1hTnM07FjhmuZQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
