---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCx1swmQJT0C3RL58XU5vjfCubHbhnxxmTG2sgE8IK3nW4PDJ1Si7a4d7tqafn6cXZCz62W0j2dv1c/qRE+ZBEAs81uH0QLjjxGqodJtnSNYmcK1eiga4vpXoVhhS+lJTJ0uSvFZJfYl4I22BaN8gZBW2dJvbUyZfVsLx0TM0gWR+Z2auFQHCF5fQDx0sPK5r8tgoAM2qWEVNtmDY6C3ZgPzLtSvuGlf/PDR5+8Yp3E/fnFQX6Q59ORr/2tWv8HsBEpfvmgZN7QrGZS5DzxPFQ4UXEvP3cNIP8AIXsmytUWRgfkLVUuy9RV4VVWeynqbdDfLd2cg4CkYvpYY/IpOksZOUW/A/ZiUIu5aIHrY9zYMbllhvC8pogxZj+4iWSoyTNqWkaOsgffJHoRHH48rTbUhbinehcvZuyDU666r5UjuVgxlWPrY2mfTVZs7CrTAOBcHTcd5mrXjShsnrU0eDClPBLtTGiSB4dnYmF+RWftwNhwyBnfCmJzseGsZPcU4Qt2JbYETxxig4FWFlSoqm/uAaduTWFPkMf54VCq29I+Re2cVlJuAWpVDCVXun4y9sABe5I/lZ67TrguzoxJ7Tea+J4z3kt/AtjwztGfpbRW5HxTYdakKFwnO3tmd4ejDYg+sMvLHPt3CpYi3/MXsN0FXGkw0/lo6GNWqQp48HYip5JrOvrugfFYoC5jgZg5tgFAOKH2+F3n
    admin-user: AgBgBI4KU8WVd/LmvQVMXyHyTbYm3kj3tfG4YXMbLLojBOBMTFPf6RSsLq+qUXaioT6LT/yxu77ZFTMiv9c0DS+PKRRvC7j9sMmrz8TWyOSOfUDqaSzmm6/Me7/lu3UEdY9ZTX7mylGrf4qo7jtpdssC4c6+fD5/QBpbosz7tJZgCCVEcoNZXVgiaseNKU75RWS4VEtBYKAK+H1EJQbc8ndifWAnnOP1rFQusBW/HIgfUaJeFmpc+yoOfHarKrJS8Qnr+BXZX7haKnOz2zyULH8OdG5j0GGu3P6uAmWCUOSPLGxdC6Ehe7YrLL0zs2rLLlMzmmroCXON5qxP6hvS41C3alW/ZK64GM0KZHx4uIFqYH2Z493bBgC1JS+kdiq3PBwp/lBvCyywrvM71llOGBZIgJv22HmBkjp3mS02yWZ9k9V6T00lXsTbwJaqVzG3N5y80vULsF8IAQa85xmBfCKHa6WTYGvCjc3bf5shl+VQdBJX1zFSKNlDOM4ruKj6M8Tfz+P7L9yhHaQN6MiLd0pJ+l8Cz0y3ttr38iNyi0VXBkQdzNuGh4NZYN0nP6g56xJpb31aqGiXWe3ewi9f1D6Zii/DuATRF/Dj2eM/SUxaf27TbLFqzvkaxgjRRh4laM9LQyNVNy6bUD8HXZcuJcs77MYcddfL4g1YgLxwTOX/ymIfTKIPyltQsQe1N3QCIFdIBzeGkA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
