---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBEKpr3lMu4c59QAX4EjuPk+r1MI0FCynRLgkznZR19kGpBxXe9rmCgIDxRrGvXlFJkZkUhI4kQo3RPG+/8NlczG00P9JXMsME5Yk2ymaTRhubjx1aarEwqrmLZKf5ycb3IbdNXWHnAXIqHqLPPyh97p3S8rrXo8yAijfITfzvQk8wpihzKoRO4Pl1FXANFjTeB3iNooafV1Q7ah4T3qXo19eOm0cq3JRQ12ABgW39TLwSyeyBIalj6/P48PiOJZsuWiXpfVxRKzw1tGgaMVW3jyuTz5ZQU1NREkmwzqPJW7XXJto2CsNLUlv0MEE/vODKbG7PvNRdFm6+z7Q2jJI5tdA9I1+FPJP/b0pPraIZbHWc65yvF+ZEnWyVyBbIA401ZlqEzOiIXscTd9oX+OgltIomznUZAl4GSFwnV+UTeHpsZwmaQu+ryuehTi+ktfO3IZzfyPT8inR3yBFElXHdRLgokxIQLqouf94vGTAVL9iYljGhamJ+oJKdsVS//4YMp7IYcFwPUwbyUrF0nfYzM7YfCcwBQCEY3jEe2eJlevbcKg6UUAEsMN7em76KARa44f+sEK2Ua2j9CFy5/pJTqRP/529ZDO3C7CIWhROSZsyysWx58TzO4hUfECdGsxoHOgZ/L1scDgjF9OfhL6wXCWcYOjNez5K8EiQ0e2h+KPwkdkFjMw6pgMBwvS0ADoLYqf0HW+NV3
    admin-user: AgCGB6mAXnYjVKDhOu0hJFAdoUjcFz45lyQhPLsHHprzkwMDinwZdmnmx5ThPPJDbNX/0yc8PZQDdsqwVIwh86YByxCdekhlby9FzBqhNUa5HGEMxTwETmI0u+kcwLHwN2Tw8SycmeznpQzHL5IUSYiIK2S00sLkCL103K4pDIR6qTHUKn1/xMGoJ1ZnYtFMYb+KDj9H/4lKAN2WORntwloYKQ1dmEX2pQCKOJ/GrgOkOQKdU+bF1MYzTlkSgiZw5gGUxedxiTCGUFgsQCY93Gha+INtG+DvneGsuMqSfGRCBGrFlTc301Al+TRdpJ+vOoven/q/XmapDXOV6WJVxv5Q2FKbak9lbSYoSZ4iEsEXocfakD4qcqay+xZstxY6Zu5f39/rsyKdadlVaRuGtkeC+KfdXKK63lFe59y1CkkC7d0EI44I3YDJXmS1JsB0mZtOJijSC+9OCC02cAbuLPwrp+cVp3xZnCixDlqoOrlKydAosxwdrNzeoIX6Tp15rXw/s7yynV8TvYVOuxYis0/CCUOgd8RG2P7vIdN+Veb9xQjJ+d3Z63VLikTEL+YfRTaYZkk18/pwef6/gKwljWwy9/agQ59XcWYQWXKNgT50pg6+GGXM/1Z/3F1rltXbO7Dlrf1NXGh1dw2Ildp543APz+d6f1q6SezOfwKzbXvbRHaaZEWyP3BZEE4XZv8WsJGOjqqyWw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
