---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBTXzKt8cqVod7VcgDbRc8wQ7wnrqnJkQjTH02vRvye7wd/dCWDKRTmjJIycfgmZFqrSBBhs4QGVTuGEEeEudNkSMaK5FCmprCHkgNpzY2uSNFwb2IDstf/Xy5ACrOmNxtXdVgmzuHtQw43JmrzByf5wX/yXjRbOmIIbiZ8PRlizVvc9ffzgGilbLw6Hcxpxc7jEAZQ64zhRH9ITupfeXJ8F/fo5BEVBEaVYrLYCPdWllMGslE3+G89UVirC/1gxeODyt+WHgt6W0u9ZSqtJ7h/MYuVAXnLr+CBnQtRooC4t15DCgALzOyULECzE0yNPqQo/NdslPQ5T7sdI8aqsmQW9Xai3jLXFvBfBH8JFRqUaO2feka8GkcQf9jFgQG3GMRD6Gd8yGfFwvMsjJzZKWmkvyssAxKKmzh6pR0kY2GuZ0755Klop7uhNOHDJT73NTi/cgHwR5Eu4hmE5C8gU5HA4vztuLQP+3BcjOV1h8eRcAmu8IzfeSu0ZYqRvWfeRIL+xS8x1uCQQcGrv/6XGducF1Ph9JMDynyC8/RauAUmvGeKvmI7QNeAoUZFRhHFLphMWuTPuGB9IPU98cLYp8MchBDiXgYhT0SeUcr8ad3EskN1hWBVGnRw9YR97nWd5DpTHJRotHBsHtDAOQe7bzG4fQ8iKhcXLW+W+nlsclmia7soEUgWvzCLrrsm3C3abqfU6j9tio4C
    client-secret: AgAowZRWBTf6PgUcTmhYn8LSu0b4nv4Ejoe79GUx3hjlMIr6twLL7HnoVP3QLnto+i9aaH5vCDiPFIGnq12qddCNCb2XxIzrm93+L3W9hRjnGJOVmt2KkjGUPpRU1IChOXDurX814pisM0hEwh5dLVmvrWN2oPlp/jIs4ov1+pajG30r3V7mokVoT/eEdm1x+OBlxkBlNtc4nxmWrSNbKo8KVzuRCkzxivWZJd9zkQFBnHi1LTjs3nEv3jdvZ4yidegj9BfRagkXua+ROUBLjez1ixo1xKnDTNggTij5ZJ8gLRAeNJ7p03iLzQ0lJFxz/DTNG81PdxDqgwKrtqszxNtVjdcnVzTRN27UR1GbKojiDP6PcB5vfngqLBt0564RSFCWqaKRcKT67kBp70fSQWKd6kSHig42htPTtEJ2CBCq2jRr4uY17S/AyyPnj8VBTviHRePOGQaSMeMmBJNN+NUm9dRMrpuEFRW94wATgdpNzbaF67i+4hsJ4+Z710lGtwWNsfDTijUTUc6NFYjRQX7j1fkB/kVrEWYtQtIJMlm1oiArKm7nC4L+yFKU/F6EkZ+lyDSPZYdd86fy5PawHGmz9g5qey+FLXjB4gCmfldJ+DkZ2XHkdrY37YFLih3zIF2DBI0LUUWSDd4ZVJcNn0Nn4dmC82vl2Eyx0E9jTxhMl77YTX0hdkbhgu4CLPYtklC1BaXAg6LNuvfAFXhPX+oRj4lHryWQlokEzpcWuXIofw==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
