---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgB5HDSQ0pPVV9lpThAgBHlUMJSxnZq8f87sacvSiEtyxG7buM+IoIn3HO7fIccm5fYNJ/4Wmdc+FK4cH3hhKTIXUjy3i5Y66qJwLg/XyltqG+Ie8TsP5gCHB4VZiR+VNuPSXAty+qvH9DGwU/e374a5ELGfo0KcXNz8On7phbIo1U5oURAq0roW42tk0NnLQC7nZVFNwdpuxeyMoaqDNtTOgRRng4dCZYym52lN1BX02/lPLQVcs29a6Hx2f8LpYj3CY1XHrKoLv3yTjQKpdR4WRUY43qSuHZgdRuUP18Ia4+Os9iPQTSk1mr78PDb30XknbcbBpxfWJYDCj3AZXUNnlJg2ELMAQ+NRf7sT8aVS9VdzhQKtv60cpnGIM+JELbzcfQqxFxW5P+/IqB77GQZ9pkJb63J1xWnYL1+rDJQFZzzb69Bx84RHeRrp6mHaQJTiw0csY04hg1iqtlIQrSK65FfQtTjeMeUsrnnXuAMJdFA+evTuH32QWSrwyoeY7D4RtEc4Dvsg86XyUXcm9D2BVbKvnnO3kApVwW1gRZGUwutwis+ap0rMmUkfwoOike/6THYLMqwNAGChoLbHaTxpKSiS56AZihWgrqqPfKrWzVplj11/8vtN0HYn/NMxfM56Ujjlt66AbPkd0udhexRpXIWaDQLXQEXEEj4zqxynC5tBPvtM9qtJGux/Sl7BQ+j2h38foVWv
    client-secret: AgAaeC5n7CHXN9kycKfT3zkjkbrNVarVf07aU1kBRsxb5hypfxPB2RX39fvJvQ25ZwWMuLWnBYZ5p2zrKwd0J5ezUzx8rNFV8NUxIwyqjk+UlNO7biBqd+6ERNzt8xNEU92ea9Z1VRGvBYkQLw/L4o0P81bM/dSKhMyJqWQl5gLJitNN0w0yOmjzvM7PMYltsa1RNCcwmgvYqMwz+ReYGd67qAbWfGHRjQlLsCkzUKvCJYVbu1Gf937FDIYKlbMpmRVr7VMDoDzwAX7MKVun7QiRR/LVGDf6G+FMabivHEiVKpJ8a+NFCCyuYNgJe+h1yX2wIjTgct2rVLte0rN4OPraP/eUBpjgrkwJ2a+ke21r6dQkTUjMX1iMZdZ+O5BL+lm7m187YsA4TEJZlfq8C7YI/1LPGW7G+7hEay24Xi6Vqa8Mj7HlQIwDhYYZ6qUu2MdSu58CQRmjn6B2Cl0JB9tAT8eUlF6ImjZVrvCqhsSN/T+/N+tnTMB6OKtc7E+xv0rU+V+FD/ThJllgGnLua7kAnUJs6r2bp04l0F5WICouYexZahuBVG3jEFe8gssC+RsrzpvqZxQtmSe8wyVFPzpAI4wZk/JNWYj9TXXTSWPpb0Ywzne9tb3D44uIOKugUEg1lu0rM2YC88AHqMsHt6lO8t8SmfBmOCN2ftTGJcOqZ521olIrzasL1RWGHdvTjTRlhXCSGz9YOA1fyzBaRkQumJ6ewAgYfeFwXvz7K7qDoA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
