---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCGqw5OPPcwaQIoltQJENPjrYgS/cTINHfaypsK4HBq0L7hni+kDMHC2q2wfyqaNs5zAcEq7wbgWx94IbO+qPovOFrikpLWm17kYog5xl1bQ8IeEQ5j+n1EpT1kY3Hb0h150lxEKtxHMM+4P8NCInQKHuXgnUDBh3IPDabbwth2kvPrOeeChO3s+BwedUqBM7HF70ib70YwqGAxVRAgyqzqTw6xGzD4JXrjnxWKiy6civJGwTCCZ96No8pdWwUM8GhLYHTk7xw8MS0UPZid+XQYjqv4bq9cE3rCt7m4+OrFclEw1L54WyMdiYH69CeDj6111I+fvis5OPfBjUC+MUoAxse3GDAEOvLuOR+n2kWazawOVAD0Xp1axU3nJxlnnNmR6wz5aSdBmbIoiwYI/H4O0gilkHLPt2IoBem9GfDnTzXAC0AdH15/3kvjyBO4Yru11wUk011g4lX0/E+SOlLTfIG6nzEaVHnhNfAPmeLPCGSc4zLluswhL4ZmaNbSA4zdtezoyC3u0tjWOREZv9i2x1VKrMpx9WUwhm2gMJeXKtzNLh6zbZNElr/HBr89MmHP8GPuOa5ti4Bjv7ppbgQQ77JBwmrBLu7KLX7XUMofRD0sx8yQnJe4qkPLpaftr42NAtDEE3Kfap1IPnyrAGEDxhlAzeyoLwxx522eFEhOcbiNW7gDZyDdN1n1m49bwq/e2AQ39W6e
    admin-user: AgCH2xJPFd236ZysLg9H+OVLHUzEvmvw4muxHp9CCQbF7zUw5U0UHj32xks9Mgb9XEPoZ2QUQgrkkE5E/7f4S7UWBgp5pg7CD40wlLOj0xyRxW6UqVclcp/MlrsQt4OLKsFm5hu7R1Ns8WA5EBSRtHn0zvD1jjNYc87W79PrpU9dLlku00GzO5hkyIT+2QMjqxzdnz27yC7FsRnRlW8HaylAsOTBLFkWro5SnU6s3X8YNF7zPr8OsKeRWHEi57Lqf/Fknc8G2bj6kurz2mqj0SRHZXQF6kVPiVNDPulCxVBPNtlokOx0wlxbP+CgLOxZRprx4t7L1d1fi//ASeXezCRl3BeSW45hD2vEhHz0mc6573+jcUvwnUWgtp2eVZnWlYLZm9n5ReIHD3Z6LPRG22g1v2j+3OupntV8x1D+wTYXeZ2ezUGkw3gztsi5U4elV2wFZIlJAK0n3BDm+1vH9V845RTdG1+0b1oZBVsKJoWi4WKjOkvEF1yls6SG0jwT2dnnHH/ZHtgCYhB+oBW3WxMDSoddLbn1Jhh6YGRhgZYMpRL05AI02KNyeRbpJZoZ1JBXsviK7LeEp/4xMKoa14Z5pufTJACs3me218qQjqX926STg/Whv9nankLEJdJea/RSEppYZFeMyjpA68l+QV31j0Nkfz6RpzccUG9dKMQ7Tckd+QW/dWhkmPa5p/a1FwpJ13n0KA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
