---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgAukkBGP3MRi7GP/zxIF3o/Y6ukGSag8nAoaL+n8tjJs1JmSOzAVfzi4o733LPDnUJuDnpx90MJXCAVpIW01cP8PRvEqYD5vmJJcmKJ84XxpIg51hctdNrSktJBYg3xR6NitCgMV0cz63C/UyuPAW1iKWVkOlQBSenNHl77l1Jj+YZR/0wTMygOLZ1eaFN1l9FKx3ySDJQmahZqtaj/nZgGQbL1Q7/Vg1mSC+vK9lyQWJ6r0hDRIHRF4Wxs10AvX//kihosk+OrIxcJe7XXIzLYHQFobcWcobiF1R3cFNAAYqPCn14xQ5tL69Tm/H4HuACpULj/7I8NAH7Xouhu8ToCw30c9eICVMmcaOSS/H3OmIP8kGbg9UNMstbcR+4SLqdqd30klUcCNJdDRH/K7qKSLqnilqNAZ0WPsWZNgsF96wOaSU2nmxZEMwZwJA9qG5cOgIUomofRb2bIl2vCsJ/kCkXXQFZ1vtcMJBW/TfTtLAEjxG/i5FJGI+3g/4jALvaBHAwaCNMi14wdvlhYI7mq+Hnk59TKkoItYnm/+cvNsyH1pruJMO6EOOsM1Wk7hjGqlqY302xSjK/Z6Z0wRy0daSPqe+z4Y/BZllF1jJ44t075tP01VmSemfjGEwGhmPWMZeWXyMSdBK4ka3bAJBAAzL8iPePb8tFX4ovh0VgMEi+dWPdqi7s0NHp1pIZFUrliAjiiYKWN
    client-secret: AgAp81EOI0/TB2NjqwVFgTUAExB9otaFfzWZBW+070Bl8Yu32AyiWY9ZbT2xkJSA7H5gvqmzqddHztvuoUgLBW86PaQ+hYBiGpGpzWdNmDKJP10xE+Ey1oXTt7jJPQETBlTYVz57T3x/vH99abZS8g+1iYuD/YXqdIHuiG5uamJZHUuIzwL1BR2ucPTmTIwAu0ifdn3EPY/JVHB4IdTW72ASCLpLAbAHOKBQhmExNRDyHxpysi+EhOZwMLiognUNTaJf3UuYkd4CbG7vMYbfpNdIzeNEQseqocVngiAF0eiSitpmxD598HbWwTM/I4WeSsEvATaHKKrfYlfZBSI3yluiGb97xNWcPYc/dNyISmkEpZo9ZkCQoBq8URP8IN/Y79EjaB+ctp3Gv3NPwERrFDNZooXANYEujO1Fh5TwPnJhHpCGC7vr88yVxsUCSuXv8v2vBBkyvcW/DN6MAtC7XydXkaW5ZRUPQV5AZylDzJ47dfgItiHADx0z+4n44ArIEI8GRyLoMKeLC2LJpHFk5sKkZuwhKdezZttcvA3J5/J2qd2mDX+vqCq6M/FMZ5eBlv/Ek8yoXy19jJkeduM7mj4Ge8aoQHL/cc/WLX2gkn/NuiyTApCRYadswQNG8Eae3muONOuicj9qDNwQAMuvR8X82RPcbWjZkA5rvdXwcpxhYR7gZ3CW6K+z6PYa+dl5KZvc16oGFAc+l7gGHKR9qpM89joymVByaS853k3zuYPwUQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
