---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgDEQn7+02Fw4bhhDwGBTi2SMTngtrCxcDVihhfU/rltE4IRSw/nSvFzGD7qrq2JVRvTKp2wSU83FLeNIds8ZToGEgJpN6xTHnM/MhJiJs02EM3cs3oQHLFlqFD9dP9GyMWlxkfNlv68Milx7xKX2JcFZ7TXEJwN5WrJGMClI5B/0ny9td4ygTzKpvIcV3IQMOgICgVQyxE7XbQ70Mv0EJzpefnOGQlCaekXDj751E1Ogcuhk0LT2YVcJnLhgLclIO0NtvMe3IfIn9DxiMEAs2BIU8SrLFvARVN/niofarkhNNWseA6ngTCMGJuqlNqvzDBUszXZkK/OPOBfpZaJWwN2TRsMpsnY/kcTK080uiP3MfzFjZPFaTlFCNt5a/goglMbYJGKc0jNTnAfc0dnJRraGZvg5kAaN4RNHoHvOi87oP4aVUJqNHmrE/IoQnocDWTmPrGJO3Ceqe78wz+pVsc6oIayU37Itl+/FdS/naVJFQCyC9WC6X7Nl2/op+1Iqi2rO/3MQ4TIl+Fj4K8m/riW4gxkp47lPYROtd0+PSb4A1jK8wfN+PWCWfmE8rr9Aag4XihefN6HkJxTW+RwxYbGmw9/xXZyKHMISHR66K4/DOSfu/4VnXbHGF9W4QETNbpfNdYaCJNfU6o5CXait+cIoYpCHB5AGm+IjeAPoanBsnt7jjPZTs8wPy4x0EGSyMU8yiuak6Ql
    admin-user: AgBV+PYtIBWaRLZifZSoxHs9n5zlf26HmGCq7VlHg5uNfuAkzawptryUWbU8uXxntcDHWDXu7Pav79NR/GL82Zrt5jJHVprNQFU1lNkFiQyXW+drdSaKz1auPqqdV09/8g4KDy1PxhOKGbIDZXLNcnDog56Cm3+NAEGDOM5/q8hMObWSOCpW1Ci2L1gu+8n8hCXrkEK2Wus8qKEmj29h6ZJSZD3zxKY7LDseTbyYc7y5UeQg2pvuF9jt3lws6k1OMmnGhcFG2/fmAbggv07SYlPTXCniHcrmLDyRqjysCOHfuAjngCC5bUF1qlP+EHa8J0h7QoPIvwT/CVAb1Oy2HDUXs3guZUtcx+lTCVOlreEKph+2uqr/gq9l73pqsFKrOtsWiOkaSWgOSvBu60HLuNsXdZDPn+p1i4DKZlZYm9Y2vaR978ICWBXo4BDm9eTniVI7S7T9VUBVfXCUfsBOkTX0F2okf/0cVJoykccqk3eiTx0jofdZJD/YjVQ1nGLNtdChcdZqqYmovKalYRYTLfQcCqdPW7RazD4MkdY92IUOSpVPR8mXHAgN0mTjoYeAlu1Xr1b/je/X3FDan+Zy7cJ4OYbJX5dzbvoKj/0CPqpRseDnRGrna6yW2dsb4Z5dtSbloiAisbij60nk1q6wIZ5k6fEYJ7i04aZ1SzlSVd58SQdaJs/rWhxCL6MgNUX5Kbo3OL8Erw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
