---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgA434get4GmSI2uzPhTkynTvlfYo7HSMiQQ0STbZbEmpb1E1k1u+Kd5XzTzvR/Rvl4yF0TEolRgFHTjFv2wggeKbkV32B1kEp52hZ65e5SQu35yffWIT/pB++eGjjrcbKE8PSVq+HQVLos95d+UD9E/R4TOhT3YaMw16SrvBxLlanGVfgXmIR/40bCrIIUaRcHFs1qciTtqRyyd1U3sqhERZLqFv2mj1sD4HN5Ft1z3M7HgIPSgdVKVLyPi+ohjPsdSw8p6Tx3DknnETRXIsMpFq/KfLEiKYpfWPA2aYmZj2CHL/i4/qWoe3wK+wJqr3aoafU9OJpovnbYTLyQ/7RIRYNC9uv4V6B6xUQf+VfXcRzZKBfbxfhCufQYUOios9YV0h3qoskBLQ9KMSBktgoKqKRaX7Sdjumh00tVUOxymANMILIHm2rykFecqmEMo/AZOTyWbMIxpX6K5pPUYvl1irG7PHUAxBSoOrDAKmvsqMqvFBgK/99ZS+jmo9UzIY8Ae+VAjU/EhWSIQiAhubuYTeGvriTTSSBSCGd6kLZjpTgKkaTpjHLmoeEHl5sCdxNToWY3yc6pgvxypvfPvf10rVQEUuKbIPWUhIOeIkNjLl0QomJHTdkKoO/ghUZwmiKY+7juxc8PuX8c8R8uOOiT9SL0SHKOb7r9cqvBK0EM9pQOGM6GxEsUjicx6dObcBvIcwlIi5Mru
    client-secret: AgBPxglvt5XFTWbG331jmB9QYLVoByQZoQk+DdegtevOpxj5ttb6QU7YAYlbbhPovwkj7KumMT0w6CTPUIMixytbS/5fsn4tk8GPVddSq9Nh3UoDW1TGFFmy3lljge+OTPL4Czx6bdSyHu5YFancYSsIs5hYdDaknCGMisYIGNgKh6hHuRZopiqaU8PFhQ5h/wPyr8SBVaZk3+uL9CAYN/mI+DP7cKzQh3EbsPM78k4ZMIzyfFfW6Najln3P5YJxd2L1PHNgr3UyCaQvY7IyvqqvzPaFsbw5kOTa6QGf6/VeSamsJGywrGGNolEorPuNL2wsdKn7reOJAF3Qy0hK4ZQ2bVld26X9w8FggDPfARR2YYDrQOGsnlVj5YesRqe476ezD5F9pc244lcLvQXM0J+BUc+DYTMnzsR5ro7UVKV4ypX08ctM0ZWBzbKPm6AYSsyAcLw321/1n9+9NZCWDugl+KGW1Ji3rPUbN8cBWMn+XyeS3vF5oPOAtHVoJpJ2Rx6t2zOguEZ072cdC1SczBgtssQrykKT4eWBMYl+HZUElft7Y7tXvsvxKA+O2x1cXGjWqPSgiV7g05idtIYmqQOrHr+pzxAoTPWSd5c0nRCsd4NOlrGvLo14GfB92lV63u49JRSD5AyfU7QroEO4SrT7Q9Hmc2V8gv/vTQqlj0kooKb/hPt6Q84dIXi5UpwID/fiWDKXDSz0G1SQEvf/TY1X9RFsRksZz1o9fK5jXbskSw==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
