---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCuyrmDfwbivmQEvnQSUJJAO4cfic5D9Ywe5ma8CdP5FMUeEa7Uu8hB41f8VXYTBWJYtm+4U4nGxN8WmyIbYYAhmx+Bbx3Izp7Nz46VCvu3xsDhTBKNHUKTD4k8cbgTydjdJbX9l9aQMC1qQG0RjRmdtcAFrhpu1JV4Be5znV7vd2yvkHWLfNYQiv1d12u5N6LH8LFulv/fdOIvnY0rqSEMEeKegECEAyPhTMbZmBgaF1qaQIkUyKohg9Dmq5AxGZmQatvLPbHBku8+iYPfoC6wh/qFIhRgueQ1InTQGd9JcAvCHw3JPEPLAcJSpmzQubXawEY58DyqiUQRx+KezcFV3aAp7V8m4D1Pe311hijY9JgU4PKMYFyJg9yZVsHEJdZJ7V1Aza+/lBcM8T8fRgavON6dOzBOwY6ptKMRUNLvESiJsvepYQXD9XKR/IN3TBHhUYFuFGbXXF5z7BQeyJWVe1nOOvRP4Cy9a30xeL5L52wSLgICV5diXtBf8Qu0AqSyHKW4mfz5Sh31k0lkdpXcMx8V261TDk/OGiFEqehYPoz6tame9ViUgi+uvMoKgXp/Iq2eYv+wUA3NbSzJXswPvoO5ezaQ5eOslg3R+MXNX/LR/jdueQlrZEDc/+34vdAMVRlNpDhPoTH5ltyPcoCeZF/wouapNGw4vamAuO0zMz4lcMmfZbNQV/6O7m/V63a0ZefE90SP
    client-secret: AgA+3UhWEFdsCpNYo2AR+80UO4Y/Zs9phKPu/nK4lUTqk5D0e2/j4ZbPlD1YZ9hR784YMDZankWZ3pc9kSvwifoJovGrvG8XlfZCUu52UosxxRCECe8+UG16EhNO3FdMH0OpEZSI76nNlEgDUHv8Mt+Cd22TrusZR12W3bsncWVtfYzvbfalvkxK+3yj/K1rapOGpfyST5K49IMKOJidOUrLW/NwBd1Xx4Uh7oy4wGMn7qoH1MQRUjviY1RCDWayGMZwovKOr23VXYKMAk4K/FpaaFRVJLj3UPhZsL8Ozs52TyiwxAM2FV/oSf4zgOxcH0uHS2H03GDu81dJf/+96Rhhf3YzC7M2ub4vBs+WJHK6p3rppfUQDW/p7uAz3dxlAg031aONasmOdKzPCK+O3vmCA7JolFbhgVbcaopnNkPoGm3mE1cDShtHpvUqNp+dmPLwa8XH7Wrmwoi5gAtqCmc4mRKWv7HagnJg8mF5ZxtBLfEN2O2T1Eh4on/1vdJkld6Cu0/8RYHw8SktwnsupAtsp/dbfoAwcZKihW1Vu72M3+YFm5MzhEV8pn7POgaDDfh7YZwsZcosxudLTRYRGez0CTwSbue3kDjfkU+Da0IdFG8R+Y/7jXw2NWD/Y+C5gvdiFJeqCdqO3QhCtLPXkPDKNflKnkOx5lMkH4gxfxjxwFHgT9MLS9Tqct/TXGKKRNgQ/+LxrZxJO36CtgBuhJsTu/doolYdCmY1rL/3fIAAdQ==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
