---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCXasAiHI+kS265hTb5/KxVdOweLXxwmbI85tGmPCO1t3NHYH01vQrVrvSc69d3tJxaGCXuPeZI1o7xlJrGh1RnufpKH3MNWeWqnTde7XOJBp0NfPIcPLPd/V3iEnFEzGR3C4kvlLDCkICnkpoyyGPpZ+C6GKXX9J8MHElDiDGb6G40+lYy0ONuddqBiGYqO9jgisRbeGQn4/+nVU0M4yCILY7kj0GRqZ8F3qIcBohrXDqqGDxqwH+VZ9q55/e3Bb14Jb0CBWiNuPYMv+gpgNRzHI83Agl+EQbLgDYYkzE7wv+M9zXbdOYo3qclNp3/ZCCF1aSHf4wJ/eEu10Adr4L8D6oyBZVdYi2KBr32Uq8fjbg74dIazdaRLFfdxKh+d4aJFtVSDdBRHfsxDDXQ+jXCTQVymsdnwyxiShfp1Awgxv8DqtpkOfcYhoQ8pgrXFBfRiHPpUG14bvteAN6x2onHjnmZQc/wiwQ/oTu9wz5Rp/jXuM51DhtbDdrt9Pr1FYlQaBRs7e+gD1mQ9eJFdm3gL+ROnxfCJrdFvnmaTb8hqTPsoXFA04S7fOUc9YY6GglsKptedbQCWt1FVFsXuN/NVznJOc99JGB7K56Q+7g0Wn/8b/VgqBBeKdzs5uEdsmfUjAwjQxAZEZRELTWGoe61e8iG63fFrszEAeLRX20OcaoGHx4EhWTrNkEpF26zCOQKnDIDOenr
    client-secret: AgA80sQoiQSDKkAEk8XiIerqmw+9BEOVsNPuubHaCFEWvS1Fu+GyjMTzEGchCLEVqJOsR2S9Kvy04bemzSWR5vkKamWMc957ksIAu7epOKiTI/dafsOmfdqPgw5HbYXhpAuFVEOjN9dd2Vp+tvDkEJuGd8N0qEARGUpBl3qaqu38QIxqjWlLN5cV4nRBnkvAvYZRdCWfAuVi4E1I0HcJJ2DNViync+r5YDifgTnOVcEczjjtAwLIPqGxlL4cshYOMbgK6bSbuFj91EKERV7/S2Uq8FYOx6jddAdj7Y+0sRaTlWcK27erQUkavFFp2Fok3rr11/yqOXJLYFDjx7Yd/w5nX2aQZoyaLdmMB29Q0WnWWPD+i3YuGc4W8vk7HTqo3aq7vLpKTskqKjSSeBmoj2REf8qGYlyUD65+sqq+Z2TD8XGr5sVRdXyAsgS60ta/Or8T+xM8qmq4gbY0mc2LevlV8ILvS+AX5UEourFSj7QWf0G25FTlAQ8n2QC280NqEdR/2Qao8DvfROcWc9XWNA/p06at7TP95ujPpdAl3SxF4dQbiLxHmmIiJZqzHqZOR1KI8ueq+RE3TGtAs0n4czu3n3sOVTXh3CFwbD3QMGwky64WVebeRY4sHUEE9y2o/cf4WldLZeUvHTuPiSZ3Jge0s4bKWCYzVn1pCcn35yk4vafZ/Ua2BXBpjL59IzpeJkZO+kv7r0BMBviffnq+//s8qUjpQvBztFSi8vRVqidieA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
