---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAtTGBDZEN3vdmWUqyOaVNOz7eQChLMHy8gcOJaRBdnFzteVDx0cTK4iy30av+kcy3JpYzcyR8MNXGnV5G3qaN3nvHdO7M0Z1qVtLgMqS9+e6KKQJodMKizmlSgCUKxLBGJNMPbRuhCwBUQCxb35bhOxPju1UZlPEa9LYMtTJZfa+smZJcOP+yHdY7dF13gh5dk38+oHP9pK+GfnAVKYfjYlX8OiEp5I8DDwPGwkPuNmHW3GyRgKgPfIaVnC/35xK8fk67rhXeN+lz0X4Nreo6w4cgZ3XiMTpDCg5DkCeDe0LutkIiGgynxvi79cpIQXzr+WyMq1V6X1kTHMWIDgWKZM98nRXhJLMSRejjqqybEfuknj0lempQJCoZ0J351DijiKielLq24VUxJ3jQJMJLWQtEfcv7uWZVgvEW644nd/gLRtSb0W4DGLM5MTGOJdaDbhaev4WWfvbUH6bRs1GHpDQ49QgpJPkSQL4EKqEDejMHFz0KZJUgLvqhQImOZEDKhkVZJ+gNRfFKEAnf0/NStjqhWD0n3DvAewOaUkMHBu8C1s7dPgMBWWtuJA6UtWmArhaMNmVzsJZ1XEgSouLOEcQ9tOME38daFHMtrA+BBxsQCrVuw/NI6In4fGQ+nmQOAVmmQ8H7ylvCqkwkep9bxoH/ISKMFY4szlvxnaevGyxQuYLjTr8UKtoysxL2Db9IclU07rPOd
    admin-user: AgAVSj8LWdLKN/c3jb+EkVglcOyII6ecVyr1i80QE+BVJKHH7HrF+pt8rLl/p0lPDAamNMer4ERWK64NNxKKVUgDJZKBDIGMrAU2oZZwUAQxo2mFzVwF3xBDT6QYUnoBoqaR5l2WdcYKZbnO1gf02yLnCMowLuKy4EGYHZTM2m0RPv2wnHIYHgrViLxXEOeZ4JuNv0IP+H15sbVf5hkAki3MB1TyKmXJe4H6RQEUMWLtf/Ub1sBHAKaxlP5U72689fLjow0StUofrnVLFfhZns0v2vYCmzaP+aMaP6SXpZQWgzMMEtl908fBgxTeNoPLNRHcn5UBFPpUelreh6MAxb/DN4SzhSr3nWNHvuHtcC3+SMBcemtLa4wd5ZQkHGcbEEPEWJpsA16CdencGYGyn4JZh+nQ95h7KB2x4+IvHiUe9QKybMOMRlcbiANTR1/C/vNTlapUvQVOG6dpM/FVqhw9SIU346NSZ22giTjcTLG9W90KHlojqNOZifaExBZgYDu8Rn1mDQ5OKBF9wf/WRggOdnaBimog6Y/47kDMZ1VBW2btewdkoP/GG29c3BXQ4xKdYrTakZgCI/2OzcfG9N4bVAqZLcITT41BCNO8zEmygAEYBwcxqkI2+FNBnxo8i4xmFuPMBfqXTvTpx39h7BSNyydKLTTpgJxns1P9bkTlDe9EYol4l/TEv95gILDD4w3TSQCb3g==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
