---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCSTjPO4BrOoxLxUAbu0bDpcAdHETEA3wOyBNPbzSAL6Sd9f2nhSPuCzenrpaC8HEWQC0IaGjqf5b5sKRQFkuQXPc83kZXlriGZP/SeHa5lyLARfE+KbDErUoZqubNyB8WKLk/rnk6MX1hXWjX/SunPOqFk5Zq3T2+KT+H99qacBSHTswIW7m51VHUHfCziBo/5IFFuOkxBnko9ireDg80ijVoSJOwvR7XlzbpJ+YO2qIco3p3XZ+l0zFotYQ3oj9L4TJciA6JobNVUTfmhqL+EKmMnJJI2IScM7EXqNN7WHgY56/3NsRFE8lgVa38e0wR0f8Xx8KXHfodKOLvSTdqksOMVNdrn1OCclBEpAUu5Sq27Tmm1D11dzdVfFSarL1KnMIex/hluWDkZnb6B634TDvXckY965LDWjyux/MD4rgM1TW/bE5mu60J9UtkzWGvya1Hfp7e34qPiDAtXTjRdcAN1g5sTYzP5wPHDwXYy5I9CsyrDH82NeQuwjUEhoAnxAykYgoloZfJfxjo15H4fnOyhvIwoovyftZ2g19vJO2EBjQ6gLxpJfFV2kNFLc8zuKkQxmfHKm4OgtRnxoTqsjAW1baU1yEo2jx5Yu1dQhyPJGoM+7zUcUGh0G0u64z7wuQvD1i24j/Fz1c6xuUOCeLXBd98hPjEguUURSMRnkcaS5oo0uzSKsF5B+AJtgH+ei+UxjAYP
    client-secret: AgBaneyoOFo5ZW4GARHNDtZGdIJHmLUqGTh6KWeoz1Htre5HSbS7SuHjsWGlmneydeE2wo2tU1UDfNyNiTXpVkIplanV4M/WOrwR0gXzTKdS4LMBYD1CxSaaHoyVrw60elyvFHwsMlSP/LxFoqFb11Ktpch+A9iQVx+9qE0tY/1MVfa018cFEF5Awxtvx/KnzGWC3gpzloHcUbXP2FVc6drycuhBJNyj8qsIfSafs7g9p37RDm3GrAu/HwGt4zh/aCXhcP9BSfU61S1JDERUt66Rb3kg0yIEqk180zsiMimTzLDyZC+Qe0bsZcbiimuW3lm+Qc7kkfxLr/NrFzO5fl1GmLLfSm/ys2RoCODW2AIuypNu/6zItYZYfafrhg8Te15nn2Ptdig3b2o9MZMwmbtXNgH6xQJyZilV9l1Qke/87jJdcB0ab9gavxMc06a68ie7MSDYFDsmlKuLNSE2NE/SYgUvlSatj+HjJezh9WP+7+D2XV7D09yQ0ihpEYDivCqfUxKaxt8MpXSnAew5uY/zjzFB6W57Dbs3YUl6toXLJtmAD9+Flg+R6Qyz6UPBPqaqVishRFSMK0z5IWIiivUlwzCHSHB4S7hOcQD49qzgVAyTUY5hYuip12BOUmT239DDhbyM9A1P+kt9//vmRr5CtWEja+oe6DHJgw08wjpxnDlGku5IH3nl6OSfIkLfjNjscQAfYLkJ9u83YZxE5O/r0dwArlV6ae823XLaZAmCnA==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
