---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAKOs+hXRV/3mJ5CfX7YnrihqIZgFshpq1zZgeydNGskzFU5BTmgJ2T75EkAoF0PZ2lterD63IkiDIOFMd/wq1Np8tISdlKAVTBoyjsUGiD4kqPYgF6QX8oqMGMiW9ZpWTI6SZ98wdwG3OqPk9k5mSSYfeZXO31fe7WI/8UwtKFBNOHJDQp4BX4BHKYIZsnlGHFAvU7IlNqZ103lURyG0PSQsso9szSp07ZYQ6gRWGTQVHlHFGKXzgGhmnJj1enYy3emDq9QjRpju/eA4bIInfNh0npSX9kE92LdmaVG41ltw1RF74l0j2aolNIIfJgFVncHZPWW3JC/vS0PjD7/FpczQSOnj656W5ViGmcVN3H5tWyI99yrRUfkCVeHhzG+accimO5fy8MhVsVGMcBZ/tHDtSDOaWIEgzY+6ix7PBnsUEUzFL/9NPpnb+xiVvmKBZkgj+L7//daGWiTkY/Iqxo5w6IZsTVBKSDlWbrSZ9nIkRpUrABABq0353UNI+uEkk62+JibX5EtXfvBaRHdrC7Z83ojMbahVcdUuHXf47mxJEBPMpg7KpieRnj2W77Vchct7dCiJzLGlKedp0B5wmCE61I29HNpVNz9YUHKP8Z+U67jG75QtKWuoHyiakwiVcB39+oiB5oxZEEltmXllxKPg26C8363RT5zSGstd0nrpJmpUn6j9NyMi5JFYSsP/RtW5wCMynj
    admin-user: AgA0Wj8FWRsgpk2PaaUyV6xqE7P32hBvmfDMVAAqKBZrtg2SDK13nmGw9BwkWlJg3Q2QhQGEh1Mp8NhrhVJBC2zN14v0VJ8vc10LGVLMkEBQ048F3Gbh7AvYpvvdU/VzlBGhWAIXGnFEJ4mRTP5za27llhQlz7E2mY8oFBog6wQDN6RhaN9GiwKwGzi+PMwLUdtuqfhr6iFIEfSsLwxVGoyTh+xSm8lyeQZW8+ahrBczb7CGF4vphZbR6vVQKcD6uExlT2hWQpsNks0PdpUTRos4jwN2K/oeDpHA6OHLoPWuBSA3PdaT3LW8bpDFyBH+E501jHT2tu5AJmVJLdHeFzd6RYdSDkQ0A+ooC/iPIZ6cjbDg/rBfnsfgDl3XuH0ye76AGqv4a5vA3ZS5nEMAzFIDC9rTzHsT/+Q1jSEEtaQlX4WTOY6zknCPexM5Ge5ARyDUAyBv9znYwyoFaiw3bICgSMxLzAPYHnRlGzeuAg0PLJd7fnLeZyb2i6mhKInZAOZBWY8Mb5/K5LlOF68tUEIH2LTbN+Q8p+NPzUvXpcQypEbSMklmZUQAAMumFZtEFzpNWbuza1XsClwggHJvxt+GvsBDCywMR4Ek8ssnmhndsR92rVoyVqHUkLlYtCbUbSYI55g+ZssqJO6Rs0M0yAmbPhVsxeDenBZQMna1HieO5Ulvh875j0j5V+4HYRNldS1QSztCNw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
