---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCQG25QE6NAhKmQv0fSBPPtpazzIm1AaHKEDsPbwhuMsrXgkRY9u/tXGJtOE2yjEViX9sHxIfOTwV0Ag7eCmUFoiY1l5GMjVLPXLEcpqTygYItcn5zlmiQGGy5KFNrv9lVI4e8Dd8asiA/CbyaKTtsa/6J5xr1xmutxkMYoKhe89XdGQEt3ApC/9QvxZdzw2dzZwJPCHxNoB7hfnZ2X6P/J9Vw5Pozgl+8sW6JtPYj2rEeP3phV6aMWm1hwMrXg4JL854nFTuBW61YOrK9UZQATygrJhI4sAZR7H2KgSWCiVeblrkxcRVWRVhEaYwiEGqDgxFCeJSlCCDQwhMEeed8wdzCzIjm5WtHjh4t3DMqNX5Ih3aUD3YrfT28QkdnV0Rqz13JWAZsbA4wCTN8avQqKiQV9Ci+remt13Vk746N/JVASO0dSxhddIJe74Ex6DxwNfuXnLvlWccaKA+CaxcxrAztghpDwhsG9R0cd/x+PATX5QNaXS821BC3y12ewuA8m8LAN94cey08FPInIMRqiawAqWdxhtAi5IB8pEAiA9PmntPz4xUkI0VlXrdaainqayogX6tTBnCJibx9JjEu1jKujHIEPDuYMrhGvjl/EF+VknmDpG+ThtXJs64Jt0bq8ITsNCAr0kGQ1pN00C7Vo2jm6MWiqyVKadxa2/FiFx4rNSrOvh6wCSlfTKam7DbRXEgNNk07z
    admin-user: AgBy0tTnlq2m8kMNxt7aOHMd66umUUqkBMyExXS+wVwmsWK00tqSSmNxVJLhZBM2PJ+VCQwl8agFJBWTGsFyq9M5to9yBlxMaiiKdsjFDjKxv8TFD/ZQ1ZK5+hINgwqsHMJ6XFchBpb4cxy+B1mmXkl/06CEWRA6WQoIgea1zH0dxSs/OwYBuwEC53/WYDq1rvP1/AFpNrU4CdsWkX2Jq/mZuZNlF708ha2BbmJAC7G+gOYIAmuLjntnvgq5qCJKelv+o7Wr6nX7N6EyyugWH0TSOlsDtg8fpceW+O3acGMMmVoD+yWiCXRYA0gPd1Dr64q7WUNkTRjHdDJZUncC9foSgISUVERCCK5dwCV1CiOiM5rRiaU8kn/z8wW5mX3Jav57p3rTc9pVgJ9rqjKqjqdBaosAupG6qD4oyeXF8NaEPofCHahosdEkHDnZOJOCY5yIzhfe8MNS9B7aHNZwPpilky2iH7TOs6UfqqQ5FVBfvSZVecxiaHE4xPT87zynNl8jhGgTWPPiJLHZWMU84mdwYaaMdBMKgBBxGTZ0ZFOAjBbWnNBdzT6gL5IVhxeY5sRfsVc8xbW3VVqpzhsvNh0GsAuv8hG7kH9HDd+w0SbpJYtOzNH+LaRGkUj2+nmmOsHakfaLCadZ3IxS+h1TUU57DgZaDMWI7ROTod2i4LrVR6ns4+5GALyV33g95/nGCNhDl9QxCw==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
