---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAy5x9WK01xG6MA76rNrnOQxQl1xqf8Va5WZKeXKX+lvoD36Y+L8/8baOp7Kkks+rpk2iboGvF+EUjDQPPegcl1L+gmLtQEeABQ9fdoAlKkDnYEo7qTJZ+JJzPBYQPqqjSgPTHNURwrF6DGzyMMB8D6QXn5aCZcTvhyPophR0YYwN5J5TULGBfunwqTJeEbo1pyhbljw0SUgondWCRkDvAwbaUfGunxA6YrUobIDGFv8SjhT3NzAKjk+FM0ZVGHAz5Gd+4KNaysTg52l4xt3aIm7dmCUwP98hlRgrHz9xLCV7tKmdAC8AyLQiS6ilIwTHGoY5dvIoHfPVltxIt+PXXCTioUbkqYWBn6Cs60+6X9Cftoawqf/s8IsmZkZL3UVCNyxVCxw/U/xpN4iFf/Ukun5NNbTB4YxvcZuqMDiIFP2XkHXBpKYNFmYUVg/6oAjkNrbKN6T2zWmQU0cXrLti1Gd2OOnV9FuA2RuDtAbx3V8eOvmvs0vs3Ugi8q3jg7V+BemLLZAi8YcpqGeOtLhBYoO+LXN555FwIoPm27DpuA2Va5LCG4UQeuDQOuzLOa2vuO3SKONrMZEKKgTRNMC9yifuPjXYPxgPP7ylpdgzsM9+TCsw04WZu7LcSun1dSZCLrvbLCoFATn+O+vDzV4iAG4e0QAZPLKraETRUvUs2SrwMqk+NCTqiAls0IR/e1F8jR/PosEuFh
    admin-user: AgBz16RmIYIlk5/nnMbw/jls+tpoMUYFU3rvKqsYTNvoN1VH7Bu9swfYs9Vevh7yvKjLRBus/L7EgcKLXPqkr2nj/EuxIeZbkchHVGFKas4TjJym3XuLs15yQaZ6fof1hR0/V7uv5KYzZdCkFMMRnGRlFoZbZMjXR2ZS5bh/2jJHMMjQzuYxj2q//rRlvEJV05NQH6whdWxmGtAT2GLQ/B1qwVL2Xm0NtCYiXojdA/hUBPf8Ylw1pHaJXmsA8+D54FAs4Iz6XgFOgd555QxSfzEA+VCdJO5aiwe16Ne1OjPbGgqlheTT4t8QXPxF9jiudUKmMJA0JYOLHYvOsHVcw6PfXQAoJcY+NXy++JWGatB+Yw+664jcDItXzn1Brd24z4TCTava97DpIW4EknXetrAJHq/51+xeWHGYrIBzUlTEiBaZ++McAgZm43n5y/IYkBLiKXRpK1ia1f1UeUq4zHrKGtJOWeg/NEc788yhdGQ80ixKBy7FH1mw8dEFYrNjf1IlD2dNoPSxr5pcCs0yEaJNgtD9L7lc2BkoVMGPGUn3ZOFOGPoRWWrX5u4jUufWwvaXp0LIecf7VpCAvtDqbTtd4ts21cnb3PE7dcBdYjqFSg7XQSS4XOH91ibvah//7Ad0d0hx+NGN5DkTS7BHQnQL9KrBJJAjn58kLh535bm5tDpATOtUAZBOzKPSgleR9hmzsN62cg==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: stringData
