---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgB/1CG5c0LlxpLDgnjIBlTw2DkAxdjf7lmQXcF2n0VRgoyw+tADhVCmyFw/0693Czi+XC1OTEeb/oEr5TD0hq5kwqdGp5UW+VQd4DPcU9qHGZ96JV6R6CLg6D4PuU5MJv+4tk88SAxZjFXQdIyaUnap40XNVtbKiImPf5yBwAPMpX/CX1Tdf6cr4tAwkGzCO1FxbKozoQWe2Nmk4x7woPOO+EEa97ZTXWIyU4c318OIi9d/PNO4TrikqCZC3cpOg5vK1WoPz0ScXpGkYNZaESk5z2b99WDmwjCnJBAbDPUMj/a68lmmm49S34lRSgIT8d0lRXJF9gQKyzlSRL9utS4+SFfzT58tz3/O+SM+w69nlf3CFEvARz76B0VzVqR2dVHzcZyspp0G9NeuDChjjJZk9sKPcHwOrnMUOTtYACnW2asfjk9wbjI+xwrN1ZY7ARXtMCGD/XiUthw4/TzF3vMk4JjGUXOoEIllCgMkOe4QMOPZn2/b949bG0NnPkDJm/Rqz/89tYsIO0cPN622MNP+DfNYz1/nhHZmePNlnweYtpOsJ61bkZGl9bODOXtsnoinQNWaUSoN5FeMMu6PYVlXmDvAqA2e14kyBBY0a3iYJcT4jAL1tbMZOReasVHQw8tnLYy0Q1G9NFzRz+Yc3o4eZTZKrINfx8PVYH8U0o2gAZKM+Q/dGxD3wqoYmc5eRnhE48utvTrW
    client-secret: AgCr+MCt4+STdI1AWdvlw4Y7z8pOgPDdjlgWN/aiwnFRWXIJJ9HsIZkh2wYnpdYqITrL5Z7Q0cDZh9/X/vIx3jEbSEIsdCrjzD+YKuigLa4Zl5BZn0k6WcVc75pZGcYZpQrn39pyQA1zrxNiGez1UEpqNplGLHUCSs5VTlez+Fc7JQa9M8SXKVuIu0CUjwIrI6juGTKTOwHSP3qh4bMBbtjUtvP3MV52CQBtbFEwNkfc5Wmjovf5tA/9uv/EL42hwwKBJbq5vLPm8JGJ096AM+UIzaXbsDxmDEJ7cfqrclGtR77Y0h28DQqa4ep0X4Ko/7bJfIQHOxJ4i3dsCWPp4HRvdxDfHOS8EoOQNQdvnMDbIQ0/29QcLd1SxJcaN5OH3R1TG/boUp5i6GIqM3kz1n7730kQR1DJwSzSePOfpjddlzFxQ6jH76V52Zg5zAdRJqjIwTMTX/cX96OACWH11fjM6bm6TNqOf99WnA/A5jPrFtzNuCREKRIu9EQcGuMI/xRGtiaNf+2CoInsxdVxE6D69Ql6h9xVPzq4f3og73yjIcLS1MIOKA0RSx7atxtmFGgLMWuspqxrX9FHd8/6xK0nQJZkh8zM8QDte1vF+sKZTU3WgbeSnCojAqoI/qidNXlTND97e/KmuRSl/SORQup4Zc8G9vXcw/iPkraINPh2SJngdTOVGViLEPDpTrGpXY8nR+A/nU0YRX5p8DQRtOlw8GMMVYr9Z7Jr7+QfyDB5xg==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
