---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgBicfW5eGyKTlFOhLdYc69/aSIUdBC6Sw5eUhn0hBCp3aMpSImKsJq0TEjgm1hCuv63YuOFKBYpS+rprEQbhNOuktPe010WuzQKxmSdKMa8cbZ1Nj2cXNCdpRbuVCCNkwLZVTFyzzXtBHYdDHuL/yGgOrN3XYcn+PxxEnF7xZvrfxTUifYihgiypsuWgRik+FMOUrw5WdzGafCQD9IIkIJ7YEQZYZxPKmVvzeSWmEE/MdzRUWWp+6g6S1+f0ft8Z01uhGs4uHRRbsrIoOdskqJ3j90/VqMYzL7UvNiUC0Ad1VMnSRtEJXJTOAINo95IrPTYwDHQXBR+k3rqa8mIIXqMOp1QfYpSYxSEdG7HVyuoVCe8KifIhxTqPM0WABGEa7ygKlEH14Bf5uyawDM+yCMub1s7jyUItIZJpK26atgp4Ig+K62otubTpDzLQXHCj1O4rmNKlFQh2PnWunzZix9/RRlLDx+oLMpYGLtIDRGjKHxE8LNXgIr43ECPD3bU+E+mjqs28kyHGdIw9SrtjcGeJd8Ei4SRKPyuRIWmk6dDdz+YAtcsF0UXsYGE58N/Lmncu0ANGVWUYebDKsrCsDaf5A/veAxkSqXkm/9Uw+wdUce75cosqpu01nc5NzEWwOz8UnElfas5TekZDVHG7pjUKhbYwKuLuUEjhtc6dT5uoQvzsOfYw8+cTo5uNArkP3TzYENqkoXd
    client-secret: AgBWe3banYI9gJkJ/R/9gUPmXaU+KyBRPmoHMwv6cfWcpFwgol+RAwxrCBKsoY/cBV2plibTSBO6kj4b6yKdH1WYIIQ8UqObAJsrXXxRiG8zRms5nfPq6//RkLqHgbHtQbSCmsAYBB93aGojhk9gqVwuafIJvYFg4KMPGHk9+Z8fsEpoBQH4DNK4aPHqHxvXQto3IXvYc0pLbgy657qm4/7dc4a6EegSB7ZRayQXRPcFUBg+lBJgB/kZKlykuqS8hm1JDxliCJmwW3HJESD7feTSH9V0JZiPAbJCA+gpE2eBIf4TjdmtNSHq2qgi9QjtOtRtU2qtq7eZREaODnJLqrYtmQEjBG4Ko3egNdsMxBnT1UVFxuXOEj/0/h0Mr73meJNjVS6s9kXLy8O5d/WTGXRVhuO3ASdS7j4N+TsJK/dSiqNrss1amC3mcUJUiiFLXXXCVExaXfH9G3m6q3BXEwM/hb690tvyGwQCfSWyd7iMAtDpXWraAu3W7QpgUPURpoFGeoMvVMjxNUygZGcz7qJ7JqbaJ+kWsIAcJGj+cpScEyee+SIx8tJUU9r1LRtTpksl/Lyfz75gHquAMpoOm2kxfwmcfL0nfCe7HlIUcyMgJYvsXOPJG0DAfJ/H5AZZu+uNJ+DEFuRXSnYdKcWjf8J3DKBkox3Ly/FQE3Luz6osUkIj/6A1uS6N1bBsM+3YjaYAwmPMa2jGtz+pkmLhUfVXtFwlCGlT8fpOHLMndfLuUw==
  template:
    metadata:
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
