apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/jupyterhub-ingress.yaml
# - base/jupyterhub-keycloak-client.yaml
# - base/jupyterhub-proxy-certificate.yaml
# - sealed-secrets/jupyterhub-hub-env-vars.yaml
# - sealed-secrets/jupyterhub-keycloak-client.yaml

# helmCharts:
# - name: jupyterhub
#   namespace: jupyterhub
#   releaseName: jupyterhub
#   repo: https://hub.jupyter.org/helm-chart
#   valuesFile: values.yaml
#   version: 4.3.2
