apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/jupyterhub-keycloak-client.yaml
- base/jupyterhub-proxy-certificate.yaml
- sealed-secrets/jupyterhub-keycloak-client.yaml

helmCharts:
- name: jupyterhub
  namespace: jupyterhub
  releaseName: jupyterhub
  repo: https://hub.jupyter.org/helm-chart
  version: 3.1.0
  valuesFile: values.yaml
