    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: k-lan
      hosts:
      - jh.k.lan
      tls:
      - hosts:
        - jh.k.lan
        secretName: jh-server-tls
    proxy:
#      annotations:
#        cert-manager.io/cluster-issuer: k-lan
#      https:
#        enabled: true
#        type: secret
#        secret:
#          name: jupyterhub-server-tls
#          key: tls.key
#          crt: tls.crt
#        hosts:
#        - jh.k.lan
      service:
        type: ClusterIP
#        disableHttpPort: true
    hub:
      config:
        Authenticator:
          admin_users:
          - william
        JupyterHub:
          admin_access: false
#          authenticator_class: generic-oauth
#        GenericOAuthenticator:
#          client_id: jupyterhub
#          client_secret: GfLNU8v0Ldqb2dVBQCSqnXfFsXNWZtO0
#          oauth_callback_url: https://jh.s.lan/hub/oauth_callback
#          authorize_url: https://kc.s.lan/auth/realms/slan/protocol/openid-connect/auth
#          token_url: https://kc.s.lan/auth/realms/slan/protocol/openid-connect/token
#          userdata_url: https://kc.s.lan/auth/realms/slan/protocol/openid-connect/userinfo
#          login_service: keycloak
#          username_key: preferred_username
#          tls_verify: false
#          auto_login: true
#          userdata_params:
#            state: state
#          admin_users:
#          - william
#      db:
#        type: sqlite-pvc
#        pvc:
#          subPath:
#          storageClassName: slan
#          accessModes:
#          - ReadWriteMany
#    prePuller:
#      continuous:
#        enabled: false
    singleuser:
#      storage:
#        type: dynamic
#        dynamic:
#          storageClass: slan
#          pvcNameTemplate: claim-{username}
#          volumeNameTemplate: volume-{username}
      profileList:
      - display_name: "Minimal environment"
        description: "To avoid too much bells and whistles: Python."
        default: true
      - display_name: "Datascience environment"
        description: "If you want the additional bells and whistles: Python, R, and Julia."
        kubespawner_override:
          image: jupyter/datascience-notebook
      - display_name: "Spark environment"
        description: "The Jupyter Stacks spark image!"
        kubespawner_override:
          image: jupyter/all-spark-notebook
      defaultUrl: "/lab"
      extraEnv:
        JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
        EDITOR: "vim"
