apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollama

helmCharts:
- name: ollama
  namespace: ollama
  releaseName: ollama
  repo: https://helm.otwld.com/
  version: 1.43.0
  valuesFile: values.yaml
