apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: fluent-bit
  namespace: fluent-bit
  releaseName: fluent-bit
  repo: https://fluent.github.io/helm-charts
  valuesFile: values.yaml
  version: 0.56.0
