config:
  # https://docs.fluentbit.io/manual/pipeline/outputs/loki
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 32MB
        Skip_Long_Lines On
        Buffer_Chunk_Size 64KB
        Buffer_Max_Size 128KB

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Buffer_Size 256KB

    # [FILTER]
    #     name         nest
    #     match        kube.*
    #     operation    lift
    #     nested_under kubernetes
    #     add_prefix   kubernetes_

    # [FILTER]
    #     name         nest
    #     match        kube.*
    #     operation    lift
    #     nested_under kubernetes_annotations
    #     add_prefix   kubernetes_annotations_

    # [FILTER]
    #     Name                modify
    #     Match               kube.*
    #     Remove              kubernetes_annotations_k8s.ovn.org/pod-networks
    #     Remove              kubernetes_annotations_k8s.v1.cni.cncf.io/network-status

  outputs: |
    [OUTPUT]
        auto_kubernetes_labels on
        # bearer_token
        host loki-distributor.loki.svc
        # http_user loki
        # http_passwd loki
        labels cluster=iaas, namespace=$kubernetes['namespace_name'], source=kubernetes
        match *
        name loki
        # tls on
    # [OUTPUT]
    #     auto_kubernetes_labels on
    #     # bearer_token
    #     host alloy.alloy.svc
    #     # http_user loki
    #     # http_passwd loki
    #     labels cluster=iaas, namespace=$kubernetes['namespace_name'], source=kubernetes
    #     match *
    #     name loki
    #     # tls on

dashboards:
  enabled: true

resources:
  limits:
    cpu: 250m
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 200Mi

securityContext:
  privileged: true

serviceMonitor:
  enabled: true
