apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubescape

# resources:
# -

helmCharts:
- name: kubescape-operator
  namespace: kubescape
  releaseName: kubescape
  repo: https://kubescape.github.io/helm-charts
  valuesFile: values.yaml
  version: 1.30.2
