apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capi-operator

helmCharts:
- name: cluster-api-operator
  namespace: capi-operator
  releaseName: capi-operator
  repo: https://kubernetes-sigs.github.io/cluster-api-operator
  # valuesFile: values.yaml
  version: 0.25.0
