kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    cert-manager.io/cluster-issuer: iaas-wcooke-me
    # forecastle.stakater.com/appName: HolmesGPT
    # forecastle.stakater.com/expose: "true"
    # forecastle.stakater.com/group: Kubernetes
    # forecastle.stakater.com/icon: https://holmesgpt.apps.iaas.wcooke.me/assets/images/logo.png
    # forecastle.stakater.com/network-restricted: "true"
  name: holmesgpt
spec:
  ingressClassName: cilium
  rules:
  - host: holmesgpt.apps.iaas.wcooke.me
    http:
      paths:
      - backend:
          service:
            name: holmesgpt
            port:
              name: https
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - holmesgpt.apps.iaas.wcooke.me
    secretName: holmesgpt-ingress
