apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pulp-operator

helmCharts:
- name: pulp-operator
  includeCRDs: true
  namespace: pulp-operator
  releaseName: pulp-operator
  repo: https://github.com/pulp/pulp-k8s-resources/raw/main/helm-charts/
  valuesFile: values.yaml
  version: 0.5.0
