apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: holmesgpt

resources:
- base/ingress.yaml

helmCharts:
- name: holmes
  namespace: holmesgpt
  releaseName: holmesgpt
  repo: https://robusta-charts.storage.googleapis.com
  version: 0.18.3
  valuesFile: values.yaml
