apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cdi

patches:
# - path: patches/remove-crd.yaml
- path: patches/remove-namespace.yaml

resources:
- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.64.0/cdi-operator.yaml
- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.64.0/cdi-cr.yaml
