apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/kube-ingress
  name: kube-ingress
  namespace: default
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "kube-ingress",
        "type": "bridge",
        "bridge": "kube-ingress@br0",
        "ipam": {},
        "macspoofchk": true,
        "preserveDefaultVlan": false
    }
