apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/asdf
  name: asdf
  namespace: default
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "asdf",
        "type": "bridge",
        "bridge": "br0",
        "ipam": {},
        "macspoofchk": true,
        "preserveDefaultVlan": false
    }
