apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
- base/ceph-datasource.yaml
- base/grafana-client.yaml
- base/grafana-pg-cluster.yaml
- base/loki-datasource.yaml
- base/pyroscope-datasource.yaml
- base/tempo-datasource.yaml
- sealed-secrets/grafana-admin.yaml
- sealed-secrets/grafana-keycloak-client.yaml

helmCharts:
- name: grafana
  namespace: grafana
  releaseName: grafana
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  version: 10.5.9
