apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tempo

resources:
- base/objectbucketclaim.yaml

helmCharts:
- name: tempo-distributed
  namespace: tempo
  releaseName: tempo
  repo: https://grafana-community.github.io/helm-charts
  valuesFile: values.yaml
  version: 2.1.0
