apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/name: whoami
    app.kubernetes.io/part-of: whoami
  name: whoami
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: pod
    app.kubernetes.io/name: whoami
    app.kubernetes.io/part-of: whoami
  type: ClusterIP
