apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/name: drawio
    app.kubernetes.io/part-of: drawio
  name: drawio
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: pod
    app.kubernetes.io/name: drawio
    app.kubernetes.io/part-of: drawio
  type: ClusterIP
