apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reloader

# resources:
# -

helmCharts:
- name: reloader
  namespace: reloader
  releaseName: reloader
  repo: https://stakater.github.io/stakater-charts
  valuesFile: values.yaml
  version: 2.2.8
