apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: iaas-wcooke-me
    # forecastle.stakater.com/appName: Ceph S3 Frontend
    # forecastle.stakater.com/expose: "true"
    # forecastle.stakater.com/group: Storage
    # forecastle.stakater.com/icon: https://ceph.apps.iaas.wcooke.me/assets/Ceph_Logo.svg
    # forecastle.stakater.com/network-restricted: "true"
    # nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: ceph-objectstore
spec:
  ingressClassName: cilium
  rules:
  - host: s3.apps.iaas.wcooke.me
    http:
      paths:
      - backend:
          service:
            name: rook-ceph-rgw-ceph-objectstore
            port:
              number: 443
        path: /
        pathType: Prefix
  - host: "*.s3.apps.iaas.wcooke.me"
    http:
      paths:
      - backend:
          service:
            name: rook-ceph-rgw-ceph-objectstore
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - s3.apps.iaas.wcooke.me
    - "*.s3.apps.iaas.wcooke.me"
    secretName: ceph-objectstore-ingress-certs
